"use client";
import { useMemo,useState } from "react";
import { ExperimentButton,ExperimentChoices,ExperimentRail,ExperimentResult,LearningPage,LessonAction,LessonSelect,LessonSummaries,LessonToggleGroup,LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeClassification,classificationNames,classificationPercent as percent,classificationPredictionMask,classificationScenarios,type ClassificationState } from "./classification-engine";
import { classificationBaseline,reachedClassification } from "./lesson-state";
import { classificationExperiments } from "./learning-experiments";
import styles from "./playground.module.css";
export function ClassificationPlayground(){
 const [state,setState]=useState(()=>classificationBaseline()),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const a=useMemo(()=>analyzeClassification(state),[state]),{tp,fp,fn,tn}=a.counts,experiment=classificationExperiments[index],transfer=index===3,reached=!!prediction&&!!experiment&&reachedClassification(index,state),complete=reached&&explanation==="0";
 function clear(){setExplanation(null);setTransferAnswer(null);}
 function start(next=index){setIndex(next);setState(classificationBaseline(next));setPrediction(null);clear();}
 function editMask(mask:number){setState(s=>({...s,mask}));clear();}
 const rail=experiment?<ExperimentRail label={`Experiment ${index+1} of 3`} title={experiment.title} phase={!prediction?0:reached?2:1}>
  {!reached&&<><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="classification-prediction" choices={experiment.predictions} value={prediction} onChange={id=>{start();setPrediction(id);}}/><p className={shared.small}>Changing prediction restores this experiment’s starting state. Reset restarts it.</p></>}
  {prediction&&!reached&&<p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
  {reached&&<><p role="status" className={shared.observation}>{prediction==="0"?"The counts match your prediction.":"The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="classification-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation}/>{explanation&&!complete&&<p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
  {complete&&<><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={()=>start(index+1)}>{index===2?"Try the transfer check":"Next experiment"}</ExperimentButton></>}
 </ExperimentRail>:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"A different class balance":"Trace every metric’s denominator"}>
  {transfer?<><p>Without Guide help, choose Balanced and predict only Case 1, Case 2 and Case 7 Positive. Leave all others Negative. Reconstruct the four counts and calculate precision, recall and F1. Does the predicted-positive set equal the actual-positive set?</p>{reachedClassification(3,state)&&<><ExperimentChoices legend="Transfer explanation" name="classification-transfer" choices={[
   {id:"sets",label:"TP 2, FP 1, FN 4 and TN 5 give accuracy 7/12 = 58.3%, precision 2/3 = 66.7%, recall 2/6 = 33.3% and F1 4/9 = 44.4%. Predicted positives are Case 1/2/7; actual positives are Case 1..6. Their denominators describe different sets, and these toy scores do not guarantee future performance."},
   {id:"swap",label:"Precision is2/6 and recall is2/3, because those denominators are interchangeable."},
   {id:"mean",label:"F1 is50%, the arithmetic mean of precision 66.7% and recall 33.3%."},
  ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="sets"?<p role="status" className={shared.feedback}>Try again. List the actual-positive and predicted-positive Case IDs separately. Count TP twice for F1, then add FP and FN to its denominator; do not take an arithmetic average.</p>:<><ExperimentResult title="Transfer explained">Different sets produce different denominators. One false positive and four misses lower positive-class metrics in different ways; a finite confusion table is not a guarantee about other cases.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(4);clear();}}>Explore freely</ExperimentButton></>)}</>}</>:<><p>Edit predictions and trace each case’s cell. Try No positives with Predict all negative, then Predict all positive to inspect zero denominators. Metrics alone do not select a model or determine acceptable error costs.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
 </ExperimentRail>;
 const ratio=(key:keyof typeof a.metrics)=>`${a.metrics[key].numerator}/${a.metrics[key].denominator}`,undef=(key:keyof typeof a.metrics,reason:string)=>a.metrics[key].value===null?`Undefined: ${reason}.`:undefined;
 return <LearningPage title="Classification Metrics Foundations" subtitle="Count the cases behind each score." rail={rail}>
  <LessonToolbar scenarios={classificationScenarios} selectedId={state.scenario} onSelect={scenario=>{setState({scenario:scenario as ClassificationState["scenario"],mask:0,selected:1});clear();}} onReset={()=>start(experiment||transfer?index:0)}/>
  <section className={styles.evidence} aria-label="Actual labels and editable predictions"><h2>Your dataset</h2><p>Twelve fixed actual labels in each preset. Edit predictions, not the truth. Positive is the class of interest; true or false says whether a prediction is correct. Scenario changes restore all predictions Negative.</p><p role="status" data-classification-status className={styles.formula}>TP {tp} · FP {fp} · FN {fn} · TN {tn} · Actual positives {a.actualPositive} · Predicted positives {a.predictedPositive} · Total 12</p>
   <table className={styles.matrix} aria-label="Confusion matrix: actual rows, predicted columns"><caption>Rows are actual labels; columns are predictions. Positive class first; every case appears in exactly one cell.</caption><thead><tr><th scope="col">Actual / Predicted</th><th scope="col">Predicted positive</th><th scope="col">Predicted negative</th></tr></thead><tbody><tr><th scope="row">Actual positive</th><td data-bucket="tp">True positive (TP)<strong>{tp}</strong></td><td data-bucket="fn">False negative (FN)<strong>{fn}</strong></td></tr><tr><th scope="row">Actual negative</th><td data-bucket="fp">False positive (FP)<strong>{fp}</strong></td><td data-bucket="tn">True negative (TN)<strong>{tn}</strong></td></tr></tbody></table>
   <div className={styles.editor}><LessonSelect label="Selected case" choices={a.rows.map(r=>({id:String(r.id),label:`Case ${r.id}`}))} value={String(state.selected)} onChange={selected=>setState(s=>({...s,selected:Number(selected)}))}/><div><p role="status" data-classification-selected>Case {state.selected}: Actual {a.selectedRow.actual?"positive":"negative"} · Predicted {a.selectedRow.predicted?"positive":"negative"} · {classificationNames[a.selectedRow.bucket]} ({a.selectedRow.bucket.toUpperCase()})</p><LessonToggleGroup label="Selected case prediction" choices={[{id:"negative",label:"Negative"},{id:"positive",label:"Positive"}]} value={a.selectedRow.predicted?"positive":"negative"} onChange={value=>editMask(classificationPredictionMask(state.mask,state.selected,value==="positive"))}/></div></div>
   <div className={styles.bulk}><LessonAction onClick={()=>editMask(0)}>Predict all negative</LessonAction><LessonAction onClick={()=>editMask(4095)}>Predict all positive</LessonAction></div><p>Choosing a case changes only selection, preserving counts and explanations. Editing predictions or selecting a scenario clears completion. No probabilities, threshold or model fitting are involved.</p>
  </section>
  <LessonSummaries label="Four metrics and their exact denominators" summaries={[
   {label:"Accuracy",color:"#5031dc",value:percent(a.metrics.accuracy.value),definition:"Correct positive and negative labels among all twelve cases.",formula:`(TP + TN)/12 = ${ratio("accuracy")}`},
   {label:"Precision",color:"#ad4508",value:percent(a.metrics.precision.value),definition:"Correct positives among predicted positives.",formula:`TP/(TP + FP) = ${ratio("precision")}`,comparison:undef("precision","no predicted positives, so 0/0")},
   {label:"Recall",color:"#087c78",value:percent(a.metrics.recall.value),definition:"Found positives among actual positives.",formula:`TP/(TP + FN) = ${ratio("recall")}`,comparison:undef("recall","no actual positives, so 0/0")},
   {label:"F1",color:"#0c1230",value:percent(a.metrics.f1.value),definition:"Harmonic balance of precision and recall where defined; ignores true negatives.",formula:`2TP/(2TP + FP + FN) = ${ratio("f1")}`,comparison:undef("f1","no true positives, false positives or false negatives, so 0/0")},
  ]}/>
  <section className={styles.evidence} aria-label="Case identities and metric limits"><p>Ratios are shown as one-decimal percentages. — means undefined, not zero. With actual positives but no positive predictions, precision is undefined while count-form F1 is zero because its FN denominator is nonzero.</p><details><summary>All twelve cases</summary><div className={styles.table} role="region" tabIndex={0} aria-label="Twelve actual and predicted labels"><table><caption>Actual labels stay fixed within a preset. Selection preserves every prediction; each row contributes to one confusion cell.</caption><thead><tr>{["Case","Actual","Predicted","Confusion cell"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.rows.map(r=><tr key={r.id} aria-current={state.selected===r.id?"true":undefined}><th scope="row">Case {r.id}</th><td>{r.actual?"Positive":"Negative"}</td><td>{r.predicted?"Positive":"Negative"}</td><td>{classificationNames[r.bucket]} ({r.bucket.toUpperCase()})</td></tr>)}</tbody></table></div></details>
   <details><summary>Metric definitions and limits</summary><p>Precision uses the predicted-positive set TP+FP; recall uses the actual-positive set TP+FN. Accuracy includes TN and all cases. F1=2TP/(2TP+FP+FN); where precision P and recall R permit, it is 2PR/(P+R), a harmonic rather than arithmetic balance. F1 does not include TN and does not encode every task’s error costs. High recall can coexist with many false positives.</p><p>Zero denominators remain undefined here. No predicted positives makes precision 0/0; no actual positives makes recall 0/0. F1 is0 when TP 0 and FP+FN is positive, but undefined when all cases are TN. Library zero_division choices may replace undefined values with 0,1 or a missing value; this page displays the raw undefined ratio explicitly. These are unweighted binary positive-class metrics, with no multiclass averaging.</p><p>Case IDs are fixed synthetic examples: Rare positives has actual-positive Cases 1/2, Balanced has 1..6, No positives has none. Scenarios change the labelled toy dataset and reset its predictions, not a real population. Editing predictions does not demonstrate training, a causal intervention, calibrated probabilities or expected future accuracy. Choosing the right metric requires task priorities, representative data and acceptable error costs beyond these counts.</p><a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html" target="_blank" rel="noreferrer">scikit-learn · Confusion matrix axes</a><br/><a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html" target="_blank" rel="noreferrer">scikit-learn · Precision</a><br/><a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.recall_score.html" target="_blank" rel="noreferrer">scikit-learn · Recall</a><br/><a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html" target="_blank" rel="noreferrer">scikit-learn · F1 and zero division</a></details></section>
 </LearningPage>;
}
