"use client";
import { useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonAction, LessonRangeControl, LessonSelect, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import sharedStyles from "@/components/learning-page/learning-page.module.css";
import { analyzeLayerNormalization, formatValue as f, valueToPercent } from "./layer-normalization-engine";
import { changeFeature, constantRow, layerExperiments, layerTransferStart, layerTransferTarget, type LayerState } from "./learning-experiments";
import type { LayerTokenId } from "./scenario";
import styles from "./playground.module.css";
const same = (a: LayerState,b: LayerState) => a.token === b.token && a.feature === b.feature && a.compare === b.compare && a.tokens.every((t,i) => t.values.every((x,j) => x === b.tokens[i].values[j])) && a.gamma.every((x,i) => x === b.gamma[i]) && a.beta.every((x,i) => x === b.beta[i]);
function Stage({title,values,selected,mean,std,color}:{title:string;values:number[];selected:number;mean:number;std:number;color:string}) {
  return <figure className={styles.stage}><figcaption><strong>{title}</strong><span>Mean {f(mean,6)} · std {f(std,6)}</span></figcaption><div className={styles.plot} aria-hidden="true"><div className={styles.zero} />{values.map((value,i) => <div key={i} className={styles.plotRow}><span className={styles.rowLabel}>{i+1}</span><div className={styles.lane}><span className={styles.dot} data-stage-value={value} data-selected={i === selected} style={{left:`${valueToPercent(value,-5,5).toPrecision(6)}%`,background:color}} /></div></div>)}<div className={styles.axis}><span>−5</span><span>0</span><span>5</span></div></div></figure>;
}
export function LayerNormalizationPlayground() {
  const [state,setState] = useState<LayerState>(layerExperiments[0].baseline), [index,setIndex] = useState(0);
  const [prediction,setPrediction] = useState<string|null>(null), [explanation,setExplanation] = useState<string|null>(null), [transferAnswer,setTransferAnswer] = useState<string|null>(null);
  const token = state.tokens.find(t => t.id === state.token)!;
  const a = analyzeLayerNormalization({values:token.values,gamma:state.gamma,beta:state.beta,epsilon:.00001});
  const column = state.tokens.map(t => t.values[state.feature]);
  const columnAnalysis = analyzeLayerNormalization({values:column,gamma:[1,1,1],beta:[0,0,0],epsilon:.00001});
  const experiment = layerExperiments[index], transfer = index === 5;
  const reached = !!prediction && !!experiment && same(state,experiment.target), complete = reached && explanation === "0", transferReached = same(state,layerTransferTarget);
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function edit(next:LayerState) { setState(next); clear(); }
  function start(next=index) { setIndex(next); setState(layerExperiments[next]?.baseline ?? layerTransferStart); setPrediction(null); clear(); }
  const rail = experiment ? <ExperimentRail label={`Experiment ${index+1} of 5`} title={experiment.title} phase={!prediction ? 0 : reached ? 2 : 1}>
    {!reached && <><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="layer-prediction" choices={experiment.predictions} value={prediction} onChange={id => { start(); setPrediction(id); }} /><p className={sharedStyles.small}>A different prediction restores starting settings. Reset restarts this experiment.</p></>}
    {prediction && !reached && <p className={sharedStyles.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
    {reached && <><p role="status" className={sharedStyles.observation}>{prediction === experiment.correctPrediction ? "Your prediction matches the evidence." : "The numeric evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="layer-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation} />{explanation && !complete && <p role="status" className={sharedStyles.feedback}>Try again. {experiment.retry}</p>}</>}
    {complete && <><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={() => start(index+1)}>{index === 4 ? "Try the transfer check" : "Next experiment"}</ExperimentButton></>}
  </ExperimentRail> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Scale a constant row" : "Explore rows and parameters"}>
    {transfer ? <><p>Sat’s row is constant at zero. Feature 4 has Scale 0.4 and Shift −0.5. Predict what happens to its output when Scale becomes 1.8. Try it, then explain without Guide help.</p><ExperimentChoices legend="Transfer explanation" name="layer-transfer" choices={[{id:"fixed",label:"Sat’s feature 4 stays at −0.5 because z=0, so y=Scale×0+Shift. The same Scale is shared with feature 4 in other rows, where z can be nonzero."},{id:"changed",label:"Sat’s output must grow because Scale always increases every output."},{id:"unit",label:"A constant row becomes unit variance, so its fourth output must be 1.8."}]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (!transferReached ? <p role="status" className={sharedStyles.feedback}>First set Scale to 1.8, keeping sat, Feature 4, Shift −0.5 and the zero row. Reset restores Scale 0.4.</p> : transferAnswer !== "fixed" ? <p role="status" className={sharedStyles.feedback}>Try again. Read z=0 in the selected calculation. Multiplying zero by either scale still gives zero before adding Shift.</p> : <><ExperimentResult title="Transfer explained">Scale cannot change this constant row’s y=Shift. Its feature-wise parameter is still shared with other rows; there it can change y when z is nonzero.</ExperimentResult><ExperimentButton onClick={() => {setIndex(6);clear();}}>Explore freely</ExperimentButton></>)}</> : <><p>Edit any of the three token rows and all four feature parameters. Exact values, the axis comparison and model notes are optional. No optimizer runs; Reset restarts the experiments.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Layer Normalization Lab" subtitle="Change a feature. Follow its row. Keep the axes straight." rail={rail}>
    <LessonToolbar scenarios={state.tokens.map((t,i) => ({id:t.id,label:t.label,shortLabel:`Row ${i+1}`}))} selectedId={state.token} onSelect={id => edit({...state,token:id as LayerTokenId})} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={styles.evidence} aria-label="LayerNorm input and controls"><h2>Your dataset · three tokens, four features</h2><p>Each row represents one token—a position in this toy sequence. Its features are illustrative numeric signals, not generated word embeddings. LayerNorm here uses all four features in the selected row.</p><div className={styles.table}><table><caption>Raw inputs. The selected token row is highlighted; edit one feature below.</caption><thead><tr><th scope="col">Token</th>{[1,2,3,4].map(i => <th key={i} scope="col">Feature {i}</th>)}</tr></thead><tbody>{state.tokens.map(t => <tr key={t.id} data-active={t.id === state.token}><th scope="row">{t.label}{t.id === state.token ? " · selected" : ""}</th>{t.values.map((x,i) => <td key={i} data-input-value={x}>{f(x,2)}</td>)}</tr>)}</tbody></table></div>
      <LessonSelect label="Selected feature" choices={[1,2,3,4].map(i => ({id:String(i-1),label:`Feature ${i}`}))} value={String(state.feature)} onChange={id => edit({...state,feature:Number(id)})} />
      <div className={styles.controls}><LessonRangeControl label="Feature value" value={token.values[state.feature]} min={-2} max={2} step={.1} help={`Edit ${token.label}, feature ${state.feature+1}, only.`} onChange={value => edit(changeFeature(state,value))} /><LessonRangeControl label="Scale" value={state.gamma[state.feature]} min={.4} max={1.8} step={.05} help="Gamma multiplies this feature’s z in all tokens." onChange={value => edit({...state,gamma:state.gamma.map((g,i) => i === state.feature ? value : g)})} /><LessonRangeControl label="Shift" value={state.beta[state.feature]} min={-1} max={1} step={.05} help="Beta adds to this feature’s output in all tokens." onChange={value => edit({...state,beta:state.beta.map((b,i) => i === state.feature ? value : b)})} /></div><LessonAction onClick={() => edit(constantRow(state))}>Make row constant</LessonAction><p>Make row constant sets the selected row’s four inputs to zero. Scale and Shift are per-feature parameters shared across all three tokens; you edit them manually here.</p>
    </section>
    <section className={styles.evidence} aria-label="Linked feature stages"><h2>Follow {token.label}’s four features</h2><div className={styles.stages}><Stage title="Input x" values={a.values} selected={state.feature} mean={a.mean} std={a.standardDeviation} color="#1470ba" /><Stage title="Normalized z" values={a.normalizedValues} selected={state.feature} mean={a.normalizedMean} std={Math.sqrt(a.normalizedVariance)} color="#5031dc" /><Stage title="Output y" values={a.outputValues} selected={state.feature} mean={a.outputMean} std={a.outputStd} color="#167d59" /></div><p className={sharedStyles.small}>Fixed numeric axes −5 to 5 keep spread changes visible. Each numbered lane follows one feature; the outlined dot marks your selection. x and y are numeric activations; z is dimensionless. Exact values are below.</p></section>
    <section className={styles.evidence} aria-label="Selected feature calculation"><h2>{token.label} · feature {state.feature+1}</h2><p className={styles.formula} data-selected-z>z = ({f(a.values[state.feature],6)} − ({f(a.mean,6)})) / √({f(a.variance,6)} + 0.00001) = {f(a.normalizedValues[state.feature],6)}</p><p className={styles.formula} data-selected-y>y = {f(state.gamma[state.feature],2)} × ({f(a.normalizedValues[state.feature],6)}) + ({f(state.beta[state.feature],2)}) = {f(a.outputValues[state.feature],6)}</p><p>Substitutions are rounded; calculations use full precision. Epsilon (0.00001) is a positive term protecting the denominator. z’s sign follows x−mean; Scale and Shift act afterward.</p></section>
    <LessonSummaries label="Selected row statistics" summaries={[{label:"Row mean",color:"#5031dc",value:f(a.mean,4),definition:"Average of this token’s four raw features.",formula:"mean = Σx / 4",comparison:`Normalized mean ${f(a.normalizedMean,6)}; output mean ${f(a.outputMean,6)}.`},{label:"Row variance",color:"#5031dc",value:f(a.variance,4),definition:"Average squared distance from the raw row mean.",formula:"variance = Σ(x−mean)² / 4",comparison:`Raw std √variance = ${f(a.standardDeviation,6)}. Denominator √(variance+epsilon) = ${f(a.denominator,6)}.`},{label:"Output spread",color:"#167d59",value:f(a.outputStd,4),definition:"Population standard deviation around y’s actual mean.",formula:"yᵢ = Scaleᵢ × zᵢ + Shiftᵢ",comparison:`var(z) = variance/(variance+epsilon) = ${f(a.normalizedVariance,6)}. Per-feature parameters need not preserve zero mean or unit spread.`}]} />
    <section className={styles.evidence}><details><summary>Exact feature values</summary><div className={styles.table}><table><caption>{token.label}: computed values rounded to six decimals.</caption><thead><tr><th scope="col">Feature</th><th scope="col">Input x</th><th scope="col">Normalized z</th><th scope="col">Output y</th></tr></thead><tbody>{a.values.map((x,i) => <tr key={i} data-active={i === state.feature}><th scope="row">{i+1}{i === state.feature ? " · selected" : ""}</th><td>{f(x,6)}</td><td>{f(a.normalizedValues[i],6)}</td><td>{f(a.outputValues[i],6)}</td></tr>)}</tbody></table></div></details>
    <details open={state.compare} onToggle={event => {if (event.currentTarget.open !== state.compare) edit({...state,compare:event.currentTarget.open});}}><summary>Compare with a BatchNorm column</summary><p>Declare the layout first. LayerNorm input [1, 3, 4] has one sequence, three token positions, four features; normalized_shape=4 uses four features per token. For BatchNorm1d, transpose the same data to [N=1, C=4, L=3]: one sequence, four feature channels, three positions. Its training forward calculation uses each channel across those three positions, as this column shows. The positions are not three independent batch examples.</p><div className={styles.table}><table><caption>BatchNorm comparison: highlighted feature {state.feature+1} column. The main plots still show LayerNorm.</caption><thead><tr><th scope="col">Token</th>{[1,2,3,4].map(i => <th key={i} scope="col">F{i}</th>)}<th scope="col">Column z</th></tr></thead><tbody>{state.tokens.map((t,r) => <tr key={t.id}><th scope="row">{t.label}</th>{t.values.map((x,i) => <td key={i} data-active={i === state.feature}>{f(x,2)}</td>)}<td data-column-z>{f(columnAnalysis.normalizedValues[r],6)}</td></tr>)}</tbody></table></div><p data-column-statistics>Selected column mean {f(columnAnalysis.mean,6)}, population variance {f(columnAnalysis.variance,6)}; z=(x−column mean)/√(column variance+0.00001). This comparison omits affine parameters to isolate axes. LayerNorm selected row mean {f(a.mean,6)}, variance {f(a.variance,6)}.</p></details>
    <details><summary>What this model includes</summary><p>Population variance divides by the number of contributing values. LayerNorm normalizes the declared trailing dimensions; this demo uses four features. It computes statistics from the current input in both training and evaluation. Per-feature gamma and beta are shared across leading token/sequence dimensions. The lab permits positive scales 0.4–1.8; real parameters can also be zero or negative.</p><p>The three words label illustrative rows; features have no assigned linguistic meaning. No optimizer, running-statistic update or training-quality comparison runs. The BatchNorm example describes the training forward grouping with explicit N,C,L axes; evaluation behavior can use saved running statistics.</p><p><a href="https://docs.pytorch.org/docs/2.14/generated/torch.nn.LayerNorm.html" target="_blank" rel="noreferrer">PyTorch LayerNorm reference</a> · <a href="https://docs.pytorch.org/docs/2.14/generated/torch.nn.BatchNorm1d.html" target="_blank" rel="noreferrer">BatchNorm1d reference</a>.</p></details></section>
    <p role="status" aria-live="polite" aria-atomic="true" className={sharedStyles.liveUpdate}>{token.label}, feature {state.feature+1}. Row mean {f(a.mean,6)}, variance {f(a.variance,6)}, denominator {f(a.denominator,6)}. Selected x {f(a.values[state.feature],6)}, z {f(a.normalizedValues[state.feature],6)}, y {f(a.outputValues[state.feature],6)}. Scale {f(state.gamma[state.feature],2)}, Shift {f(state.beta[state.feature],2)} are shared with this feature in other tokens.</p>
  </LearningPage>;
}
