"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonAction, LessonRangeControl, LessonSelect, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeKMeans, assignKMeans, editKMeans, kmeansBaseline, kmeansChart, kmeansNumber as number, kmeansPresetId, kmeansScenarios, sameKMeans, updateKMeans, type KMeansState } from "./kmeans-engine";
import { kmeansExperiments } from "./learning-experiments";
import { reachedKMeans } from "./lesson-state";
import styles from "./playground.module.css";
const objects=[...Array.from({length:6},(_,i)=>({id:`P${i+1}`,label:`Point P${i+1}`})),...Array.from({length:2},(_,i)=>({id:`C${i+1}`,label:`Centroid C${i+1}`}))];
const colors=["#5031dc","#ad4508"];
export function KMeansPlayground() {
 const [state,setState]=useState<KMeansState>(kmeansBaseline),[object,setObject]=useState("P3"),[index,setIndex]=useState(0);
 const [prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const chartRef=useRef<HTMLDivElement>(null),[width,setWidth]=useState(440);
 useEffect(()=>{const el=chartRef.current;if(!el)return;const update=()=>setWidth(Math.max(260,el.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(el);return()=>observer.disconnect();},[]);
 const a=useMemo(()=>analyzeKMeans(state),[state]),chart=kmeansChart(state,width);
 const selected=(object[0]==="P"?state.points:state.centroids)[Number(object.slice(1))-1]!;
 const experiment=kmeansExperiments[index],transfer=index===3,reached=!!prediction&&!!experiment&&!!reachedKMeans(index,state),complete=reached&&explanation==="0";
 function clear(){setExplanation(null);setTransferAnswer(null);}
 function start(next=index){setIndex(next);setState(kmeansBaseline());setObject("P3");setPrediction(null);clear();}
 function edit(next:KMeansState){if(!sameKMeans(state,next)){setState(next);clear();}}
 const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="kmeans-prediction" explanationName="kmeans-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores Separated seeds, unassigned points and zero updates. Reset restarts this experiment.</>} observation={prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}
    onNext={()=>start(index+1)} nextLabel={index===2?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Move one point, rebuild the means":"Explore assign/update cycles"}>
  {transfer?<><p>Without Guide help, keep Separated seeds, choose Point P3, then set X coordinate=50 and Y coordinate=50 in either order. Press Assign points, then Update centroids. Reconstruct P3’s two initial distances and tie choice, the new coordinate means, held membership and total SSE. Decide whether those means must be observed points.</p>{reachedKMeans(3,state)&&<><ExperimentChoices legend="Transfer explanation" name="kmeans-transfer" choices={[
   {id:"means",label:"P3 initially has squared distance 2500 to both centers and joins C1 by the tie rule. Both groups have 3 members. Update gives C1=(30,110/3) and C2=(80,70), with held SSE=4400/3, about 1466.666667. Data points and assignments stay fixed during Update. A coordinate mean need not be an observed point, and this does not prove a global clustering optimum."},
   {id:"round",label:"The mean must be an observed point, so C1 should snap onto P3=(50,50)."},
   {id:"random",label:"P3 ties, so a random choice is required and the exact group means cannot be determined."},
  ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="means"?<p role="status" className={shared.feedback}>Try again. Use the explicit C1 tie rule, divide coordinate sums by each held count, and sum the six assigned squared distances.</p>:<><ExperimentResult title="Transfer explained">An edited point can change the means without moving any other data point. Assignment and Update remain separate; a mean can lie between observed points.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(4);clear();}}>Explore freely</ExperimentButton></>)}</>}</>:<><p>Try Swapped seeds, duplicate points or endpoints. For Coincident seeds, assign then update, then assign again: the previously empty center can gain members. Repeat cycles and inspect held memberships; stable centers do not prove a global optimum. Coordinate edits restart assignment so comparisons across changed datasets do not claim monotonic SSE.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
 </ExperimentRail>;
 return <LearningPage title="K-Means Clustering Studio" subtitle="Assign members. Then move their centroids." rail={rail}>
  <LessonToolbar scenarios={kmeansScenarios} selectedId={kmeansPresetId(state)} onSelect={id=>edit(kmeansBaseline(id))} onReset={()=>start(experiment||transfer?index:0)}/>
  <section className={shared.evidence} aria-label="Editable points and centroids"><h2>Your dataset</h2><p>Six authored points and two centroids, or group centers, share X/Y axes 0–100. Choose an object and edit its coordinates. Assign points chooses nearest centers by squared Euclidean distance, (X−center X)²+(Y−center Y)². Exact computed ties go to C1. Update centroids moves only the centers to their held members’ coordinate means.</p>
   <div className={styles.workbench}><div className={styles.chart} ref={chartRef}><svg data-kmeans-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label="Editable points as circles, C1 and C2 centers as diamonds on X/Y axes zero to100. Colors show held assignments only. Coincident marks may overlap; all exact IDs, coordinates, distances and members are in the following tables.">
    {chart.ticks.map(t=><g key={t.value}><line x1={t.x} x2={t.x} y1={chart.top} y2={chart.top+chart.span} className={styles.grid}/><line x1={chart.left} x2={chart.left+chart.span} y1={t.y} y2={t.y} className={styles.grid}/><text x={t.x} y={chart.top+chart.span+20} textAnchor="middle">{t.value}</text><text x={chart.left-9} y={t.y+4} textAnchor="end">{t.value}</text></g>)}
    {chart.points.map((p,i)=><g key={p.id} data-km-point={p.id}><title>{`${p.id} (${number(state.points[i]![0])},${number(state.points[i]![1])}), ${p.cluster===null?"unassigned":`C${p.cluster+1}`}`}</title><circle cx={p.x} cy={p.y} r={object===p.id?7:5} fill={p.cluster===null?"#536487":colors[p.cluster]} stroke={object===p.id?"#0c1230":"white"} strokeWidth="2"/><line x1={p.x} y1={p.y} x2={p.labelX} y2={p.labelY-4} className={styles.leader}/><text x={p.labelX} y={p.labelY} textAnchor="middle">{p.id}</text></g>)}
    {chart.centroids.map((c,i)=><g key={c.id} data-km-center={c.id}><title>{`${c.id} center (${number(state.centroids[i]![0])},${number(state.centroids[i]![1])})`}</title><path d={`M ${c.x} ${c.y-8} L ${c.x+8} ${c.y} L ${c.x} ${c.y+8} L ${c.x-8} ${c.y} Z`} fill={colors[i]} stroke={object===c.id?"#0c1230":"white"} strokeWidth="2"/><line x1={c.x} y1={c.y} x2={c.labelX} y2={c.labelY-4} className={styles.leader}/><text x={c.labelX} y={c.labelY} textAnchor="middle">{c.id}</text></g>)}
    <text x={chart.left+chart.span/2} y={chart.height-7} textAnchor="middle">X</text><text x="10" y={chart.top+chart.span/2} textAnchor="middle">Y</text>
   </svg><p>Circles are data points; diamonds are centers. Indigo indicates held C1, orange C2 and gray unassigned. IDs, shapes and tables accompany color. Coincident marks can overlap. Labels use separate positions and leader lines; the exact tables retain every object. The selected object has a navy outline.</p></div>
   <div className={shared.controlGrid} data-columns="1"><LessonSelect label="Selected object" choices={objects} value={object} onChange={setObject}/>{selected.map((value,axis)=><LessonRangeControl key={`${object}-${axis}`} label={`${axis===0?"X":"Y"} coordinate`} value={value} min={0} max={100} step="any" help={`Edit ${object}'s ${axis===0?"X":"Y"} value. Actual edits clear all assignments and restart at Ready. Means retain full precision; no coordinate grid is imposed.`} onChange={v=>edit(editKMeans(state,object,axis as 0|1,v))}/>)}<div className={styles.actions}><LessonAction onClick={()=>edit(assignKMeans(state))}>Assign points</LessonAction><LessonAction disabled={state.phase!=="assigned"} onClick={()=>edit(updateKMeans(state))}>Update centroids</LessonAction></div><p>Assign changes members without moving coordinates. Update changes centers without reassigning members. Assign again before the next Update. Empty centers keep their previous location.</p></div></div>
   <p role="status" data-km-status className={shared.math}>{state.phase==="ready"?"Ready · Not assigned":state.phase==="assigned"?"Assigned":"Updated · Membership held from last Assign"} · {state.updates} updates · C1=({state.centroids[0]!.map(number).join(",")}) · C2=({state.centroids[1]!.map(number).join(",")})</p><p>Coordinate edits clear stale explanations and transfer answers. Object inspection, unchanged exact edits and an unchanged Assign preserve them. Changing scenario restores its coordinates and unassigned state. The display rounds to six decimals; operations use full precision. Clusters have no known class labels.</p>
  </section>
  <LessonSummaries label="Held cluster members and assigned squared-distance sum" summaries={[
   ...a.groups.map((g,i)=>({label:`Cluster ${i+1} members`,color:colors[i]!,value:state.assignments===null?"Unassigned":String(g.count),definition:state.assignments===null?"Press Assign points first.":g.members.map(j=>`P${j+1}`).join(", ")||"No members",formula:`Current center: (${g.center.map(number).join(", ")})`,comparison:"Held from the last Assign points; Update does not reassign."})),
   {label:"Assigned SSE",color:"#0c1230",value:number(a.sse),definition:"Sum of squared distances to each point's held assigned center.",formula:"Σ (X − center X)² + (Y − center Y)²",comparison:"Squared coordinate units. Not class accuracy or a global-optimum certificate."},
  ]}/>
  <section className={shared.evidence} aria-label="Point and squared-distance evidence"><h2>All six points</h2><div className={`${shared.tableScroll} ${styles.table}`} tabIndex={0} role="region" aria-label="Six coordinates, current distances and held assignments"><table><caption>Distances and ties use current centers. Held assignment comes from the last Assign points and can differ from the current nearest center after Update.</caption><thead><tr>{["ID","X","Y","d² to C1","d² to C2","Current tie?","Held group","SSE term"].map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{state.points.map((p,i)=><tr key={i} data-km-row={i}><th scope="row">P{i+1}</th><td>{number(p[0])}</td><td>{number(p[1])}</td><td>{number(a.distances[i]![0]!)}</td><td>{number(a.distances[i]![1]!)}</td><td>{a.ties[i]?"Yes":"No"}</td><td>{state.assignments===null?"Unassigned":`C${state.assignments[i]!+1}`}</td><td>{state.assignments===null?"Not assigned":number(a.distances[i]![state.assignments[i]!]!)}</td></tr>)}</tbody></table></div><p data-km-sse className={shared.math}>{state.assignments===null?"SSE is not defined until points have assignments.":`Assigned SSE = ${state.assignments.map((c,i)=>number(a.distances[i]![c]!)).join(" + ")} = ${number(a.sse)}.`}</p></section>
  <section className={shared.evidence} aria-label="Centroid mean construction"><h2>Build the next centers</h2><div className={`${shared.tableScroll} ${styles.table}`} tabIndex={0} role="region" aria-label="Two centers and held-member mean construction"><table><caption>Each mean uses the currently held members. Update uses it only after Assign; a new assignment can change these means. Empty mean is undefined; this lab retains the current center.</caption><thead><tr>{["Center","Current X","Current Y","Count","Σ X","Σ Y","Mean X","Mean Y","Group SSE"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.groups.map((g,i)=><tr key={i} data-km-group={i}><th scope="row">C{i+1}</th><td>{number(g.center[0])}</td><td>{number(g.center[1])}</td><td>{state.assignments===null?"Unassigned":g.count}</td><td>{state.assignments===null?"Not assigned":number(g.sum[0])}</td><td>{state.assignments===null?"Not assigned":number(g.sum[1])}</td><td>{state.assignments===null?"Not assigned":g.mean?number(g.mean[0]):"Undefined"}</td><td>{state.assignments===null?"Not assigned":g.mean?number(g.mean[1]):"Undefined"}</td><td>{number(g.sse)}</td></tr>)}</tbody></table></div>{a.groups.map((g,i)=><p key={i} data-km-mean={i} className={shared.math}>{state.assignments===null?`C${i+1}: no assigned group yet.`:g.mean?`C${i+1}: (${number(g.sum[0])}/${g.count}, ${number(g.sum[1])}/${g.count}) = (${g.mean.map(number).join(", ")}).`:`C${i+1}: count 0; mean undefined; keep previous center (${g.center.map(number).join(", ")}). Empty group SSE contribution=0.`}</p>)}</section>
  <section className={shared.evidence} aria-label="K-Means construction and limits"><details><summary>Construction and limits</summary><p>This is a hand-authored, six-point, two-center Lloyd demonstration. Coordinates are finite values within 0–100; fractional coordinate means are not rounded onto a grid or snapped to observed points. The display rounds to six decimals. Squared distances, means, ties and subsequent operations use JavaScript full-precision arithmetic. Exact equality of computed distances uses a fixed C1 tie rule.</p><p>For a fixed dataset, Assign picks a nearest center and Update minimizes each nonempty held group’s squared-distance sum by using its coordinate means. Either action cannot increase SSE apart from floating-point roundoff. Empty centers stay where they were; other algorithms/libraries can choose a different policy. Updating changes current distance ties without retroactively changing the last assignment. Another Assign may give an empty center members.</p><p>Initialization can change a local result; swapping center IDs merely renames equivalent groups. Stable assignments or centers do not guarantee a globally best clustering. No known classes, supervised accuracy, probability, learned embedding, choice of K, scaling study, automatic iterations or recommended seed strategy is supplied. Edits change the dataset/centers and restart assignment; monotonic SSE is not claimed across manual edits. Reset/prediction restores Separated seeds for the current experiment; free Reset restarts Experiment 1.</p><a href="https://www-nlp.stanford.edu/IR-book/html/htmledition/k-means-1.html" target="_blank" rel="noreferrer">Stanford · K-Means assignment, mean update and local optima</a></details></section>
 </LearningPage>;
}
