"use client";
import { useState } from "react";
import { ExperimentButton,ExperimentChoices,ExperimentRail,ExperimentResult,LearningPage,LessonAction,LessonRangeControl,LessonSelect,LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { commitProofRound,edgeById,formatProbability,graphEdges,graphNodes,initialProofState,openProofEdge,proofTheory,uniformIndex,type ProofState,type ProverMode } from "./zero-knowledge-proofs-engine";
import { experimentBaseline,proofExperiments,reachedExperiment } from "./learning-experiments";
import { EscapeFigure,ProofGraph } from "./ProofFigures";
import styles from "./playground.module.css";
function sample(size:number){return uniformIndex(size,()=>crypto.getRandomValues(new Uint32Array(1))[0]);}
export function ZeroKnowledgeProofsPlayground(){
  const [state,setState]=useState<ProofState>(initialProofState()),[index,setIndex]=useState(0);
  const [prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
  const experiment=proofExperiments[index],transfer=index===5,reached=!!prediction&&!!experiment&&reachedExperiment(index,state),complete=reached&&explanation==="0";
  const current=state.current,row=current?.opened,committed=!!current&&!row,theory=proofTheory(state.rounds),opened=row?{[row.edge.from]:row.openedColors[0],[row.edge.to]:row.openedColors[1]}:{};
  function clear(){setExplanation(null);setTransferAnswer(null);}
  function edit(next:ProofState){setState(next);clear();}
  function start(next=index){setIndex(next);setState(experimentBaseline(next,next===0||next===4?0:sample(6)));setPrediction(null);clear();}
  function open(random=false){const edge=random?graphEdges[sample(graphEdges.length)].id:state.edge;edit(openProofEdge(state,edge,random?"random":"selected"));}
  const rail=experiment?<ExperimentRail label={`Experiment ${index+1} of 5`} title={experiment.title} phase={!prediction?0:reached?2:1}>
    {!reached&&<><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="proof-prediction" choices={experiment.predictions} value={prediction} onChange={id=>{start();setPrediction(id);}}/><p className={shared.small}>A different prediction restores the exercise’s starting settings. Reset restarts this experiment.</p></>}
    {prediction&&!reached&&<p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
    {reached&&<><p role="status" className={shared.observation}>{prediction==="0"?"Your prediction matches the evidence.":"The opened evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="proof-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation}/>{explanation&&!complete&&<p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
    {complete&&<><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={()=>start(index+1)}>{index===4?"Try the transfer check":"Next experiment"}</ExperimentButton></>}
  </ExperimentRail>:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"A passing invalid coloring":"Explore local checks"}>
    {transfer?<><p>A fresh cheating round is committed with A-B selected. Without Guide help, open that edge and decide whether one pass repairs the coloring or proves the prover honest.</p><ExperimentChoices legend="Transfer explanation" name="proof-transfer" choices={[{id:"local",label:"A-B passes, but C-D and A-E are still invalid. This manual local check proves neither whole-coloring validity nor honesty; another edge needs a fresh commitment."},{id:"certain",label:"One pass makes the whole coloring valid and the prover certainly honest."},{id:"rerun",label:"Changing theoretical k silently checks all remaining edges."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!reachedExperiment(5,state)?<p role="status" className={shared.feedback}>First press Open selected edge for A-B, keeping Cheating prover. Reset restores the committed starting round.</p>:transferAnswer!=="local"?<p role="status" className={shared.feedback}>Try again. Inspect this passing edge separately from the invalid C-D and A-E edges. The theoretical formula is not a posterior probability of honesty.</p>:<><ExperimentResult title="Transfer explained">A local pass can coexist with an invalid coloring. Every new edge opening requires a fresh round; manually selected examples and independent random repetition answer different questions.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(6);clear();}}>Explore freely</ExperimentButton></>)}</>:<><p>Choose either prover. Commit round, then choose and open an edge or use Open random edge. Repeat with fresh commitments. Theoretical k changes no history. Reset restarts experiments.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Zero-Knowledge Proofs" subtitle="Commit colors, open one edge, and separate a local check from repeated evidence." rail={rail}>
    <LessonToolbar label="Prover examples" scenarios={[{id:"honest",label:"Honest prover",shortLabel:"Valid coloring"},{id:"cheating",label:"Cheating prover",shortLabel:"Two invalid edges"}]} selectedId={state.mode} onSelect={id=>edit(initialProofState(id as ProverMode,state.rounds))} onReset={()=>start(experiment||transfer?index:0)}/>
    <section className={styles.evidence} aria-label="Proof round"><h2>Your proof round</h2><p>A coloring gives each vertex one of three colors. Valid edges join different colors. A commitment hides a value and prevents changing it after the challenge. This visual simulation makes no cryptographic commitments; both roles and their example colors live in this browser.</p>
      <p className={styles.view} role="status" data-round-status>{current?`Round ${current.number} · ${row?"Opened":"Committed"}`:"No round committed"}{row?` · ${row.verdict.toUpperCase()}`:""}</p>
      <div className={styles.actions}><LessonAction disabled={committed} onClick={()=>edit(commitProofRound(state,sample(6)))}>Commit round</LessonAction><fieldset disabled={!committed}><LessonSelect label="Challenge edge" choices={graphEdges.map(e=>({id:e.id,label:e.id}))} value={state.edge} onChange={id=>{edgeById(id);edit({...state,edge:id});}}/></fieldset><LessonAction disabled={!committed} onClick={()=>open()}>Open selected edge</LessonAction><LessonAction disabled={!committed} onClick={()=>open(true)}>Open random edge</LessonAction></div>
      <p className={shared.small}>Commit before choosing a challenge. Open only one edge per round. Open random edge samples uniformly with replacement after commitment; selecting an edge is a controlled example.</p>
      <ProofGraph state={state}/><p className={styles.view} data-verifier-view>{row?`Current verifier view: ${row.edge.from}=${row.openedColors[0]}, ${row.edge.to}=${row.openedColors[1]}; ${row.verdict.toUpperCase()} (${row.verdict==="pass"?"different":"same"} colors). Six other colors remain hidden in this view.`:current?"Current verifier view: all eight colors are committed; no colors opened.":"Current verifier view: no colors opened; press Commit round first."}</p>
      <details><summary>Node values and public edges</summary><div className={styles.table} tabIndex={0} role="region" aria-label="Node values table scroll area"><table><caption>Only this round’s opened colors. Every vertex and all nine edges are public.</caption><thead><tr><th scope="col">Vertex</th><th scope="col">Verifier view</th></tr></thead><tbody>{graphNodes.map(n=><tr key={n.id} data-node-value={n.id}><th scope="row">{n.id}</th><td>{opened[n.id]??(current?"Hidden":"Not committed")}</td></tr>)}</tbody></table></div><p>Edges: {graphEdges.map(e=>e.id).join(", ")}.</p></details>
      <details><summary>Transcript · completed openings</summary><p data-history-count>{state.history.length} completed opening{state.history.length===1?"":"s"} in this view. Only the most recent 20 are retained. Switching prover or restarting an exercise clears history.</p><div className={styles.table} tabIndex={0} role="region" aria-label="Transcript table scroll area"><table><caption>Actual completed illustration rounds; prepared exercise openings are marked Starting example. No future rounds are listed.</caption><thead><tr><th scope="col">Round</th><th scope="col">Edge</th><th scope="col">Endpoint colors</th><th scope="col">Verdict</th><th scope="col">Challenge</th><th scope="col">Origin</th></tr></thead><tbody>{state.history.map(r=><tr key={r.round} data-history-round={r.round}><td>{r.round}</td><td>{r.edge.id}</td><td>{r.openedColors.join(" / ")}</td><td>{r.verdict.toUpperCase()}</td><td>{r.challenge==="random"?"Uniform random":"Selected example"}</td><td>{r.origin==="learner"?"Your action":"Starting example"}</td></tr>)}</tbody></table></div></details>
    </section>
    <section className={styles.evidence} aria-label="Independent random repetition"><h2>Theory · repeated random checks</h2><p>The fixed cheating coloring has seven passing edges and two invalid edges (C-D, A-E). One uniform random edge passes with probability 7/9 and catches it with probability 2/9. The honest coloring passes every edge under this idealized model.</p><div className={styles.theory}><div><LessonRangeControl label="Theoretical random rounds (k)" value={state.rounds} min={1} max={20} step={1} help="This changes a theoretical probability, never runs rounds or adds transcript rows." onChange={rounds=>edit({...state,rounds})}/><p className={styles.formula} data-escape-formula>P(all k checks pass | this fixed invalid coloring) = (7/9)^{state.rounds} = {formatProbability(theory.escapeProbability)}.</p><p data-percent>About {Number((100*theory.escapeProbability).toPrecision(6))}% escape. This is not a probability that the prover is honest.</p><p>Assume uniform independent edge challenges, with replacement, and fresh commitments each round. The same edge may repeat. A manually selected sequence, sampling without replacement, or a different malicious strategy needs a different calculation.</p></div><EscapeFigure rounds={state.rounds}/></div>
      <details><summary>Exact integer-round probabilities</summary><div className={styles.table} tabIndex={0} role="region" aria-label="Probability table scroll area"><table><caption>Independent uniform challenges of this fixed invalid coloring, including k=0.</caption><thead><tr><th scope="col">k</th><th scope="col">All-pass probability</th></tr></thead><tbody>{theory.chartPoints.map(p=><tr key={p.rounds} data-theory-round={p.rounds}><th scope="row">{p.rounds}</th><td>{formatProbability(p.probability)}</td></tr>)}</tbody></table></div></details>
      <details><summary>What this model includes</summary><p>Eight vertices, nine public edges and two fixed supplied colorings. The graph is colorable; the cheating example supplies an invalid coloring, not a graph with no valid coloring. A global color permutation preserves all equality/difference checks. Real commitments must hide and bind, and opening checks must match the original commitments; grey boxes only illustrate these constraints.</p><p>New rounds independently sample one of six color permutations. A repeated visible color pair can occur by chance. A round number is an identifier, not the permutation or a secrecy measurement. Opening many edges of one committed coloring would leak that coloring, so each commitment can be opened once. Randomness does not make the page itself a secure protocol: the source contains the example colorings, both roles execute together and no cryptographic commitments or formal simulator run here.</p><p>Under ideal hiding commitments, an honest edge’s six ordered distinct color pairs are equally likely after a uniform permutation. They can be simulated without its original coloring; that is the intuition for zero knowledge. A complete cryptographic proof, arbitrary adversarial strategies and modern proof systems are outside this illustration.</p><p><a href="https://zkproof.org/2020/08/12/information-theoretic-proof-systems/" target="_blank" rel="noreferrer">Yuval Ishai’s graph-coloring protocol explanation</a> · <a href="https://zoo.cs.yale.edu/classes/cs461/2009/attach/ln19.html" target="_blank" rel="noreferrer">Yale cryptography notes: commitments and graph coloring</a></p></details>
    </section>
  </LearningPage>;
}
