"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonAction, LessonToolbar, LessonToggleGroup } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeBias, biasChart, biasScenarios, keepProbability, type BiasScenario, type BiasState } from "./bias-engine";
import { biasBaseline, reachedBias } from "./lesson-state";
import { biasExperiments } from "./learning-experiments";
import styles from "./playground.module.css";
const signed=(v:number)=>`${v>=0?"+":""}${v.toFixed(4)}`;
export function BiasPlayground(){
  const [state,setState]=useState<BiasState>(()=>biasBaseline()),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null),[width,setWidth]=useState(640);
  const chartRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const element=chartRef.current;if(!element)return;const update=()=>setWidth(Math.max(200,element.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(element);return()=>observer.disconnect();},[]);
  const a=useMemo(()=>analyzeBias(state),[state]),chart=biasChart(a,width),experiment=biasExperiments[index],transfer=index===5,reached=!!prediction&&!!experiment&&reachedBias(index,state),complete=reached&&explanation==="0";
  function clear(){setExplanation(null);setTransferAnswer(null);}
  function start(next=index){setIndex(next);setState(biasBaseline(next));setPrediction(null);clear();}
  function edit(patch:Partial<BiasState>){setState(s=>({...s,...patch}));clear();}
  const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 5`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="bias-prediction" explanationName="bias-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores this experiment’s starting scenario, method, size and sample number. Reset restarts it.</>} observation={prediction==="0"?"The observed evidence matches your prediction.":"The evidence challenges your prediction."}
    onNext={()=>start(index+1)} nextLabel={index===4?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"New sample, same response bias":"Inspect other collection rules"}>
    {transfer?<><p>Without Guide help, choose Nonresponse and Biased collection. Set Observed sample size to 1000 and Sample number to 7. Explain expected bias and the selected sample’s gap.</p><ExperimentChoices legend="Transfer explanation" name="bias-transfer" choices={[{id:"bias",label:"The selected mean is 6.88, with observed gap +1.38 from population mean 5.5. Collection expectation is 7 and expected bias remains +1.5. More observed responses did not make collection unbiased."},{id:"exact",label:"A sample of 1000 must equal 5.5, so any difference means the population changed."},{id:"gap",label:"Expected bias is exactly +1.38 because that is this selected sample’s gap."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!reachedBias(5,state)?<p role="status" className={shared.feedback}>First choose Nonresponse, Biased collection, Observed sample size 1000 and Sample number 7. Compare the exact selected evidence.</p>:transferAnswer!=="bias"?<p role="status" className={shared.feedback}>Try again. One sample’s gap is not its repeated-sampling expected bias. Size does not change the declared observation probabilities.</p>:<><ExperimentResult title="Transfer explained">Total 6880 / 1000 = 6.88, giving observed gap +1.38. Collection expectation 7 minus population mean 5.5 gives expected bias +1.5. These quantities need not match.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(6);clear();}}>Explore freely</ExperimentButton></>)}</>:<><p>Change the observation stage, method, size or sample number. Next sample stops at 20; the exact editor can revisit any prepared sample. Keep the target fixed at the original population while comparing observed expectations. Reset returns to Experiment 1.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Sampling Bias Lab" subtitle="Change who gets observed, then change sample size." rail={rail}>
    <LessonToolbar label="Observation stages" scenarios={biasScenarios} selectedId={state.scenario} onSelect={scenario=>edit({scenario:scenario as BiasScenario})} onReset={()=>start(experiment||transfer?index:0)}/>
    <section className={shared.evidence} aria-label="Collection controls"><LessonToggleGroup label="Collection method" choices={[{id:"ideal",label:"Ideal random"},{id:"biased",label:"Biased collection"}]} value={state.rule} onChange={rule=>edit({rule:rule as BiasState["rule"]})}/><p>The synthetic population has ten equally weighted records, values 1–10, with mean 5.5. The target is always all original records. Sampling uses replacement, so records can repeat.</p><p data-mechanism>{state.rule==="biased"?a.scenario.mechanism:"Ideal random benchmark: every original record has equal chance and is observed. This counterfactual comparison does not promise to force real responses or recover exited records."}</p><div className={shared.controlGrid}><LessonRangeControl label="Observed sample size" value={state.size} min={1} max={1000} step={1} help="Show more or fewer retained observations from the same prepared sample." onChange={size=>edit({size})}/><LessonRangeControl label="Sample number" value={state.sample} min={1} max={20} step={1} help="Select another prepared sample under the same method and size." onChange={sample=>edit({sample})}/></div><div className={styles.actions}><LessonAction disabled={state.sample===20} onClick={()=>edit({sample:Math.min(20,state.sample+1)})}>Next sample</LessonAction></div><p role="status" data-bias-status>Showing sample {state.sample} of 20, with {state.size} observed records. {a.scenario.label} · {state.rule==="ideal"?"Ideal random":"Biased collection"}.</p></section>
    <section className={shared.evidence} aria-label="Repeated observed estimates"><h2>20 sample estimates</h2><p>Each numbered dot is a sample mean, not an individual record. A double ring marks the selected sample. Orange dashed reference: population mean {a.target}. Blue dotted reference: collection expectation {a.expectation.toFixed(4)}. {state.rule==="ideal"?"The two references coincide in the ideal benchmark.":"The reference gap is expected bias."}</p><div className={styles.chart} ref={chartRef}><svg viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`Twenty observed sample means at size ${state.size}. Selected sample ${state.sample} averages ${a.current.mean.toFixed(4)}. Population mean 5.5, collection expectation ${a.expectation.toFixed(4)}. Exact means in optional table below.`} data-bias-chart><text x="4" y="16">Sample</text><text x={chart.width-4} y="16" textAnchor="end">Mean</text><line x1={chart.targetX} x2={chart.targetX} y1={chart.top-9} y2={chart.baseline} data-population-mean/><line x1={chart.expectationX} x2={chart.expectationX} y1={chart.top-9} y2={chart.baseline} data-collection-expectation/>{chart.rows.map(r=><g key={r.number} data-sample={r.number} data-selected={r.selected}><text x={chart.left-14} y={r.y+4} textAnchor="end">{r.number}</text><circle cx={r.x} cy={r.y} r="3.5"/>{r.selected&&<circle cx={r.x} cy={r.y} r="6.5" data-selected-ring/>}<text x={chart.width-4} y={r.y+4} textAnchor="end">{r.mean.toFixed(4)}</text></g>)}<line x1={chart.left} x2={chart.width-chart.right} y1={chart.baseline} y2={chart.baseline}/>{chart.ticks.map((t,i)=><text key={t.value} x={t.x} y={chart.baseline+19} textAnchor={i===0?"start":i===2?"end":"middle"}>{t.value}</text>)}<text x={(chart.left+chart.width-chart.right)/2} y={chart.height-3} textAnchor="middle">Observed sample mean · fixed 1–10 scale</text></svg></div><p data-estimate-range>Twenty means range from {a.meanMinimum.toFixed(4)} to {a.meanMaximum.toFixed(4)}. This finite illustrative batch is not the exact sampling distribution. Increasing size keeps the same full-population axis.</p></section>
    <LessonSummaries label="Observation and collection targets" summaries={[{label:"Observed mean",color:"#5031dc",value:a.current.mean.toFixed(4),definition:"Statistic from retained observations.",formula:`${a.current.total} / ${state.size}`},{label:"Population mean",color:"#ad4508",value:"5.5000",definition:"Target: all ten original records.",formula:"(1 + 2 + … + 10) / 10"},{label:"Collection expectation",color:"#1f6486",value:a.expectation.toFixed(4),definition:"Expected mean under this collection rule.",formula:"Σ(value × keep chance) / Σ(keep chance)"}]}/>
    <section className={shared.evidence} aria-label="Selected sample and observation rule"><p className={shared.math} data-selected-sample>Sample {state.sample}: total {a.current.total} / observed size {state.size} = mean {a.current.mean.toFixed(4)}. Signed observed gap = {a.current.mean.toFixed(4)} − 5.5 = {signed(a.gap)}. Expected bias = {a.expectation.toFixed(4)} − 5.5 = {signed(a.bias)}.</p><p data-candidates>Simulator candidate attempts to obtain these observations: {a.current.attempts}. Recent observed values: {a.current.values.slice(-8).join(", ")}. Observed size counts retained records. Candidates represent invitations in Nonresponse; elsewhere they are simulator proposals, not actual invitations to excluded or exited records.</p><details><summary>Original records and observation probabilities</summary><table className={`${shared.dataTable} ${styles.table}`}><caption>Original target remains all ten records. Conditional observed share = keep chance / sum of keep chances.</caption><thead><tr><th scope="col">Value</th><th scope="col">Declared biased mechanism</th><th scope="col">Active keep chance</th><th scope="col">Observed share</th></tr></thead><tbody>{a.population.map((v,i)=><tr key={v}><th scope="row">{v}</th><td>{state.scenario==="frame"?(v>=6?"In frame":"Outside frame"):state.scenario==="response"?`Response ${keepProbability(state.scenario,v)}`:v>=4?"Survived":"Exited"}</td><td>{a.weights[i].toFixed(1)}</td><td>{(a.weights[i]/a.weightTotal).toFixed(4)}</td></tr>)}</tbody></table></details><details><summary>Exact means of the 20 samples</summary><table className={`${shared.dataTable} ${styles.table}`}><caption>Same method and size {state.size}; selected sample labelled.</caption><thead><tr><th scope="col">Sample</th><th scope="col">Total</th><th scope="col">Mean</th><th scope="col">Candidate attempts</th></tr></thead><tbody>{a.samples.map(s=><tr key={s.number}><th scope="row">{s.number}{s.number===state.sample?" · selected":""}</th><td>{s.total}</td><td>{s.mean.toFixed(4)}</td><td>{s.attempts}</td></tr>)}</tbody></table></details></section>
    <section className={shared.evidence} aria-label="Model assumptions"><details><summary>Assumptions and reproducible collection</summary><p>The original target is a fixed bounded toy population. Every candidate independently selects one of ten records uniformly with replacement. The biased mechanism changes observation probability; every accepted record remains available for later draws. Nonresponse is newly simulated per invitation, while frame membership and survivor flags are fixed. These are illustrative mechanisms, not a causal model of why real records disappear.</p><p>A seed-1309 32-bit generator prepares 20 nonoverlapping blocks of 10000 candidate attempts, consuming two uniform positions per attempt. The first chooses a record, the second tests observation probability. Each sample shows its first n accepted records. Size edits preserve that retained prefix; changing scenario or method filters the same candidates. Finite pseudorandom blocks do not prove independence, convergence or monotone improvement.</p><p>Expected bias concerns the collection expectation minus the original target; one observed gap is finite sample error. These rules push upward by construction. Missingness need not bias a mean, and real bias can have either sign. Survivor-only sampling can suit a survivor-only target; here the target deliberately includes exited records. Ideal random is a comparison, not a practical correction promise. Weighting, standard error, intervals and identification from missing data are outside this lesson.</p><a href="https://www.stat.berkeley.edu/users/stark/SticiGui/Text/sampling.htm" target="_blank" rel="noreferrer">Berkeley SticiGui · Frame and nonresponse bias</a><br/><a href="https://haas.berkeley.edu/wp-content/uploads/survivors.pdf" target="_blank" rel="noreferrer">Stambaugh · Inference about survivors</a></details></section>
  </LearningPage>;
}
