"use client";
import { useMemo, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSelect, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import sharedStyles from "@/components/learning-page/learning-page.module.css";
import { analyzeTransformerAttention, formatScore, formatWeight } from "./transformer-attention-engine";
import { attentionDimensions, attentionScenarios, type AttentionScenarioId, type AttentionVector } from "./scenario";
import { attentionDefaults, attentionExperiments, attentionToolbarScenarios, attentionTransferStart, attentionTransferTarget, type AttentionState } from "./learning-experiments";
import styles from "./playground.module.css";
const tuple = (v: number[]) => `[${v.map(x => x.toFixed(5)).join(", ")}]`;
const valueTuple = (v: AttentionVector) => tuple(attentionDimensions.map(d => v[d.id]));
const same = (a: AttentionState, b: AttentionState) => a.scenario === b.scenario && a.query === b.query && a.sharpness === b.sharpness;
const presets = [{ id: "0.6", label: "Low" }, { id: "1.9", label: "Mid" }, { id: "3.2", label: "High" }];
export function TransformerAttentionPlayground() {
  const [state, setState] = useState<AttentionState>(attentionDefaults);
  const [index, setIndex] = useState(0);
  const [prediction, setPrediction] = useState<string | null>(null);
  const [explanation, setExplanation] = useState<string | null>(null);
  const [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const scenario = attentionScenarios.find(s => s.id === state.scenario)!;
  const analysis = useMemo(() => analyzeTransformerAttention(scenario, state.query, state.sharpness), [scenario, state.query, state.sharpness]);
  const experiment = attentionExperiments[index], transfer = index === 4;
  const reached = !!experiment && !!prediction && same(state, experiment.target);
  const complete = reached && explanation === experiment?.correctExplanation;
  const transferReached = same(state, attentionTransferTarget);
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function edit(next: AttentionState) { setState(next); clear(); }
  function start(next = index) { setIndex(next); setState(attentionExperiments[next]?.baseline ?? attentionTransferStart); setPrediction(null); clear(); }
  const rail = experiment ? <GuidedExperiment label={`Experiment ${index + 1} of 4`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="attention-prediction" explanationName="attention-explanation"
    onPredict={id => { start(); setPrediction(id); }} onExplain={setExplanation}
    predictionHelp={<>A different prediction restores this experiment’s starting state. Reset restarts it.</>} observation={prediction === experiment.correctPrediction ? "Your prediction matches the evidence." : "The scores, weights and mixed output challenge your prediction."}
    onNext={() => start(index + 1)} nextLabel={index === 3 ? "Try the transfer check" : "Next experiment"} /> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Transfer to query cash" : "Follow another query"}>
    {transfer ? <><p>Money Bank starts with query cash at sharpness 0.6. Predict: can positive sharpness change the key ranking or remove every other value? Set Attention sharpness to 3.2, then compare cash’s weight and the Finance feature with cash’s V.</p><ExperimentChoices legend="Transfer explanation" name="attention-transfer" choices={[{ id: "mix", label: "cash stays highest, rising from 20.07% to 38.83%, still below half. Finance rises from 0.37811 to 0.56743, not cash’s V of 1. All values still contribute." }, { id: "swap", label: "Higher sharpness changes the highest-score key, so bank must overtake cash." }, { id: "copy", label: "High gives cash 100% and copies its V unchanged." }]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (!transferReached ? <p role="status" className={sharedStyles.feedback}>First keep Money Bank and query cash, then set Attention sharpness to 3.2. Reset restores the transfer starting state.</p> : transferAnswer !== "mix" ? <p role="status" className={sharedStyles.feedback}>Try again. Positive sharpness preserves score order. Read all six positive weights and the contribution sum; the largest is still below half.</p> : <><ExperimentResult title="Transfer explained">Only sharpness changed in this comparison. It concentrates weights without changing their order, and the output remains a mixture of values.</ExperimentResult><ExperimentButton onClick={() => setIndex(5)}>Explore freely</ExperimentButton></>)}</> : <><p>Select any original query or sharpness. Use the arithmetic to connect Q/K scores to weights and the contribution sum to output. Compare fixtures without claiming an isolated context effect.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Transformer Attention" subtitle="Compare keys. Normalize weights. Mix values." rail={rail}>
    <LessonToolbar label="Attention fixtures" scenarios={attentionToolbarScenarios} selectedId={state.scenario} onSelect={id => edit({ scenario: id as AttentionScenarioId, query: "bank", sharpness: state.sharpness })} onReset={() => start(experiment || transfer ? index : 0)} />
    <p className={styles.context}>One unmasked toy attention head. Q, K and V are hand-authored: no model training or learned word meanings. Every modeled token can receive weight, including the query itself and later positions.</p>
    <section className={sharedStyles.evidence} aria-label="Modeled tokens and attention controls"><h2>Your modeled tokens</h2><p>Original context sentence: <strong>{scenario.sentence}</strong></p><p>Six simplified modeled tokens: <span className={sharedStyles.math}>{scenario.tokens.map(t => t.label).join(" · ")}</span>. {state.scenario === "river-bank" ? "The second the is omitted from this toy; this is not a complete tokenizer." : "This is a fixed toy token list, not a complete tokenizer."}</p>
      <LessonSelect label="Query token" choices={scenario.tokens.map(t => ({ id: t.id, label: t.label }))} value={state.query} onChange={query => edit({ ...state, query })} />
      <LessonRangeControl label="Attention sharpness" value={state.sharpness} min={0.6} max={3.2} step={0.1} onChange={sharpness => edit({ ...state, sharpness })} help="Multiply scaled scores before softmax. Higher means less uniform here; it preserves their rank. Equivalent temperature = 1 / sharpness." />
      <div className={styles.presets}><LessonToggleGroup label="Sharpness presets" choices={presets} value={String(state.sharpness)} onChange={id => edit({ ...state, sharpness: Number(id) })} /></div>
    </section>
    <section className={sharedStyles.evidence} aria-label="Attention weights"><h2>Weights from query {analysis.queryToken.label}</h2><p className={sharedStyles.math}>Q = {tuple(analysis.queryToken.query)}<br />scoreᵢ = Q · Kᵢ / √3 · weightᵢ = softmax({state.sharpness} × score)ᵢ</p><p>Softmax normalizes exponentiated scores into positive weights that add to 1. Each lane uses the same 0–100% scale, with no minimum bar width.</p>
      <div className={styles.axis} aria-hidden="true"><span>0%</span><span>50%</span><span>100%</span></div>
      <div className={styles.lanes}>{analysis.weights.map(entry => <div key={entry.token.id} className={styles.lane} data-token={entry.token.id}><strong>{entry.token.label}{entry.token.id === state.query && <small> · Q</small>}</strong><div className={styles.track} aria-hidden="true"><span className={styles.weightBar} style={{ width: `${(100 * entry.weight).toPrecision(6)}%` }} /></div><output aria-label={`${entry.token.label} attention weight`}>{formatWeight(entry.weight)}</output></div>)}</div><p>{analysis.summary}</p>
    </section>
    <LessonSummaries label="Weight distribution" summaries={[{ label: "Largest weight", value: formatWeight(analysis.topWeight), color: "#5031dc", definition: `Highest-weight ${analysis.topTokens.length > 1 ? "tokens (tied)" : "token"}: ${analysis.topTokens.map(t => t.label).join(", ")}.`, formula: "All attention weights sum to 100%", comparison: analysis.topWeight < 0.5 ? "Largest is below half. It is not a majority or a causal-importance proof." : "A large routing weight alone does not establish causal importance." }, { label: "Entropy", value: `${analysis.entropy.toFixed(5)}`, color: "#1760db", definition: "Spread of the weight distribution, in nats (natural-log units).", formula: "H = −Σ weight × ln(weight)", comparison: `Maximum at uniform weights: ln(6) = ${Math.log(6).toFixed(5)} nats. Relative spread H/ln(6) = ${analysis.normalizedEntropy.toFixed(5)}.` }]} />
    <section className={sharedStyles.evidence} aria-label="Mixed value output"><h2>Mixed value output</h2><p>output = Σ weightᵢ × Vᵢ. Each feature has arbitrary toy units; these three numbers are not class probabilities and need not sum to 1. Values here lie on a common 0–1 scale.</p><div className={styles.features}>{attentionDimensions.map(d => <div className={styles.feature} key={d.id}><strong>{d.label}</strong><div className={styles.track} aria-hidden="true"><span className={styles.valueBar} style={{ width: `${(100 * analysis.outputVector[d.id]).toPrecision(6)}%`, background: d.color }} /></div><output aria-label={`Output ${d.label}`}>{analysis.outputVector[d.id].toFixed(5)}</output></div>)}</div></section>
    <section className={sharedStyles.evidence} aria-label="Weighted value contributions"><h2>Weighted value contributions</h2><p>Multiply each V by its attention weight, then add all six rows. Keys choose weights; values supply content. Products are rounded for display; sums use full precision.</p><div className={styles.scroller} role="region" aria-label="Scrollable value contributions" tabIndex={0}><table><caption>Value coordinates in order: Shore, Finance, Glue. All six tokens contribute.</caption><thead><tr><th scope="col">Token</th><th scope="col">Weight</th><th scope="col">Value V</th><th scope="col">Weight × V</th></tr></thead><tbody>{analysis.weights.map(entry => <tr key={entry.token.id}><th scope="row">{entry.token.label}</th><td>{formatWeight(entry.weight)}</td><td>{valueTuple(entry.token.value)}</td><td>{valueTuple(entry.contribution)}</td></tr>)}</tbody><tfoot><tr><th scope="row">Sum</th><td>100%</td><td>—</td><td>{valueTuple(analysis.outputVector)}</td></tr></tfoot></table></div></section>
    <section className={styles.optional} aria-label="Supporting attention evidence"><details><summary>Q, K and V arithmetic</summary><p>Q uses the selected token’s query vector. Multiply matching Q/K coordinates and add, then divide by √3. Softmax uses exp(focused score − maximum) divided by the sum of these shifted exponentials; subtracting the same maximum is numerically stable and preserves weights.</p><div className={styles.scroller} role="region" aria-label="Scrollable attention arithmetic" tabIndex={0}><table><caption>All source vectors and score stages; values are shown in the contribution table.</caption><thead><tr><th scope="col">Token</th><th scope="col">Stored Q</th><th scope="col">Key K</th><th scope="col">Q(selected) · K</th><th scope="col">Score / √3</th><th scope="col">Sharpness × score</th><th scope="col">Weight</th></tr></thead><tbody>{analysis.weights.map(entry => <tr key={entry.token.id}><th scope="row">{entry.token.label}</th><td>{tuple(entry.token.query)}</td><td>{tuple(entry.token.key)}</td><td>{formatScore(entry.rawScore * Math.sqrt(3))}</td><td>{formatScore(entry.rawScore)}</td><td>{formatScore(entry.focusedScore)}</td><td>{formatWeight(entry.weight)}</td></tr>)}</tbody></table></div></details>
      <details><summary>Compare the two fixtures</summary><p>Both rows select bank at the current sharpness. This switch changes bank’s Q and the fixture’s K/V arrays together. It cannot isolate a context-only effect or prove learned language understanding.</p><div className={styles.scroller} role="region" aria-label="Scrollable fixture comparison" tabIndex={0}><table><thead><tr><th scope="col">Fixture</th><th scope="col">bank Q</th><th scope="col">Sharpness</th><th scope="col">Highest-weight token</th><th scope="col">Weight</th><th scope="col">Mixed output</th></tr></thead><tbody>{attentionScenarios.map(s => { const a = analyzeTransformerAttention(s, "bank", state.sharpness); return <tr key={s.id}><th scope="row">{s.label}</th><td>{tuple(a.queryToken.query)}</td><td>{state.sharpness}</td><td>{a.topTokens.map(t => t.label).join(", ")}</td><td>{formatWeight(a.topWeight)}</td><td>{valueTuple(a.outputVector)}</td></tr>; })}</tbody></table></div></details></section>
    <p className={styles.context}>This shows one attention-head output. Learned projections, multiple heads, output projection, residual connections, feedforward layers and causal masks are outside this lab. Attention weights alone do not explain a full model’s decisions.</p>
    <p role="status" aria-live="polite" aria-atomic="true" className={sharedStyles.liveUpdate}>{scenario.label}, query {analysis.queryToken.label}, sharpness {state.sharpness}. Largest weight {formatWeight(analysis.topWeight)} for {analysis.topTokens.map(t => t.label).join(", ")}. Entropy {analysis.entropy.toFixed(5)} nats. Mixed values {valueTuple(analysis.outputVector)}.</p>
  </LearningPage>;
}
