"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonAction, LessonRangeControl, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeRegularization, changeRegularizationStrength, changeRegularizationWeight, fitRegularization, penaltyModes, regularizationChart, regularizationNumber as number, regularizationPresetId, regularizationPresets, regularizationScenarios, sameRegularization, type PenaltyMode, type RegularizationState } from "./regularization-engine";
import { reachedRegularization, regularizationBaseline } from "./lesson-state";
import { regularizationExperiments } from "./learning-experiments";
import styles from "./playground.module.css";

export function RegularizationPlayground() {
 const [state,setState]=useState<RegularizationState>(regularizationBaseline);
 const [index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const chartRef=useRef<HTMLDivElement>(null),[width,setWidth]=useState(440);
 useEffect(()=>{const el=chartRef.current;if(!el)return;const update=()=>setWidth(Math.max(260,el.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(el);return()=>observer.disconnect();},[]);
 const a=useMemo(()=>analyzeRegularization(state),[state]),fit=useMemo(()=>fitRegularization(state),[state]),chart=regularizationChart(state,width);
 const experiment=regularizationExperiments[index],transfer=index===3,reached=!!prediction&&!!experiment&&reachedRegularization(index,state),complete=reached&&explanation==="0";
 function clear(){setExplanation(null);setTransferAnswer(null);}
 function start(next=index){setIndex(next);setState(regularizationBaseline());setPrediction(null);clear();}
 function edit(next:RegularizationState){if(!sameRegularization(state,next)){setState(next);clear();}}
 function applyFit(){edit({...state,weightUnits:[...fit.selected]});}
 const rail=experiment?<ExperimentRail label={`Experiment ${index+1} of 3`} title={experiment.title} phase={!prediction?0:reached?2:1}>
  {!reached&&<><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="regularization-prediction" choices={experiment.predictions} value={prediction} onChange={id=>{start();setPrediction(id);}}/><p className={shared.small}>Changing prediction restores Unregularized weights 1,0.5, None and strength 0.25. Reset restarts this experiment.</p></>}
  {prediction&&!reached&&<p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
  {reached&&<><p role="status" className={shared.observation}>{prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="regularization-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation}/>{explanation&&!complete&&<p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
  {complete&&<><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={()=>start(index+1)}>{index===2?"Try the transfer check":"Next experiment"}</ExperimentButton></>}
 </ExperimentRail>:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Interpret zero weights":"Separate fitting from prediction"}>
  {transfer?<><p>Without Guide help, choose L1 and Penalty strength 0.5, in either order, then Fit on weight grid. Reconstruct data loss, penalty, objective, the score-zero geometry and training accuracy using the explicit +1 tie rule. Compare with the original unregularized fit without claiming held-out improvement.</p>{reachedRegularization(3,state)&&<><ExperimentChoices legend="Transfer explanation" name="regularization-transfer" choices={[
    {id:"ties",label:"The best grid weights are (0,0). Every score is zero, so every prediction is +1 by the declared tie rule; 5/8 are correct, or 62.5%. Data loss is 0.5, penalty is zero and objective is 0.5. The whole feature plane has score zero, so there is no unique separating line. Zero coefficients or zero penalty do not prove better prediction or generalization."},
    {id:"undefined",label:"With zero weights there are no predictions, so training accuracy is undefined."},
    {id:"perfect",label:"A zero penalty means zero data loss and perfect accuracy, so stronger L1 is always best."},
  ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="ties"?<p role="status" className={shared.feedback}>Try again. Apply the stated score-zero tie rule to all eight fixed targets. Separate a zero penalty from the residual data loss and from a unique boundary.</p>:<><ExperimentResult title="Transfer explained">A regularized optimum can sacrifice fit. Predictions still follow a declared cutoff, while a fully zero scorer has no unique separating line.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(4);clear();}}>Explore freely</ExperimentButton></>)}</>}</>:<><p>Try Signed weights, Zero weights, zero strength, or both parameter endpoints. At L2 strength 0.30 inspect both tied best grid pairs. Fit applies the lower Weight 1, then lower Weight 2, among ties. Every displayed fit is on the declared grid; compare weights, scores and data loss separately from training accuracy and any held-out claim.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
 </ExperimentRail>;
 return <LearningPage title="Regularization Lab" subtitle="Choose a penalty. Then fit the weights." rail={rail}>
  <LessonToolbar scenarios={regularizationScenarios} selectedId={regularizationPresetId(state)} onSelect={id=>{const p=regularizationPresets[id]!;edit({...p,weightUnits:[...p.weightUnits]});}} onReset={()=>start(experiment||transfer?index:0)}/>
  <section className={styles.evidence} aria-label="Fixed toy dataset and weight editor"><h2>Your dataset</h2><p>Eight authored cases have two features and fixed targets +1 or −1. Score = w1×x1 + w2×x2; bias stays zero. This toy scorer uses squared error and then a sign cutoff, not logistic probabilities. Predict +1 when score≥0, including exact ties, and −1 otherwise. Cases 6 and 8 share coordinates but have opposite targets; both cannot be correct under one deterministic score.</p>
   <div className={styles.workbench}><div className={styles.chart} ref={chartRef}><svg data-regularization-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label="Current score regions and fixed grouped cases on feature axes minus1.5 to1.5. Teal means predicted plus1; orange minus1. The boundary has score zero. All eight exact cases and predictions follow in the table.">
    <polygon data-reg-region="positive" points={chart.positive.map(p=>p.join(",")).join(" ")} className={styles.positive}/><polygon data-reg-region="negative" points={chart.negative.map(p=>p.join(",")).join(" ")} className={styles.negative}/>
    {chart.ticks.map(t=><g key={t.value}><line x1={t.x} x2={t.x} y1={chart.top} y2={chart.top+chart.span} className={styles.grid}/><line x1={chart.left} x2={chart.left+chart.span} y1={t.y} y2={t.y} className={styles.grid}/><text x={t.x} y={chart.top+chart.span+20} textAnchor="middle">{t.value}</text><text x={chart.left-9} y={t.y+4} textAnchor="end">{t.value}</text></g>)}
    {chart.boundary&&<line data-reg-boundary x1={chart.boundary[0]![0]} y1={chart.boundary[0]![1]} x2={chart.boundary[1]![0]} y2={chart.boundary[1]![1]} className={styles.boundary}/>}
    {chart.sites.map((site,i)=><g key={i} data-reg-site={i}><title>{`${site.label} at (${site.x1},${site.x2}); fixed targets, two cases`}</title>{site.kind==="mixed"?<rect x={site.x-6} y={site.y-6} width="12" height="12" fill="white" stroke="#ad4508"/>:<circle cx={site.x} cy={site.y} r="6" fill={site.kind==="positive"?"#087c78":"#ad4508"}/>}<text x={site.x1?site.x:site.x+12} y={site.x1?site.y-14:site.y+4} textAnchor={site.x1?"middle":"start"} className={styles.siteLabel}>{site.label}</text></g>)}
    <text x={chart.left+chart.span/2} y={chart.height-7} textAnchor="middle">x1</text><text x="12" y={chart.top+chart.span/2} textAnchor="middle">x2</text>
   </svg><p data-reg-boundary-text>{chart.boundary?`Score-zero boundary: ${number(a.weights[0]!)}×x1 + ${number(a.weights[1]!)}×x2 = 0. Boundary scores tie and predict +1.`:"All weights are zero: the whole feature plane scores zero and predicts +1. There is no unique separating line."}</p><p>Circles show single-target groups, a square mixed targets. Text lists exact case IDs and fixed labels; marker color does not represent model confidence. Teal region predicts +1, orange −1; boundary ties predict +1.</p></div>
   <div className={styles.controls}>{a.weights.map((value,i)=><LessonRangeControl key={i} label={`Weight ${i+1}`} value={value} min={-2} max={2} step={0.05} help={`Signed coefficient for feature x${i+1}. Manual edits immediately change scores, data loss and the current boundary.`} onChange={value=>edit(changeRegularizationWeight(state,i as 0|1,value))}/>)}<div><LessonToggleGroup label="Penalty mode" choices={penaltyModes.map(id=>({id,label:id==="none"?"None":id.toUpperCase()}))} value={state.mode} onChange={mode=>edit({...state,mode:mode as PenaltyMode})}/><p>Mode changes keep current weights fixed.</p></div><LessonRangeControl label="Penalty strength" value={a.strength} min={0} max={1} step={0.05} help="λ multiplies the chosen penalty; None has zero penalty at every strength. A strength edit keeps current weights fixed." onChange={value=>edit(changeRegularizationStrength(state,value))}/><LessonAction onClick={applyFit}>Fit on weight grid</LessonAction><p>Fit checks all 81×81=6,561 weight pairs in −2..2, step 0.05. It minimizes data loss plus the current penalty on this grid; it does not prove the unrestricted continuous optimum. Among ties it applies the lowest Weight 1, then Weight 2.</p></div></div>
   <p role="status" data-reg-status className={styles.formula}>{regularizationPresetId(state)==="custom"?"Custom settings":regularizationScenarios.find(p=>p.id===regularizationPresetId(state))!.label} · Weights ({a.weights.map(number).join(", ")}) · {state.mode==="none"?"None":state.mode.toUpperCase()} · Strength {number(a.strength)} · {a.correct}/8 correct, {number(a.accuracy)}%</p><p data-reg-fit className={styles.formula}>{fit.currentIsBest?"Current weights are a best grid fit.":"Current weights are not a best grid fit."} {fit.minima.length} best pair{fit.minima.length===1?"":"s"}: {fit.minima.map(w=>`(${w.map(v=>number(v/20)).join(", ")})`).join("; ")}. Minimum objective {number(fit.objective)}. Fit applies ({fit.selected.map(v=>number(v/20)).join(", ")}).</p><p>Actual weight, mode or strength changes clear stale answers; unchanged controls and a fit that leaves weights unchanged preserve them. All accuracy here describes the same eight training cases; no held-out evidence is supplied.</p>
  </section>
  <section className={styles.evidence} aria-label="All eight fixed cases and scoring evidence"><h2>Fixed-case evidence</h2><div className={styles.table} tabIndex={0} role="region" aria-label="Eight targets, scores, predictions and half-squared errors"><table><caption>Both cases at every site remain separate. A zero score predicts +1. Each row contributes ½×(score−target)²; data loss averages all eight terms.</caption><thead><tr>{["ID","x1","x2","Target","Score","Predicted","Tie?","Correct?","½ residual²"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.cases.map(c=><tr key={c.id} data-reg-case={c.id}><th scope="row">{c.id}</th><td>{c.x1}</td><td>{c.x2}</td><td>{c.target}</td><td>{number(c.score)}</td><td>{c.predicted}</td><td>{c.tied?"Yes":"No"}</td><td>{c.correct?"Yes":"No"}</td><td>{number(c.loss)}</td></tr>)}</tbody></table></div><p data-reg-calculation className={styles.formula}>Data loss = ({a.cases.map(c=>number(c.loss)).join(" + ")}) / 8 = {number(a.dataLoss)}. Penalty = {a.penaltyFormula} = {number(a.penalty)}. Objective = {number(a.dataLoss)} + {number(a.penalty)} = {number(a.objective)}.</p></section>
  <LessonSummaries label="Data loss, penalty and total objective" summaries={[
   {label:"Data loss",color:"#087c78",value:number(a.dataLoss),definition:"Mean half-squared error over all eight fixed cases.",formula:"Σ ½(score − target)² / 8 = SSE / 16",comparison:"Includes every case, whether its sign prediction is correct or not."},
   {label:"Penalty",color:"#ad4508",value:number(a.penalty),definition:"The chosen cost of coefficient magnitudes.",formula:state.mode==="none"?"None: 0":state.mode==="l1"?"L1: λ(|w1| + |w2|)":"L2: λ(w1² + w2²) / 2",comparison:"Identical λ does not imply equal L1 and L2 penalty magnitudes."},
   {label:"Objective",color:"#5031dc",value:number(a.objective),definition:"Data loss plus the current penalty.",formula:`${number(a.dataLoss)} + ${number(a.penalty)}`,comparison:"Fit minimizes this quantity on the declared weight grid, not accuracy."},
  ]}/>
  <section className={styles.evidence} aria-label="Regularization construction and limits"><details><summary>Construction and limits</summary><p>Targets are five +1 and three −1 labels. Cases 6 and 8 have identical (0,−1) features and opposite targets. Inputs are fixed, same-scale toy columns; there is no intercept fit. We fit signed scores by squared error and then use a sign cutoff for an illustrative decision boundary. This is not logistic regression, calibrated probability or a recommended application model.</p><p>Exact grid parameters use twentieths: weights −40..40 divided by 20, strength 0..20 divided by 20. Objective arithmetic has an exact integer numerator over 16,000, so tied grid minima are identified without a numerical tolerance. Fit searches every pair, reports all best pairs and applies their ascending Weight 1/Weight 2 order. At L2 strength 0.30 the tied pairs are (0.60,0.30) and (0.65,0.30), both objective 0.305; Fit chooses (0.60,0.30).</p><p>L1 uses λ times absolute weights; L2 uses λ/2 times squared weights. Data loss is SSE/(2n), n=8. Other libraries or texts can use different scale factors, so λ must be interpreted with its declared formula. L1 can create zeros; L2 often shrinks weights, but neither guarantees improved accuracy or useful feature selection. Grid approximation, feature scaling and different datasets can change coefficients or boundary ratios. The experiment’s exact common half-scale is one specific L2 case.</p><p>Penalty edits leave current weights fixed; only a weight edit or Fit changes them. Training data loss and training accuracy are different from objective and from held-out generalization. No validation data, optimizer path, learned feature encoder, automatic λ selection or bias penalty is supplied. An all-zero scorer has no unique separating line, but its explicit +1 tie rule still defines predictions and accuracy. Reset/prediction restores Unregularized for the current experiment; free-exploration Reset begins Experiment 1.</p><a href="https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html" target="_blank" rel="noreferrer">scikit-learn · Squared-error, L1 and L2 scaling convention</a><br/><a href="https://web.stanford.edu/class/stats202/notes/Model-selection/Shrinkage.html" target="_blank" rel="noreferrer">Stanford STATS 202 · Shrinkage and sparsity</a></details></section>
 </LearningPage>;
}
