"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSelect, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeForward, editForward, forwardBaseline, forwardEdges, forwardGraph, forwardNumber as number, forwardPresetId, forwardScenarios, sameForward, type ForwardState } from "./forward-engine";
import { forwardExperiments } from "./learning-experiments";
import { forwardTargets, reachedForward } from "./lesson-state";
import styles from "./playground.module.css";

export function ForwardPassPlayground() {
  const [state, setState] = useState<ForwardState>(forwardBaseline), [selected, setSelected] = useState(1);
  const [index, setIndex] = useState(0), [prediction, setPrediction] = useState<string | null>(null), [explanation, setExplanation] = useState<string | null>(null), [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const chartRef = useRef<HTMLDivElement>(null), [width, setWidth] = useState(640);
  useEffect(() => {
    const el = chartRef.current; if (!el) return;
    const update = () => setWidth(Math.max(290, el.getBoundingClientRect().width)); update();
    const observer = new ResizeObserver(update); observer.observe(el); return () => observer.disconnect();
  }, []);
  const a = useMemo(() => analyzeForward(state), [state]), graph = forwardGraph(state, selected, width), edge = a.edges[selected]!;
  const experiment = forwardExperiments[index], transfer = index === 3, reached = !!prediction && !!experiment && reachedForward(index, state), complete = reached && explanation === "0";
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function start(next = index) { setIndex(next); setState(forwardBaseline()); setSelected(forwardTargets[next]?.edge ?? 1); setPrediction(null); clear(); }
  function edit(next: ForwardState) { if (!sameForward(state, next)) { setState(next); clear(); } }
  const rail = experiment ? <ExperimentRail label={`Experiment ${index + 1} of 3`} title={experiment.title} phase={!prediction ? 0 : reached ? 2 : 1}>
    {!reached && <><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="forward-prediction" choices={experiment.predictions} value={prediction} onChange={id => { start(); setPrediction(id); }} /><p className={shared.small}>Changing prediction restores Baseline. Reset restarts this experiment.</p></>}
    {prediction && !reached && <p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
    {reached && <><p role="status" className={shared.observation}>{prediction === "0" ? "The evidence matches your prediction." : "The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="forward-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation} />{explanation && !complete && <p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
    {complete && <><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={() => start(index + 1)}>{index === 2 ? "Try the transfer check" : "Next experiment"}</ExperimentButton></>}
  </ExperimentRail> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Trace a new hidden path" : "Explore every weight"}>
    {transfer ? <><p>Without Guide help, choose Baseline. Set the x1 → H2 Weight value to 1. Reconstruct H2&apos;s sum, its ReLU output and both class scores. Explain which input stayed fixed, which paths changed, and whether a highest score establishes model accuracy.</p>{reachedForward(3, state) && <><ExperimentChoices legend="Transfer explanation" name="forward-transfer" choices={[
      { id: "path", label: "x1 stays 1. H2's sum becomes 1×1+2×1−1=2, so ReLU output is 2; H1 stays 1. Class A=1×1+2×(−1)=−1, Class B=1×(−1)+2×1=1. Class B is highest. This forward computation shows no training, probability or accuracy evidence." },
      { id: "negative", label: "Both class scores must be clipped to 0 because they cannot be negative." },
      { id: "training", label: "The class switch proves the edited network has learned and is more accurate." },
    ]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (transferAnswer !== "path" ? <p role="status" className={shared.feedback}>Try again. Recompute the hidden sum first, apply ReLU there, then use its output in both raw score sums. No labeled evaluation or training step was provided.</p> : <><ExperimentResult title="Transfer explained">A newly active hidden path can change both scores. The scores summarize this computation; their ordering alone does not establish correctness on real data.</ExperimentResult><ExperimentButton onClick={() => { setIndex(4); clear(); }}>Explore freely</ExperimentButton></>)}</>}</> : <><p>Try all eight Weight edge choices at Weight value −2, 0 and 2. Compare source value, weighted contribution, hidden sum, activation and scores. In Both hidden off, edit an output-edge weight: its source is zero. Test a tie without inventing a unique winner. Selection alone changes only the highlighted edge.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;

  return <LearningPage title="Neural Network Forward Pass Lab" subtitle="Change one weight. Trace the signal to class scores." rail={rail}>
    <LessonToolbar scenarios={forwardScenarios} selectedId={forwardPresetId(state)} onSelect={id => edit(forwardBaseline(id))} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={styles.evidence} aria-label="Editable network weights"><h2>Your dataset</h2><p>A forward pass computes outputs from the current inputs and weights. Inputs stay fixed at x1=1 and x2=2. Each hidden node adds its weighted inputs and a fixed bias of −1, then applies ReLU, the rectified linear unit: max(0,sum). The output layer uses those hidden activations in raw class-score sums, with fixed bias 0. These authored weights are editable; no training is performed.</p>
      <div className={styles.chart} ref={chartRef}><svg data-forward-graph viewBox={`0 0 ${graph.width} ${graph.height}`} role="img" aria-label="Two fixed inputs feed two ReLU hidden nodes, which feed two raw class scores. Arrows show connections; the dashed purple edge is selected. The exact calculation table provides every weighted sum and output.">
        <defs><marker id="forward-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#8c96ae" /></marker><marker id="forward-selected-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#5031dc" /></marker></defs>
        {graph.layerXs.map((x, i) => <text key={i} x={x} y="23" textAnchor="middle">{["Inputs", "Hidden · ReLU", "Raw scores"][i]}</text>)}
        {[...graph.edges].sort((a, b) => Number(a.selected) - Number(b.selected)).map(e => <line key={e.id} data-forward-edge={e.id} x1={e.x1} y1={e.y1} x2={e.x2} y2={e.y2} stroke={e.selected ? "#5031dc" : "#8c96ae"} strokeWidth={e.selected ? 3 : 1.3} strokeDasharray={e.selected ? "6 4" : undefined} markerEnd={`url(#${e.selected ? "forward-selected-arrow" : "forward-arrow"})`} />)}
        <text data-forward-weight className={styles.selectedWeight} x={graph.width / 2} y="326" textAnchor="middle">Selected weight = {number(edge.weight)}</text>
        {graph.nodes.map(n => <g key={n.id} data-forward-node={n.id}><text x={n.x} y={n.y - 39} textAnchor="middle">{n.label}</text><circle cx={n.x} cy={n.y} r={graph.radius} fill="white" stroke={n.id >= 2 ? "#5031dc" : "#8c96ae"} /><text className={styles.nodeValue} style={{ fontSize: number(n.value).length > 5 ? 12 : 18 }} x={n.x} y={n.y + 6} textAnchor="middle">{number(n.value)}</text>{n.sum !== null && <text x={n.x} y={n.y + 48} textAnchor="middle">sum {number(n.sum)}</text>}</g>)}
      </svg></div>
      <p className={shared.small}>Arrows show connectivity, not weight magnitude. A thicker dashed purple edge and its weight label mark the selection. Use the named controls below; the graph has no drag targets.</p>
      <div className={styles.controls}><LessonSelect label="Weight edge" choices={forwardEdges} value={String(selected)} onChange={id => setSelected(Number(id))} /><LessonRangeControl label="Weight value" value={edge.weight} min={-2} max={2} step={0.25} help="Edit only the selected edge in quarter steps. Its source value stays separate from its weight." onChange={v => edit(editForward(state, selected, v))} /></div>
      <p role="status" data-forward-contribution className={styles.formula}>{edge.label}: source {number(edge.input)} × weight {number(edge.weight)} = contribution {number(edge.contribution)}.</p><p className={shared.small}>Actual weight or scenario changes clear stale explanations and transfer answers. Selecting another edge or applying an unchanged value preserves them. Inputs and biases remain fixed.</p>
    </section>
    <LessonSummaries label="Raw output scores and highest score" summaries={[
      { label: "Class A score", color: "#087c78", value: number(a.scores[0]!), definition: "A raw weighted sum of hidden outputs.", formula: "H1 × w(H1→A) + H2 × w(H2→A)" },
      { label: "Class B score", color: "#5031dc", value: number(a.scores[1]!), definition: "A raw weighted sum, with no output ReLU.", formula: "H1 × w(H1→B) + H2 × w(H2→B)" },
      { label: "Highest score", color: "#ad4508", value: a.leader, definition: a.leader === "Tie" ? "Equal scores: no unique highest class." : "The class with the larger raw score.", formula: "Compare scores; equal means Tie", comparison: "Scores may be negative or exceed 1. They are not probabilities or measured accuracy." },
    ]} />
    <section className={styles.evidence} aria-label="Exact forward calculations"><h2>Multiply, add, then activate</h2><p>Each term is source × weight. Add the terms and bias to get the sum. Hidden nodes apply ReLU to that sum; the output layer keeps its raw sum. The next layer consumes the hidden output, not its pre-activation sum. All displayed quarter/sixteenth values are exact in this model.</p><div className={styles.table} tabIndex={0} role="region" aria-label="Every hidden and output calculation"><table><caption>Fixed inputs 1,2; hidden bias −1 each; output bias 0. Hidden output=max(0,sum); Class A and B keep raw sums.</caption><thead><tr>{["Node / score", "Weighted terms + bias", "Sum", "Output / score"].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.rows.map((r, i) => <tr key={r.label} data-forward-row={i}><th scope="row">{r.label}</th><td>{r.terms}</td><td>{number(r.sum)}</td><td>{r.rule}: {number(r.output)}</td></tr>)}</tbody></table></div></section>
    <section className={styles.evidence} aria-label="Forward pass construction and limits"><details><summary>Construction and limits</summary><p>This is an authored network with two inputs, two hidden nodes and two output scores. Every input connects to each hidden node; every hidden node connects to each output. Eight weights use −2..2 in increments of 0.25, encoded as integer units divided by 4. Hidden biases are −1; output biases are 0. Only the hidden layer uses ReLU. Negative final scores are valid raw sums.</p><p>Baseline weights in Weight edge order are 1,0.5,−1,1,1,−1,−1,1. Both hidden off changes x1→H1 to −1 and x2→H1 to 0. Both hidden active changes x1→H2 to 1. Reset and predictions restore Baseline for the current experiment; free Reset begins Experiment 1. Selecting an edge only changes the highlight. No training, gradient computation, probability conversion, classification accuracy, or recommendation of this architecture is supplied.</p><a href="https://docs.pytorch.org/docs/2.14/generated/torch.nn.Linear.html" target="_blank" rel="noreferrer">PyTorch · Weighted linear layer and bias</a><br /><a href="https://docs.pytorch.org/docs/2.14/generated/torch.nn.ReLU.html" target="_blank" rel="noreferrer">PyTorch · ReLU definition</a></details></section>
  </LearningPage>;
}
