"use client";
import { useMemo, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import sharedStyles from "@/components/learning-page/learning-page.module.css";
import { analyzeQuantization, formatPercent, formatSigned, inspectorBounds, type QuantizationRangePreset } from "./linear-quantization-int4-engine";
import { quantizationScenarios, type QuantizationScenarioId } from "./scenario";
import { quantizationDefaults, quantizationExperiments, quantizationToolbarScenarios, quantizationTransferStart, quantizationTransferTarget, type QuantizationState } from "./learning-experiments";
import styles from "./playground.module.css";
const same = (a: QuantizationState, b: QuantizationState) => a.scenario === b.scenario && a.preset === b.preset && a.value === b.value;
const rangeChoices = [{ id: "auto", label: "Auto" }, { id: "tighter", label: "Tighter" }, { id: "wider", label: "Wider" }];
const limit = (value: number) => Number.isFinite(value) ? formatSigned(value) : value < 0 ? "−∞" : "+∞";
export function LinearQuantizationInt4Playground() {
  const [state, setState] = useState<QuantizationState>(quantizationDefaults);
  const [index, setIndex] = useState(0);
  const [prediction, setPrediction] = useState<string | null>(null);
  const [explanation, setExplanation] = useState<string | null>(null);
  const [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const scenario = quantizationScenarios.find(s => s.id === state.scenario)!;
  const a = useMemo(() => analyzeQuantization(scenario, state.preset, state.value), [scenario, state.preset, state.value]);
  const bounds = inspectorBounds(scenario);
  const position = (value: number) => ((value - bounds.min) / (bounds.max - bounds.min) * 100).toPrecision(6) + "%";
  const experiment = quantizationExperiments[index], transfer = index === 5;
  const reached = !!experiment && !!prediction && same(state, experiment.target);
  const complete = reached && explanation === experiment?.correctExplanation;
  const transferReached = same(state, quantizationTransferTarget);
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function edit(next: QuantizationState) { setState(next); clear(); }
  function start(next = index) { setIndex(next); setState(quantizationExperiments[next]?.baseline ?? quantizationTransferStart); setPrediction(null); clear(); }
  const rail = experiment ? <GuidedExperiment label={`Experiment ${index + 1} of 5`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="quant-prediction" explanationName="quant-explanation"
    onPredict={id => { start(); setPrediction(id); }} onExplain={setExplanation}
    predictionHelp={<>A different prediction restores this experiment’s starting state. Reset restarts it.</>} observation={prediction === experiment.correctPrediction ? "Your prediction matches the evidence." : "The code, reconstructed value and block metrics challenge your prediction."}
    onNext={() => start(index + 1)} nextLabel={index === 4 ? "Try the transfer check" : "Next experiment"} /> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Same code, another map" : "Compare maps and errors"}>
    {transfer ? <><p>Tiny sensor model starts at Auto with probe 0.037. Predict: if code 9 stays the same, must reconstruction and whole-block error stay fixed? Choose Tighter while keeping the probe fixed, then explain.</p><ExperimentChoices legend="Transfer explanation" name="quant-transfer" choices={[{ id: "map", label: "Code 9 stays, but the scale changes reconstruction 0.04000 → 0.03400. Probe absolute error stays 0.00300; block mean absolute error rises 0.00301 → 0.00354 and clamped samples 3 → 8." }, { id: "same", label: "The same code always means the same real value, whatever the scale and zero point." }, { id: "better", label: "A smaller scale guarantees less error for every value and the whole block." }]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (!transferReached ? <p role="status" className={sharedStyles.feedback}>First keep Tiny sensor model and probe 0.037, then choose Tighter. Reset restores Auto at 0.037.</p> : transferAnswer !== "map" ? <p role="status" className={sharedStyles.feedback}>Try again. A code needs its scale and zero point to reconstruct a value. Compare the probe with the separate fixed-block summaries.</p> : <><ExperimentResult title="Transfer explained">The map gives the code meaning. The probe’s absolute error can stay unchanged while block error and clamping change.</ExperimentResult><ExperimentButton onClick={() => setIndex(6)}>Explore freely</ExperimentButton></>)}</> : <><p>Explore all three synthetic blocks and their presets. Compare endpoint cells, half-step boundaries, fixed sample counts and packed codes. Separate payload savings from total storage and model performance.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  const nibble = a.selected.code.toString(2).padStart(4, "0"), byte = (a.selected.code * 16 + 6).toString(16).toUpperCase().padStart(2, "0");
  return <LearningPage title="Linear Quantization (INT4) Lab" subtitle="Share a scale. Round a value. Inspect the cost." rail={rail}>
    <LessonToolbar label="Synthetic blocks" scenarios={quantizationToolbarScenarios} selectedId={state.scenario} onSelect={id => { const s = quantizationScenarios.find(s => s.id === id)!; edit({ scenario: id as QuantizationScenarioId, preset: "auto", value: s.selectedValue }); }} onReset={() => start(experiment || transfer ? index : 0)} />
    <p className={styles.context}>Synthetic blocks, not trained-model measurements. This toy uses unsigned 4-bit codes 0–15 (uint4); signed int4 uses −8..7. Reconstructed real values can be negative through the zero-point offset.</p>
    <section className={sharedStyles.evidence} aria-label="Quantizer controls"><h2>Your quantizer</h2><LessonToggleGroup label="Range preset" choices={rangeChoices} value={state.preset} onChange={id => edit({ ...state, preset: id as QuantizationRangePreset })} /><p>Auto is a fixed demonstration preset, not an automatic sample-min/max estimate. All presets round calibration endpoints to 0.001. Clamping limits a code to 0–15 by choosing the closest boundary.</p><div className={styles.parameters}><p>Calibration min <output aria-label="Calibration minimum">{formatSigned(a.min)}</output></p><p>Calibration max <output aria-label="Calibration maximum">{formatSigned(a.max)}</output></p><p>Scale s <output aria-label="Quantization scale">{a.scale.toFixed(5)}</output></p><p>Zero point z <output aria-label="Zero point">{a.zeroPoint}</output></p></div><p className={sharedStyles.math}>16 codes = 15 gaps · s = (max − min) / 15 · z = clamp(round(−min/s), 0, 15)</p>
      <LessonRangeControl label="Inspect one value" value={state.value} min={bounds.min} max={bounds.max} step={0.001} onChange={value => edit({ ...state, value })} help={`Probe bounds ${formatSigned(bounds.min, 3)} to ${formatSigned(bounds.max, 3)} stay fixed across this block’s presets. The probe does not change the ${scenario.samples.length} fixed block samples.`} />
    </section>
    <section className={sharedStyles.evidence} aria-label="Real value map"><h2>Real value to reconstructed level</h2><p>Three rows share the same real-number scale, including sources beyond the levels. The top row has all 16 reconstructed levels; code {a.zeroPoint} represents zero. The dot is x, the square is x̂. Exact positions have no minimum drawn error.</p>
      <div className={styles.axis} aria-hidden="true"><span>{formatSigned(bounds.min, 3)}</span><span>{formatSigned(bounds.max, 3)}</span></div>
      <div className={styles.mapRow}><strong>Levels</strong><div className={styles.mapTrack} aria-hidden="true">{a.codeBins.map(bin => <span key={bin.code} className={styles.level} data-code={bin.code} style={{ left: position(bin.center) }} data-selected={bin.selected} />)}</div></div>
      <div className={styles.mapRow}><strong>x {formatSigned(state.value, 3)}</strong><div className={styles.mapTrack} aria-hidden="true"><span className={styles.source} data-marker="source" style={{ left: position(state.value) }} /></div></div>
      <div className={styles.mapRow}><strong>x̂ {formatSigned(a.selected.dequantized)}</strong><div className={styles.mapTrack} aria-hidden="true"><span className={styles.reconstructed} data-marker="reconstructed" style={{ left: position(a.selected.dequantized) }} /><span className={styles.errorLine} style={{ left: position(Math.min(state.value, a.selected.dequantized)), width: `${(Math.abs(a.selected.error) / (bounds.max - bounds.min) * 100).toPrecision(6)}%` }} /></div></div>
      <p className={sharedStyles.math}>Reconstructed endpoints: code 0 = {formatSigned(a.codeBins[0].center)} · code 15 = {formatSigned(a.codeBins[15].center)}</p><p>These can differ from calibration min/max after the zero point rounds to an integer. Each unclamped rounded code has an error bound s/2 = {a.maxRoundingError.toFixed(5)}. The bound does not apply to clamped values.</p>
    </section>
    <section className={sharedStyles.evidence} aria-label="Quantization arithmetic"><h2>Arithmetic trace</h2><p className={sharedStyles.math}>q = clamp(round(x/s) + z, 0, 15) · x̂ = s(q − z) · error = x̂ − x</p><dl className={styles.trace}><div><dt>x / s</dt><dd>{(state.value / a.scale).toFixed(5)}</dd></div><div><dt>Rounded offset</dt><dd>{a.selected.rounded}</dd></div><div><dt>Raw code = offset + z</dt><dd>{a.selected.rawCode}</dd></div><div><dt>Clamped code q</dt><dd>{a.selected.code}</dd></div><div><dt>Reconstructed x̂</dt><dd>{formatSigned(a.selected.dequantized)}</dd></div><div><dt>Signed error</dt><dd>{formatSigned(a.selected.error)}</dd></div></dl><p><strong>{a.selected.clipped ? "Raw code was clamped." : "Raw code was not clamped."}</strong> Round nearest, with half ties toward +∞ (for example −2.5 → −2). Authored decimal inputs are treated exactly for this tie decision; ONNX uses ties-to-even instead.</p><p>Input cell after clamping: {limit(a.inputInterval.start)} ≤ x &lt; {limit(a.inputInterval.end)}. Endpoint codes include arbitrarily far tails; not every input assigned an endpoint code was clamped. This describes the mathematical decimal rule, beyond the bounded inspector.</p></section>
    <LessonSummaries label="Fixed block errors" summaries={[{ label: "Mean absolute error", value: a.averageAbsoluteError.toFixed(5), color: "#5031dc", definition: `Average |x̂ − x| across the ${scenario.samples.length} fixed samples, including clamped samples.`, formula: "Σ absolute error / sample count", comparison: "Changing only the separate probe leaves this unchanged." }, { label: "Clamped samples", value: `${a.clippedCount} / ${scenario.samples.length}`, color: "#b24500", definition: "Samples whose rounded raw code falls below 0 or above 15.", formula: formatPercent(a.clippedRatio), comparison: "This is different from merely lying outside calibration endpoints, or being assigned code 0/15." }]} />
    <section className={sharedStyles.evidence} aria-label="Code packing"><h2>Pack two codes</h2><p>A nibble is 4 bits; a byte is 8. The first code occupies the high nibble, the fixed second code 6 the low nibble. This pair is a packing demonstration, not two selected block samples.</p><p className={`${sharedStyles.math} ${styles.packing}`}>{a.selected.code} = {nibble} · fixed 6 = 0110 → 0x{byte} ({nibble}0110, one byte)</p><p>Codes alone: 32-bit FP32 → 4-bit payload = 8× reduction. Illustrative block format: {a.storage.packedBytes} payload bytes + 4-byte FP32 scale + 1-byte zero point = {a.storage.totalBytes} bytes, versus {a.storage.fp32Bytes} FP32 bytes ({a.storage.ratio.toFixed(2)}×). An odd sample count pads the last half-byte; real formats can add alignment, containers or other metadata. This does not measure model accuracy or speed.</p></section>
    <section className={styles.optional} aria-label="Supporting quantization evidence"><details><summary>Code counts and reconstructed levels</summary><p>Bars use a common 0–100% scale of all {scenario.samples.length} samples. Zero-count codes have zero width. The final column counts genuinely clamped samples, not every boundary assignment.</p><div className={styles.scroller} role="region" aria-label="Scrollable code counts" tabIndex={0}><table><thead><tr><th scope="col">Code</th><th scope="col">Reconstructed level</th><th scope="col">Count / share of block</th><th scope="col">Clamped count</th></tr></thead><tbody>{a.codeBins.map(bin => <tr key={bin.code} data-frequency={bin.code} aria-current={bin.selected ? "true" : undefined}><th scope="row">{bin.code}{bin.selected ? " · Probe code" : ""}</th><td>{formatSigned(bin.center)}</td><td><div className={styles.frequency} aria-hidden="true"><span style={{ width: `${(bin.ratio * 100).toPrecision(6)}%` }} /></div>{bin.count} / {formatPercent(bin.ratio)}</td><td>{bin.clippedCount}</td></tr>)}</tbody></table></div></details>
      <details><summary>All original and quantized samples</summary><p>Every original occurrence is retained, including repeated synthetic values. This is the fixed dataset used by the block error summaries.</p><div className={styles.scroller} role="region" aria-label="Scrollable sample trace" tabIndex={0}><table><thead><tr><th scope="col">Sample</th><th scope="col">Original x</th><th scope="col">Rounded offset</th><th scope="col">Raw code</th><th scope="col">Stored q</th><th scope="col">Reconstructed</th><th scope="col">Error</th><th scope="col">Clamped?</th></tr></thead><tbody>{a.quantizedValues.map((v,i) => <tr key={i}><th scope="row">{i+1}</th><td>{formatSigned(v.source)}</td><td>{v.rounded}</td><td>{v.rawCode}</td><td>{v.code}</td><td>{formatSigned(v.dequantized)}</td><td>{formatSigned(v.error)}</td><td>{v.clipped ? "Yes" : "No"}</td></tr>)}</tbody></table></div></details>
      <details><summary>Original distribution bins</summary><p>Twenty-four calibration bins use [start, end), with the final right endpoint included. Explicit underflow/overflow counts retain out-of-range samples; these counts are not code-clamping counts.</p><div className={styles.scroller} role="region" aria-label="Scrollable original distribution" tabIndex={0}><table><thead><tr><th scope="col">Source interval</th><th scope="col">Count</th><th scope="col">Share of block</th></tr></thead><tbody>{a.realHistogram.map((bin,i) => <tr key={i}><th scope="row">{bin.label}</th><td>{bin.count}</td><td>{formatPercent(bin.ratio)}</td></tr>)}</tbody></table></div></details></section>
    <p role="status" aria-live="polite" aria-atomic="true" className={sharedStyles.liveUpdate}>{scenario.title}, {state.preset} range. Probe {formatSigned(state.value)}, rounded offset {a.selected.rounded}, raw code {a.selected.rawCode}, stored code {a.selected.code}, reconstructed {formatSigned(a.selected.dequantized)}, error {formatSigned(a.selected.error)}. {a.selected.clipped ? "Clamped." : "Not clamped."} Block mean absolute error {a.averageAbsoluteError.toFixed(5)}, {a.clippedCount} clamped samples of {scenario.samples.length}. Packed byte 0x{byte}.</p>
  </LearningPage>;
}
