"use client";
import { useEffect, useMemo, useRef, useState, type PointerEvent } from "react";
import { DatasetHeading, ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeCovariance, covarianceChart, covarianceDataset, covarianceDrag, covarianceNumber as number, covariancePresetId, covariancePresets, type Pair } from "./covariance-engine";
import { covarianceBaseline, reachedCovariance } from "./lesson-state";
import { covarianceExperiments } from "./learning-experiments";
import styles from "./playground.module.css";

export function CovariancePlayground() {
  const [state, setState] = useState(() => covarianceBaseline()), [index, setIndex] = useState(0), [selected, setSelected] = useState(4);
  const [prediction, setPrediction] = useState<string | null>(null), [explanation, setExplanation] = useState<string | null>(null), [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const [width, setWidth] = useState(640), chartRef = useRef<HTMLDivElement>(null), dragging = useRef<number | null>(null);
  useEffect(() => { const element = chartRef.current; if (!element) return; const update = () => setWidth(Math.max(200, element.getBoundingClientRect().width)); update(); const observer = new ResizeObserver(update); observer.observe(element); return () => observer.disconnect(); }, []);
  const a = useMemo(() => analyzeCovariance(state), [state]), chart = covarianceChart(a, width), term = a.terms[selected], experiment = covarianceExperiments[index], transfer = index === 4;
  const reached = !!prediction && !!experiment && reachedCovariance(index, state), complete = reached && explanation === "0";
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function start(next = index) { setIndex(next); setState(covarianceBaseline(next)); setSelected(next === 4 ? 0 : 4); setPrediction(null); dragging.current = null; clear(); }
  function pointEdit(point: number, patch: Partial<Pair>) { setState(s => ({ ...s, points: s.points.map((p, i) => i === point ? { ...p, ...patch } : p) })); clear(); }
  function pointerMove(event: PointerEvent<SVGSVGElement>) { if (dragging.current === null) return; const rect = event.currentTarget.getBoundingClientRect(); pointEdit(dragging.current, covarianceDrag(event.clientX, event.clientY, rect, chart)); }
  function pointerStart(event: PointerEvent<SVGSVGElement>) {
    if (event.button !== 0) return;
    const rect = event.currentTarget.getBoundingClientRect(), x = (event.clientX - rect.x) / rect.width * chart.width, y = (event.clientY - rect.y) / rect.height * chart.height;
    const candidates = chart.points.map(p => ({ id: p.id, distance: Math.hypot(x - p.x, y - p.y) })).filter(p => p.distance <= 20).sort((p, q) => p.distance - q.distance || (p.id === selected ? -1 : q.id === selected ? 1 : p.id - q.id));
    if (!candidates.length) return;
    event.preventDefault(); dragging.current = candidates[0].id; setSelected(candidates[0].id); event.currentTarget.setPointerCapture(event.pointerId);
  }
  const rail = experiment ? <GuidedExperiment label={`Experiment ${index + 1} of 4`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="covariance-prediction" explanationName="covariance-explanation"
    onPredict={id => { start(); setPrediction(id); }} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores this experiment’s starting dataset. Reset restarts it.</>} observation={prediction === "0" ? "The observed evidence matches your prediction." : "The evidence challenges your prediction."}
    onNext={() => start(index + 1)} nextLabel={index === 3 ? "Try the transfer check" : "Next experiment"} /> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "A changed pair in new units" : "Explore paired association"}>
    {transfer ? <><p>Without Guide help, keep Downward, select Point 1, set Y coordinate to 6, and set X unit multiplier to 2. Keep its X coordinate at 4 in the new units. Explain the resulting covariance and r.</p><ExperimentChoices legend="Transfer explanation" name="covariance-transfer" choices={[
      { id: "normalized", label: "Mean X = 10 and mean Y = 4.6. Covariance = −10; spread product ≈ 10.5736, so r ≈ −0.9458. The unit factor affects numerator and denominator equally; the edited pair changes the linear alignment. This is descriptive association, not causal proof." },
      { id: "probability", label: "r is −10, meaning a negative probability that X causes Y." },
      { id: "unchanged", label: "Changing Point 1 leaves all means and products unchanged; only units explain the new r." },
    ]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (!reachedCovariance(4, state) ? <p role="status" className={shared.feedback}>First use the Downward dataset, Point 1 Y = 6 and X unit multiplier = 2. Keep the other pairs unchanged.</p> : transferAnswer !== "normalized" ? <p role="status" className={shared.feedback}>Try again. Recompute both means and products after editing a pair; divide covariance by the positive sample-spread product. Unit changes cancel in r; data changes can alter it.</p> : <><ExperimentResult title="Transfer explained">Changing Point 1 updates mean Y to 4.6. The unit factor doubles covariance from −5 to −10 and doubles the spread product, preserving the edited dataset’s r ≈ −0.9458. Direction is negative, and linear alignment is close to perfect; neither proves causation.</ExperimentResult><ExperimentButton onClick={() => { setIndex(5); clear(); }}>Explore freely</ExperimentButton></>)}</> : <><p>Move any pair, compare presets or convert X units. Inspect both spreads before interpreting Pearson r. Reset returns to Experiment 1.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Covariance & Correlation Map" subtitle="Move paired values; separate direction, strength and units." rail={rail}>
    <LessonToolbar scenarios={covariancePresets} selectedId={covariancePresetId(state.points)} onSelect={id => { setState(s => ({ ...s, points: covarianceDataset(id) })); clear(); }} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={shared.evidence} aria-label="Paired data manipulation"><DatasetHeading /><p>Each numbered dot is one quantitative (X, Y) pair. Dashed lines cross at the current means. Drag a dot or select its number below and use the coordinate controls. Labels have leader lines; the dots encode the actual values.</p>
      <p role="status" data-covariance-status>Point {selected + 1}: X = {number(term.x)}, Y = {number(term.y)}. Covariance = {number(a.covariance)}; Pearson r = {a.r === null ? "undefined (zero spread)" : number(a.r)}.</p>
      <div ref={chartRef} className={styles.chart}><svg data-covariance-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`Five paired observations. Mean X ${number(a.mx)}, mean Y ${number(a.my)}. Sample covariance ${number(a.covariance)}; Pearson r ${a.r === null ? "undefined because one spread is zero" : number(a.r)}. X axis 0 to ${10 * state.scale}; Y axis 0 to 10. Coordinate controls and paired-value table provide the data equivalent.`} onPointerDown={pointerStart} onPointerMove={pointerMove} onPointerUp={event => { pointerMove(event); dragging.current = null; }} onPointerCancel={() => { dragging.current = null; }} onLostPointerCapture={() => { dragging.current = null; }}>
        {chart.xTicks.map(t => <g key={t.value}><line x1={t.x.toFixed(3)} x2={t.x.toFixed(3)} y1={chart.top} y2={chart.baseline} /><text x={t.x.toFixed(3)} y={chart.baseline + 20} textAnchor="middle">{t.value}</text></g>)}{chart.yTicks.map(t => <g key={t.value}><line x1={chart.left} x2={chart.width - chart.right} y1={t.y.toFixed(3)} y2={t.y.toFixed(3)} /><text x={chart.left - 10} y={(t.y + 4).toFixed(3)} textAnchor="end">{t.value}</text></g>)}<text x="8" y="18">Y</text><text x={(chart.width / 2).toFixed(3)} y="353" textAnchor="middle">X · current units</text>
        <line data-mean-x x1={chart.meanX.toFixed(3)} x2={chart.meanX.toFixed(3)} y1={chart.top} y2={chart.baseline} /><line data-mean-y x1={chart.left} x2={chart.width - chart.right} y1={chart.meanY.toFixed(3)} y2={chart.meanY.toFixed(3)} />
        {chart.points.map((p, i) => <g key={i}><line data-leader x1={p.x.toFixed(3)} y1={p.y.toFixed(3)} x2={chart.labels[i].x.toFixed(3)} y2={chart.labels[i].y.toFixed(3)} /><circle data-point={i + 1} cx={p.x.toFixed(3)} cy={p.y.toFixed(3)} r={i === selected ? 10 : 7} data-selected={i === selected} /><text data-point-label={i + 1} x={chart.labels[i].x.toFixed(3)} y={(chart.labels[i].y + 4).toFixed(3)} textAnchor="middle">{i + 1}</text></g>)}
      </svg></div><p className={shared.math} data-covariance-means>Mean X = {number(a.mx)}; mean Y = {number(a.my)}. Five paired observations; sample denominator n − 1 = 4.</p>
      <LessonToggleGroup label="Select a point" choices={state.points.map((_, i) => ({ id: String(i), label: `Point ${i + 1}` }))} value={String(selected)} onChange={id => setSelected(Number(id))} />
      <div className={shared.controlGrid}><LessonRangeControl label="X coordinate" value={term.x} min={0} max={10 * state.scale} step={.5 * state.scale} help={`Selected Point ${selected + 1}, in current X units. Grid step ${.5 * state.scale}; bound ${10 * state.scale}.`} onChange={x => pointEdit(selected, { x: x / state.scale })} /><LessonRangeControl label="Y coordinate" value={term.y} min={0} max={10} step={.5} help={`Selected Point ${selected + 1}. Moving a pair recomputes both means and all departure products.`} onChange={y => pointEdit(selected, { y })} /></div>
      <LessonRangeControl label="X unit multiplier" value={state.scale} min={1} max={5} step={1} help="Positive factor applied to every X number, its mean, SD and covariance. Y values stay fixed." onChange={scale => { setState(s => ({ ...s, scale })); clear(); }} />
      <p>Positive unit changes rescale X numbers and the X axis ticks together. The point pattern stays in place because the axis uses the new units too. Point edits change the underlying pairs. Coincident points remain separately selectable by number; when dragging coincident dots, the selected point takes priority.</p>
    </section>
    <section className={shared.evidence} aria-label="Paired departure construction"><h2>Paired departures from the means</h2><p className={shared.math} data-covariance-product>Point {selected + 1}: ({number(term.x)} − {number(a.mx)}) × ({number(term.y)} − {number(a.my)}) = {number(term.dx)} × {number(term.dy)} = {number(term.product)}.</p><p>Same-sign departures give positive products; opposite signs give negative products; a zero departure gives zero. Every center and product is recomputed after a pair changes.</p><p className={shared.math} data-covariance-formula>Sum of products = {number(a.total)}. Sample covariance = {number(a.total)} / 4 = {number(a.covariance)}. Sample SD X = {number(a.sx)}; sample SD Y = {number(a.sy)}.</p></section>
    <LessonSummaries label="Covariance and scale-normalized correlation" summaries={[
      { label: "Sample covariance", color: "#33486d", value: number(a.covariance), definition: "Signed co-variation, in X units × Y units.", formula: "Σ[(X − mean X)(Y − mean Y)] / (n − 1)" },
      { label: "Pearson r", color: "#5031dc", value: a.r === null ? "Undefined" : number(a.r), definition: a.r === null ? "At least one sample SD is zero." : "Unitless direction and linear alignment.", formula: a.r === null ? "Zero spread: normalization is undefined" : `${number(a.covariance)} / ${number(a.denominator)}` },
      { label: "Spread product", color: "#33486d", value: number(a.denominator), definition: "Both sample spreads normalize covariance.", formula: `sX × sY = ${number(a.sx)} × ${number(a.sy)}` },
    ]} />
    <section className={shared.evidence} aria-label="Interpretation and paired evidence"><p>r describes linear association, not slope, probability or causation. Zero correlation need not mean independence or no nonlinear relationship. If either variable has zero spread, r is undefined. These five toy pairs are descriptive data; no population estimate, test or causal conclusion is supplied.</p><details><summary>Paired values and departure products</summary><div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="Paired product evidence"><table><caption>Five current pairs; all departures use the current means. Sample covariance divides the sum by 4.</caption><thead><tr>{["Point", "X", "Y", "X departure", "Y departure", "Product"].map(h => <th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{a.terms.map((t, i) => <tr key={i}><th scope="row">{i + 1}</th><td>{number(t.x)}</td><td>{number(t.y)}</td><td>{number(t.dx)}</td><td>{number(t.dy)}</td><td>{number(t.product)}</td></tr>)}</tbody><tfoot><tr><th scope="row" colSpan={5}>Sum of paired products</th><td>{number(a.total)}</td></tr></tfoot></table></div></details><details><summary>Conventions and sources</summary><p>Sample covariance and both sample variances use n − 1 = 4; sample SD is the square root of sample variance. Dividing all three by n instead gives different covariance and SDs but the same Pearson r when spread is nonzero. Pearson r equals covariance divided by the product of the consistently defined SDs. Positive scale factors cancel. Negating just one variable would reverse the sign.</p><p>The finite editable grid contains five pairs with base values 0 to 10 in half-unit steps. X unit multiplier is a positive integer 1 to 5; X editors use displayed units and a correspondingly scaled grid. Statistical calculations precede display rounding. Dots remain correctly mapped when axis labels change; displaced number labels identify dots through leader lines. Strong nonlinear patterns, outlier diagnostics, inference and confounding have separate lessons.</p><a href="https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/correlat.htm" target="_blank" rel="noreferrer">NIST · Pearson correlation formula</a><br /><a href="https://www.itl.nist.gov/div898/software/dataplot/refman2/ch2/covarian.pdf" target="_blank" rel="noreferrer">NIST · Sample covariance convention</a><br /><a href="https://www.stat.berkeley.edu/~stark/SticiGui/Text/computeR.htm" target="_blank" rel="noreferrer">Berkeley · Unit transformations and correlation</a></details></section>
  </LearningPage>;
}
