"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSelect, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeRanking, moveRankingItem, rankingChart, rankingGrades, rankingIds, rankingNumber as number, rankingScenarios, type RankingScenario, type RankingState } from "./ranking-engine";
import { rankingBaseline, reachedRanking } from "./lesson-state";
import { rankingExperiments } from "./learning-experiments";
import styles from "./playground.module.css";

export function RankingPlayground(){
  const [state,setState]=useState(rankingBaseline),[query,setQuery]=useState(0),[item,setItem]=useState("A"),[width,setWidth]=useState(640);
  const [index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
  const chartRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const el=chartRef.current;if(!el)return;const update=()=>setWidth(Math.max(200,el.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(el);return()=>observer.disconnect();},[]);
  const a=useMemo(()=>analyzeRanking(state),[state]),result=a.queries[query],chart=rankingChart(result,width),experiment=rankingExperiments[index],transfer=index===3,rank=state.orders[query].indexOf(item)+1;
  const reached=!!prediction&&!!experiment&&reachedRanking(index,state),complete=reached&&explanation==="0";
  function clear(){setExplanation(null);setTransferAnswer(null);}
  function start(next=index){setIndex(next);setState(rankingBaseline(next));setQuery(0);setItem("A");setPrediction(null);clear();}
  function edit(next:RankingState){if(JSON.stringify(next)===JSON.stringify(state))return;setState(next);clear();}
  function move(next:number){if(next===rank)return;const orders:[readonly string[],readonly string[]]=[state.orders[0],state.orders[1]];orders[query]=moveRankingItem(orders[query],item,next);edit({...state,orders});}
  function scenario(next:RankingScenario){if(next===state.scenario)return;edit({...rankingBaseline(next==="binary"?0:2),scenario:next});setQuery(0);setItem("A");}
  const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="ranking-prediction" explanationName="ranking-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores this experiment’s orders and settings. Reset restarts it.</>} observation={prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}
    onNext={()=>start(index+1)} nextLabel={index===2?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Handle a query with no relevant items":"Match the metric to the question"}>
    {transfer?<><p>Without Guide help, choose No relevant Q2, inspect Q2 under Query, and keep Top k 3 and its starting orders. Reconstruct Q2’s precision, recall, reciprocal rank and ideal gain; then use both query terms to compute MRR. Should an empty relevant set be skipped automatically?</p>
      {query===1&&reachedRanking(3,state)&&<><ExperimentChoices legend="Transfer explanation" name="ranking-transfer" choices={[
        {id:"explicit",label:"Q2 has no relevant IDs. Precision@3 is 0/3=0, but recall is Undefined because its relevant-count denominator is zero. Ideal DCG@3 is zero, so nDCG is Undefined too. This demo assigns Q2 RR=0 and includes both queries: Q1 RR=1, so MRR=(1+0)/2=0.5. These explicit empty-query conventions are different from silently skipping Q2; none proves production quality."},
        {id:"perfect",label:"Nothing relevant was missed, so recall and nDCG must both equal 1 and prove perfect retrieval."},
        {id:"skip",label:"Q2 must be skipped without stating a policy, so the displayed two-query MRR must be 1."},
      ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="explicit"?<p role="status" className={shared.feedback}>Try again. Separate a defined zero numerator from division by a zero denominator. RR uses an explicit zero convention for no hit; the shown mean includes both query terms. Skipping an empty query would be a different aggregation policy.</p>:<><ExperimentResult title="Transfer explained">Empty-query behavior is part of a metric’s definition. State undefined denominators and the RR/mean policy before comparing results; a silent policy change can change the reported mean.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(4);clear();}}>Explore freely</ExperimentButton></>)}</>}
    </>:<><p>Reorder either query, change k, and compare binary counts, first-hit rank and graded gain. Query and Item to move select evidence; Move to rank changes an order. Keep judgments and evaluation conventions fixed when comparing rankings. These two toy queries do not establish general production quality.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Retrieval Ranking Metrics Lab" subtitle="Reorder results; separate metric questions." rail={rail}>
    <LessonToolbar scenarios={rankingScenarios} selectedId={state.scenario} onSelect={id=>scenario(id as RankingScenario)} onReset={()=>start(experiment||transfer?index:0)}/>
    <section className={shared.evidence} aria-label="Manually ranked judged retrieval results">
      <h2>Your dataset</h2><p>Six fixed IDs for each of two toy queries have authored relevance grades. Grade 0 means not relevant; any positive grade counts as one relevant item for binary metrics. Larger grades carry more gain for nDCG. Reorder results without changing these judgments. No learned score or real semantic model is evaluated.</p>
      <h3>Discounted gain by rank (Q{query+1})</h3>
      <div className={styles.chart} ref={chartRef}><svg data-ranking-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`Q${query+1} counted gain by rank, fixed gain scale 0 to 7. Exact grades, discounts and contributions are in the all-ID table.`}>
        {chart.ticks.map(t=><g key={t.value}><line x1={t.x} x2={t.x} y1="20" y2="203"/><text x={t.x} y="222" textAnchor="middle">{t.value}</text></g>)}
        {chart.rows.map(r=>{const inside=r.width>chart.span-65;return <g data-ranking-bar={r.id} key={r.id}><text x={chart.left-10} y={r.y+13} textAnchor="end">{r.rank}. {r.id}</text><rect data-ranking-gain x={r.x} y={r.y} width={r.width} height="18" className={styles.gain}/><text data-ranking-gain-label x={inside?r.x+r.width-6:r.x+r.width+8} y={r.y+13} textAnchor={inside?"end":"start"} className={inside?styles.inside:undefined}>{number(r.contribution)}</text>{!r.returned&&<line className={styles.outside} x1={chart.left} x2={chart.left+chart.span} y1={r.y+22} y2={r.y+22}/>}</g>;})}
        <line data-ranking-cutoff className={styles.cutoff} x1={chart.left} x2={chart.left+chart.span} y1={chart.rows[state.k-1].y+24} y2={chart.rows[state.k-1].y+24}/>
        <text x={chart.left+chart.span/2} y="240" textAnchor="middle">Counted gain (fixed 0..7)</text>
      </svg></div><p>The dashed boundary is after rank {state.k}. Bars count gain only in the returned prefix; rows outside it have zero counted gain, not necessarily grade 0. Every exact ID, relevance grade and inclusion remains in the table. Fixed gain scale 0..7 permits direct comparisons.</p>
      <div className={shared.controlGrid}><LessonSelect label="Query" value={String(query)} choices={[{id:"0",label:"Q1"},{id:"1",label:"Q2"}]} onChange={id=>setQuery(Number(id))}/><LessonSelect label="Item to move" value={item} choices={rankingIds.map(id=>({id,label:id}))} onChange={setItem}/><LessonRangeControl label="Move to rank" value={rank} min={1} max={6} step={1} help={`Remove ${item} from Q${query+1} and insert at this rank; other IDs keep their relative order.`} onChange={move}/><LessonRangeControl label="Top k" value={state.k} min={1} max={6} step={1} help="Shared cutoff for precision, recall and nDCG; full-list RR/MRR do not use this cutoff." onChange={k=>edit({...state,k})}/></div>
      <p role="status" data-ranking-status className={shared.math}>{rankingScenarios.find(s=>s.id===state.scenario)!.label} · Inspect Q{query+1} · Item {item} at rank {rank} · Top k {state.k} · Q1 {state.orders[0].join(",")} · Q2 {state.orders[1].join(",")}</p>
      <p>Query inspects a different list; Item to move selects an ID. These selections preserve both orders and answers. Only Move to rank changes an order. Scenario changes restore named starting orders/k; prediction or Reset restores the current experiment.</p>
    </section>
    <section className={shared.evidence} aria-label="All-ID ranking construction"><h2>Ranked results for Q{query+1}</h2>
      <div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="All six query-specific IDs, grades, discounts and counted gains"><table><caption>Every ID appears exactly once. Relevant means grade&gt;0. Gain = 2ᵍʳᵃᵈᵉ−1; discount = 1/log₂(rank+1). Counted gain is zero outside Top k. Values are computed at full precision, displayed rounded to six decimals.</caption><thead><tr>{["Rank","Item","Grade","Relevant?","Gain","Discount","Counted gain","Returned"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{result.rows.map(r=><tr data-ranking-row={r.id} key={r.id}><td>{r.rank}</td><th scope="row">{r.id}</th><td>{r.grade}</td><td>{r.relevant?"Yes":"No"}</td><td>{number(r.gain)}</td><td>{number(r.discount)}</td><td>{number(r.contribution)}</td><td>{r.returned?"Included":"Outside"}</td></tr>)}</tbody></table></div>
      <p data-ranking-normalization className={shared.math}>Q{query+1}: found {result.found} / returned {state.k}; found {result.found} / total relevant {result.total}. DCG@{state.k} = {number(result.dcg)}; ideal DCG@{state.k} = {number(result.idcg)} from all six grades sorted descending ({[...rankingGrades[state.scenario][query]].sort((a,b)=>b-a).join(",")}) before the same cutoff.</p>
      {result.total===0&&<p role="status" data-ranking-empty>No relevant IDs for this query: precision is 0/{state.k}=0. Recall has denominator 0, and nDCG’s ideal gain is 0, so both are Undefined. This demo defines no-hit RR as 0 and includes it in the two-query mean.</p>}
    </section>
    <LessonSummaries label="Selected-query metrics and two-query mean" summaries={[
      {label:`Precision@${state.k} (Q${query+1})`,color:"#5031dc",value:number(result.precision),definition:"Relevant fraction of the returned prefix.",formula:`${result.found} found / ${state.k} returned`,comparison:"Uses binary relevance; order inside the same set does not matter."},
      {label:`Recall@${state.k} (Q${query+1})`,color:"#087c78",value:number(result.recall),definition:"Fraction of all relevant IDs recovered.",formula:`${result.found} found / ${result.total} total relevant`,comparison:"Complete six-item judged universe; zero denominator is undefined."},
      {label:"MRR (two queries)",color:"#ad4508",value:number(a.mrr),definition:"Mean of both full-list reciprocal ranks.",formula:`(${number(a.queries[0].rr)} + ${number(a.queries[1].rr)}) / 2`,comparison:"First hit only; includes no-hit RR=0. This is not MRR@k."},
      {label:`nDCG@${state.k} (Q${query+1})`,color:"#33486d",value:number(result.ndcg),definition:"Discounted graded gain versus the ideal prefix.",formula:`${number(result.dcg)} / ${number(result.idcg)}`,comparison:"Same k/gain/discount in numerator and ideal denominator."},
    ]}/>
    <section className={shared.evidence} aria-label="Both query reciprocal-rank terms and metric limits">
      <p data-ranking-rr className={shared.math}>Q1 first relevant rank {a.queries[0].first??"None"}: RR = {number(a.queries[0].rr)}. Q2 first relevant rank {a.queries[1].first??"None"}: RR = {number(a.queries[1].rr)}. MRR = (RRQ1+RRQ2)/2 = {number(a.mrr)}.</p>
      <p>RR uses the first relevant item in the full six-item list; changing only k cannot change this untruncated RR or MRR. One query’s RR is not the two-query mean. Later relevant items do not affect first-hit RR. Other tasks may use MRR@k or different empty-query policies; state the convention.</p>
      <details><summary>Construction and limits</summary><p>Both queries have six unique IDs with fixed toy relevance grades. Query-specific judgments need not agree for an ID. Positive grades are binary relevant; nDCG uses gains 2ᵍʳᵃᵈᵉ−1 (grades 0,1,2,3 give gains 0,1,3,7), discounted by 1/log₂(rank+1). A grade is not a probability. There are no learned ranking scores or score ties: the manual order is strict. Moving one ID preserves all other relative order and every identity.</p>
        <p>Precision@k=found/k. Recall@k=found/total relevant when the relevant count is positive, otherwise Undefined. DCG sums the top-k discounted gains; ideal DCG sorts every judged item by descending grade and then applies the same k and discounts. nDCG=DCG/ideal DCG when the ideal is positive, otherwise Undefined. Equal-grade ideal permutations give the same denominator. Different gain conventions give different values; for example, scikit-learn uses supplied true scores directly, rather than automatically applying this demo’s exponential gain.</p>
        <p>MRR is the arithmetic mean of two full-list RR values. Each RR is 1/first relevant rank, or explicitly 0 if no relevant item exists. Empty queries remain in the mean. Skipping or scoring them differently would be another policy; undefined recall/nDCG does not imply perfect retrieval. Selected-query precision/recall/nDCG are not averages across queries. More results or a higher one-metric score does not establish overall task success.</p>
        <p>Actual rank/k/scenario edits clear stale explanations; Query and Item to move only select evidence. Reset restores the current baseline, and free-exploration Reset starts Experiment 1. Native selects, number editors and sliders make every order reachable without dragging. This small evaluation demo excludes training, embeddings, ANN/indexing, unknown judgments, label editing, significance tests and production-quality claims. Compare only with the same query set, judgments, cutoff, gain/discount and aggregation conventions.</p>
        <a href="https://nlp.stanford.edu/IR-book/html/htmledition/evaluation-of-ranked-retrieval-results-1.html" target="_blank" rel="noreferrer">Stanford IR book · Ranked retrieval and exponential graded gain</a><br/><a href="https://trec.nist.gov/presentations/TREC8/removed/tsld051.htm" target="_blank" rel="noreferrer">NIST TREC · Reciprocal rank and mean across queries</a><br/><a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.ndcg_score.html" target="_blank" rel="noreferrer">scikit-learn · nDCG and gain conventions</a>
      </details>
    </section>
  </LearningPage>;
}
