"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonAction, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import {analyzeSe,seChart,seModels,type SeState} from "./se-engine";
import {seBaseline,reachedSe} from "./lesson-state";
import {seExperiments} from "./learning-experiments";
import styles from "./playground.module.css";
export function StandardErrorPlayground(){
  const [state,setState]=useState<SeState>(()=>seBaseline()),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null),[width,setWidth]=useState(640);
  const chartRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const element=chartRef.current;if(!element)return;const update=()=>setWidth(Math.max(200,element.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(element);return()=>observer.disconnect();},[]);
  const a=useMemo(()=>analyzeSe(state),[state]),chart=seChart(a,width),experiment=seExperiments[index],transfer=index===4,reached=!!prediction&&!!experiment&&reachedSe(index,state),complete=reached&&explanation==="0";
  function clear(){setExplanation(null);setTransferAnswer(null);}
  function start(next=index){setIndex(next);setState(seBaseline(next));setPrediction(null);clear();}
  function edit(patch:Partial<SeState>){setState(s=>({...s,...patch}));clear();}
  const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 4`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="se-prediction" explanationName="se-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores this experiment’s starting source, size and sample number. Reset restarts it.</>} observation={prediction==="0"?"The observed evidence matches your prediction.":"The evidence challenges your prediction."}
    onNext={()=>start(index+1)} nextLabel={index===3?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Does SE bound every error?":"Compare other mean distributions"}>
    {transfer?<><p>Without Guide help, choose Two levels, set Sample size to 320 and Sample number to 46. Compare the selected error with Theoretical SE and Batch SD.</p><ExperimentChoices legend="Transfer explanation" name="se-transfer" choices={[{id:"spread",label:"Mean 5.84375 has absolute error 0.84375, larger than theoretical SE 0.2795. SE describes distribution spread, not a guaranteed error bound. Batch SD 0.2812 is a finite approximation, not exact SE."},{id:"bound",label:"Every sample error must stay below SE; this selected mean proves the population changed."},{id:"repeats",label:"Theoretical SE uses 200 repetitions as n, so choosing sample 46 changes the formula."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!reachedSe(4,state)?<p role="status" className={shared.feedback}>First choose Two levels, Sample size 320 and Sample number 46. Read the exact selected record and distribution summaries.</p>:transferAnswer!=="spread"?<p role="status" className={shared.feedback}>Try again. Theoretical SE is a standard deviation across possible means, not a bound on each realized error. Each sample has 320 observations; 200 is the repetition count.</p>:<><ExperimentResult title="Transfer explained">1870 / 320 = 5.84375, with error 0.84375 from population mean 5. Theoretical SE = 5 / √320 = 0.279508… . Batch SD is 0.281224… . The selected error exceeds SE without changing the population or contradicting its definition.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(5);clear();}}>Explore freely</ExperimentButton></>)}</>:<><p>Compare another source, size or selected sample. The prepared batch stays fixed when only Sample number changes; changing size extends each sample’s prefix. More observations reduce theoretical SE under this model, without guaranteeing each realized error or a normal shape. Reset returns to Experiment 1.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Sampling Distributions & Standard Error" subtitle="Repeat samples. Measure how their means vary." rail={rail}>
    <LessonToolbar label="Known toy populations" scenarios={seModels} selectedId={state.model} onSelect={model=>edit({model:model as SeState["model"]})} onReset={()=>start(experiment||transfer?index:0)}/>
    <section className={shared.evidence} aria-label="Sampling controls"><p>Independent, equal-chance draws with replacement from a known fixed population. Records can repeat. Current source values: {a.model.values.join(", ")}; population mean = 5. This is an ideal model illustrated by reproducible samples.</p><div className={shared.controlGrid}><LessonRangeControl label="Sample size" value={state.size} min={1} max={400} step={1} help="Number of observations inside each mean. Extend or shorten the same prepared samples." onChange={size=>edit({size})}/><LessonRangeControl label="Sample number" value={state.sample} min={1} max={200} step={1} help="Highlight another of the same 200 sample means, without changing the batch." onChange={sample=>edit({sample})}/></div><div className={styles.actions}><LessonAction disabled={state.sample===200} onClick={()=>edit({sample:Math.min(200,state.sample+1)})}>Next sample</LessonAction></div><p role="status" data-se-status>Selected sample {state.sample} of 200. Each sample contains {state.size} {state.size===1?"observation":"observations"} from {a.model.label}. The repetition count 200 is different from sample size n = {state.size}.</p></section>
    <section className={shared.evidence} aria-label="Sampling distribution illustration"><h2>200 sample means</h2><p>A sampling distribution describes a statistic over possible repeated samples. These bars count a finite batch of 200 sample means, not individual observations or an exact probability law. Orange dashed line: population mean 5. Indigo solid line: selected mean {a.current.mean.toFixed(5)}. {a.current.mean===5?"The two lines coincide.":""}</p><div ref={chartRef} className={styles.chart}><svg viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`Histogram of 200 sample means at size ${state.size}. Fixed mean axis 0 to 10 and count axis 0 to 200. Selected mean ${a.current.mean.toFixed(5)}, population mean 5. Exact means and bin counts below.`} data-se-chart><text x="4" y="16">Count</text>{chart.counts.map(t=><g key={t.value}><line x1={chart.left} x2={chart.width-chart.right} y1={t.y} y2={t.y}/><text x={chart.left-7} y={t.y+4} textAnchor="end">{t.value}</text></g>)}{chart.bars.map(b=><rect key={b.lower} x={b.x} y={b.y} width={b.width} height={b.height} data-bin={b.lower} data-count={b.count}/>)}<line x1={chart.targetX} x2={chart.targetX} y1={chart.top} y2={chart.baseline} data-population-mean/><line x1={chart.selectedX} x2={chart.selectedX} y1={chart.top} y2={chart.baseline} data-selected-mean/>{chart.ticks.map((t,i)=><text key={t.value} x={t.x} y={chart.baseline+19} textAnchor={i===0?"start":i===4?"end":"middle"}>{t.value}</text>)}<text x={(chart.left+chart.width-chart.right)/2} y={chart.height-5} textAnchor="middle">Sample mean · fixed 0–10 scale</text></svg></div><p data-se-range>Observed means range from {a.meanMinimum.toFixed(5)} to {a.meanMaximum.toFixed(5)}. Each bin has width 0.25 and includes its lower endpoint, excluding its upper endpoint; the last includes 10. Count axis remains 0–200 as size changes.</p></section>
    <LessonSummaries label="Three different spreads" summaries={[{label:"Population SD",color:"#ad4508",value:a.sigma.toFixed(4),definition:"Spread of individual source values.",formula:"σ = √mean[(value − 5)²]"},{label:"Theoretical SE",color:"#5031dc",value:a.se.toFixed(4),definition:"SD of the model’s sample-mean distribution.",formula:`σ / √n = ${a.sigma.toFixed(4)} / √${state.size}`},{label:"Batch SD",color:"#33486d",value:a.batchSd.toFixed(4),definition:"Descriptive spread of these 200 means.",formula:"√[Σ(mean − batch average)² / 200]"}]}/>
    <section className={shared.evidence} aria-label="Selected estimate and batch data"><p className={shared.math} data-selected-sample>Sample {state.sample}: total {a.current.total} / size {state.size} = mean {a.current.mean.toFixed(5)}. Signed gap from population mean 5 = {a.gap.toFixed(5)}; absolute error = {Math.abs(a.gap).toFixed(5)}. Theoretical SE = {a.se.toFixed(6)}.</p><p data-batch-spread>Batch average of 200 means = {a.batchMean.toFixed(6)}. Batch SD = {a.batchSd.toFixed(6)}, computed around this batch average with denominator 200; it need not equal theoretical SE. Recent individual observations in the selected sample: {a.current.values.slice(-8).join(", ")}.</p><details><summary>Exact means of the 200 samples</summary><div className={styles.scrollTable} tabIndex={0} role="region" aria-label="Scrollable exact sample means"><table className={`${shared.dataTable} ${styles.table}`}><caption>Each sample has {state.size} observations. Selecting a sample changes its marker only.</caption><thead><tr><th scope="col">Sample</th><th scope="col">Total</th><th scope="col">Mean</th></tr></thead><tbody>{a.samples.map(s=><tr key={s.number}><th scope="row">{s.number}{s.number===state.sample?" · selected":""}</th><td>{s.total}</td><td>{s.mean.toFixed(5)}</td></tr>)}</tbody></table></div></details><details><summary>Exact histogram counts</summary><div className={styles.scrollTable} tabIndex={0} role="region" aria-label="Scrollable histogram counts"><table className={`${shared.dataTable} ${styles.table}`}><caption>40 bins of width 0.25. Counts sum to 200; empty bins included.</caption><thead><tr><th scope="col">Mean interval</th><th scope="col">Count</th></tr></thead><tbody>{a.bins.map((b,i)=><tr key={b.lower}><th scope="row">[{b.lower}, {b.upper}{i===39?"]":")"}</th><td>{b.count}</td></tr>)}</tbody></table></div></details></section>
    <section className={shared.evidence} aria-label="Sampling assumptions"><details><summary>Assumptions and reproducible sampling</summary><p>For independent draws with replacement from a fixed finite-variance source, Var(sample mean) = population variance / n and SE = σ / √n. These known-source identities require no normal shape. We use population SD, not an estimated sample SD; dependent or without-replacement designs require other formulas.</p><p>Seed 1309 creates 200 nonoverlapping blocks of 400 uniform draw positions using a 32-bit generator. Size reveals each block’s prefix; source changes map the same positions to new values. Sample number highlights one existing mean without resampling. Finite pseudorandom illustrations do not prove independence or convergence.</p><p>Theoretical SE describes all possible means under the model. The histogram and descriptive Batch SD summarize only 200 realized means; denominator 200 treats that batch as the complete displayed list. Neither quantity bounds one sample’s error or guarantees that every larger prefix improves. More repeated samples refine a distribution illustration; they do not change n or theoretical SE. Normal approximation, estimated SE, confidence intervals, dependence and bias correction are outside this lesson.</p><a href="https://www.stat.berkeley.edu/~stark/SticiGui/Text/standardError.htm" target="_blank" rel="noreferrer">Berkeley SticiGui · Standard error and the square-root rule</a></details></section>
  </LearningPage>;
}
