"use client";
import {useMemo,useState} from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import sharedStyles from "@/components/learning-page/learning-page.module.css";
import {adjustProbability,analyzeLoss} from "./cross-entropy-engine";
import {crossEntropyLessons,type CrossEntropyMode} from "./scenario";
import {lossDefaults,lossExperiments,modeChoices,modeDefaults,type CrossEntropyState} from "./learning-experiments";
import styles from "./playground.module.css";

const percent=(value:number)=>Number((value*100).toFixed(10));
const lossNumber=(value:number)=>value===Infinity?"∞":Number(value.toFixed(6)).toString();
const same=(a:CrossEntropyState,b:CrossEntropyState)=>a.mode===b.mode&&a.targets.length===b.targets.length&&a.targets.every(id=>b.targets.includes(id))&&crossEntropyLessons[a.mode].classes.every(c=>Math.abs(a.probabilities[c.id]-b.probabilities[c.id])<1e-10);

export function CategoricalCrossEntropyPlayground(){
  const [state,setState]=useState<CrossEntropyState>(lossDefaults);
  const [index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
  const lesson=crossEntropyLessons[state.mode];
  const a=useMemo(()=>analyzeLoss(lesson.classes,state.probabilities,state.targets,state.mode),[lesson,state]);
  const experiment=lossExperiments[index],transfer=index===3;
  const target=experiment?{...experiment.baseline,probabilities:adjustProbability(crossEntropyLessons[experiment.baseline.mode].classes,experiment.baseline.probabilities,experiment.changedId,experiment.value,experiment.baseline.mode)}:null;
  const reached=!!prediction&&!!target&&same(state,target),complete=reached&&explanation===experiment?.correctExplanation;
  const transferReached=same(state,{mode:"binary",targets:["negative"],probabilities:{negative:.1,positive:.9}});
  function clear(){setExplanation(null);setTransferAnswer(null)}
  function start(next=index){setIndex(next);setState(lossExperiments[next]?.baseline??lossDefaults);setPrediction(null);clear()}
  function edit(next:CrossEntropyState){setState(next);clear()}
  const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="loss-prediction" explanationName="loss-explanation"
    onPredict={id=>{start();setPrediction(id)}} onExplain={setExplanation}
    predictionHelp={<>Choosing a prediction restores the experiment’s starting mode, target and probabilities.</>} observation={prediction===experiment.correctPrediction?"Your prediction matches the evidence.":"The loss challenges your prediction. Compare the actual targets and their loss contributions."}
    onNext={()=>start(index+1)} nextLabel={index===2?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Change what happened":"Match the target shape"}>
    {transfer?<><p>Choose Binary, set True outcome to No and Yes probability (%) to 90. Which probability now determines the loss?</p><ExperimentChoices legend="Transfer explanation" name="loss-transfer" choices={[{id:"no",label:"No has the actual outcome’s 10% probability, so loss is −ln(0.10) ≈ 2.303 nats."},{id:"yes",label:"Yes has 90%, so loss remains −ln(0.90) ≈ 0.105 nats regardless of the target."},{id:"ignore",label:"The loss ignores this example because the binary target is No."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!transferReached?<p className={sharedStyles.feedback} role="status">First choose Binary, set True outcome to No and Yes probability (%) to 90.</p>:transferAnswer!=="no"?<p className={sharedStyles.feedback} role="status">Try again. Use No’s complement probability. A negative binary target still contributes to loss.</p>:<><ExperimentResult title="Transfer explained">The probabilities stayed fixed, but the target selects No. Its probability is 10%, so loss is about 2.303 nats. A confident guess for Yes is wrong for this known outcome.</ExperimentResult><ExperimentButton onClick={()=>setIndex(4)}>Explore freely</ExperimentButton></>)}</>:<><p>Compare targets and predictions separately. In Multi-label, try no true labels or all four true labels. Every label still contributes. In Categorical, the loss depends on the one true probability.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  const editable=state.mode==="binary"?lesson.classes.filter(c=>c.id==="positive"):lesson.classes;
  const formula=state.mode==="multilabel"?"Mean of all four binary loss terms":"−ln(probability of the true outcome)";
  return <LearningPage title="Cross Entropy Loss" subtitle="Put probability on what happened." rail={rail}>
    <LessonToolbar label="Target shapes" scenarios={modeChoices} selectedId={state.mode} onSelect={id=>edit(modeDefaults(id as CrossEntropyMode))} onReset={()=>start(experiment||transfer?index:0)}/>
    <p className={styles.context}>{state.mode==="binary"?"One yes/no question: No + Yes = 100%. No is the complement of Yes.":state.mode==="categorical"?"Exactly one class is true. One-hot means one target is 1 and the rest are 0. These four probabilities sum to 100%.":"Separate yes/no predictions: any subset of labels can be true, including none. Their probabilities need not sum to 100%; actual labels can be related."}</p>
    {state.mode==="multilabel"?<fieldset className={styles.targets}><legend>True labels</legend>{lesson.classes.map(c=><label key={c.id}><input type="checkbox" checked={state.targets.includes(c.id)} onChange={()=>edit({...state,targets:state.targets.includes(c.id)?state.targets.filter(id=>id!==c.id):[...state.targets,c.id]})}/>{c.label}</label>)}</fieldset>:<><h2 className={styles.targetHeading}>{state.mode==="binary"?"True outcome":"True class"}</h2><LessonToggleGroup label={state.mode==="binary"?"True outcome":"True class"} choices={lesson.classes} value={state.targets[0]} onChange={id=>edit({...state,targets:[id]})}/></>}
    <p className={styles.context}>The target records what happened. Changing it keeps the predicted probabilities fixed.</p>
    <div className={sharedStyles.controlGrid} data-single={editable.length===1}>{editable.map(c=><LessonRangeControl key={`${state.mode}-${c.id}`} label={`${c.label} probability`} unit="%" value={percent(state.probabilities[c.id])} min={1} max={state.mode==="categorical"?97:99} step={1} onChange={value=>edit({...state,probabilities:adjustProbability(lesson.classes,state.probabilities,c.id,value/100,state.mode)})} help={state.mode==="binary"?"No probability is 100% minus this value.":state.mode==="categorical"?"The other classes redistribute to keep 100%, each with at least 1%. This class keeps the chosen whole percent.":"This label changes alone; the other probabilities stay fixed."}/>)}</div>
    <section className={sharedStyles.evidence} aria-label="Prediction and loss contributions"><h2>Prediction and loss contributions</h2><p>Bars share a fixed 0–100% scale. A target of 1 marks a true outcome or label; 0 marks a false one.</p><div className={styles.axis}><span/><div><span>0%</span><span>50%</span><span>100%</span></div><span/></div>{a.terms.map(t=><div key={t.classItem.id} className={styles.termRow}><div className={styles.barRow}><strong>{t.classItem.label}<small>Target {t.target}</small></strong><div className={styles.track} role="img" aria-label={`${t.classItem.label}, target ${t.target}, predicted ${percent(t.probability)}%`}><span style={{width:`${Number((t.probability*100).toPrecision(6))}%`}}/></div><output>{percent(t.probability)}%</output></div><p>{state.mode!=="multilabel"&&t.target===0?"Contribution = 0 (this class is not the actual outcome).":`Contribution = −ln(${t.target===0?`1 − ${t.probability}`:t.probability}) ≈ ${lossNumber(t.loss)} nats.`}</p></div>)}</section>
    <LessonSummaries label="Loss and probability contract" summaries={[{label:"Cross entropy",value:a.loss.toFixed(3),color:"#5031dc",definition:"Surprise for this known target, measured in natural-log units called nats.",formula,comparison:state.mode==="multilabel"?`Sum ${lossNumber(a.loss*4)} nats / 4 labels`:"Only the actual outcome’s probability sets this loss."},{label:"Prediction total",value:`${percent(a.total)}%`,color:"#1760db",definition:state.mode==="multilabel"?"Sum of four separate label probabilities, without a shared normalization rule.":"Probability across mutually exclusive outcomes.",formula:state.mode==="multilabel"?"Each label is its own yes/no prediction":"Probabilities sum to 100%",comparison:state.mode==="multilabel"?"A total above 100% is valid here.":"Changing one class automatically adjusts the others."}]}/>
    <section className={styles.optional} aria-label="Supporting loss evidence"><details><summary>Worked loss</summary><p>ln is the natural logarithm. The negative log −ln(p) measures surprise: larger probability on what happened means less loss. These are per-example losses, not accuracy.</p><p>{state.mode==="multilabel"?"For every label: true uses −ln(p); false uses −ln(1−p). Add all four terms and divide by 4, including false labels. This is not an average of only the true labels.":"The categorical expression −sum(y × ln(p)) reduces to −ln(pTrue) for a one-hot target. Binary uses the same idea for No/Yes: actual Yes uses −ln(pYes), actual No uses −ln(1−pYes)."}</p><div className={styles.scroller} role="region" aria-label="Scrollable loss calculation" tabIndex={0}><table><caption>Targets, predictions and natural-log contributions. Numbers are rounded for display; loss uses actual predictions without clipping.</caption><thead><tr><th scope="col">Class / label</th><th scope="col">Target</th><th scope="col">Prediction</th><th scope="col">Contribution (nats)</th></tr></thead><tbody>{a.terms.map(t=><tr key={t.classItem.id}><th scope="row">{t.classItem.label}</th><td>{t.target}</td><td>{t.probability}</td><td>{lossNumber(t.loss)}</td></tr>)}</tbody></table></div><p>{formula}: ≈ {lossNumber(a.loss)} nats.</p><p>These controls deliberately avoid 0% and 100%. Mathematically, assigning zero probability to an event that happened gives infinite loss; assigning probability one gives zero loss. For a false label, its event is absence, with probability 1−p.</p></details><details><summary>Reference cases</summary><p>Three fixed examples for this mode. They are comparisons rather than controls.</p><div className={styles.scroller} role="region" aria-label="Scrollable reference cases" tabIndex={0}><table><thead><tr><th scope="col">Case</th><th scope="col">True outcomes / labels</th><th scope="col">Predictions (%)</th><th scope="col">Loss (nats)</th></tr></thead><tbody>{lesson.examples.map(e=>{const ids=e.trueClassIds??[e.trueClassId],loss=analyzeLoss(lesson.classes,e.probabilities,ids,state.mode).loss;return <tr key={e.id}><th scope="row">{e.title}</th><td>{lesson.classes.filter(c=>ids.includes(c.id)).map(c=>c.label).join(", ")||"None"}</td><td>{lesson.classes.map(c=>`${c.label} ${percent(e.probabilities[c.id])}`).join("; ")}</td><td>{lossNumber(loss)}</td></tr>})}</tbody></table></div></details></section>
    <p className={styles.context}>Lower loss rewards probabilities consistent with the known target. It does not supply a universal good/bad cutoff, prove calibration, or substitute for evaluation on other examples.</p>
    <p role="status" aria-live="polite" aria-atomic="true" className={sharedStyles.liveUpdate}>{state.mode}. True {a.trueClasses.map(c=>c.label).join(", ")||"none"}. {a.terms.map(t=>`${t.classItem.label} prediction ${percent(t.probability)}%, target ${t.target}, contribution ${lossNumber(t.loss)} nats`).join("; ")}. Cross entropy {lossNumber(a.loss)} nats; prediction total {percent(a.total)}%.</p>
  </LearningPage>;
}
