"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { alternativeMean, analyzeErrors, differenceSE, errorChart, errorExamples, errorPercent, type ErrorState } from "./errors-engine";
import { errorsBaseline, reachedErrors } from "./lesson-state";
import { errorExperiments } from "./learning-experiments";
import styles from "./playground.module.css";

export function ErrorsPlayground() {
  const [state, setState] = useState<ErrorState>(() => errorsBaseline()), [index, setIndex] = useState(0);
  const [prediction, setPrediction] = useState<string | null>(null), [explanation, setExplanation] = useState<string | null>(null), [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const [width, setWidth] = useState(640), chartRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const element = chartRef.current;
    if (!element) return;
    const update = () => setWidth(Math.max(200, element.getBoundingClientRect().width));
    update();
    const observer = new ResizeObserver(update); observer.observe(element);
    return () => observer.disconnect();
  }, []);
  const a = useMemo(() => analyzeErrors(state), [state]), experiment = errorExperiments[index], transfer = index === 3;
  const reached = !!prediction && !!experiment && reachedErrors(index, state), complete = reached && explanation === "0";
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function start(next = index) { setIndex(next); setState(errorsBaseline(next)); setPrediction(null); clear(); }
  function edit(patch: Partial<ErrorState>) { setState(s => ({ ...s, ...patch })); clear(); }
  const rail = experiment ? <GuidedExperiment label={`Experiment ${index + 1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="errors-prediction" explanationName="errors-explanation"
    onPredict={id => { start(); setPrediction(id); }} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores this experiment’s starting settings. Reset restarts it.</>} observation={prediction === "0" ? "The observed evidence matches your prediction." : "The evidence challenges your prediction."}
    onNext={() => start(index + 1)} nextLabel={index === 2 ? "Try the transfer check" : "Next experiment"} /> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "A missed real effect" : "Explore the error tradeoff"}>
    {transfer ? <><p>Without Guide help, select Real gap · Observed Z 1.2 and set Two-sided cutoff to 2.58. Classify this known-truth example and explain β.</p><ExperimentChoices legend="Transfer explanation" name="errors-transfer" choices={[
      { id: "miss", label: "This real-gap example fails to reject because 1.2 is below 2.58: one Type II miss. β ≈ 64.44% is the repeated miss rate given true gap 2.5. It is not a posterior probability that this decision is wrong, and α ≈ 0.99% is conditioned on a different truth." },
      { id: "null", label: "Failing to reject proves there is no real gap, so a Type II error is impossible." },
      { id: "posterior", label: "β is the chance this particular conclusion is wrong, and α must equal 100% minus β." },
    ]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (!reachedErrors(3, state) ? <p role="status" className={shared.feedback}>First select Real gap · Observed Z 1.2 and set Two-sided cutoff to 2.58. Compare its decision with the supplied truth.</p> : transferAnswer !== "miss" ? <p role="status" className={shared.feedback}>Try again. A miss combines a real effect with failure to reject. β conditions on this specified real effect across repeated tests; α conditions on H0, so the two rates are not complements.</p> : <><ExperimentResult title="Transfer explained">The prepared example is a Type II miss. β ≈ 64.44% describes misses across repetitions in the real-gap world, while α ≈ 0.99% describes false alarms in the null world. Knowing this example’s truth classifies it directly; a real test does not reveal that truth.</ExperimentResult><ExperimentButton onClick={() => { setIndex(4); clear(); }}>Explore freely</ExperimentButton></>)}</> : <><p>Compare cutoffs and known-truth examples. Keep the population laws fixed, conditional rates separate and one outcome distinct from repeated behavior. Reset returns to Experiment 1.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;

  return <LearningPage title="Type I & Type II Errors Lab" subtitle="Move a cutoff; compare false alarms and missed effects." rail={rail}>
    <LessonToolbar label="Prepared known-truth examples" scenarios={errorExamples} selectedId={state.exampleId} onSelect={id => { const example = errorExamples.find(e => e.id === id); if (example) edit({ exampleId: example.id }); }} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={shared.evidence} aria-label="Error model and decision rule"><p>Fixed toy A/B model: independent normal observations, known population SD 4 in each group, size 25 per group. True gap is 0 under H0 or 2.5 under one specified real alternative. Difference SE = {differenceSE.toFixed(4)}. Standardized Z has SD 1 in either world; its mean is 0 or {alternativeMean.toFixed(4)}.</p><p>The toolbar’s supplied truths and observed Z values are prepared hypothetical possibilities, not random samples, frequencies or known truth in a real study. Selecting an example preserves both probability laws and their error rates.</p><LessonRangeControl label="Two-sided cutoff" value={state.cutoff} min={0} max={4} step={0.01} help="Reject H0 if |observed Z| is at least this cutoff, including equality. Choose a real rule before collecting data." onChange={cutoff => edit({ cutoff })} /><p role="status" data-errors-status>Cutoff {state.cutoff.toFixed(2)}; prepared {a.example.truth === "null" ? "null truth" : "real gap 2.5"}, observed Z {a.example.z.toFixed(1)}. Decision: {a.reject ? "reject H0" : "fail to reject H0"}. Classification: {a.classification}.</p></section>
    <section className={shared.evidence} aria-label="Two conditional error worlds"><p>The same cutoff applies to both worlds. Indigo dashed lines mark ±cutoff. The dark baseline dot appears only in the prepared example’s supplied-truth panel. Shaded areas describe errors over repetitions, not the chance this particular conclusion is wrong.</p><div className={styles.chart} ref={chartRef}>{(["null", "real"] as const).map(truth => {
      const chart = errorChart(a, width, truth), nullWorld = truth === "null";
      return <div key={truth}><h2>{nullWorld ? "When H0 is true · Type I false alarm" : "When real gap 2.5 is true · Type II miss"}</h2><p>{nullWorld ? `α = P(reject H0 given H0 true) ≈ ${errorPercent(a.alpha)}. Orange outer tails are false alarms.` : `β = P(fail to reject H0 given true gap 2.5) ≈ ${errorPercent(a.beta)}. Lavender central area is misses.`}</p><svg data-errors-chart={truth} viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`${nullWorld ? "Null mean 0" : `Real-gap mean ${alternativeMean.toFixed(4)}`} standard-deviation-1 Z density on fixed −7 to 7 axis. Cutoff boundaries ±${state.cutoff.toFixed(2)}; ${nullWorld ? "both outer tails, Type I rate" : "central non-rejection area, Type II rate"} approximately ${errorPercent(nullWorld ? a.alpha : a.beta)}. ${chart.marker ? `Prepared observed Z ${a.example.z.toFixed(1)} baseline marker.` : "No prepared marker in this world."} Probabilities extend beyond the plot.`}>
        <text x="4" y="16">Density</text>{chart.densityTicks.map(t => <g key={t.value}><line x1={chart.left} x2={chart.width - chart.right} y1={t.y.toFixed(3)} y2={t.y.toFixed(3)} /><text x={chart.left - 7} y={(t.y + 4).toFixed(3)} textAnchor="end">{t.value}</text></g>)}{chart.areas.map((points, i) => <polygon key={i} points={points} data-error-area data-truth={truth} />)}<polyline points={chart.curve} data-density />{chart.boundaries.map((x, i) => <line key={i} x1={x.toFixed(3)} x2={x.toFixed(3)} y1={chart.top} y2={chart.baseline} data-boundary />)}{chart.marker && <circle cx={chart.observedX.toFixed(3)} cy={chart.baseline} r="4" data-example />}{chart.ticks.map(t => <text key={t.value} x={t.x.toFixed(3)} y={chart.baseline + 20} textAnchor="middle">{t.value}</text>)}<text x={(chart.width / 2).toFixed(3)} y="225" textAnchor="middle">Z · standardized gap</text>
      </svg></div>;
    })}</div><p className={shared.math} data-errors-rates>α ≈ {errorPercent(a.alpha)}; β ≈ {errorPercent(a.beta)}. α + β ≈ {errorPercent(a.alpha + a.beta)}; these different conditional rates need not add to 100%.</p><p>The finite plots show −7 to 7 with the same density scale 0 to 0.45; numerical rates include the full real line. A density height is not point probability. Moving the cutoff changes the rule and shaded regions, not the curves or true gap. These are model probabilities, not empirical counts.</p></section>
    <LessonSummaries label="Conditional error rates and one prepared outcome" summaries={[
      { label: "False alarm α", color: "#ad4508", value: `≈ ${errorPercent(a.alpha)}`, definition: "Type I rate when H0 is true.", formula: "P(reject H0 | true gap = 0)" },
      { label: "Miss β", color: "#5031dc", value: `≈ ${errorPercent(a.beta)}`, definition: "Type II rate for true gap 2.5.", formula: "P(fail to reject H0 | true gap = 2.5)" },
      { label: "Prepared example", color: "#33486d", value: a.reject ? "Reject H0" : "Fail to reject", definition: `${a.classification}. Truth is supplied only in this illustration.`, formula: `|Z| = ${a.example.z.toFixed(1)} ${a.reject ? "≥" : "<"} cutoff ${state.cutoff.toFixed(2)}` },
    ]} />
    <section className={shared.evidence} aria-label="Conditional interpretation and optional evidence"><p>Type I and Type II labels combine truth with a decision. A real test does not reveal whether one result is an error. α and β are conditional repeated-test rates, not posterior truth probabilities, p-values or individual guarantees. Fail to reject does not prove no effect. No cutoff is universally best without context and consequences.</p><details><summary>Conditional decision table</summary><div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="Conditional decision evidence"><table><caption>Each truth row totals 100% before rounding; the rows describe separate worlds.</caption><thead><tr><th scope="col">Supplied population truth</th><th scope="col">Reject H0</th><th scope="col">Fail to reject H0</th></tr></thead><tbody><tr><th scope="row">H0 true · gap 0</th><td>Type I false alarm · {errorPercent(a.alpha)}</td><td>Correct non-alarm · {errorPercent(a.nonAlarm)}</td></tr><tr><th scope="row">Specified real gap 2.5</th><td>Correct detection · {errorPercent(a.detection)}</td><td>Type II miss · {errorPercent(a.beta)}</td></tr></tbody></table></div></details><details><summary>Model assumptions and exact rates</summary><p className={shared.math} data-errors-exact>SE = √(16 / 25 + 16 / 25) = {differenceSE.toFixed(6)}; real-world mean of Z = 2.5 / SE = {alternativeMean.toFixed(6)}. α = 2Q({state.cutoff.toFixed(2)}) ≈ {a.alpha.toPrecision(10)}. β = Φ({state.cutoff.toFixed(2)} − {alternativeMean.toFixed(6)}) − Φ(−{state.cutoff.toFixed(2)} − {alternativeMean.toFixed(6)}) ≈ {a.beta.toPrecision(10)}.</p><p>Q is the standard-normal upper tail; Φ is its CDF. Numerical rates use A&S 26.2.17 for moderate tails and NIST DLMF 7.9.2 above standardized distance 4. The decision uses the displayed cutoff with equality rejecting; endpoints have zero probability under these continuous laws. Unknown SD, dependence, paired groups, non-normal samples, collection bias, different alternatives, error costs, repeated peeking and multiple testing require other analysis. Cutoff comparisons here are explanatory: real tests predeclare their procedure before data. Correct detection is 1 − β, also called power; effect-size and sample-size tradeoffs belong to the next lesson. Statistical significance does not establish a causal or practically important effect.</p><a href="https://www.stat.berkeley.edu/~stark/SticiGui/Text/testing.htm" target="_blank" rel="noreferrer">Berkeley SticiGui · Conditional Type I and Type II errors</a><br /><a href="https://www.itl.nist.gov/div898/handbook/prc/section2/prc22.htm" target="_blank" rel="noreferrer">NIST · Known-SD tests and two-sided rules</a><br /><a href="https://dlmf.nist.gov/7.9" target="_blank" rel="noreferrer">NIST DLMF · Numerical tail continued fractions</a></details></section>
  </LearningPage>;
}
