"use client";
import {useMemo,useState} from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonSelect, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import {analyzeOps,patternChoices,tokenChoices,deliveryChoices,cacheChoices,opsBaseline,opsNumber as number,opsPresetId,opsScenarios,sameOps,opsTimeX,type OpsState} from "./ops-engine";
import {opsExperiments} from "./learning-experiments";
import {reachedOps} from "./lesson-state";
import styles from "./playground.module.css";
export function OpsPlayground(){
 const[state,setState]=useState<OpsState>(opsBaseline),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const a=useMemo(()=>analyzeOps(state),[state]),experiment=opsExperiments[index],transfer=index===4,reached=!!prediction&&!!experiment&&reachedOps(index,state),complete=reached&&explanation==="0";
 function clear(){setExplanation(null);setTransferAnswer(null);}function start(next=index){setIndex(next);setState(opsBaseline());setPrediction(null);clear();}function edit(next:OpsState){if(!sameOps(state,next)){setState(next);clear();}}
 const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 4`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="ops-prediction" explanationName="ops-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores Spaced requests. Reset restarts this experiment.</>} observation={prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}
    onNext={()=>start(index+1)} nextLabel={index===3?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Transfer a buffered cached workload":"Explore workload and delivery choices"}>{transfer?<><p>Without Guide help, set Request pattern to Spaced repeated prefix, Output tokens to 8 tokens, Delivery to Buffer until complete and Prefix cache to On · Cold at start. Reconstruct Model TTFT, client first delay, full latency, output throughput, mean cost and request-hit rate from the ledgers.</p>{reachedOps(4,state)&&<><ExperimentChoices legend="Transfer explanation" name="ops-transfer" choices={[
 {id:"counts",label:"R1 misses; R2/R3/R4 hit, so request-hit rate=3/4=0.75. Model TTFT delays are 450,150,150,150 ms: mean 225 ms. Eight-token completion and buffered first-content delays are 800,500,500,500: mean 575 ms. The final request finishes at 3500 ms; 32 output tokens / 3.5 s=9.142857 tokens/s. Costs are 0.136,0.061,0.061,0.061 credits: mean 0.07975. Every answer still decodes eight tokens; prefix reuse never returns a stored answer."},
 {id:"missing",label:"Cache On makes every request a hit and buffering delivers the first token at model TTFT."},
 {id:"citation",label:"Output throughput is reciprocal mean latency, and prefix reuse removes all output costs."}
 ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="counts"?<p role="status" className={shared.feedback}>Try again. Trace the cold miss and three hits, then separate generation time from buffered delivery. Divide 32 tokens by the entire 3.5-second window.</p>:<><ExperimentResult title="Transfer explained">Use the request timeline, observation window and disclosed charge rule to interpret the metrics together.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(5);clear();}}>Explore freely</ExperimentButton></>)}</>}</>:<><p>Try 1 token: Model TTFT and full latency coincide, and no generation inter-token gap exists. Toggle Prefix cache On with unique prefixes: no hits. Compare all three patterns, delivery modes and output lengths. Reset starts Experiment 1.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}</ExperimentRail>;
 return<LearningPage title="LLM App Ops Metrics Lab" subtitle="Trace first content, completion and work over time." rail={rail}>
 <LessonToolbar scenarios={opsScenarios} selectedId={opsPresetId(state)} onSelect={id=>edit(opsBaseline(id))} onReset={()=>start(experiment||transfer?index:0)}/>
 <section className={shared.evidence} aria-label="Toy request workload"><h2>Your dataset</h2><p>Four requests use one worker, fixed toy processing times and fictional credits. A token is a piece of input or output text. Each request has 120 input tokens: a 100-token prefix and a 20-token suffix. Prefill means processing that input before generation; a miss takes 400 ms and a prefix-cache hit takes 100 ms. Each output token takes 50 ms, including the first.</p><p>The worker finishes a whole request before taking the next, in arrival order; simultaneous arrivals use R1–R4 order. Every recomputation starts with an empty cache. There is no actual inference, network delay or provider billing; these are explanatory assumptions.</p>
 <div className={shared.controlGrid}><LessonSelect label="Request pattern" choices={patternChoices} value={state.pattern} onChange={pattern=>edit({...state,pattern})}/><LessonSelect label="Output tokens" choices={tokenChoices} value={state.tokens} onChange={tokens=>edit({...state,tokens})}/><LessonSelect label="Delivery" choices={deliveryChoices} value={state.delivery} onChange={delivery=>edit({...state,delivery})}/><LessonSelect label="Prefix cache" choices={cacheChoices} value={state.cache} onChange={cache=>edit({...state,cache})}/></div>
 <p role="status" data-ops-status>4 requests · {a.totalTokens} output tokens · Observation span {a.span} ms · Prefix hits {a.hits}/4 · Mean queue {number(a.meanQueue)} ms · Mean prefill {number(a.meanPrefill)} ms · Mean client first delay {number(a.meanClientDelay)} ms.</p><p className={shared.small}>Actual control/preset changes clear stale explanation/transfer answers; identical states preserve them. Cache On cannot reuse distinct prefixes.</p>
 </section>
 <section className={shared.evidence} aria-label="Request timeline and exact timing"><h2>Trace arrival, work and delivery</h2><p>Absolute clock in ms. Gray = queue, indigo = prefill, teal = all output-token work. Orange dot = model first token; navy diamond = client first content; end stroke = completion. The exact table below supplies every timestamp and duration.</p>
 <svg className={styles.timeline} viewBox="0 0 800 248" aria-hidden="true">{[0,1,2,3,4].map(i=><g key={i}><line x1={48+i*175} x2={48+i*175} y1={16} y2={208} stroke="#dfe4f4"/><text x={48+i*175} y={232} textAnchor="middle">{number(a.span*i/4)}</text></g>)}{a.rows.map((r,i)=>{const y=32+i*44,x=(t:number)=>opsTimeX(t,a.span);return<g key={r.id} data-ops-timeline={r.id}><text x={8} y={y+14}>{r.id}</text><rect data-phase="queue" x={x(r.arrival)} y={y} width={x(r.start)-x(r.arrival)} height={20} fill="#8993ae"/><rect data-phase="prefill" x={x(r.start)} y={y} width={x(r.start+r.prefill)-x(r.start)} height={20} fill="#5031dc"/><rect data-phase="decode" x={x(r.start+r.prefill)} y={y} width={x(r.finish)-x(r.start+r.prefill)} height={20} fill="#087c78"/><circle data-first-token cx={x(r.first)} cy={y+10} r={4} fill="#ad4508" stroke="white"/><path data-client-first d={`M ${x(r.clientFirst)} ${y-6} l 5 5 l -5 5 l -5 -5 Z`} fill="#0c1230"/><line data-completion x1={x(r.finish)} x2={x(r.finish)} y1={y-3} y2={y+23} stroke="#0c1230" strokeWidth={2}/></g>;})}</svg>
 <div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="Exact request timestamps and durations"><table><caption>All units ms. Arrival/start/first/completion are absolute clock times. Queue, prefill, TTFT, client delay and latency are durations. Model TTFT is time to first token from arrival; client delay is time to first visible content.</caption><thead><tr>{["Request","Arrival","Start","Queue","Prefill","Model first","Completion","Model TTFT","Client first","Client delay","Latency"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.rows.map(r=><tr key={r.id} data-ops-time={r.id}><th scope="row">{r.id}</th>{[r.arrival,r.start,r.queue,r.prefill,r.first,r.finish,r.ttft,r.clientFirst,r.clientDelay,r.latency].map((v,i)=><td key={i}>{number(v)}</td>)}</tr>)}</tbody></table></div>
 <p>Model TTFT = queue + prefill + 50 ms. Full latency = queue + prefill + N×50 ms. Delivery changes only the client first-content marker: stream at model first token, buffer at full completion. Mean client first delay = <strong data-ops-client>{number(a.meanClientDelay)}</strong> ms.</p><p>Generation inter-token gap = <strong data-ops-gap>{number(a.gap)}</strong>{a.gap===null?" · No successive token pair with 1 token.":" ms between successive generated tokens."} For one output token, TTFT and completion coincide. This is a generation measure; buffered content arrives together and does not provide a client inter-token event series.</p></section>
 <LessonSummaries label="Current latency first-token and throughput results" summaries={[
 {label:"Mean latency",color:"#5031dc",value:`${number(a.meanLatency)} ms`,definition:"Arrival to complete response, averaged over four requests.",formula:"Σ(completion − arrival) / 4",comparison:"Includes queueing. Streaming does not shorten full generation in this toy."},
 {label:"Model TTFT",color:"#087c78",value:`${number(a.meanTtft)} ms`,definition:"Arrival to model first token, averaged over four requests.",formula:"Σ(queue + prefill + 50 ms) / 4",comparison:"Buffering can delay client first content without changing this model clock."},
 {label:"Output throughput",color:"#ad4508",value:`${number(a.outputThroughput)} tokens/s`,definition:"All generated output tokens over the observation window.",formula:"total output tokens / elapsed seconds",comparison:`${a.totalTokens} / ${number(a.span/1000)} s. Includes idle gaps; finite window, not steady-state capacity.`},
 ]}/>
 <section className={shared.evidence} aria-label="Toy cache hits and charges"><h2>Count work and charges</h2><p>Request throughput = 4 completed requests / {number(a.span/1000)} s = <strong data-ops-requests>{number(a.requestThroughput)}</strong> requests/s. The window begins at the first arrival and ends at the final completion; it includes idle time. It is not reciprocal mean request latency or a claim about real serving capacity.</p><p>Prefix-cache request-hit rate = {a.hits}/4 = <strong data-ops-hits>{number(a.hitRate)}</strong>. A hit reuses the identical 100-token input prefix of a previously completed request. The 20-token suffix and all output tokens are still processed. The cache starts cold, never evicts in this toy and stores no complete answer. This request fraction is not a cache-block or token-hit rate.</p><p><strong>Fictional charge rule:</strong> uncached input 0.001 credits/token, cached prefix 0.00025 credits/token, output 0.002 credits/token. Timing and charges are deliberately specified independently; cache savings in this model do not promise any provider discount.</p>
 <div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="Prefix reuse and exact fictional token charges"><table><caption>All four requests have 100 prefix + 20 suffix input tokens. Credits are fictional. Output work is always N×50 ms, even on a hit.</caption><thead><tr>{["Request","Prefix ID","Hit?","Uncached input","Cached prefix","Output tokens","Input credits","Output credits","Total credits"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.rows.map(r=><tr key={r.id} data-ops-cost={r.id}><th scope="row">{r.id}</th><td>{r.prefix}</td><td>{r.hit?"Yes":"No"}</td>{[r.uncachedTokens,r.cachedTokens,r.outputTokens,r.inputCost,r.outputCost,r.cost].map((v,i)=><td key={i}>{number(v)}</td>)}</tr>)}</tbody></table></div><p>Total cost = <strong data-ops-total-cost>{number(a.totalCost)}</strong> fictional credits. Mean cost per request = total / 4 = <strong data-ops-cost-mean>{number(a.meanCost)}</strong> fictional credits/request.</p></section>
 <section className={shared.evidence} aria-label="App operations conventions and limits"><details><summary>Construction and limits</summary><p>The finite model has three request patterns, three output lengths, two delivery modes and two cache settings: 36 states. Spaced unique prefixes use arrivals 0,1000,2000,3000 ms with IDs A/B/C/D. Burst unique prefixes all arrive at 0 ms, in R1–R4 order. Spaced repeated prefix uses the spaced arrivals with A/A/A/A. All four requests complete successfully. One worker runs each entire request before the next; start=max(arrival,previous completion). No batching, concurrency, preemption, network overhead, client rendering, failures, retries or percentile estimation is modeled.</p><p>Every state recalculates from a cold cache. A hit requires the same prefix to have appeared in a previously completed request with cache On. Miss prefill is 400 ms, hit prefill 100 ms; the remaining input/suffix work and fixed overhead are included in those authored constants. Decode is 50 ms per token including the first. Model TTFT=queue+prefill+50; latency=queue+prefill+50N. With one token, no inter-token pair exists, so its gap is Undefined rather than a fabricated observation. The toy reports generation timing separately from client delivery.</p><p>Output throughput includes all 4N tokens and request throughput all four requests over first arrival to final completion, including idle time. Request-hit rate is hits/4. Fictional input charges are uncached tokens×0.001 + cached prefix tokens×0.00025; output charges are N×0.002. These constants are not hardware measurements or current provider prices. Reset/prediction restore Spaced requests for the current exercise; free Reset starts Experiment 1.</p><a href="https://docs.vllm.ai/en/v0.31.0/design/metrics/" target="_blank" rel="noreferrer">vLLM · Explicit latency metric conventions</a><br/><a href="https://docs.vllm.ai/en/v0.15.0/features/automatic_prefix_caching/" target="_blank" rel="noreferrer">vLLM · Prefix reuse and decoding limits</a></details></section>
 </LearningPage>;
}
