"use client";
import { useMemo, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSelect, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzePerplexity, editPerplexity, perplexityBaseline, perplexityNumber as number, perplexityPositions, perplexityPresetId, perplexityScenarios, samePerplexity, type PerplexityState } from "./perplexity-engine";
import { perplexityExperiments } from "./learning-experiments";
import { reachedPerplexity } from "./lesson-state";
import styles from "./playground.module.css";

export function PerplexityPlayground() {
  const [state, setState] = useState<PerplexityState>(perplexityBaseline), [position, setPosition] = useState(0);
  const [index, setIndex] = useState(0), [prediction, setPrediction] = useState<string | null>(null), [explanation, setExplanation] = useState<string | null>(null), [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const a = useMemo(() => analyzePerplexity(state), [state]), row = a.rows[position]!, experiment = perplexityExperiments[index];
  const transfer = index === 3, reached = !!prediction && !!experiment && reachedPerplexity(index, state), complete = reached && explanation === "0";
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function start(next = index) { setIndex(next); setState(perplexityBaseline()); setPosition(next === 0 ? 0 : next === 3 ? 1 : 3); setPrediction(null); clear(); }
  function edit(next: PerplexityState) { if (!samePerplexity(state, next)) { setState(next); clear(); } }
  const rail = experiment ? <GuidedExperiment label={`Experiment ${index + 1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="perplexity-prediction" explanationName="perplexity-explanation"
    onPredict={id => { start(); setPrediction(id); }} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores Balanced targets. Reset restarts this experiment.</>} observation={prediction === "0" ? "The evidence matches your prediction." : "The evidence challenges your prediction."}
    onNext={() => start(index + 1)} nextLabel={index === 2 ? "Try the transfer check" : "Next experiment"} /> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Average a new sequence cost" : "Explore probabilities and costs"}>
    {transfer ? <><p>Without Guide help, choose Certain targets. Choose 2 · cat under Prediction position, then set Target probability to 25%. Reconstruct the selected NLL, the full sequence mean, perplexity and bits per token. Explain whether a lower perplexity on these authored targets proves better real-world answers.</p>{reachedPerplexity(3, state) && <><ExperimentChoices legend="Transfer explanation" name="perplexity-transfer" choices={[
      { id: "mean", label: "Only cat has a nonzero cost, −ln(0.25)=ln(4). All four targets count, so mean=ln(4)/4≈0.346574 nats, perplexity≈1.414214 and bits per token=0.5. Its prefix is <BOS> The, excluding cat and later tokens. These authored scores do not establish real-model answer quality or calibration." },
      { id: "denominator", label: "The denominator becomes one because only one token has a nonzero loss, so perplexity is 4." },
      { id: "quality", label: "A lower perplexity always proves safer, more accurate and more truthful generated answers." },
    ]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (transferAnswer !== "mean" ? <p role="status" className={shared.feedback}>Try again. Zero-cost targets still count. Average all four NLLs, then apply exp and the log-base conversion. The demo runs no real model or answer evaluation.</p> : <><ExperimentResult title="Transfer explained">A sequence with three zero-cost targets still has four scored targets. Local cost, average cost and its equivalent perplexity/bits scales answer different questions.</ExperimentResult><ExperimentButton onClick={() => { setIndex(4); clear(); }}>Explore freely</ExperimentButton></>)}</>}</> : <><p>Inspect all four Prediction position choices. Try Target probability 0%, 1%, 50% and 100% under each preset. Selection alone leaves aggregates unchanged. All targets at 100% give perplexity 1 and bits per token 0; any zero gives infinite aggregate costs. Keep tokenization, data, scored positions and context policy consistent when comparing real-model perplexities.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;

  return <LearningPage title="LLM Loss & Perplexity Lab" subtitle="Change a token probability. Compare local cost with sequence cost." rail={rail}>
    <LessonToolbar scenarios={perplexityScenarios} selectedId={perplexityPresetId(state)} onSelect={id => edit(perplexityBaseline(id))} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={shared.evidence} aria-label="Next-token probability and local loss"><h2>Your dataset</h2><p>Four illustrative actual tokens are The, cat, sat and a period. Each next-token probability is conditioned on the previous actual tokens, called teacher forcing. &lt;BOS&gt; means beginning of sequence: a context marker, not a scored target. The context excludes the current and future target tokens. These are authored probabilities; no real model, tokenizer, generated text or training runs here.</p>
      <div className={styles.flow} aria-label="Previous context to actual target, assigned probability and local cost"><div><h3>Context</h3><p data-ppl-context className={styles.context}>{row.context}</p></div><span aria-hidden="true">→</span><div><h3>Actual next token</h3><p data-ppl-token className={styles.value}>{row.token}</p></div><span aria-hidden="true">→</span><div><h3>Target probability</h3><p data-ppl-percent className={styles.value}>{row.percent}%</p></div><span aria-hidden="true">→</span><div><h3>Token loss</h3><p data-ppl-loss className={styles.loss}>{number(row.nll)}</p><p>nats {row.nll === Infinity && "· infinite"}</p></div></div>
      <div className={styles.controls}><LessonSelect label="Prediction position" choices={perplexityPositions} value={String(position)} onChange={id => setPosition(Number(id))} /><LessonRangeControl label="Target probability" unit="%" value={row.percent} min={0} max={100} step={1} help="Assigned probability of this actual next token, given its fixed previous context. Other tokens share the remaining mass." onChange={percent => edit(editPerplexity(state, position, percent))} /></div>
      <p role="status" data-ppl-status className={shared.math}>{row.nll === Infinity ? "−ln(0) → +∞ (infinite log loss)" : `−ln(${number(row.p)}) = ${number(row.nll)} nats`} · {number(row.bits)} bits for this token · All other tokens share {row.otherPercent}%.</p><p className={shared.small}>Position selection changes inspection only. All four targets always count. Editing one probability leaves the provided actual tokens, prefixes and other authored probabilities fixed. Actual probability or scenario changes clear stale explanations and transfer answers; no-ops and position selection preserve them.</p>
    </section>
    <LessonSummaries label="Full four-target sequence scores" summaries={[
      { label: "Mean cross entropy", color: "#087c78", value: number(a.mean), definition: "Average negative log likelihood (NLL), in nats per target.", formula: "sum of four NLLs / 4", comparison: `Total NLL=${number(a.total)} nats. Count=4, including zero-cost targets.` },
      { label: "Perplexity", color: "#5031dc", value: number(a.ppl), definition: "Exponentiated mean NLL; an equivalent likelihood scale.", formula: "exp(mean NLL) = 2^(bits per token)", comparison: "Not exp(total NLL) or the arithmetic average of 1/p." },
      { label: "Bits per token", color: "#ad4508", value: number(a.bpt), definition: "Average cost in base 2, per scored token.", formula: "mean NLL / ln(2) = log2(perplexity)", comparison: "Bits per token is not bits per character or measured file size." },
    ]} />
    <section className={shared.evidence} aria-label="All target costs and aggregation"><h2>Count all four targets</h2><p>NLL means negative log likelihood: −ln(p), where ln is the natural logarithm and nats are its cost units. exp reverses ln: exp(x)=e raised to x. Bits use log base 2; divide nats by ln(2) to convert. Mean cross entropy here is the average NLL of the actual targets. Perplexity is also the inverse geometric mean of their probabilities. A very low target probability has a high cost. Probability 1 gives zero cost; probability 0 gives infinite cost, with no epsilon substitution or finite cap.</p><div className={`${shared.tableScroll} ${styles.table}`} tabIndex={0} role="region" aria-label="Fixed prefixes and all four actual target losses"><table><caption>All four actual targets are scored. &lt;BOS&gt; supplies context only. Selecting a position never changes the denominator 4; calculations precede six-decimal display rounding.</caption><thead><tr>{["Position", "Prior-only context", "Actual token", "Target p", "NLL · nats", "Bits"].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.rows.map(r => <tr key={r.position} data-ppl-row={r.position} aria-current={r.position === position ? "true" : undefined}><th scope="row">{r.position + 1}</th><td>{r.context}</td><td>{r.token}</td><td>{number(r.p)}</td><td>{number(r.nll)}{r.nll === Infinity && " (infinite)"}</td><td>{number(r.bits)}{r.bits === Infinity && " (infinite)"}</td></tr>)}</tbody></table></div><p role="status">{a.zeroCount ? `${a.zeroCount} zero-probability target${a.zeroCount > 1 ? "s" : ""}: the mean, perplexity and bits per token are infinite. Other local costs stay as shown.` : "Every assigned target probability is positive, so all costs are finite."}</p></section>
    <section className={shared.evidence} aria-label="Perplexity construction and limits"><details><summary>Construction and limits</summary><p>The four authored conditional probabilities use 0..100% in steps of one percentage point. Each context distributes p to its actual next token and 1−p to all other tokens collectively, without specifying a vocabulary or individual alternative probabilities. Prefixes use the previous supplied actual tokens even after probability edits. No model is run to recompute later conditionals.</p><p>Every target has equal weight and all four always count. There is no masking, context-window truncation or denominator change. &lt;BOS&gt; is a defined context marker; the first actual token The is scored given that marker. Balanced targets uses four 50% probabilities; One surprise uses 50%,50%,50%,1%; Certain targets uses four 100% probabilities. Reset and predictions restore Balanced targets for the current experiment; free Reset starts Experiment 1.</p><p>For positive probabilities, perplexity≥1. All probabilities 1 give mean 0, perplexity 1 and bits per token 0. The smallest positive probability supported here is 0.01, so the largest finite mean is ln(100), largest finite perplexity is 100 and largest finite bits per token is log2(100). Exact probability 0 gives infinite costs and does not claim a finite-precision softmax produced zero. Lower perplexity on fixed targets and protocol reflects higher assigned likelihood, not proof of better general answers, truth, safety, accuracy or calibration. Real comparisons require consistent tokenization, data, scored positions and context policy.</p><a href="https://huggingface.co/docs/transformers/en/perplexity" target="_blank" rel="noreferrer">Hugging Face · Perplexity, tokenization and scored-token context</a></details></section>
  </LearningPage>;
}
