"use client";
import {useMemo,useState} from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonSelect, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import sharedStyles from "@/components/learning-page/learning-page.module.css";
import {analyzeBroadcast,clampOutputIndex,formatShape,getValueTrace,type AxisAnalysis} from "./tensor-shape-broadcasting-engine";
import {broadcastPresets,defaultOutputIndex} from "./scenario";
import {tensorDefaults,tensorExperiments,tensorScenarios,tensorTransferStart,tensorTransferTarget,type TensorState} from "./learning-experiments";
import styles from "./playground.module.css";
const same=(a:TensorState,b:TensorState)=>['a','b','index'].every(k=>a[k as keyof TensorState].every((v,i)=>v===b[k as keyof TensorState][i]));
const options=(n:number,start=0)=>Array.from({length:n},(_,i)=>({id:String(i+start),label:String(i+start)}));
const status=(axis:AxisAnalysis)=>axis.status==='same'?'Same size':axis.status==='fail'?'Incompatible: unequal and neither is 1':`${axis.status==='stretch-a'?'A':'B'} reuses index 0 (size 1 → ${axis.outputSize})`;
export function TensorShapeBroadcastingPlayground(){
 const [state,setState]=useState<TensorState>(tensorDefaults),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const analysis=useMemo(()=>analyzeBroadcast(state.a,state.b),[state]),trace=analysis.outputShape?getValueTrace({aShape:state.a,bShape:state.b,outputIndex:state.index}):null;
 const experiment=tensorExperiments[index],transfer=index===3,reached=!!prediction&&!!experiment&&same(state,experiment.target),complete=reached&&explanation===experiment?.correctExplanation,transferReached=same(state,tensorTransferTarget);
 const preset=broadcastPresets.find(p=>p.aShape.every((v,i)=>v===state.a[i])&&p.bShape.every((v,i)=>v===state.b[i]));
 function clear(){setExplanation(null);setTransferAnswer(null)}
 function start(next=index){setIndex(next);setState(tensorExperiments[next]?.baseline??tensorTransferStart);setPrediction(null);clear()}
 function edit(next:TensorState){const a=analyzeBroadcast(next.a,next.b);setState({...next,index:clampOutputIndex(next.index,a.outputShape)});clear()}
 function shape(target:'a'|'b',i:number,v:number){edit({...state,[target]:state[target].map((n,j)=>i===j?v:n)})}
 const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="tensor-prediction" explanationName="tensor-explanation"
    onPredict={id=>{start();setPrediction(id)}} onExplain={setExplanation}
    predictionHelp={<>Choosing a different prediction restores this experiment’s starting shapes and output index. Reset restarts it.</>} observation={prediction===experiment.correctPrediction?'Your prediction matches the evidence.':'The aligned axes and source mapping challenge your prediction.'}
    onNext={()=>start(index+1)} nextLabel={index===2?'Try the transfer check':'Next experiment'} />:<ExperimentRail label={transfer?'Transfer check':'Free exploration'} title={transfer?'Move the singleton':'Trace any compatible pair'}>
 {transfer?<><p>Repair A axis −3 to 1, change A axis −1 to 4, then set Output axis −3 index to 3 and Output axis −1 index to 1. Keep the middle index 2 and B [4,3,4]. How does C[3,2,1] map to the inputs?</p><ExperimentChoices legend="Transfer explanation" name="tensor-transfer" choices={[{id:'map',label:'A[0,2,1] + B[3,2,1] = 3 + 21 = 24. A’s first size-1 axis reuses 0; its last size-4 axis keeps 1.'},{id:'last',label:'A[3,2,0] + B[0,2,1]: every A last axis reuses 0, regardless of its size.'},{id:'crop',label:'Crop the output to A’s first size 1, so C[3,2,1] cannot exist.'}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!transferReached?<p role="status" className={sharedStyles.feedback}>First follow the four edits above. A should be [1,3,4], B [4,3,4] and output index [3,2,1]. Reset restores the transfer starting state.</p>:transferAnswer!=='map'?<p role="status" className={sharedStyles.feedback}>Try again. Check each input’s current axis size, not where a zero happened to appear in the previous experiment.</p>:<><ExperimentResult title="Transfer explained">The output shape is [4,3,4], with 64 elements. Only A’s first axis is singleton here; C[3,2,1] reads A[0,2,1] and B[3,2,1], giving 24.</ExperimentResult><ExperimentButton onClick={()=>setIndex(4)}>Explore freely</ExperimentButton></>)}</>:<><p>Try all original presets and axis sizes 1 through 5. Inspect how source indices change, including ordinary index 0 on an axis that is larger than 1. Broadcasting is elementwise addition here, not matrix multiplication.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
 </ExperimentRail>;
 return <LearningPage title="Tensor Shape & Broadcasting Lab" subtitle="Align the axes. Trace one output value." rail={rail}>
 <LessonToolbar label="Original shape presets" scenarios={tensorScenarios} selectedId={preset?.id??'custom'} onSelect={id=>{const p=broadcastPresets.find(p=>p.id===id)!;edit({a:[...p.aShape],b:[...p.bShape],index:[...defaultOutputIndex]})}} onReset={()=>start(experiment||transfer?index:0)}/>
 <p className={styles.context}>Shape lists the sizes of an array’s axes; rank is the number of axes. This lab keeps rank 3. Axis −1 is last, −2 is middle and −3 is first. Each size can be an integer from 1 through 5.</p>
 <div className={styles.shapeControls}>{(['a','b'] as const).map(target=><fieldset key={target}><legend>{target.toUpperCase()} shape {formatShape(state[target])}</legend><div>{state[target].map((v,i)=><LessonSelect key={i} label={`${target.toUpperCase()} axis ${i-3}`.replace('-', '−')} choices={options(5,1)} value={String(v)} onChange={id=>shape(target,i,Number(id))}/>)}</div></fieldset>)}</div>
 <section className={sharedStyles.evidence} aria-label="Aligned axes"><h2>Aligned axes, checked from the right</h2><p>Equal sizes OR one size is 1. Every axis must pass. Each compatible pair below gives a candidate axis size; the final output exists only when no pair fails.</p><div className={styles.scroller} role="region" aria-label="Scrollable aligned axes" tabIndex={0}><table><caption>A {formatShape(state.a)}, B {formatShape(state.b)}. Check order: −1, −2, −3.</caption><thead><tr><th scope="col">Axis</th><th scope="col">A size</th><th scope="col">B size</th><th scope="col">Candidate size</th><th scope="col">Rule</th></tr></thead><tbody>{[...analysis.axes].reverse().map(axis=><tr key={axis.axisLabel} data-status={axis.status}><th scope="row">{axis.axisLabel}</th><td>{axis.aSize}</td><td>{axis.bSize}</td><td>{axis.outputSize??'Unavailable'}</td><td>{status(axis)}</td></tr>)}</tbody></table></div><p role="status">{analysis.isCompatible?'All axes pass.':`Failed axes: ${analysis.axes.filter(a=>a.status==='fail').map(a=>a.axisLabel).join(', ')}. No output shape or output value exists.`}</p></section>
 <LessonSummaries label="Broadcast result" summaries={[{label:'Output shape',value:analysis.outputShape?formatShape(analysis.outputShape):'Unavailable',color:'#5031dc',definition:'One output axis for each aligned pair, if all pairs pass.',formula:analysis.outputShape?analysis.outputShape.join(' × '):'Unequal non-singleton sizes block the operation',comparison:analysis.isCompatible?'Inputs keep their stored shapes.':'Repair each failed axis before tracing a value.'},{label:'Output elements',value:analysis.totalElements===null?'Unavailable':String(analysis.totalElements),color:'#1760db',definition:'Number of elements in the resulting array.',formula:analysis.outputShape?`${analysis.outputShape.join(' × ')} = ${analysis.totalElements}`:'No resulting array',comparison:'Elementwise C = A + B, not matrix multiplication.'}]}/>
 <section className={sharedStyles.evidence} aria-label="Output value trace"><h2>Trace one output value</h2>{trace&&analysis.outputShape?<><p>Indices start at 0. An output axis of size n has indices 0 through n−1. Shape edits keep the index within a smaller compatible output’s bounds.</p><div className={styles.indexControls}>{state.index.map((v,i)=><LessonSelect key={i} label={`Output axis ${i-3} index`.replace('-','−')} choices={options(analysis.outputShape![i])} value={String(v)} onChange={id=>edit({...state,index:state.index.map((n,j)=>i===j?Number(id):n)})}/>)}</div><div className={styles.trace}><p>C{formatShape(trace.outputIndex)} = A{formatShape(trace.aIndex)} + B{formatShape(trace.bIndex)}</p><p>= {trace.aValue} + {trace.bValue} = <strong>{trace.outputValue}</strong></p></div><div className={styles.scroller} role="region" aria-label="Scrollable source index mapping" tabIndex={0}><table><caption>Only an input axis of size 1 reuses index 0. A non-singleton axis can also have an ordinary zero index.</caption><thead><tr><th scope="col">Axis</th><th scope="col">Output index</th><th scope="col">A index</th><th scope="col">B index</th></tr></thead><tbody>{state.index.map((v,i)=><tr key={i}><th scope="row">{i-3}</th><td>{v}</td><td>{trace.aIndex[i]} · {state.a[i]===1?'reused, size 1':'kept output index'}</td><td>{trace.bIndex[i]} · {state.b[i]===1?'reused, size 1':'kept output index'}</td></tr>)}</tbody></table></div><p>Fixed sample data: A(i,j,k) = 1 + 3i + j; B(i,j,k) = 10 + 5j + k. A ignores k and B ignores i by construction. Repeated values alone do not prove broadcasting; use the axis sizes and mapped indices.</p></>:<p>No output value exists until all aligned axes are compatible.</p>}</section>
 <section className={styles.optional} aria-label="Supporting broadcast evidence"><details><summary>Axis −3 comparisons</summary><p>All five possible B sizes for the current A axis −3 = {state.a[0]}. Either side may supply size 1.</p><div className={styles.scroller} role="region" aria-label="Scrollable axis comparisons" tabIndex={0}><table><thead><tr><th scope="col">B axis −3</th><th scope="col">Candidate size</th><th scope="col">Rule</th><th scope="col">Current</th></tr></thead><tbody>{[1,2,3,4,5].map(b=>{const axis=analyzeBroadcast([state.a[0]],[b]).axes[0];return <tr key={b}><th scope="row">{b}</th><td>{axis.outputSize??'Unavailable'}</td><td>{status(axis)}</td><td>{state.b[0]===b?'Selected':''}</td></tr>})}</tbody></table></div></details><details><summary>Missing leading axes and data reuse</summary><p>In general, ranks can differ. Align from the right and treat missing leading axes as size 1. For A [3,1] and B [2,3,4], align A as [1,3,1]: all pairs pass, giving output [2,3,4]. This lab’s editable arrays retain three axes.</p><p>Broadcasting logically reuses source values without requiring tiled input copies. An addition result can allocate output memory; broadcasting does not make the result cost-free. It does not change stored input shapes. Size-0 axes are outside these controls.</p></details></section>
 <p role="status" aria-live="polite" aria-atomic="true" className={sharedStyles.liveUpdate}>A {formatShape(state.a)}, B {formatShape(state.b)}. {analysis.isCompatible?`Output ${formatShape(analysis.outputShape!)}, ${analysis.totalElements} elements. C${formatShape(state.index)} = A${formatShape(trace!.aIndex)} + B${formatShape(trace!.bIndex)} = ${trace!.outputValue}.`:'Incompatible shapes; no output value.'}</p>
 </LearningPage>;
}
