"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeRoc,rocChart,rocPercent as percent,rocScenarios,rocThreshold as threshold,type RocState } from "./roc-engine";
import { rocBaseline,reachedRoc } from "./lesson-state";
import { rocExperiments } from "./learning-experiments";
import styles from "./playground.module.css";
export function RocPlayground(){
 const [state,setState]=useState(()=>rocBaseline()),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null),[width,setWidth]=useState(640),chartRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const el=chartRef.current;if(!el)return;const update=()=>setWidth(Math.max(200,el.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(el);return()=>observer.disconnect();},[]);
 const a=useMemo(()=>analyzeRoc(state),[state]),chart=rocChart(a,width),experiment=rocExperiments[index],transfer=index===3,reached=!!prediction&&!!experiment&&reachedRoc(index,state),complete=reached&&explanation==="0";
 function clear(){setExplanation(null);setTransferAnswer(null);}
 function start(next=index){setIndex(next);setState(rocBaseline(next));setPrediction(null);clear();}
 function edit(patch:Partial<RocState>){setState(s=>({...s,...patch}));clear();}
 const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="roc-prediction" explanationName="roc-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores this experiment’s starting state. Reset restarts it.</>} observation={prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}
    onNext={()=>start(index+1)} nextLabel={index===2?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Same labels, reversed ranking":"A threshold selects a point"}>
  {transfer?<><p>Without Guide help, choose Reversed and set Decision threshold to 0.45. Reconstruct FPR and TPR from the two actual-label groups, then compare the whole-ranking AUC with Mostly ordered.</p>{reachedRoc(3,state)&&<><ExperimentChoices legend="Transfer explanation" name="roc-transfer" choices={[
   {id:"ranking",label:"TP 1 and FP 5 give TPR 1/6 = 16.7% and FPR 5/6 = 83.3%. Reversed has 5 wins and 2 ties among 36 positive/negative pairs, giving AUC 1/6 ≈0.166667 versus Mostly ordered 5/6. Reversal changed the ranking; the threshold only selects this point. None of these toy values establishes calibration, task utility or future performance."},
   {id:"point",label:"AUC equals this threshold’s TPR, so it will necessarily change at the next cutoff."},
   {id:"denominator",label:"FPR is 5/(1+5) because ROC rates use the predicted-positive set."},
  ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="ranking"?<p role="status" className={shared.feedback}>Try again. FPR divides FP by the six actual negatives; TPR divides TP by the six actual positives. Pair wins and ties determine AUC across the full ranking, independently of the current threshold.</p>:<><ExperimentResult title="Transfer explained">This reversed ranking has lower AUC and a different operating point. Rate denominators still use actual classes; one threshold does not choose a universally good decision policy.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(4);clear();}}>Explore freely</ExperimentButton></>)}</>}</>:<><p>Sweep thresholds through score ties and plateaus. Scores and labels remain fixed within a scenario; changing the threshold changes predictions, not the ROC curve or AUC. Task costs and external evaluation are outside this toy.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
 </ExperimentRail>;
 return <LearningPage title="ROC, AUC & Thresholds Lab" subtitle="Move one operating point; inspect the whole ranking." rail={rail}>
  <LessonToolbar scenarios={rocScenarios} selectedId={state.scenario} onSelect={scenario=>edit({scenario:scenario as RocState["scenario"]})} onReset={()=>start(experiment||transfer?index:0)}/>
  <section className={shared.evidence} aria-label="Fixed score ranking and operating point"><h2>Your dataset</h2><p>Twelve fixed scored cases: Cases 1..6 actually positive, Cases 7..12 negative. Predict Positive when score ≥ threshold, including equality. Scores are ranking signals, not calibrated probabilities. Scenario changes preserve the threshold and actual labels while changing scores.</p><p role="status" data-roc-status className={shared.math}>Threshold {threshold(state.tick)} · TP {a.tp} · FP {a.fp} · FN {a.fn} · TN {a.tn} · TPR {a.tp}/6 · FPR {a.fp}/6 · AUC {a.auc.toFixed(6)}</p>
   <div className={styles.chart} ref={chartRef}><svg data-roc-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`False-positive rate horizontally and true-positive rate vertically, both 0 to 1. ${chart.points.length} grouped ROC vertices; selected threshold ${threshold(state.tick)} at FPR ${a.fpr.toFixed(6)}, TPR ${a.tpr.toFixed(6)}. Shaded whole-curve area ${a.auc.toFixed(6)}. Exact case and vertex tables follow.`}>
    {chart.ticks.map(t=><g key={t.value}><line x1={chart.left} x2={chart.width-chart.right} y1={t.y} y2={t.y}/><line x1={t.x} x2={t.x} y1={chart.top} y2={chart.baseline}/><text x={chart.left-12} y={t.y+4} textAnchor="end">{t.value.toFixed(1)}</text><text x={t.x} y={chart.baseline+24} textAnchor="middle">{t.value.toFixed(1)}</text></g>)}<text x="14" y={(chart.top+chart.baseline)/2} transform={`rotate(-90 14 ${(chart.top+chart.baseline)/2})`} textAnchor="middle">True-positive rate</text><text x={chart.width/2} y={chart.height-7} textAnchor="middle">False-positive rate</text>
    <path data-roc-area d={chart.area}/><line data-roc-reference {...chart.diagonal}/><path data-roc-curve d={chart.path}/>{chart.points.map(p=><circle key={p.id} data-roc-vertex={p.id} cx={p.cx} cy={p.cy} r="4"/>)}<polygon data-roc-selected points={chart.selected.diamond}/>
   </svg></div><p>Circles = grouped score-sweep vertices. Hollow diamond = selected operating point. Pale fill = area under the whole ROC curve. Dashed diagonal = tied-ranking reference (AUC 0.5). Connecting segments summarize area; tied groups may leave intermediate points unavailable to a hard threshold.</p>
   <LessonRangeControl label="Decision threshold" value={state.tick/20} min={0} max={1} step={.05} help="Score ≥ threshold predicts Positive. Move in 0.05 steps. Equal scores move together; intervals with no scores can preserve the same point. This changes predictions, not scores or AUC." onChange={value=>edit({tick:Math.round(value*20)})}/><p className={shared.math} data-roc-pairs>AUC = ({a.wins} wins + 0.5 × {a.ties} ties)/36 = {a.wins+a.ties/2}/36 = {a.auc.toFixed(6)}. Whole-ranking area is independent of the selected threshold.</p>
  </section>
  <LessonSummaries label="Operating rates and whole-ranking area" summaries={[
   {label:"False-positive rate",color:"#ad4508",value:percent(a.fpr),definition:"Accepted actual negatives among all six actual negatives.",formula:`FPR = FP/(FP + TN) = ${a.fp}/6`},
   {label:"True-positive rate",color:"#087c78",value:percent(a.tpr),definition:"Found actual positives among all six actual positives; this is recall.",formula:`TPR = TP/(TP + FN) = ${a.tp}/6`},
   {label:"AUC",color:"#5031dc",value:a.auc.toFixed(3),definition:"Area under the entire ROC curve; a ranking statistic from 0 to 1.",formula:`(${a.wins} wins + 0.5 × ${a.ties} ties)/36`,comparison:"Neither current-threshold accuracy nor calibration."},
  ]}/>
  <section className={shared.evidence} aria-label="Score identities, curve construction and limits"><details><summary>Twelve scores and decisions</summary><div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="Twelve score identities and classifications"><table><caption>Actual labels and IDs stay fixed. Current score ≥ {threshold(state.tick)} predicts Positive; every case contributes to one count.</caption><thead><tr>{["Case","Score","Actual","Predicted","Confusion cell"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.rows.map(r=><tr key={r.id}><th scope="row">Case {r.id}</th><td>{threshold(r.scoreTick)}</td><td>{r.actual?"Positive":"Negative"}</td><td>{r.predicted?"Positive":"Negative"}</td><td>{r.bucket}</td></tr>)}</tbody></table></div></details>
   <details><summary>ROC vertices and area</summary><div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="Grouped thresholds and trapezoid contributions"><table><caption>Representative distinct-score cutoffs plus 1.00 (above all scores here). Equal scores enter together. Each segment’s area is its FPR width × average endpoint TPR; vertical width contributes zero.</caption><thead><tr>{["Threshold","FP","TP","FPR","TPR","Area from previous"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.vertices.map(v=><tr key={v.tick}><th scope="row">{threshold(v.tick)}</th><td>{v.fp}</td><td>{v.tp}</td><td>{v.fpr.toFixed(6)}</td><td>{v.tpr.toFixed(6)}</td><td>{v.segmentArea.toFixed(6)}</td></tr>)}</tbody></table><p className={shared.math}>Sum of full-precision segment areas = {a.auc.toFixed(6)}. Displayed terms are rounded.</p></div></details>
   <details><summary>Construction and limits</summary><p>Mostly ordered scores for Cases 1..12 are 0.90,0.80,0.70,0.70,0.60,0.40,0.80,0.50,0.40,0.30,0.20,0.10. Reversed uses 1 − score with the same actual labels; All tied uses 0.50. Scores and threshold are compared on integer 0.05 ticks. Every dataset has six actual positives and six negatives, so no zero-denominator ROC case is introduced.</p><p>ROC uses actual-class denominators. It does not plot precision, accuracy or predicted-positive proportions. Sweep score groups in descending order; lowering the inclusive threshold can increase or leave unchanged each rate. Tie groups jump together, so a straight area segment does not make every intermediate point a separate hard-threshold outcome.</p><p>AUC is the trapezoidal area and equals (positive-over-negative pair wins+half ties)/36. Here each of the 36 pairs chooses one positive and one negative uniformly from this finite sample. Mostly ordered has 29 wins and 2 ties, Reversed 5 wins and 2 ties, All tied 0 wins and 36 ties. AUC 0.5 need not mean random score generation. AUC does not select an optimal threshold, measure calibrated probabilities, encode error costs or guarantee future performance. No fitting, ROC uncertainty, class-prevalence editing or precision–recall curve is implemented.</p><a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_curve.html" target="_blank" rel="noreferrer">scikit-learn · ROC thresholds and score grouping</a><br/><a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.auc.html" target="_blank" rel="noreferrer">scikit-learn · Trapezoidal area</a><br/><a href="https://mlr3measures.mlr-org.com/reference/auc.html" target="_blank" rel="noreferrer">mlr3measures · Ranking pairs and tied scores</a><br/><a href="https://developers.google.com/machine-learning/crash-course/classification/roc-and-auc" target="_blank" rel="noreferrer">Google · ROC and AUC interpretation</a></details></section>
 </LearningPage>;
}
