"use client";
import {useEffect,useMemo,useState} from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonAction, LessonRangeControl, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import sharedStyles from "@/components/learning-page/learning-page.module.css";
import {analyzeDescent,formatNumber as num,formatSigned as signed,loss,simulateDescent,stepDescent,type DescentState} from "./gradient-descent-engine";
import {gradientPresets} from "./scenario";
import {gradientDefaults,gradientExperiments,gradientScenarios,startState,type GradientSetup} from "./learning-experiments";
import styles from "./playground.module.css";
type Workbench=GradientSetup&{running:boolean};
const fresh=(setup:GradientSetup):Workbench=>({...setup,history:setup.history.map(s=>({...s})),running:false});
const current=(s:GradientSetup)=>s.history.at(-1)!;
const near=(a:number,b:number)=>Math.abs(a-b)<1e-10;
function LossPlot({history,nextTheta}:{history:DescentState[];nextTheta:number}){
 const extent=Math.max(3.2,...history.map(s=>Math.abs(s.theta)*1.12),Math.abs(nextTheta)*1.12),top=loss(extent)*1.08;
 const x=(t:number)=>54+(t+extent)/(2*extent)*590,y=(l:number)=>306-l/top*268;
 const path=Array.from({length:161},(_,i)=>{const t=-extent+i*2*extent/160;return `${i?'L':'M'}${x(t)},${y(loss(t))}`;}).join(' '),s=history.at(-1)!;
 return <><div className={styles.chartScroller} role="region" aria-label="Scrollable loss curve" tabIndex={0}><svg viewBox="0 0 680 380" role="img" aria-label={`Quadratic loss. Current θ ${num(s.theta,8)}, loss ${num(loss(s.theta),8)}; next θ ${num(nextTheta,8)}, loss ${num(loss(nextTheta),8)}. Circle current, diamond proposed, line recorded steps.`}>
 <title>{`L(θ) = θ²/2. Current step ${s.step}; next step ${s.step+1}.`}</title>
 {[0,.25,.5,.75,1].map(f=><g key={f}><line x1="54" x2="644" y1={y(f*top)} y2={y(f*top)} stroke="#dfe4f4"/><text x="44" y={y(f*top)+6} textAnchor="end">{num(f*top,2)}</text></g>)}
 {[-1,-.5,0,.5,1].map(f=><g key={f}><line x1={x(f*extent)} x2={x(f*extent)} y1="306" y2="312" stroke="#536487"/><text x={x(f*extent)} y="338" textAnchor="middle">{num(f*extent,2)}</text></g>)}
 <line x1="54" x2="644" y1="306" y2="306" stroke="#536487"/><line x1={x(0)} x2={x(0)} y1="38" y2="306" stroke="#536487" strokeDasharray="5 5"/>
 <text x="54" y="24">Loss L(θ)</text><text x="644" y="368" textAnchor="end">Parameter θ</text><text x={x(0)} y="368" textAnchor="middle">Minimum 0</text>
 <path d={path} fill="none" stroke="#5031dc" strokeWidth="3"/><path d={history.map((p,i)=>`${i?'L':'M'}${x(p.theta)},${y(loss(p.theta))}`).join(' ')} fill="none" stroke="#1760db" strokeWidth="2" strokeDasharray="4 3"/>
 {history.slice(0,-1).map(p=><circle key={p.step} cx={x(p.theta)} cy={y(loss(p.theta))} r="4" fill="#1760db"/>)}
 <circle data-point="current" cx={x(s.theta)} cy={y(loss(s.theta))} r="7" fill="#5031dc" stroke="white" strokeWidth="2"/>
 <path data-point="next" d={`M${x(nextTheta)},${y(loss(nextTheta))-8} l8,8 -8,8 -8,-8 Z`} fill="white" stroke="#0c1230" strokeWidth="2"/>
 </svg></div><p className={styles.context}>● Current point · ◇ Next point · Dashed line: recorded steps. Axis: θ from {num(-extent,2)} to {num(extent,2)}; loss from 0 to {num(top,2)}. Axes expand when needed to include actual positions.</p></>;
}
export function GradientDescentPlayground(){
 const [work,setWork]=useState<Workbench>(()=>fresh(gradientDefaults)),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const s=current(work),a=useMemo(()=>analyzeDescent(s,work.eta,work.beta),[s,work.eta,work.beta]);
 const experiment=gradientExperiments[index],transfer=index===4;
 const expected=experiment?simulateDescent(2.4,experiment.targetEta,experiment.targetBeta,experiment.targetStep).at(-1):null;
 const momentumTarget=experiment&&index===3?stepDescent(current(experiment.baseline),.42,.9):null;
 const target=momentumTarget??expected;
 const reached=!!prediction&&!!experiment&&!!target&&near(work.eta,experiment.targetEta)&&near(work.beta,experiment.targetBeta)&&s.step===experiment.targetStep&&near(s.theta,target.theta)&&near(s.velocity,target.velocity),complete=reached&&explanation===experiment?.correctExplanation;
 const transferReached=near(work.eta,1.8)&&work.beta===0&&s.step===1&&near(s.theta,-1.92)&&near(s.velocity,-4.32);
 const preset=gradientPresets.find(p=>near(p.learningRate,work.eta)&&near(p.momentum,work.beta));
 function clear(){setExplanation(null);setTransferAnswer(null)}
 function start(next=index){setIndex(next);setWork(fresh(gradientExperiments[next]?.baseline??{eta:.42,beta:0,history:[startState]}));setPrediction(null);clear()}
 function editParam(key:'eta'|'beta',value:number){setWork(w=>({...w,[key]:value,running:false}));clear()}
 function step(){setWork(w=>({...w,running:false,history:[...w.history,stepDescent(current(w),w.eta,w.beta)]}));clear()}
 useEffect(()=>{if(!work.running)return;const timer=window.setInterval(()=>{setWork(w=>{const last=current(w);if(last.step>=60||(Math.abs(last.theta)<.002&&Math.abs(last.velocity)<.002))return {...w,running:false};return {...w,history:[...w.history,stepDescent(last,w.eta,w.beta)]};});setExplanation(null);setTransferAnswer(null);},520);return()=>window.clearInterval(timer);},[work.running]);
 const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 4`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="gradient-prediction" explanationName="gradient-explanation"
    onPredict={id=>{start();setPrediction(id)}} onExplain={setExplanation}
    predictionHelp={<>Choosing a different prediction restores this experiment’s parameters, position and previous updates.</>} observation={prediction===experiment.correctPrediction?"Your prediction matches the evidence.":"The actual position and loss challenge your prediction. Read the step arithmetic."}
    action={<p className={sharedStyles.actionPrompt}><strong>Now try it.</strong> {experiment.action} If you take extra steps, use Reset, then choose a prediction again.</p>}
    onNext={()=>start(index+1)} nextLabel={index===3?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Another crossing":"Compare actual updates"}>
 {transfer?<><p>The start θ = 2.4, velocity = 0 and β = 0 are loaded. Set Learning rate η to 1.80 and press Step once. Why did crossing zero still lower loss?</p><ExperimentChoices legend="Transfer explanation" name="gradient-transfer" choices={[{id:"closer",label:"θ = −1.92 is closer to zero than 2.4, so θ²/2 falls from 2.88 to 1.8432 despite crossing."},{id:"sign",label:"Every negative parameter has zero loss."},{id:"diverge",label:"Crossing proves this run diverges, regardless of its loss."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!transferReached?<p className={sharedStyles.feedback} role="status">Restore this transfer baseline with Reset, set Learning rate η to 1.80, keep Momentum β = 0 and press Step once.</p>:transferAnswer!=="closer"?<p className={sharedStyles.feedback} role="status">Try again. Compare distances from zero and squared magnitudes, not just signs.</p>:<><ExperimentResult title="Transfer explained">Crossing changes the side of the minimum. Here the smaller magnitude lowers loss; overshooting and diverging are different claims.</ExperimentResult><ExperimentButton onClick={()=>setIndex(5)}>Explore freely</ExperimentButton></>)}</>:<><p>Change one parameter at a time, restart the path and compare equal step counts. At θ close to zero, inspect stored velocity before predicting the next update. Preset names describe demonstrations, not universal performance guarantees.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
 </ExperimentRail>;
 return <LearningPage title="Gradient Descent Playground" subtitle="Predict a step. Follow the actual update." rail={rail}>
 <LessonToolbar label="Original parameter presets" scenarios={gradientScenarios} selectedId={preset?.id??'custom'} onSelect={id=>{const p=gradientPresets.find(p=>p.id===id)!;setWork(fresh({eta:p.learningRate,beta:p.momentum,history:[startState]}));clear()}} onReset={()=>start(experiment||transfer?index:0)}/>
 <p className={styles.context}>One parameter θ, one deterministic loss L(θ) = θ²/2, minimum at zero. Its gradient g = θ is the local uphill slope; −g points locally downhill. A finite update can still raise loss.</p>
 <div className={sharedStyles.controlGrid}><LessonRangeControl label="Learning rate η" value={work.eta} min={.02} max={1.8} step={.01} onChange={v=>editParam('eta',v)} help="Scales the current negative gradient. Editing keeps position and previous update, and pauses Run."/><LessonRangeControl label="Momentum β" value={work.beta} min={0} max={.9} step={.01} onChange={v=>editParam('beta',v)} help="Carries a fraction of the previous signed parameter update. Editing keeps that stored update."/></div>
 <div className={styles.actions}><LessonAction onClick={step}>Step</LessonAction><LessonAction onClick={()=>setWork(w=>({...w,running:!w.running}))}>{work.running?'Pause':'Run'}</LessonAction><LessonAction onClick={()=>{setWork(w=>({...w,history:[startState],running:false}));clear()}}>Restart path</LessonAction></div>
 <p className={styles.context}>Presets restart at θ = 2.4 with velocity 0 and load both parameters. Restart path preserves the parameters. Run stops at step 60 or when both |θ| and |previous update| are below 0.002; this is a convenience threshold, not exact convergence. Step remains available.</p>
 <section className={sharedStyles.evidence} aria-label="Loss curve and actual update"><h2>Loss curve and actual update</h2><p>Step {s.step} · θ = {num(s.theta,8)} · Previous update v = {signed(s.velocity,8)} · Gradient g = {signed(a.gradient,8)}</p><LossPlot history={work.history} nextTheta={a.nextTheta}/><div className={styles.arithmetic}><p>vNext = −η × g + β × vPrevious</p><p>= −{num(work.eta)} × ({signed(a.gradient,8)}) + {num(work.beta)} × ({signed(s.velocity,8)})</p><p>= ({signed(a.gradientTerm,8)}) + ({signed(a.momentumTerm,8)}) = {signed(a.proposedUpdate,8)}</p><p>θNext = {num(s.theta,8)} + ({signed(a.proposedUpdate,8)}) = {num(a.nextTheta,8)}</p></div></section>
 <LessonSummaries label="Current and next loss" summaries={[{label:"Current loss",value:num(a.loss,6),color:"#5031dc",definition:`Loss at current θ = ${num(s.theta,8)}.`,formula:'L(θ) = θ²/2',comparison:`Distance from minimum: ${num(Math.abs(s.theta),8)}.`},{label:"Next loss",value:num(a.nextLoss,6),color:"#1760db",definition:'Proposed loss if you press Step with the current parameters.',formula:`L(${num(a.nextTheta,8)}) = θNext²/2`,comparison:`${a.nextLoss<a.loss?'Lower':a.nextLoss>a.loss?'Higher':'Unchanged'} next loss. ${a.crossesMinimum?'The next step crosses zero.':'The next step does not cross zero.'}`}]} />
 <section className={styles.optional} aria-label="Supporting optimizer evidence"><details><summary>Step history</summary><p>Each row records the position, previous signed update and loss. Display rounds numbers; the recurrence uses full precision.</p><div className={styles.scroller} role="region" aria-label="Scrollable descent history" tabIndex={0}><table><caption>Recorded position, previous signed update and loss. The start has no prior update.</caption><thead><tr><th scope="col">Step</th><th scope="col">θ</th><th scope="col">Previous update</th><th scope="col">Loss</th></tr></thead><tbody>{work.history.map(p=><tr key={p.step}><th scope="row">{p.step}</th><td>{num(p.theta,10)}</td><td>{signed(p.velocity,10)}</td><td>{num(loss(p.theta),10)}</td></tr>)}</tbody></table></div></details><details><summary>Preset comparisons</summary><p>All three original presets start at θ = 2.4, velocity 0 and run 12 updates. Presets change both η and β, so this does not isolate either parameter.</p><div className={styles.scroller} role="region" aria-label="Scrollable preset comparison" tabIndex={0}><table><thead><tr><th scope="col">Preset</th><th scope="col">η</th><th scope="col">β</th><th scope="col">θ after 12</th><th scope="col">Loss after 12</th></tr></thead><tbody>{gradientPresets.map(p=>{const last=simulateDescent(2.4,p.learningRate,p.momentum,12).at(-1)!;return <tr key={p.id}><th scope="row">{p.label}</th><td>{p.learningRate}</td><td>{p.momentum}</td><td>{num(last.theta,8)}</td><td>{num(last.loss,8)}</td></tr>})}</tbody></table></div><p>On this particular quadratic, all three fixed presets converge in the long run; Overshoot crosses the minimum without diverging. These results do not guarantee behavior for other losses or changing parameters.</p></details></section>
 <p className={styles.context}>Velocity here stores the previous signed parameter update. Momentum can reinforce or oppose the current negative gradient. The full update, not gradient direction alone, determines the next position and loss.</p>
 <p role="status" aria-live="polite" aria-atomic="true" className={sharedStyles.liveUpdate}>Step {s.step}; θ {num(s.theta,8)}, previous update {signed(s.velocity,8)}, gradient {signed(a.gradient,8)}. Next update {signed(a.proposedUpdate,8)}, next θ {num(a.nextTheta,8)}. Current loss {num(a.loss,8)}, next loss {num(a.nextLoss,8)}.</p>
 </LearningPage>;
}
