"use client";

import { useMemo, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSelect, LessonSummaries, LessonToolbar, PointValueEditor } from "@/components/learning-page/learning-page";
import { NumberLinePoint, useNumberLineLayout } from "@/components/learning-page/number-line-controls";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeContrastive, changeContrastiveMargin, contrastivePresetId, contrastivePresets, contrastiveScenarios, moveContrastivePoint, pointIds, pointRoles, sameContrastive, type ContrastiveState, type PointId } from "./contrastive-engine";
import { contrastiveBaseline, contrastiveBaselinePoint, reachedContrastive } from "./lesson-state";
import { contrastiveExperiments } from "./learning-experiments";
import styles from "./playground.module.css";

const colors = ["#0c1230", "#087c78", "#ad4508"];
export function ContrastivePlayground() {
  const [state, setState] = useState<ContrastiveState>(contrastiveBaseline);
  const [selected, setSelected] = useState<PointId>("P");
  const [index, setIndex] = useState(0);
  const [prediction, setPrediction] = useState<string | null>(null);
  const [explanation, setExplanation] = useState<string | null>(null);
  const [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const points = useMemo(() => pointIds.map((id, i) => ({ id, label: id, value: state.coordinates[i]!, color: colors[i] })), [state.coordinates]);
  const { trackRef, lanes } = useNumberLineLayout(points, 44);
  const a = useMemo(() => analyzeContrastive(state), [state]);
  const experiment = contrastiveExperiments[index], transfer = index === 3;
  const reached = !!prediction && !!experiment && reachedContrastive(index, state), complete = reached && explanation === "0";
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function start(next = index) { setIndex(next); setState(contrastiveBaseline()); setSelected(contrastiveBaselinePoint(next)); setPrediction(null); clear(); }
  function edit(next: ContrastiveState) { if (!sameContrastive(state, next)) { setState(next); clear(); } }
  function move(id: string, value: number) { edit(moveContrastivePoint(state, id as PointId, value)); }
  const rail = experiment ? <ExperimentRail label={`Experiment ${index + 1} of 3`} title={experiment.title} phase={!prediction ? 0 : reached ? 2 : 1}>
    {!reached && <><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="contrastive-prediction" choices={experiment.predictions} value={prediction} onChange={id => { start(); setPrediction(id); }} /><p className={shared.small}>Changing prediction restores Near negative, Margin 30 and the current experiment’s selected point. Reset restarts this experiment.</p></>}
    {prediction && !reached && <p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
    {reached && <><p role="status" className={shared.observation}>{prediction === "0" ? "The evidence matches your prediction." : "The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="contrastive-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation} />{explanation && !complete && <p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
    {complete && <><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={() => start(index + 1)}>{index === 2 ? "Try the transfer check" : "Next experiment"}</ExperimentButton></>}
  </ExperimentRail> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Move the shared anchor" : "Compare pair roles and margins"}>
    {transfer ? <><p>Without Guide help, set A=30, P=20, N=60 and Margin=40, in any order. Compare with A=20, P=20, N=60 at the same margin: moving the shared anchor changes both pairs. Reconstruct both distances, penalties and their mean.</p>{reachedContrastive(3, state) && <><ExperimentChoices legend="Transfer explanation" name="contrastive-transfer" choices={[
      { id: "both", label: "A–P is similar at distance 10: ½×10²=50. A–N is dissimilar at distance 30, with margin shortfall 40−30=10: ½×10²=50. Mean pair loss is (50+50)/2=50. Both terms rose from zero after moving their shared anchor; the labels stayed fixed. This describes two authored pairs, not trained semantics or generalization." },
      { id: "only", label: "Moving A changes only the positive pair, so the mean is (50+0)/2=25." },
      { id: "distance", label: "Both pairs square their raw distance, so the negative penalty is ½×30²=450 and mean loss is 250." },
    ]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (transferAnswer !== "both" ? <p role="status" className={shared.feedback}>Try again. A is an endpoint in both pairs. Choose each formula by its fixed pair label, then average both terms.</p> : <><ExperimentResult title="Transfer explained">Shared endpoints can couple pair losses. Pair labels choose the formula; the margin caps the dissimilar shortfall at zero.</ExperimentResult><ExperimentButton onClick={() => { setIndex(4); clear(); }}>Explore freely</ExperimentButton></>)}</>}</> : <><p>Compare Separated with Collapsed, move N beyond the margin, or change the shared anchor. Try endpoint coordinates 0 and 100 and the margin endpoints 10 and 100. Keep labels fixed and reconstruct both terms. These manual edits evaluate a loss; they do not train an encoder.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Contrastive Loss Lab" subtitle="Move pairs. Watch the margin stop the penalty." rail={rail}>
    <LessonToolbar scenarios={contrastiveScenarios} selectedId={contrastivePresetId(state)} onSelect={id => { const preset = contrastivePresets[id]!; edit({ coordinates: [...preset.coordinates], margin: preset.margin }); }} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={styles.evidence} aria-label="Scalar embedding editor and labeled pair distances"><h2>Your dataset</h2><p>Three hand-authored one-dimensional embeddings are numeric coordinates. A is the shared anchor; P its similar partner, N its dissimilar partner. Pair A–P has fixed label Y=0 (similar), and A–N fixed label Y=1 (dissimilar). Positive and negative describe pair roles, not coordinate signs or probabilities. Only these two pairs are scored; P–N is not.</p>
      <div className={styles.chart}>
        <div className={styles.chartRow}><span className={styles.laneLabel}>Values</span><div className={styles.track} ref={trackRef} data-contrastive-track><span className={styles.valueAxis} aria-hidden="true" />{points.map((point, i) => <NumberLinePoint key={point.id} point={point} selected={selected === point.id} valueText={`${point.label}: ${point.value}, ${pointRoles[i]}`} helpId="contrastive-keyboard-help" trackRef={trackRef} onSelect={id => setSelected(id as PointId)} onMove={move} style={{ bottom: 8 + (lanes.positions.get(point.id) ?? 0) * 44 }} />)}</div></div>
        <div className={styles.chartRow} aria-hidden="true"><span /><div className={styles.axis}>{[0,25,50,75,100].map(t => <span key={t} className={styles.tick} style={{ left: `${t}%` }}><span>{t}</span></span>)}</div></div>
        {a.pairs.map((pair, i) => <div className={styles.chartRow} key={pair.id}><span className={styles.laneLabel}>{pair.name}<br />d={pair.distance}</span><div className={styles.distance}><svg data-contrastive-distance={pair.id} viewBox="0 0 100 10" preserveAspectRatio="none" role="img" aria-label={`${pair.name} ${pair.relationship.toLowerCase()} pair: endpoints ${pair.endpoints.join(" and ")}, distance ${pair.distance}, coordinate units`}><line x1={pair.left} x2={pair.left + pair.span} y1="5" y2="5" stroke={colors[i+1]} />{pair.endpoints.map((v,j) => <line key={j} x1={v} x2={v} y1="2" y2="8" stroke={j ? colors[i+1] : colors[0]} />)}</svg></div></div>)}
      </div>
      <div className={styles.controls}><LessonSelect label="Selected point" choices={pointIds.map((id,i) => ({ id, label: `${id} · ${pointRoles[i]}` }))} value={selected} onChange={id => setSelected(id as PointId)} /><PointValueEditor label={selected} value={state.coordinates[pointIds.indexOf(selected)]} helpId="contrastive-keyboard-help" onChange={value => move(selected, value)} /></div>
      <LessonRangeControl label="Margin" value={state.margin} min={10} max={100} step={10} help="Minimum separation that removes the dissimilar-pair penalty, in coordinate units. This parameter edit keeps all points fixed." onChange={margin => edit(changeContrastiveMargin(state, margin))} />
      <p role="status" data-contrastive-status className={styles.formula}>{contrastivePresetId(state) === "custom" ? "Custom settings" : contrastiveScenarios.find(s => s.id === contrastivePresetId(state))!.label} · A={state.coordinates[0]}, P={state.coordinates[1]}, N={state.coordinates[2]} · Margin={state.margin} · Selected {selected} · {a.active ? "Negative pair inside margin" : "Negative pair at or beyond margin"}</p><p>Selecting or focusing a point only inspects and preserves answers. Actual coordinate or margin changes clear stale explanations. Coincident points occupy separate handle rows without changing their numeric positions.</p>
    </section>
    <section className={styles.evidence} aria-label="Pair labels, distances and penalty construction"><h2>Two labeled pairs</h2><div className={styles.table} tabIndex={0} role="region" aria-label="Both pair calculations and fixed label conventions"><table><caption>Distances are absolute coordinate differences. Y=0 chooses the similar penalty; Y=1 the dissimilar penalty. The margin shortfall is used only by the dissimilar term.</caption><thead><tr>{["Pair", "Relationship", "Y", "Distance", "Shortfall", "Penalty", "Calculation"].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.pairs.map(p => <tr key={p.id} data-contrastive-pair={p.id}><th scope="row">{p.name}</th><td>{p.relationship}</td><td>{p.label}</td><td>{p.distance}</td><td>{p.shortfall === null ? "Not used" : p.shortfall}</td><td>{p.loss}</td><td className={styles.formula}>{p.formula}</td></tr>)}</tbody></table></div><p data-contrastive-mean className={styles.formula}>Mean pair loss = ({a.positiveLoss} + {a.negativeLoss}) / 2 = {a.mean}. Include both terms, even a zero term.</p><p>Distance and Margin use toy coordinate units; penalties and their mean use squared coordinate units. They are not probabilities, confidence scores or nats. At or beyond the margin the dissimilar penalty is zero, with no further loss reward for increasing that distance.</p></section>
    <LessonSummaries label="Both pair penalties and their mean" summaries={[
      { label: "Positive penalty", color: "#087c78", value: String(a.positiveLoss), definition: "Squared separation cost for the similar pair A–P.", formula: `½ × ${a.positiveDistance}²`, comparison: "Zero only when this similar pair coincides." },
      { label: "Negative penalty", color: "#ad4508", value: String(a.negativeLoss), definition: "Squared margin shortfall for the dissimilar pair A–N.", formula: `½ × max(0, ${state.margin} − ${a.negativeDistance})²`, comparison: "Zero at and beyond the margin; never negative." },
      { label: "Mean pair loss", color: "#5031dc", value: String(a.mean), definition: "Average of exactly these two authored pair penalties.", formula: `(${a.positiveLoss} + ${a.negativeLoss}) / 2`, comparison: "Moving shared anchor A can change both terms." },
    ]} />
    <section className={styles.evidence} aria-label="Contrastive construction and limits"><details><summary>Construction and limits</summary><p>This page scores scalar toy embeddings rather than learning an encoder from data. A real shared encoder maps inputs to embeddings through shared parameters; manual point edits here isolate the objective. Only A–P and A–N are scored. The fixed pair labels represent authored similarity relationships; distance does not relabel a pair.</p><p>Each coordinate is an integer 0..100. Margin is strictly positive, 10..100 in steps of 10. One-dimensional Euclidean distance is |a−b|. The convention is Y=0 similar, Y=1 dissimilar, with factor ½ in each term. Other implementations may reverse label coding or omit that factor; inspect their declared formula. The reference sums pair losses; this page also explicitly averages its two selected terms.</p><p>Collapsed puts all points at 40 with Margin 30: the similar penalty is zero, dissimilar penalty ½×30²=450 and mean 225. The negative term penalizes collapse here. The page draws no gradient arrows and makes no claim about a unique descent direction at a coincident dissimilar pair. Zero loss on two authored pairs does not establish learned semantics or generalization.</p><p>This margin objective is distinct from triplet loss and from temperature-based multi-negative softmax objectives. No temperature, normalization, probability model, optimizer or automatic training is used. Coordinates, labels and the chosen pair set define every displayed value. Prediction and Reset restore Near negative for the current experiment; free-exploration Reset begins Experiment 1.</p><a href="https://www.cs.toronto.edu/~hinton/csc2535/readings/hadsell-chopra-lecun-06-1.pdf" target="_blank" rel="noreferrer">Hadsell, Chopra & LeCun · Contrastive loss, Equation 4</a></details></section>
  </LearningPage>;
}
