"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSelect, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeEntropy, entropyChart, entropyIds, entropyNumber as number, entropyPairs, entropyPresetId, entropyPresets, entropyScenarios, moveEntropyMass, type EntropyPair, type EntropyState } from "./entropy-engine";
import { entropyBaseline, entropyBaselinePair, reachedEntropy } from "./lesson-state";
import { entropyExperiments } from "./learning-experiments";
import styles from "./playground.module.css";

export function EntropyPlayground(){
  const [state,setState]=useState(entropyBaseline),[pair,setPair]=useState<EntropyPair>("AB"),[width,setWidth]=useState(640);
  const [index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
  const chartRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const el=chartRef.current;if(!el)return;const update=()=>setWidth(Math.max(200,el.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(el);return()=>observer.disconnect();},[]);
  const a=useMemo(()=>analyzeEntropy(state),[state]),chart=entropyChart(a,width),experiment=entropyExperiments[index],transfer=index===3,preset=entropyPresetId(state.masses),[first,second]=entropyPairs[pair],pairTotal=state.masses[first]+state.masses[second];
  const reached=!!prediction&&!!experiment&&reachedEntropy(index,state),complete=reached&&explanation==="0";
  function clear(){setExplanation(null);setTransferAnswer(null);}
  function start(next=index){setIndex(next);setState(entropyBaseline(next));setPair(entropyBaselinePair(next));setPrediction(null);clear();}
  function edit(next:EntropyState){if(next.grouping===state.grouping&&next.masses.every((m,i)=>m===state.masses[i]))return;setState(next);clear();}
  const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="entropy-prediction" explanationName="entropy-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores this experiment’s probabilities, grouping and transfer pair. Reset restarts it.</>} observation={prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}
    onNext={()=>start(index+1)} nextLabel={index===2?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"A certain outcome; an impossible group":"Separate distributions from observations"}>
    {transfer?<><p>Without Guide help, concentrate all 100% mass into A while keeping Observed grouping AB | CD. From the four equal buckets, use pair A/B and first mass 50, then A/C and first mass 75, then A/D and first mass 100. Reconstruct A’s surprise, the other entropy contributions, conditional entropy and information gain. What does the impossible CD group mean?</p>
      {reachedEntropy(3,state)&&<><ExperimentChoices legend="Transfer explanation" name="entropy-transfer" choices={[
        {id:"certain",label:"A has probability 1 and surprise 0, so H(X)=0. B/C/D are impossible under this model and each contributes 0 to entropy, despite the infinite surprise limit at zero probability. AB occurs with probability 1 and its conditional entropy is 0. CD has probability 0: its conditional distribution/entropy are Undefined, with weighted contribution 0. Expected conditional entropy and group information gain are both 0; a constant group label adds no information. None proves real-world accuracy."},
        {id:"infinite",label:"Three impossible outcomes make total entropy infinite because their surprises are unweighted."},
        {id:"one",label:"Any two named groups always reveal 1 bit; the impossible CD group should be assigned a 50/50 posterior."},
      ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="certain"?<p role="status" className={shared.feedback}>Try again. Weight each entropy contribution by its probability and condition only on groups with positive mass. A group label that is already certain has no uncertainty to resolve; naming two groups does not force 1 bit of gain.</p>:<><ExperimentResult title="Transfer explained">Certain outcomes have zero average surprise. Impossible events contribute zero to the expectation, and conditioning on a zero-probability group is undefined. A constant observation supplies zero information.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(4);clear();}}>Explore freely</ExperimentButton></>)}</>}
    </>:<><p>Move conserved mass within any pair, then compare group observations with the distribution held fixed. Check rare-outcome surprise, expected contributions and impossible groups before interpreting total uncertainty. Low entropy is not evidence of good predictions.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Entropy & Information Starter" subtitle="Move mass; distinguish surprise from uncertainty." rail={rail}>
    <LessonToolbar scenarios={entropyScenarios} selectedId={preset} onSelect={id=>{edit({masses:entropyPresets[id as keyof typeof entropyPresets],grouping:"ab-cd"});setPair(id==="likely"?"AC":"AB");}} onReset={()=>start(experiment||transfer?index:0)}/>
    <section className={shared.evidence} aria-label="Conserved categorical probability mass">
      <h2>Your dataset</h2><p>Four categorical outcomes A/B/C/D have probabilities summing to 100%. Entropy is their probability-weighted average surprise in bits, not accuracy. Move mass within one selected pair; the other two buckets stay fixed. The bars show probabilities on a fixed 0..100% scale.</p>
      <div className={styles.chart} ref={chartRef}><svg data-entropy-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label="Four probability bars on a fixed zero to hundred percent scale. Exact probabilities, base 2 surprises and entropy contributions are in the table.">
        {chart.ticks.map(t=><g key={t.value}><line x1={t.x} x2={t.x} y1="20" y2="162"/><text x={t.x} y="182" textAnchor="middle">{t.value}%</text></g>)}
        {chart.rows.map(r=>{const inside=r.width>chart.span-42;return <g data-entropy-bar={r.id} key={r.id}><text x={chart.left-12} y={r.y+15} textAnchor="end">{r.id}</text><rect className={styles.track} x={r.x} y={r.y} width={chart.span} height="20"/><rect data-entropy-probability x={r.x} y={r.y} width={r.width} height="20" className={styles.probability}/><text data-entropy-label x={inside?r.x+r.width-7:r.x+r.width+8} y={r.y+15} textAnchor={inside?"end":"start"} className={inside?styles.inside:undefined}>{r.mass}%</text></g>;})}
        <text x={chart.left+chart.span/2} y="202" textAnchor="middle">Probability (fixed 0..100%)</text>
      </svg></div>
      <div className={shared.controlGrid}><LessonSelect label="Transfer pair" value={pair} choices={Object.keys(entropyPairs).map(id=>({id,label:id.split("").join("/")}))} onChange={id=>setPair(id as EntropyPair)}/><LessonRangeControl label="First bucket mass" unit="%" value={state.masses[first]} min={0} max={pairTotal} step={1} help={`${entropyIds[first]}/${entropyIds[second]} total ${pairTotal}%. Set ${entropyIds[first]}; ${entropyIds[second]} receives the complement. The other two buckets stay fixed.`} onChange={mass=>edit({...state,masses:moveEntropyMass(state.masses,pair,mass)})}/></div>
      {pairTotal===0&&<p role="status" data-entropy-empty-pair>No mass in {pair.split("").join("/")}: both remain 0%. Choose a pair containing positive mass to transfer it.</p>}
      <h3>Observed grouping</h3><LessonToggleGroup label="Observed grouping" choices={[{id:"ab-cd",label:"AB | CD"},{id:"ac-bd",label:"AC | BD"}]} value={state.grouping} onChange={grouping=>edit({...state,grouping:grouping as EntropyState["grouping"]})}/>
      <p role="status" data-entropy-status className={shared.math}>{preset==="custom"?"Custom probabilities":entropyScenarios.find(s=>s.id===preset)!.label} · Masses ({state.masses.join(", ")})% · Pair {pair.split("").join("/")} · First {state.masses[first]}% of {pairTotal}% · Grouping {state.grouping==="ab-cd"?"AB | CD":"AC | BD"} · Total 100%</p>
      <p>Choosing a transfer pair only selects an editor and preserves answers. Mass edits change the distribution; grouping changes what the observation reports. Neither changes a measured accuracy value or trains a model.</p>
    </section>
    <section className={shared.evidence} aria-label="All outcome surprises and entropy contributions"><h2>All outcomes (X)</h2>
      <div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="All four outcome identities, probabilities, surprises and entropy terms"><table><caption>For p&gt;0, surprise=−log₂(p); entropy contribution=p×surprise. At p=0, surprise has an infinite limit and the outcome is impossible under this model; the entropy term is 0 by continuity. Base 2 units are bits; probabilities and expectations are not observed correctness.</caption><thead><tr>{["Outcome","Mass (%)","Probability","Surprise (bits)","Entropy contribution (bits)","Group"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.buckets.map(b=><tr data-entropy-row={b.id} key={b.id}><th scope="row">{b.id}</th><td>{b.mass}</td><td>{number(b.p)}</td><td>{b.surprise===null?"∞ (impossible)":number(b.surprise)}</td><td>{number(b.contribution)}</td><td>{a.groups.find(g=>g.ids.includes(b.id))!.ids.join("")}</td></tr>)}</tbody></table></div>
      <p data-entropy-sum className={shared.math}>H(X) = Σ p×surprise = {a.buckets.map(b=>number(b.contribution)).join(" + ")} = {number(a.entropy)} bits.</p>
    </section>
    <section className={shared.evidence} aria-label="Probability-weighted entropy after a group observation"><h2>Groups (G)</h2>
      <p>G tells you which named group contains X. Within a positive-probability group, divide each member’s mass by the group mass. Conditional entropy averages each group’s remaining entropy using that group’s probability. It is not an unweighted sum or just one observed branch.</p>
      <div className={styles.groupTable} role="region" tabIndex={0} aria-label="Both groups, conditional probabilities and weighted entropy"><table><caption>Conditional probabilities sum 1 within each possible group. A zero-probability group has Undefined conditional distribution/entropy and weighted term 0. One rare branch can have more entropy than the prior; the probability-weighted average cannot.</caption><thead><tr>{["Group","Group probability","Conditional outcomes","Group entropy (bits)","Weighted entropy (bits)"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.groups.map(g=><tr data-entropy-group={g.ids.join("")} key={g.ids.join("")}><th scope="row">{g.ids.join("")}</th><td>{number(g.probability)}</td><td>{g.posterior===null?"Undefined (impossible group)":g.ids.map((id,i)=>`${id}: ${number(g.posterior![i])}`).join("; ")}</td><td>{g.entropy===null?"Undefined":number(g.entropy)}</td><td>{number(g.weighted)}</td></tr>)}</tbody></table></div>
      <p data-entropy-conditional className={shared.math}>H(X|G) = {a.groups.map(g=>g.entropy===null?"0 (impossible group)":`${number(g.probability)}×${number(g.entropy)}`).join(" + ")} = {number(a.conditional)} bits. Impossible-group terms are defined as 0; no numerical 0×Undefined product is evaluated.</p>
    </section>
    <LessonSummaries label="Prior entropy, expected conditional entropy and information gain" summaries={[
      {label:"H(X)",color:"#5031dc",value:number(a.entropy),definition:"Expected surprise before the group observation, in bits.",formula:"Σx −p(x) log₂ p(x)",comparison:"Four equal outcomes give the maximum 2 bits; not accuracy."},
      {label:"H(X|G)",color:"#087c78",value:number(a.conditional),definition:"Expected remaining entropy after observing the group, in bits.",formula:"Σg P(g) × H(X given g)",comparison:"Weight possible groups; impossible-group term 0."},
      {label:"Information gain",color:"#ad4508",value:number(a.gain),definition:"Expected reduction from learning G, in bits.",formula:`${number(a.entropy)} − ${number(a.conditional)}`,comparison:"At most 1 bit for this binary group observation; not always 1."},
    ]}/>
    <section className={shared.evidence} aria-label="Observation information and entropy limits">
      <p data-entropy-gain className={shared.math}>I(X;G) = H(X)−H(X|G) = {number(a.gain)} bits. Here G is a deterministic function of X, so I(X;G)=H(G)={number(a.groupEntropy)} bits.</p>
      <details><summary>Construction and limits</summary><p>All four nonnegative integer percentage masses sum 100; probabilities are masses/100. Pair editing conserves the selected pair total and fixes the other two masses. A zero-total pair cannot transfer nonexistent mass; choose another pair. Presets restore their probabilities and grouping AB | CD; the One likely bucket preset selects A/C, the others A/B. Prediction and Reset restore the current experiment; free-exploration Reset starts Experiment 1. Actual probability/grouping edits clear stale answers; pair inspection preserves mastery.</p>
        <p>Entropy uses base 2 logarithms and full-precision arithmetic. For p&gt;0, surprise=−log₂p and the entropy term is−p log₂p. For p=0, the outcome is impossible under the model; its surprise diverges in the limit, but its entropy contribution tends 0. These are separate statements, not numerical multiplication 0×Infinity. A certain outcome has surprise 0 and a point-mass distribution has entropy 0. Entropy is bounded by log₂4=2 bits and is not the largest single outcome surprise.</p>
        <p>The two fixed groupings partition the four outcomes into two pairs. For each positive group, normalize its members by group mass, then compute their conditional entropy. H(X|G) is the group-probability-weighted average. A zero-probability group has no defined conditional distribution here and contributes 0 to that expected entropy. Individual branch entropy can exceed the prior; expected conditional entropy cannot.</p>
        <p>Expected information gain is I(X;G)=H(X)−H(X|G), nonnegative and no greater than either H(X) or 1 bit here. Because this group label is a deterministic function of the outcome, gain equals H(G); this equality need not hold for general noisy observations. Tiny floating error in the nonnegative difference is clipped at 0. Editing marginal probabilities changes the model; an arbitrary before/after entropy decrease is not itself information gained from observing G.</p>
        <p>These are authored finite distributions, not accuracy estimates, calibrated model confidences or semantic uncertainty. There is no simulation, learning, code construction, differential entropy, KL/cross-entropy, general decision tree or automatic best-observation choice. Lower entropy or greater gain alone does not prove real-world task quality.</p>
        <a href="https://www.stat.cmu.edu/~cshalizi/dm/20/lectures/09/lecture-09.html" target="_blank" rel="noreferrer">CMU · Entropy, weighted conditional entropy and mutual information</a><br/><a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.entropy.html" target="_blank" rel="noreferrer">SciPy · Entropy and logarithm-base units</a>
      </details>
    </section>
  </LearningPage>;
}
