"use client";
import { useMemo, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSelect, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeRms, editRmsGain, editRmsValue, rmsBaseline, rmsEpsilons, rmsNumber as number, rmsPresetId, rmsScenarios, rmsX as x, sameRms, type RmsState } from "./rms-engine";
import { rmsExperiments } from "./learning-experiments";
import { reachedRms } from "./lesson-state";
import styles from "./playground.module.css";

export function RmsPlayground() {
  const [state,setState]=useState<RmsState>(rmsBaseline);
  const [index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
  const a=useMemo(()=>analyzeRms(state),[state]),experiment=rmsExperiments[index],transfer=index===3,reached=!!prediction&&!!experiment&&reachedRms(index,state),complete=reached&&explanation==="0";
  function clear(){setExplanation(null);setTransferAnswer(null);}
  function start(next=index){setIndex(next);setState(rmsBaseline());setPrediction(null);clear();}
  function edit(next:RmsState){if(!sameRms(state,next)){setState(next);clear();}}
  const rail=experiment?<ExperimentRail label={`Experiment ${index+1} of 3`} title={experiment.title} phase={!prediction?0:reached?2:1}>
    {!reached&&<><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="rms-prediction" choices={experiment.predictions} value={prediction} onChange={id=>{start();setPrediction(id);}}/><p className={shared.small}>Changing prediction restores Positive. Reset restarts this experiment.</p></>}
    {prediction&&!reached&&<p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
    {reached&&<><p role="status" className={shared.observation}>{prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="rms-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation}/>{explanation&&!complete&&<p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
    {complete&&<><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={()=>start(index+1)}>{index===2?"Try the transfer check":"Next experiment"}</ExperimentButton></>}
  </ExperimentRail>:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Compare a centered vector":"Explore scale and singular cases"}>
    {transfer?<><p>Without Guide help, choose Centered. Set Gain γ to 0.5 and Epsilon to 1, in either order. Explain why RMSNorm and LayerNorm now agree, and reconstruct their output RMS. Does agreement prove that RMSNorm always centers its inputs?</p>{reachedRms(3,state)&&<><ExperimentChoices legend="Transfer explanation" name="rms-transfer" choices={[
      {id:"centered",label:"The input −2,0,2 already has mean 0, so mean square and centered variance both equal 8/3. Both denominators are sqrt(11/3), giving outputs approximately −0.522233,0,0.522233 and output RMS≈0.426401 after gain 0.5. They agree for this centered vector; RMSNorm did not subtract a mean or guarantee unit RMS."},
      {id:"always",label:"Their agreement proves RMSNorm always subtracts the mean and outputs unit RMS, regardless of gain or epsilon."},
      {id:"outside",label:"Their shared denominator is sqrt(8/3)+1, because epsilon is added after the square root."},
    ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="centered"?<p role="status" className={shared.feedback}>Try again. Mean is already zero, so the two statistics agree. Add epsilon inside the root, then multiply normalized coordinates by gain.</p>:<><ExperimentResult title="Transfer explained">A zero input mean can make the two rules agree without making them identical operations. Epsilon and gain still determine the final scale.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(4);clear();}}>Explore freely</ExperimentButton></>)}</>}</>:<><p>Try every preset, input coordinate, Gain γ boundary and Epsilon option. All-zero input with positive epsilon gives zero outputs; with epsilon 0 both denominators are zero and outputs are Undefined. A constant nonzero vector with epsilon 0 has defined RMSNorm but undefined LayerNorm. Gain 0 gives zero only when normalization is defined. These arithmetic examples do not measure transformer training speed or guarantee stable training.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="RMSNorm Lab" subtitle="Rescale a vector. Compare RMS scaling with mean centering." rail={rail}>
    <LessonToolbar scenarios={rmsScenarios} selectedId={rmsPresetId(state)} onSelect={id=>edit(rmsBaseline(id))} onReset={()=>start(experiment||transfer?index:0)}/>
    <section className={styles.evidence} aria-label="RMSNorm and LayerNorm output comparison"><h2>Your dataset</h2><p>One authored activation vector has three feature coordinates. Both rules use the same inputs, Epsilon and shared Gain γ; no batch statistics, running averages or training are involved. RMS means root mean square: square all inputs, average the three squares, then take the square root. RMSNorm divides the original coordinates; LayerNorm first subtracts their mean.</p><h3>Current outputs · Solid purple: RMSNorm · Dashed outline: LayerNorm</h3><p className={shared.small}>Bars start at zero on the shared signed output scale. Dots mark a defined zero output. Undefined means a zero denominator; it has no bar or invented zero marker. Exact values and Positive-reference outputs follow in the construction table.</p>
      <div className={styles.chart} tabIndex={0} role="region" aria-label="Paired signed normalization outputs; exact values in the table"><svg viewBox="0 0 620 275" aria-hidden="true">{[-4,-3,-2,-1,0,1,2,3,4].map(v=><g key={v}><line x1={x(v)} x2={x(v)} y1={15} y2={240} stroke={v===0?"#536487":"#dfe4f4"}/><text x={x(v)} y={265} textAnchor="middle">{v}</text></g>)}{state.values.map((_,i)=><g key={i}><text x={12} y={52+i*70}>x{i+1}</text>{[{id:"rms",values:a.rmsOutput},{id:"layer",values:a.layerOutput}].map((series,j)=>{const value=series.values?.[i]??null,y=40+i*70+j*24;return <g key={series.id} data-rms-chart={series.id} data-rms-coordinate={i}><line x1={90} x2={490} y1={y} y2={y} stroke="#dfe4f4"/>{value===null?null:Math.abs(value)>1e-12?<rect data-rms-bar x={Math.min(x(0),x(value))} y={y-6} width={Math.abs(x(value)-x(0))} height={12} fill={j===0?"#5031dc":"none"} stroke={j===0?"#5031dc":"#536487"} strokeWidth={j===0?1:2} strokeDasharray={j===1?"3 2":undefined}/>:<circle data-rms-zero cx={x(0)} cy={y} r={4} fill={j===0?"#5031dc":"white"} stroke={j===0?"#5031dc":"#536487"}/>}<text data-rms-chart-value x={510} y={y+5}>{number(value)}</text></g>;})}</g>)}</svg></div>
      <div className={styles.controls}>{state.values.map((value,i)=><LessonRangeControl key={i} label={`x${i+1}`} value={value} min={-6} max={6} step={1} help={`Feature coordinate ${i+1}. Both rules and every statistic update after an edit.`} onChange={v=>edit(editRmsValue(state,i,v))}/>)}<LessonRangeControl label="Gain γ" value={state.gain} min={0} max={2} step={0.5} help="One nonnegative shared scalar multiplies all normalized outputs afterward. Real models can learn separate gains per feature." onChange={v=>edit(editRmsGain(state,v))}/><LessonSelect label="Epsilon" choices={rmsEpsilons} value={String(state.epsilon)} onChange={id=>edit({...state,epsilon:Number(id)})}/></div>
      <p className={styles.formula}>RMSNorm = gain × x / sqrt(mean(x²) + epsilon)<br/>LayerNorm = gain × (x − mean) / sqrt(variance + epsilon)<br/>mean = sum(x)/3; variance = sum((x − mean)²)/3; bias β=0</p><p role="status" data-rms-status>Input mean {number(a.mean)} · RMS denominator {number(a.rmsDenominator)} · LayerNorm denominator {number(a.layerDenominator)}. {a.rmsOutput===null?"RMSNorm is Undefined: zero denominator. ":""}{a.layerOutput===null?"LayerNorm is Undefined: zero denominator. ":""}LayerNorm output mean: {number(a.layerMean)}.</p><p className={shared.small}>Epsilon is inside the square root; gain is applied after normalization. A zero denominator is undefined even when gain is zero. Actual input, gain, epsilon or preset changes clear stale explanations and transfer answers; reapplying the same state preserves them. The reference always uses Positive inputs 1,2,3 with the current gain and epsilon.</p>
    </section>
    <LessonSummaries label="RMSNorm input scale and output statistics" summaries={[
      {label:"Input RMS",color:"#5031dc",value:number(a.inputRMS),definition:"Root mean square of the original input.",formula:"sqrt(mean(x²))",comparison:`Mean square=${number(a.meanSquare)}. This statistic is defined at zero even if normalization is not.`},
      {label:"RMSNorm mean",color:"#087c78",value:number(a.rmsMean),definition:"Average of the three RMSNorm outputs.",formula:"gain × input mean / RMS denominator",comparison:"RMSNorm does not subtract the mean. Shared-gain LayerNorm with zero bias has mean zero when defined."},
      {label:"Output RMS",color:"#ad4508",value:number(a.rmsOutputRMS),definition:"Root mean square after RMSNorm and gain.",formula:"gain × sqrt(meanSquare / (meanSquare + epsilon))",comparison:"No general unit-RMS guarantee. Small positive epsilon can round a slightly smaller value to 1."},
    ]}/>
    <section className={styles.evidence} aria-label="Exact normalization construction and reference"><h2>Square, center, divide, then apply gain</h2><p>Population variance averages all three squared centered deviations; it does not use a sample-size correction. Mean square averages squares without centering. The table shows both constructions and compares outputs with Positive 1,2,3 under the current gain and epsilon. Display rounds to six decimals; calculations use unrounded values.</p><div className={styles.table} tabIndex={0} role="region" aria-label="Three feature calculations and Positive-reference outputs"><table><caption>Current inputs {state.values.join(", ")} · Gain {state.gain} · Epsilon {state.epsilon}. Reference: Positive 1,2,3, same gain and epsilon. Undefined is not zero.</caption><thead><tr>{["Coordinate","Input","Square","Centered","RMSNorm output","LayerNorm output","RMS reference","Layer reference"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{state.values.map((value,i)=><tr key={i} data-rms-row={i}><th scope="row">x{i+1}</th><td>{value}</td><td>{value*value}</td><td>{number(a.centered[i]!)}</td><td>{number(a.rmsOutput?.[i]??null)}</td><td>{number(a.layerOutput?.[i]??null)}</td><td>{number(a.reference.rmsOutput?.[i]??null)}</td><td>{number(a.reference.layerOutput?.[i]??null)}</td></tr>)}</tbody></table></div></section>
    <section className={styles.evidence} aria-label="RMSNorm construction and limits"><details><summary>Construction and limits</summary><p>Inputs are three integer feature values −6..6. They are normalized together as one vector, independently of other tokens or samples. Gain 0..2 in steps of 0.5 is one nonnegative scalar shared across coordinates and both rules; real elementwise gains may differ or be negative and can be learned. This toy has no gain training or additive bias. Epsilon choices 0,0.000001 and 1 are explicit demo settings, not a library precision-dependent default. Zero exposes a mathematical boundary; 1 is a large contrast, not a recommended training value.</p><p>RMSNorm uses sqrt(mean(x²)+epsilon), not sqrt(mean(x²))+epsilon. LayerNorm uses sqrt(mean((x−mean)²)+epsilon) and the original minus mean as numerator. Both apply gain afterward. When a denominator is zero, normalization and its gained output are Undefined, even with gain zero. All-zero input has zero input RMS but undefined normalization at epsilon zero. With positive epsilon, both zero-vector outputs are zero. A constant nonzero vector at epsilon zero has defined RMSNorm but undefined LayerNorm; positive epsilon makes constant-vector LayerNorm output zero.</p><p>For a nonzero vector and epsilon zero, multiplying all inputs by a positive factor cancels exactly in RMS normalization. A fixed positive epsilon generally breaks exact rescaling invariance. A negative input factor flips the normalized sign at epsilon zero, so do not call that identical output. A common additive shift preserves LayerNorm’s centered deviations and variance when its denominator is nonzero; it need not preserve RMSNorm. If the input already has mean zero, both rules agree with the same gain and epsilon, without RMSNorm performing centering.</p><p>Normalized RMS is sqrt(meanSquare/(meanSquare+epsilon)) when defined; output RMS is the shared nonnegative gain times that value. Epsilon zero gives normalized RMS 1 for nonzero inputs; positive epsilon lowers it. Neither gain nor epsilon guarantees a final RMS of 1. This lesson demonstrates arithmetic, not measured training speed, transformer residual-stream behavior, long-context performance or guaranteed stable training. Presets restore gain 1 and epsilon 0.000001. Reset/predictions restore Positive for the current experiment; free Reset starts Experiment 1.</p><a href="https://docs.pytorch.org/docs/2.14/generated/torch.nn.RMSNorm.html" target="_blank" rel="noreferrer">PyTorch · RMSNorm denominator and elementwise gain</a><br/><a href="https://docs.pytorch.org/docs/2.14/generated/torch.nn.LayerNorm.html" target="_blank" rel="noreferrer">PyTorch · LayerNorm centering and population variance</a><br/><a href="https://arxiv.org/abs/1910.07467" target="_blank" rel="noreferrer">Root Mean Square Layer Normalization · Original paper</a></details></section>
  </LearningPage>;
}
