"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { activationBaseline, activationChart, activationDefinitions, activationNumber as number, activationPresetId, activationScenarios, analyzeActivation, editActivation, sameActivation, type Activation, type ActivationState } from "./activation-engine";
import { activationExperiments } from "./learning-experiments";
import { reachedActivation } from "./lesson-state";
import styles from "./playground.module.css";
export function ActivationPlayground() {
 const [state,setState]=useState<ActivationState>(activationBaseline),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const chartRef=useRef<HTMLDivElement>(null),[width,setWidth]=useState(640);
 useEffect(()=>{const el=chartRef.current;if(!el)return;const update=()=>setWidth(Math.max(260,el.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(el);return()=>observer.disconnect();},[]);
 const a=useMemo(()=>analyzeActivation(state),[state]),chart=activationChart(state,width),experiment=activationExperiments[index],transfer=index===3,reached=!!prediction&&!!experiment&&reachedActivation(index,state),complete=reached&&explanation==="0";
 function clear(){setExplanation(null);setTransferAnswer(null);}
 function start(next=index){setIndex(next);setState(activationBaseline());setPrediction(null);clear();}
 function edit(next:ActivationState){if(!sameActivation(state,next)){setState(next);clear();}}
 const selectedFormula=state.activation==="relu"?`max(0,${number(a.input)})`:state.activation==="sigmoid"?`1 / (1 + exp(${number(-a.input)}))`:`tanh(${number(a.input)})`;
 const rail=experiment?<ExperimentRail label={`Experiment ${index+1} of 3`} title={experiment.title} phase={!prediction?0:reached?2:1}>
  {!reached&&<><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="activation-prediction" choices={experiment.predictions} value={prediction} onChange={id=>{start();setPrediction(id);}}/><p className={shared.small}>Changing prediction restores Positive input 2 and ReLU. Reset restarts this experiment.</p></>}
  {prediction&&!reached&&<p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
  {reached&&<><p role="status" className={shared.observation}>{prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="activation-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation}/>{explanation&&!complete&&<p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
  {complete&&<><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={()=>start(index+1)}>{index===2?"Try the transfer check":"Next experiment"}</ExperimentButton></>}
 </ExperimentRail>:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Transform a new negative input":"Explore fixed activation rules"}>
  {transfer?<><p>Without Guide help, choose Negative input, then set Input value=−4 and choose Tanh in either order. Reconstruct all three outputs, identify which can be negative, and explain whether choosing a function changed the input. Separate a value near a bound from an exact bound.</p>{reachedActivation(3,state)&&<><ExperimentChoices legend="Transfer explanation" name="activation-transfer" choices={[
   {id:"rules",label:"The input remains−4. ReLU gives0, sigmoid about 0.017986 and tanh about −0.999329. Tanh is negative and close to −1 but not exactly−1 here. Changing Activation selected a different fixed rule without changing the input or training weights. Sigmoid’s positive bounded value alone does not prove a calibrated class probability."},
   {id:"identity",label:"Every activation returns−4 because the input is negative."},
   {id:"bounds",label:"Tanh is exactly−1 and sigmoid is exactly0 for every finite negative input."},
  ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="rules"?<p role="status" className={shared.feedback}>Try again. Apply each fixed formula to the unchanged input −4. Read the six-decimal values and their stated finite-input ranges before claiming an exact endpoint or probability.</p>:<><ExperimentResult title="Transfer explained">The same negative input is clipped, made positive or kept negative under different fixed rules. Bounded output is different from a calibrated probability or an exact bound.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(4);clear();}}>Explore freely</ExperimentButton></>)}</>}</>:<><p>Try Input value−6,−0.1,0,0.1 and6 under every Activation. Switch functions without changing the input; compare all outputs and their changes from the fixed input 2 reference. Open Compare the curves to inspect common axes and coincident zero markers. These rules transform values; they do not train a network.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
 </ExperimentRail>;
 return <LearningPage title="Activation Functions Lab" subtitle="Change the input. Compare three activation rules." rail={rail}>
  <LessonToolbar scenarios={activationScenarios} selectedId={activationPresetId(state)} onSelect={id=>edit(activationBaseline(id))} onReset={()=>start(experiment||transfer?index:0)}/>
  <section className={styles.evidence} aria-label="Shared input and selected activation"><h2>Your dataset</h2><p>One scalar input x passes through a fixed activation, an input-output rule. ReLU means rectified linear unit; tanh means hyperbolic tangent. All three rules use the same input. Choosing Activation keeps x fixed, while editing Input value recomputes all outputs. No learned weights, bias or training is supplied.</p>
   <div className={styles.flow} aria-label="Input, selected rule and output"><div><h3>Input x</h3><p data-act-input className={styles.value}>{number(a.input)}</p></div><span aria-hidden="true">→</span><div><h3>Selected rule</h3><p className={styles.rule}>{a.selected.label}</p><p data-act-rule className={styles.formula}>{selectedFormula}</p></div><span aria-hidden="true">→</span><div><h3>Output</h3><p data-act-output className={styles.value}>{number(a.selected.output)}</p></div></div>
   <div className={styles.controls}><LessonToggleGroup label="Activation" choices={activationDefinitions.map(d=>({id:d.id,label:d.label}))} value={state.activation} onChange={activation=>edit({...state,activation:activation as Activation})}/><LessonRangeControl label="Input value" value={a.input} min={-6} max={6} step={0.1} help="A shared scalar input in tenths. All rules transform the same x; the selected rule determines the primary output." onChange={v=>edit(editActivation(state,v))}/></div>
   <p role="status" data-act-status className={styles.formula}>{a.selected.label}({number(a.input)}) = {number(a.selected.output)} · {a.selected.range}</p><p>Actual input or function changes clear stale explanations and transfer answers. Unchanged controls preserve them. Display values round to six decimals; calculations use full precision. A bounded sigmoid output by itself is not evidence of a trained or calibrated class probability.</p>
  </section>
  <LessonSummaries label="Three activation outputs for the same input" summaries={a.rows.map(r=>({label:r.label,color:r.color,value:number(r.output),definition:r.range,formula:r.formula,comparison:`Fixed input 2: ${number(r.baseline)}. Current output minus that reference: ${number(r.delta)}.`}))}/>
  <section className={styles.evidence} aria-label="Current activation and reference calculations"><h2>Compare each fixed rule</h2><p>exp(x) is the exponential e raised to x, where e is about 2.71828. ReLU is max(0,x). Sigmoid is 1/(1+exp(−x)); tanh is (exp(x)−exp(−x))/(exp(x)+exp(−x)). At input 0, exp(0)=1 gives sigmoid 0.5 and tanh 0. Saturation means approaching a bound with smaller output changes, not becoming exactly constant at a finite input here.</p><div className={styles.table} tabIndex={0} role="region" aria-label="Three current outputs and changes from fixed input 2"><table><caption>Reference input 2 remains fixed across scenarios and function changes. Every current output uses the same x; changes are f(x)−f(2), computed before display rounding.</caption><thead><tr>{["Activation","Current x","Current output","Fixed x=2 output","Change from x=2"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.rows.map(r=><tr key={r.id} data-act-row={r.id}><th scope="row">{r.label}</th><td>{number(a.input)}</td><td>{number(r.output)}</td><td>{number(r.baseline)}</td><td>{number(r.delta)}</td></tr>)}</tbody></table></div></section>
  <section className={styles.evidence} aria-label="Optional common-axis activation curves"><details><summary>Compare the curves</summary><p>All curves share input −6..6 and output −1..6. Circle/solid line=ReLU; square/dashed=Sigmoid; diamond/dotted=Tanh. A navy outline highlights the selected output at the shared input guide. Shapes, patterns, labels and the exact table accompany color; coincident markers draw the selected one last.</p><div className={styles.chart} ref={chartRef}><svg data-activation-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label="All three fixed activation curves on common X minus6 to 6 and Y minus1 to 6 axes, current-input vertical guide and shape-specific output markers. Exact current and reference values are in the table above.">
   {chart.xTicks.map(t=><g key={t.value}><line x1={t.x} x2={t.x} y1={chart.top} y2={chart.top+chart.spanY} className={styles.grid}/><text x={t.x} y={chart.top+chart.spanY+20} textAnchor="middle">{t.value}</text></g>)}{chart.yTicks.map(t=><g key={t.value}><line x1={chart.left} x2={chart.left+chart.spanX} y1={t.y} y2={t.y} className={styles.grid}/><text x={chart.left-9} y={t.y+4} textAnchor="end">{t.value}</text></g>)}
   <line x1={chart.left} x2={chart.left+chart.spanX} y1={chart.zeroY} y2={chart.zeroY} className={styles.axis}/><line x1={chart.zeroX} x2={chart.zeroX} y1={chart.top} y2={chart.top+chart.spanY} className={styles.axis}/><line data-act-guide x1={chart.inputX} x2={chart.inputX} y1={chart.top} y2={chart.top+chart.spanY} className={styles.guide}/>
   {chart.curves.map(c=><polyline key={c.id} data-act-curve={c.id} points={c.vertices.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke={c.color} strokeWidth={c.selected?3:1.8} strokeDasharray={c.id==="sigmoid"?"6 4":c.id==="tanh"?"2 4":undefined}/>)}
   {[...chart.curves].sort((a,b)=>Number(a.selected)-Number(b.selected)).map(c=><g key={c.id} data-act-marker={c.id}><title>{`${c.label} at input ${number(a.input)} gives ${number(c.output)}`}</title>{c.id==="relu"?<circle cx={c.marker.x} cy={c.marker.y} r="6" fill={c.color} stroke={c.selected?"#0c1230":"white"} strokeWidth={c.selected?3:1}/>:c.id==="sigmoid"?<rect x={c.marker.x-6} y={c.marker.y-6} width="12" height="12" fill={c.color} stroke={c.selected?"#0c1230":"white"} strokeWidth={c.selected?3:1}/>:<path d={`M ${c.marker.x} ${c.marker.y-7} L ${c.marker.x+7} ${c.marker.y} L ${c.marker.x} ${c.marker.y+7} L ${c.marker.x-7} ${c.marker.y} Z`} fill={c.color} stroke={c.selected?"#0c1230":"white"} strokeWidth={c.selected?3:1}/>}</g>)}
   <text x={chart.left+chart.spanX/2} y="345" textAnchor="middle">Input x</text><text x="10" y={chart.top+chart.spanY/2} textAnchor="middle">y</text>
  </svg></div><p>Curves connect the 121 supported input positions in steps of 0.1. Values and marker positions are exact at those positions up to floating arithmetic; straight segments between them are illustrative. The editor’s maximum6 is not a mathematical upper bound on ReLU. Sigmoid and tanh approach their ideal bounds without reaching them at any supported input.</p></details></section>
  <section className={styles.evidence} aria-label="Activation construction and limits"><details><summary>Construction and limits</summary><p>The input is encoded as an integer−60..60 divided by 10, with no weights, bias, network layers or dataset. ReLU uses max(0,x), sigmoid uses1/(1+exp(−x)), and tanh uses the hyperbolic tangent. These fixed scalar functions can also be applied element by element in a tensor, but tensor behavior is outside this lesson.</p><p>For finite real inputs, sigmoid lies strictly between 0 and1 and tanh strictly between −1 and1. At the supported endpoints, sigmoid(6)≈0.997527 and tanh(6)≈0.999988; neither is exactly1. ReLU is zero at and below 0 and has no global upper bound. No derivatives, gradient at the ReLU kink, optimization, learned representation, calibrated probability or recommendation of an activation for a task is claimed.</p><p>Reference input 2 is fixed for each activation. Changing function preserves input; changing input recomputes all three functions. Reset/prediction restores Positive input 2/ReLU for the current experiment; free Reset begins Experiment 1. Ordinary display rounding is not used for subsequent calculations or mastery checks. The optional common-axis curves have121 vertices and preserve this same numeric model.</p><a href="https://docs.pytorch.org/docs/2.14/generated/torch.nn.ReLU.html" target="_blank" rel="noreferrer">PyTorch · ReLU definition</a><br/><a href="https://docs.pytorch.org/docs/2.14/generated/torch.nn.Sigmoid.html" target="_blank" rel="noreferrer">PyTorch · Sigmoid definition</a><br/><a href="https://docs.pytorch.org/docs/2.14/generated/torch.nn.Tanh.html" target="_blank" rel="noreferrer">PyTorch · Tanh definition</a></details></section>
 </LearningPage>;
}
