"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeNormal, normalChart, normalModels, type NormalState, type NormalTail } from "./normal-engine";
import { normalBaseline, reachedNormal } from "./lesson-state";
import { normalExperiments } from "./learning-experiments";
import styles from "./playground.module.css";
export function NormalDistributionPlayground() {
  const [state,setState]=useState<NormalState>(()=>normalBaseline()),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null),[width,setWidth]=useState(640);
  const chartRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const element=chartRef.current;if(!element)return;const update=()=>setWidth(Math.max(200,element.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(element);return()=>observer.disconnect();},[]);
  const a=useMemo(()=>analyzeNormal(state),[state]),chart=normalChart(a,width),preset=normalModels.find(m=>m.mean===state.mean&&m.sd===state.sd),experiment=normalExperiments[index],transfer=index===5,reached=!!prediction&&!!experiment&&reachedNormal(index,state),complete=reached&&explanation==="0";

  function clear(){setExplanation(null);setTransferAnswer(null);}
  function start(next=index){setIndex(next);setState(normalBaseline(next));setPrediction(null);clear();}
  function edit(patch:Partial<NormalState>){setState(s=>({...s,...patch}));clear();}
  const rail=experiment?<ExperimentRail label={`Experiment ${index+1} of 5`} title={experiment.title} phase={!prediction?0:reached?2:1}>
    {!reached&&<><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="area-prediction" choices={experiment.predictions} value={prediction} onChange={id=>{start();setPrediction(id);}}/><p className={shared.small}>Changing prediction restores this experiment’s starting mean, spread, value and tail. Reset restarts it.</p></>}
    {prediction&&!reached&&<p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
    {reached&&<><p role="status" className={shared.observation}>{prediction==="0"?"The observed evidence matches your prediction.":"The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="area-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation}/>{explanation&&!complete&&<p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
    {complete&&<><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={()=>start(index+1)}>{index===4?"Try the transfer check":"Next experiment"}</ExperimentButton></>}
  </ExperimentRail>:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Use a new reference and spread":"Explore normal tails"}>
    {transfer?<><p>Without Guide help, set Mean to 10, Standard deviation to 4 and Value to 6. Choose At or below. Explain z and the tail probability, including the model assumption.</p><ExperimentChoices legend="Transfer explanation" name="normal-transfer" choices={[{id:"normal",label:"z = (6 − 10) / 4 = −1. Under this assumed normal model, probability at or below 6 is about 0.1587. Standardizing alone does not establish normality."},{id:"raw",label:"z = 6 / 4 = 1.5, because every z-score uses zero as its reference."},{id:"universal",label:"Any dataset with this mean and SD has this normal tail probability; the point 6 itself has probability 0.1587."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!reachedNormal(5,state)?<p role="status" className={shared.feedback}>First set Mean 10, Standard deviation 4, Value 6 and At or below. Read the formula and both tails.</p>:transferAnswer!=="normal"?<p role="status" className={shared.feedback}>Try again. Subtract this model’s mean, divide by its positive SD and retain the normal-distribution assumption. A tail probability covers an interval, not a single point.</p>:<><ExperimentResult title="Transfer explained">Value 6 is one SD below mean 10: z = −1. Its normal left tail is about 0.1587. Z measures relative distance; normality supplies the probability model.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(6);clear();}}>Explore freely</ExperimentButton></>)}</>:<><p>Change the mean, spread, value and selected tail. Presets replace all three parameters and retain the tail. Watch the raw axis labels as the chart window follows the model. Reset returns to Experiment 1.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Normal Distribution & Z-Scores Lab" subtitle="Read a value in standard-deviation units." rail={rail}>
    <LessonToolbar label="Starting normal models" scenarios={normalModels} selectedId={preset?.id??"custom"} onSelect={id=>{const m=normalModels.find(m=>m.id===id)!;edit({mean:m.mean,sd:m.sd,value:m.mean});}} onReset={()=>start(experiment||transfer?index:0)}/>
    <section className={styles.evidence} aria-label="Normal model controls"><p>These are assumed normal models, not fitted observations. Current mean {state.mean}, standard deviation {state.sd}. Presets replace Mean, Standard deviation and Value; they keep the selected tail.</p><div className={styles.controls}><LessonRangeControl label="Mean" value={state.mean} min={-10} max={30} step={.5} help="The normal model’s center and reference for signed distance." onChange={mean=>edit({mean})}/><LessonRangeControl label="Standard deviation" value={state.sd} min={.5} max={5} step={.5} help="Positive spread in the same raw units as Value." onChange={sd=>edit({sd})}/><LessonRangeControl label="Value" value={state.value} min={-30} max={50} step={.5} help="Compare this value with the current mean and spread." onChange={value=>edit({value})}/></div><LessonToggleGroup label="Selected tail" choices={[{id:"left",label:"At or below"},{id:"right",label:"Above"}]} value={state.tail} onChange={tail=>edit({tail:tail as NormalTail})}/></section>
    <section className={styles.evidence} aria-label="Normal density chart"><h2>Normal density and selected tail</h2><p>Solid curve · density. Shading · selected tail within the window. Dashed line · mean. Solid vertical line · selected value.</p><div className={styles.chart} ref={chartRef}><svg viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`Assumed normal model, mean ${state.mean}, SD ${state.sd}. Value ${state.value}, z ${a.z.toFixed(2)}. ${state.tail==="left"?"At or below":"Above"} probability approximately ${a.probability.toFixed(4)}. Window ${chart.min} to ${chart.max}; the model extends indefinitely. Exact parameter and numeric tail evidence is below.`} data-normal-chart>
      {chart.yTicks.map(t=><g key={t.value}><line x1={chart.left} x2={chart.width-chart.right} y1={t.y} y2={t.y}/><text x={chart.left-8} y={t.y+4} textAnchor="end">{t.value}</text></g>)}<polygon points={chart.polygon} data-tail-area/><polyline points={chart.points} data-normal-density/><line x1={chart.centerX} x2={chart.centerX} y1={chart.top} y2={chart.baseline} data-mean/><line x1={chart.valueX} x2={chart.valueX} y1={chart.top} y2={chart.baseline} data-value/>
      {chart.xTicks.map((t,i)=><text key={t.value} x={t.x} y={chart.height-chart.bottom+19} textAnchor={i===0?"start":i===4?"end":"middle"}>{t.value}</text>)}<text x={(chart.left+chart.width-chart.right)/2} y={chart.height-3} textAnchor="middle">Raw value x</text><text x="4" y="12">Density per raw unit</text>{chart.offWindow&&<text x={chart.valueX} y={chart.top+14} textAnchor={chart.offWindow==="left"?"start":"end"} data-off-window>{chart.offWindow==="left"?"← Value off window":"Value off window →"}</text>}
    </svg></div><p data-window>Window: {chart.min} to {chart.max}. It follows the mean and covers at least four SD units each side; it widens for SD above 2. The density scale stays 0–0.85. Shading shows only the visible part of the selected tail; the probability includes its entire infinite extent.</p>{chart.offWindow&&<p role="status">Value {state.value} lies {chart.offWindow==="left"?"below":"above"} the shown window. Its labelled edge marker is a direction cue, not its plotted position. The formula and probability still use Value {state.value}.</p>}</section>
    <LessonSummaries label="Standardized distance and probability" summaries={[{label:"Signed distance",color:"#ad4508",value:a.distance.toFixed(2),definition:"Raw units relative to the model mean.",formula:`${state.value} − ${state.mean}`},{label:"Z-score",color:"#5031dc",value:a.z.toFixed(2),definition:"Signed distance in SD units.",formula:`${a.distance} / ${state.sd}`},{label:"Approx. tail probability",color:"#33486d",value:a.probability.toFixed(4),definition:state.tail==="left"?"All values at or below Value.":"All values above Value.",formula:`P(X ${state.tail==="left"?"≤":">"} ${state.value})`}]}/>
    <section className={styles.evidence} aria-label="Numeric probability evidence"><p className={styles.formula} data-z-formula>z = ({state.value} − {state.mean}) / {state.sd} = {a.z.toFixed(2)}.</p><table className={styles.table} data-tail-table><caption>Numerical probabilities under the assumed normal model. The two tails add to 1.</caption><thead><tr><th scope="col">Event</th><th scope="col">Approx. probability</th></tr></thead><tbody><tr><th scope="row">At or below {state.value}</th><td>{a.left.toFixed(4)}</td></tr><tr><th scope="row">Above {state.value}</th><td>{a.right.toFixed(4)}</td></tr><tr><th scope="row">Single point: X = {state.value}</th><td>0 (exact)</td></tr></tbody></table><p data-density-height>Density at Value = {a.density.toFixed(6)} per raw unit. This height is not a point or tail probability. A z-score is a distance, and can be negative or greater than 1; probabilities stay within 0–1.</p><p>Tails are calculated numerically and rounded to four decimals. A tiny positive normal tail may display 0.0000; that does not mean an off-window value is impossible.</p></section>
    <section className={styles.evidence} aria-label="Normal model assumptions"><details><summary>Normality, standardization and numerical scope</summary><p>The normal model is symmetric about its mean, has positive standard deviation and extends over all real values. Each tail at the mean is 0.5. The standardized variable Z = (X − mean) / SD has mean 0 and SD 1 under this normal model. A value’s z-score describes signed relative distance; standardization does not make an arbitrary distribution normal.</p><p>Normal density is exp(−z²/2) / (SD × √(2π)). Tail probabilities use the Abramowitz–Stegun 26.2.17 numerical approximation, with the smaller tail computed directly. Finite precision and rounding affect very small tails. The plotted curve and shading use finite sampled line segments; probability is calculated independently over the entire selected tail.</p><p>This lesson assumes a distribution. It does not infer normality from data, estimate parameters, perform a hypothesis test or attach a probability to a single point.</p><a href="https://www.itl.nist.gov/div898/handbook/eda/section3/eda3661.htm" target="_blank" rel="noreferrer">NIST · Normal distribution</a><br/><a href="https://dlmf.nist.gov/7.1" target="_blank" rel="noreferrer">NIST DLMF · Normal tail functions</a></details></section>
  </LearningPage>;
}
