"use client";
import {useMemo,useState} from "react";
import {ExperimentButton,ExperimentChoices,ExperimentRail,ExperimentResult,LearningPage,LessonSelect,LessonSummaries,LessonToolbar} from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import {analyzeRag,answerChoices,citationChoices,contextChoices,ragBaseline,ragNumber as number,ragPresetId,ragScenarios,sameRag,type RagState} from "./rag-engine";
import {ragExperiments} from "./learning-experiments";
import {reachedRag} from "./lesson-state";
import styles from "./playground.module.css";
export function RagPlayground(){
 const[state,setState]=useState<RagState>(ragBaseline),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const a=useMemo(()=>analyzeRag(state),[state]),experiment=ragExperiments[index],transfer=index===4,reached=!!prediction&&!!experiment&&reachedRag(index,state),complete=reached&&explanation==="0";
 function clear(){setExplanation(null);setTransferAnswer(null);}function start(next=index){setIndex(next);setState(ragBaseline());setPrediction(null);clear();}function edit(next:RagState){if(!sameRag(state,next)){setState(next);clear();}}
 const rail=experiment?<ExperimentRail label={`Experiment ${index+1} of 4`} title={experiment.title} phase={!prediction?0:reached?2:1}>
 {!reached&&<><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="rag-prediction" choices={experiment.predictions} value={prediction} onChange={id=>{start();setPrediction(id);}}/><p className={shared.small}>Changing prediction restores Fully supported. Reset restarts this experiment.</p></>}{prediction&&!reached&&<p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}{reached&&<><p role="status" className={shared.observation}>{prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="rag-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation}/>{explanation&&!complete&&<p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}{complete&&<><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={()=>start(index+1)}>{index===3?"Try the transfer check":"Next experiment"}</ExperimentButton></>}
 </ExperimentRail>:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Transfer partial support and citations":"Explore independent failure modes"}>{transfer?<><p>Without Guide help, set Retrieved context to Partial · D1 only, Answer bundle to Unsupported fee · Tuesday, 10:00, free, and Citation rule to Mixed · Matched first two, then D3. Trace each claim against the retrieved source and current reference. Reconstruct all five metrics and their denominators.</p>{reachedRag(4,state)&&<><ExperimentChoices legend="Transfer explanation" name="rag-transfer" choices={[
 {id:"counts",label:"D1 is the one retrieved relevant document, so context relevance=1. Tuesday and 10:00 are supported; free admission is not: Faithfulness=2/3≈0.666667. The first two D1 citations are valid; the third D3 citation is neither retrieved nor entailing: Citation support=2/3 and Citation precision=2/3. Two of three correct required facts are present, so Completeness=2/3. The metrics share this numeric value for different reasons; free admission is not inferred from missing fee evidence."},
 {id:"missing",label:"With no retrieved fee source, free admission must be true and completeness is 1."},
 {id:"citation",label:"Any citation label is valid, so Citation support is 1 even when the cited document is not retrieved."}
 ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="counts"?<p role="status" className={shared.feedback}>Try again. Read which fact IDs D1 supports, require the cited source to be retrieved and entailing, and compare the fee with the current 4-credit reference.</p>:<><ExperimentResult title="Transfer explained">Separate the retrieved documents, claims made, actual citations and required reference facts before combining their measurements.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(5);clear();}}>Explore freely</ExperimentButton></>)}</>}</>:<><p>Try Empty answer with every context: Faithfulness and Citation support are Undefined, while Completeness is 0. With a nonempty answer and No citations, Citation support is 0 and Citation precision Undefined. With No retrieved documents, context relevance is Undefined and nonempty claim support is 0. Try Off-topic garden benches with Noisy context: it is faithful but covers none of the question. Reset starts Experiment 1.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}</ExperimentRail>;
 return<LearningPage title="RAG Groundedness Metrics Lab" subtitle="Separate evidence, citations and coverage." rail={rail}>
 <LessonToolbar scenarios={ragScenarios} selectedId={ragPresetId(state)} onSelect={id=>edit(ragBaseline(id))} onReset={()=>start(experiment||transfer?index:0)}/>
 <section className={styles.evidence} aria-label="Fictional retrieval dataset"><h2>Your dataset</h2><p>Retrieval-augmented generation (RAG) supplies retrieved source material to a generator before it answers. Here, authored source and answer bundles expose the evaluation steps.</p><p><strong>Fictional question:</strong> When does the Harbor Museum open, and what is admission?</p><p><strong>Authored current reference:</strong> Tuesday · 10:00 · 4 fictional credits. This is a teaching example, not information about a real venue.</p><p>The four sources have disclosed fact IDs. Support means the exact claim’s fact ID is listed by a retrieved source; no actual retriever, language model or semantic entailment judge runs here. “Entails” means the source supports that claim in this authored mapping. D4 is relevant but outdated; relevance does not imply freshness.</p>
 <div className={styles.table} role="region" tabIndex={0} aria-label="Four authored sources with retrieval and relevance labels"><table><caption>Retrieved context selects sources; it does not regenerate the answer.</caption><thead><tr>{["Source","Exact authored text","Fact IDs","Retrieved?","Question-relevant?"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.documents.map(d=><tr key={d.id} data-rag-document={d.id}><th scope="row">{d.id}</th><td>{d.text}</td><td>{d.facts.join(", ")}</td><td>{d.retrieved?"Yes":"No"}</td><td>{d.relevant?"Yes":"No"}{d.id==="D4"?" · Outdated":""}</td></tr>)}</tbody></table></div>
 <div className={styles.controls}><LessonSelect label="Retrieved context" choices={contextChoices} value={state.context} onChange={context=>edit({...state,context})}/><LessonSelect label="Answer bundle" choices={answerChoices} value={state.answer} onChange={answer=>edit({...state,answer})}/><LessonSelect label="Citation rule" choices={citationChoices} value={state.citations} onChange={citations=>edit({...state,citations})}/></div>
 <p role="status" data-rag-status>Retrieved {a.retrievedCount} documents · Relevant {a.relevantCount} · Answer claims {a.claimCount} · Supported {a.supportedCount} · Present citations {a.citedCount} · Valid citations {a.citationSupportedCount} · Covered required facts {a.coveredCount}/3.</p><p>Context relevance = relevant retrieved documents / all retrieved documents = {a.relevantCount}/{a.retrievedCount} = <strong data-rag-context>{number(a.contextRelevance)}</strong>. No retrieved documents makes this Undefined. This is a simple document fraction, not rank-aware context precision or an exact RAGAS implementation.</p><p className={shared.small}>Each actual control/preset change clears stale explanation/transfer answers; reapplying the same state preserves them. Context, claims and citation labels can change independently.</p>
 </section>
 <section className={styles.evidence} aria-label="Claim and citation support"><h2>Trace each answer claim</h2><p>Faithfulness uses any retrieved source. Citation support instead checks the source actually cited: it must be retrieved and individually entail the claim. A cited source may entail a claim in the full corpus but be absent from retrieved context; that citation is invalid in this toy convention.</p><div className={styles.table} role="region" tabIndex={0} aria-label="Answer claims with support and citation checks"><table><caption>One optional citation per claim. All support and reference mappings are authored, not model judgments.</caption><thead><tr>{["Claim / fact ID","Support in retrieved context","Cited source","Cited source retrieved?","Cited source entails?","Valid citation?"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.claims.map(c=><tr key={c.id} data-rag-claim={c.id}><th scope="row">{c.text}<span className={styles.itemDetails}>{c.id}</span></th><td>{c.supportDocs.join(", ")||"None"}</td><td>{c.citation??"None"}</td><td>{c.citation===null?"No citation":c.citationRetrieved?"Yes":"No"}</td><td>{c.citation===null?"No citation":c.citationEntails?"Yes":"No"}</td><td>{c.citationSupported?"Yes":"No"}</td></tr>)}{a.claimCount===0&&<tr><td colSpan={6}>No answer claims. Faithfulness and Citation support are Undefined; the answer covers 0 required facts.</td></tr>}</tbody></table></div></section>
 <LessonSummaries label="Current RAG support and completeness results" summaries={[
 {label:"Faithfulness",color:"#5031dc",value:number(a.faithfulness),definition:"Claims supported by any retrieved source.",formula:"supported answer claims / answer claims",comparison:`${a.supportedCount}/${a.claimCount}. Undefined for no claims. Relative to these sources, not guaranteed current truth.`},
 {label:"Citation support",color:"#087c78",value:number(a.citationCoverage),definition:"Claims with a retrieved, individually entailing citation.",formula:"validly cited claims / answer claims",comparison:`${a.citationSupportedCount}/${a.claimCount}. Coverage of all claims; support elsewhere does not validate the cited source.`},
 {label:"Completeness",color:"#ad4508",value:number(a.completeness),definition:"Correct required current reference facts present.",formula:"covered required facts / 3",comparison:`${a.coveredCount}/3. Empty answer is 0. Extra unsupported claims are not penalized by this coverage measure.`},
 ]}/>
 <section className={styles.evidence} aria-label="Citation precision and required reference coverage"><h2>Check the denominator and the question</h2><p>Citation precision = valid citations / present citations = {a.citationSupportedCount}/{a.citedCount} = <strong data-rag-precision>{number(a.citationPrecision)}</strong>. No citations makes precision Undefined. A nonempty answer with no citations still has Citation support 0. With one citation per claim, precision and claim coverage agree only when all claims have a citation.</p><div className={styles.table} role="region" tabIndex={0} aria-label="Three required current facts and answer coverage"><table><caption>Completeness counts distinct correct required facts, independently of source support or citation placement.</caption><thead><tr><th scope="col">Required current fact</th><th scope="col">Fact ID</th><th scope="col">Present in answer?</th></tr></thead><tbody>{a.required.map(r=><tr key={r.id} data-rag-required={r.id}><th scope="row">{r.text}</th><td>{r.id}</td><td>{r.covered?"Yes":"No"}</td></tr>)}</tbody></table></div><p>A faithful fragment omits required facts. A faithful garden answer can be off-topic. An answer supported by outdated D4 can be well cited but disagree with the current reference. Conversely, a correct reference fact can appear without retrieved support. These scores are separate measurements; none is a complete model-quality verdict.</p></section>
 <section className={styles.evidence} aria-label="RAG conventions and limits"><details><summary>Construction and limits</summary><p>The finite model has five retrieved context bundles, six answer bundles and four citation rules: 120 states. The museum and credits are fictional. Claims are atomic disclosed fact IDs; entailment uses membership in a source’s authored fact list. No search, generation, natural-language inference or real-world fact verification runs. Contradiction versus missing support is not separately graded. The current authored reference requires Tuesday, 10:00 and 4 credits; outdated Monday/09:00 are supported by D4 but do not cover those current facts.</p><p>Context relevance counts question-relevant retrieved documents divided by retrieved documents, with Undefined for no documents. Relevance is not source freshness or truth and this is not rank-aware context precision. Faithfulness counts claims supported by any retrieved source divided by claims made, Undefined for an empty answer. Citation support counts claims with an optional citation that is both retrieved and individually entailing, divided by all claims. Precision uses present citations instead. Empty answers have Undefined coverage and precision; no citations gives Undefined precision and zero citation coverage for nonempty answers. Missing evidence never implies free admission. No fabricated perfect empty-answer score is supplied.</p><p>Matched sources are D1 for day/time, D2 for fee/free, D4 for old day/time and D3 for benches; D2 does not entail free admission. Misplaced cites D3 for all claims. Mixed matches the first two claims and cites D3 thereafter. There is at most one citation per claim; no multi-source joint entailment or redundant-citation evaluation is modeled. These are simplified teaching conventions rather than exact RAGAS or full ALCE metrics. Completeness is distinct correct required facts covered over three; it ignores unsupported extras and is not overall accuracy. Presets restore complete states; Reset/prediction restore Fully supported for the current exercise, free Reset starts Experiment 1.</p><a href="https://aclanthology.org/2024.eacl-demo.16/" target="_blank" rel="noreferrer">RAGAs · Separate evaluation dimensions</a><br/><a href="https://arxiv.org/abs/2305.14627" target="_blank" rel="noreferrer">ALCE · Citation evaluation</a><br/><a href="https://aclanthology.org/2024.tacl-1.38/" target="_blank" rel="noreferrer">Correctness and faithfulness in question answering</a></details></section>
 </LearningPage>;
}
