"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeArea, areaChart, areaModels, type AreaModelId, type AreaView } from "./probability-area-engine";
import { areaBaseline, reachedArea, type AreaState } from "./lesson-state";
import { areaExperiments } from "./learning-experiments";
import styles from "./playground.module.css";
export function ProbabilityAreaPlayground() {
  const [state,setState]=useState<AreaState>(()=>areaBaseline()),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null),[width,setWidth]=useState(640);
  const chartRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const element=chartRef.current;if(!element)return;const update=()=>setWidth(Math.max(200,element.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(element);return()=>observer.disconnect();},[]);
  const a=useMemo(()=>analyzeArea(state.model,state.lower,state.upper),[state.model,state.lower,state.upper]),chart=areaChart(a,state.view,width),experiment=areaExperiments[index],transfer=index===5,reached=!!prediction&&!!experiment&&reachedArea(index,state),complete=reached&&explanation==="0";
  function clear(){setExplanation(null);setTransferAnswer(null);}
  function start(next=index){setIndex(next);setState(areaBaseline(next));setPrediction(null);clear();}
  function edit(patch:Partial<AreaState>){setState(s=>({...s,...patch}));clear();}
  const rail=experiment?<ExperimentRail label={`Experiment ${index+1} of 5`} title={experiment.title} phase={!prediction?0:reached?2:1}>
    {!reached&&<><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="area-prediction" choices={experiment.predictions} value={prediction} onChange={id=>{start();setPrediction(id);}}/><p className={shared.small}>Changing prediction restores this experiment’s starting model, interval and view. Reset restarts it.</p></>}
    {prediction&&!reached&&<p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
    {reached&&<><p role="status" className={shared.observation}>{prediction==="0"?"The observed evidence matches your prediction.":"The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="area-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation}/>{explanation&&!complete&&<p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
    {complete&&<><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={()=>start(index+1)}>{index===4?"Try the transfer check":"Next experiment"}</ExperimentButton></>}
  </ExperimentRail>:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"A new interval, both representations":"Explore other intervals"}>
    {transfer?<><p>Without Guide help, choose Narrow uniform, set Lower bound to 0.1 and Upper bound to 0.4, then select Cumulative (CDF). What is this interval’s probability? Use the endpoint evidence to explain it.</p><ExperimentChoices legend="Transfer explanation" name="area-transfer" choices={[{id:"area",label:"F(0.4) − F(0.1) = 0.8 − 0.2 = 0.6, also width 0.3 × density 2. The density height 2 is not probability."},{id:"height",label:"Probability is 2, because that is the density height."},{id:"cdf",label:"Probability is 0.8, because the upper endpoint CDF already contains the interval."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!reachedArea(5,state)?<p role="status" className={shared.feedback}>First choose Narrow uniform, bounds [0.1, 0.4] and Cumulative (CDF), then read both endpoints.</p>:transferAnswer!=="area"?<p role="status" className={shared.feedback}>Try again. Subtract the cumulative probability below the lower bound, or multiply the selected width by this flat density.</p>:<><ExperimentResult title="Transfer explained">Both methods give 0.6: cumulative difference 0.8 − 0.2 and rectangle area 0.3 × 2. Probability is area, not density height or the upper cumulative value alone.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(6);clear();}}>Explore freely</ExperimentButton></>)}</>:<><p>Move either bound, compare models and switch representations. Bounds outside a model’s values add no density area. Collapsing the interval gives zero probability. Reset returns to Experiment 1.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="PDF, CDF & Probability Area Lab" subtitle="Connect density area to cumulative probability." rail={rail}>
    <LessonToolbar label="Probability models" scenarios={areaModels} selectedId={state.model} onSelect={id=>edit({model:id as AreaModelId})} onReset={()=>start(experiment||transfer?index:0)}/>
    <section className={styles.evidence} aria-label="Interval controls"><p>{a.model.formula}; density is zero outside that interval. Each model has total density area 1. Values of x use an arbitrary unit; density is measured per x-unit.</p><div className={styles.controls}><LessonRangeControl label="Lower bound" value={state.lower} min={-1} max={state.upper} step={.05} help="Cannot exceed Upper bound. Exact editor or keyboard slider; steps of 0.05." onChange={lower=>edit({lower})}/><LessonRangeControl label="Upper bound" value={state.upper} min={state.lower} max={5} step={.05} help="Cannot fall below Lower bound. To shift right, raise this bound first." onChange={upper=>edit({upper})}/></div><LessonToggleGroup label="Probability representation" choices={[{id:"pdf",label:"Density (PDF)"},{id:"cdf",label:"Cumulative (CDF)"}]} value={state.view} onChange={view=>edit({view:view as AreaView})}/></section>
    <section className={styles.evidence} aria-label="Probability chart"><h2>{state.view==="pdf"?"Density area":"Cumulative endpoints"}</h2><p className={styles.legend}>{state.view==="pdf"?"Solid line · density f(x). Shaded region · selected interval probability.":"Solid line · accumulated probability F(x). Thick vertical segment · F(upper) − F(lower)."} Dashed lines mark the selected bounds.</p>
      <div className={styles.chart} ref={chartRef}><svg viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`${a.model.label}, ${state.view==="pdf"?"density":"cumulative probability"}. Interval ${state.lower} to ${state.upper}, probability ${a.mass.toFixed(4)}. Exact endpoint evidence is below.`} data-area-chart data-view={state.view}>
        {chart.yTicks.map(t=><g key={t.value}><line x1={chart.left} x2={chart.width-chart.right} y1={t.y} y2={t.y}/><text x={chart.left-8} y={t.y+4} textAnchor="end">{t.value}</text></g>)}
        {state.view==="pdf"&&<polygon points={chart.polygon} data-density-area/>}
        <polyline points={chart.points} data-distribution/>
        {[chart.lower,chart.upper].map((p,i)=><line key={i} x1={p.x} x2={p.x} y1={chart.top} y2={chart.baseline} data-bound={i===0?"lower":"upper"}/>)}
        {state.view==="cdf"&&<><line x1={chart.left} x2={chart.lower.x} y1={chart.lower.y} y2={chart.lower.y} data-projection/><line x1={chart.left} x2={chart.upper.x} y1={chart.upper.y} y2={chart.upper.y} data-projection/><line x1={chart.difference.x} x2={chart.difference.x} y1={chart.difference.low} y2={chart.difference.high} data-cdf-difference/><circle cx={chart.lower.x} cy={chart.lower.y} r="4"/><circle cx={chart.upper.x} cy={chart.upper.y} r="4"/></>}
        {chart.xTicks.map(t=><text key={t.value} x={t.x} y={chart.height-chart.bottom+19} textAnchor={t.value===-1?"start":t.value===5?"end":"middle"}>{t.value}</text>)}<text x={(chart.left+chart.width-chart.right)/2} y={chart.height-3} textAnchor="middle">Value x</text><text x="4" y="12">{state.view==="pdf"?"Density per x-unit":"Cumulative probability"}</text>
      </svg></div><p>{state.view==="pdf"?"The fixed density scale is 0–2.25 across all models. Density height can exceed 1; shaded area is probability and stays within 0–1.":"F(x) means P(X ≤ x): all density area up through x. Interval probability is the vertical endpoint difference. It is not area under this CDF curve."}</p>
    </section>
    <LessonSummaries label="Interval evidence" summaries={[{label:"Interval probability",color:"#5031dc",value:a.mass.toFixed(4),definition:"Area under the density in these bounds.",formula:"F(upper) − F(lower)"},{label:"F(lower)",color:"#ad4508",value:a.cdfLower.toFixed(4),definition:"Probability at or below the lower bound.",formula:`P(X ≤ ${state.lower})`},{label:"F(upper)",color:"#33486d",value:a.cdfUpper.toFixed(4),definition:"Probability at or below the upper bound.",formula:`P(X ≤ ${state.upper})`}]}/>
    <section className={styles.evidence} aria-label="Exact endpoint evidence"><p className={styles.formula} data-probability>Probability = F({state.upper}) − F({state.lower}) = {a.cdfUpper.toFixed(4)} − {a.cdfLower.toFixed(4)} = {a.mass.toFixed(4)}.</p><h2>Endpoint evidence</h2><table className={styles.table}><caption>Density height and cumulative probability are different quantities.</caption><thead><tr><th scope="col">Bound x</th><th scope="col">Density f(x)</th><th scope="col">Cumulative F(x)</th></tr></thead><tbody>{[[state.lower,a.pdfLower,a.cdfLower],[state.upper,a.pdfUpper,a.cdfUpper]].map(([x,f,c],i)=><tr key={i}><th scope="row">{i===0?"Lower":"Upper"}: {x}</th><td>{f.toFixed(4)}</td><td>{c.toFixed(4)}</td></tr>)}</tbody></table><p className={styles.formula} data-area-construction>Within the model’s values: width {a.width.toFixed(4)} × average density ({a.heightLower.toFixed(4)} + {a.heightUpper.toFixed(4)}) / 2 = area {a.area.toFixed(4)}.</p><p>The selected width inside the model is clipped to its supported values. These flat or linearly rising densities give exact rectangle or trapezoid areas. A collapsed or entirely outside interval has area 0.</p></section>
    <section className={styles.evidence} aria-label="Definitions and model scope"><details><summary>Definitions, formulas and endpoint convention</summary><p>A probability density function (PDF), written f(x), is nonnegative and has total area 1. The cumulative distribution function (CDF), written F(x), equals P(X ≤ x). For each supplied continuous density model, the probability of [lower, upper] is F(upper) − F(lower). Every single point has probability zero; including or excluding endpoints changes no interval probability. This does not apply to discrete point masses.</p><p>Uniform 0–4: F(x) = x/4 within [0, 4]. Rising triangle: F(x) = x²/4 within [0, 2]. Narrow uniform: F(x) = 2x within [0, 0.5]. Each CDF is 0 below its interval and 1 above. Endpoint PDF values use the displayed closed-interval formula; changing the value at a single endpoint would not change areas.</p><p>These are exact teaching distributions. A CDF curve may be shown by closely spaced line segments, but endpoint values and rectangle/trapezoid probabilities are calculated directly from the exact formulas.</p><a href="https://itl.nist.gov/div898/handbook/eda/section3/eda3662.htm" target="_blank" rel="noreferrer">NIST · Uniform distribution</a><br/><a href="https://stat20.berkeley.edu/fall-2025/3-generalization/06-normal-approx/notes.html" target="_blank" rel="noreferrer">Berkeley Stat 20 · Density and cumulative distributions</a></details></section>
  </LearningPage>;
}
