"use client";
import {useMemo,useState} from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import sharedStyles from "@/components/learning-page/learning-page.module.css";
import {analyzeThreshold,type ThresholdAnalysis} from "./confusion-matrix-thresholds-engine";
import {thresholdScenarios} from "./scenario";
import {thresholdDefaults,thresholdExperiments,type ThresholdState} from "./learning-experiments";
import styles from "./playground.module.css";
const scorePercent=(value:number)=>Number((100*value).toFixed(10));
const percent=(value:number|null)=>value===null?"Undefined":`${Number((100*value).toFixed(2))}%`;
const same=(a:ThresholdState,b:ThresholdState)=>a.scenario===b.scenario&&Math.abs(a.threshold-b.threshold)<1e-9;
const titleFor={tp:"True positive",fp:"False positive",fn:"False negative",tn:"True negative"};
function ScorePlot({analysis:a}:{analysis:ThresholdAnalysis}){const x=(value:number)=>56+value*388;return <section className={styles.plot} aria-label="Fixed scores"><h2>Scores stay fixed</h2><p>Circle = actual positive; square = actual negative. A–L identify examples in All 12 decisions. Shading marks predicted positive: score ≥ cutoff, including equality.</p><svg viewBox="0 0 480 230" role="img" aria-label={`Twelve fixed scores in two actual-class lanes. Cutoff ${scorePercent(a.threshold)}%. Exact scores and decisions are listed below.`}><rect x={x(a.threshold)} y={25} width={x(1)-x(a.threshold)} height={135} fill="#f1effc"/><line x1={x(a.threshold)} x2={x(a.threshold)} y1={25} y2={160} stroke="#5031dc" strokeDasharray="5 4"/>{[0,.5,1].map(v=><g key={v}><line x1={x(v)} x2={x(v)} y1={25} y2={170} stroke="#dfe4f4"/><text x={x(v)} y={195} textAnchor="middle">{v*100}</text></g>)}<text x={8} y={64}>+</text><text x={8} y={131}>−</text>{a.examples.map(p=>{const y=p.actual==="positive"?60:126;return <g key={p.id}><title>{`${p.id.toUpperCase()}: ${p.label}, score ${scorePercent(p.score)}%, actual ${p.actual}, ${titleFor[p.bucket]}`}</title><text x={x(p.score)} y={y-14} textAnchor="middle">{p.id.toUpperCase()}</text>{p.actual==="positive"?<circle cx={x(p.score)} cy={y} r={5} fill="#1760db"/>:<rect x={x(p.score)-5} y={y-5} width={10} height={10} fill="#ad4508"/>}</g>})}<text x={250} y={225} textAnchor="middle">Model score (%)</text></svg></section>}
export function ConfusionMatrixThresholdsPlayground(){
 const [state,setState]=useState<ThresholdState>(thresholdDefaults);const [index,setIndex]=useState(0);const [prediction,setPrediction]=useState<string|null>(null);const [explanation,setExplanation]=useState<string|null>(null);const [transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const scenario=thresholdScenarios.find(s=>s.id===state.scenario)??thresholdScenarios[0];const a=useMemo(()=>analyzeThreshold(scenario.examples,state.threshold),[scenario,state.threshold]);const c=a.counts,m=a.metrics;const experiment=thresholdExperiments[index],transfer=index===3;const reached=!!prediction&&!!experiment&&same(state,experiment.target),complete=reached&&explanation===experiment?.correctExplanation;const transferReached=same(state,{scenario:"spam",threshold:.79});
 function clear(){setExplanation(null);setTransferAnswer(null)}function start(next=index){setIndex(next);setState(thresholdExperiments[next]?.baseline??thresholdDefaults);setPrediction(null);clear()}function edit(next:ThresholdState){setState(next);clear()}
 const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="threshold-prediction" explanationName="threshold-explanation"
    onPredict={id=>{start();setPrediction(id)}} onExplain={setExplanation}
    predictionHelp={<>Choosing a prediction restores the experiment’s starting scenario and cutoff.</>} observation={prediction===experiment.correctPrediction?"Your prediction matches the evidence.":"The decisions challenge your prediction. Compare the four counts and metric denominators."}
    onNext={()=>start(index+1)} nextLabel={index===2?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Include a score on the cutoff":"Choose the mistake tradeoff"}>{transfer?<><p>Choose Spam Filter and set Threshold (%) to 79. Password reset has score 79% and actual negative. What is its decision bucket?</p><ExperimentChoices legend="Transfer explanation" name="threshold-transfer" choices={[{id:"fp",label:"False positive: equality is predicted positive, while its actual class is negative. Counts are TP2, FP2, FN3, TN5."},{id:"tn",label:"True negative: only scores strictly greater than the cutoff are positive."},{id:"tp",label:"True positive: the threshold changes its actual class."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!transferReached?<p role="status" className={sharedStyles.feedback}>First choose Spam Filter and set Threshold (%) to 79.</p>:transferAnswer!=="fp"?<p role="status" className={sharedStyles.feedback}>Try again. The rule includes equality; actual negative remains negative.</p>:<><ExperimentResult title="Transfer explained">At 79%, Password reset is a false positive. Precision is 2/4 = 50%; recall is 2/5 = 40%. Raising to 80% excludes this negative and changes FP to TN. A cutoff changes decisions, never actual labels.</ExperimentResult><ExperimentButton onClick={()=>setIndex(4)}>Explore freely</ExperimentButton></>)}</>:<><p>Explore all scenarios and cutoffs. Lowering the cutoff grows the positive queue, but precision depends on which examples cross it. Task costs determine the tradeoff; no single metric supplies a universal best cutoff.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}</ExperimentRail>;
 return <LearningPage title="Confusion Matrix & Thresholds" subtitle="Move the cutoff. Keep scores and actual classes fixed." rail={rail}><LessonToolbar label="Decision scenarios" scenarios={thresholdScenarios} selectedId={scenario.id} onSelect={id=>{const next=thresholdScenarios.find(s=>s.id===id)!;edit({scenario:id,threshold:next.defaultThreshold})}} onReset={()=>start(experiment||transfer?index:0)}/><p className={styles.context}>{scenario.description} Positive decision: {scenario.thresholdLabel}. Actual positive class: {scenario.positiveLabel}; actual negative: {scenario.negativeLabel}. Each preset loads its default cutoff.</p><LessonRangeControl label="Threshold" unit="%" min={5} max={95} step={1} value={Number((state.threshold*100).toFixed(10))} onChange={value=>edit({...state,threshold:value/100})} help="Predict positive when model score is at least the cutoff. Scores use the same percentage scale."/><ScorePlot analysis={a}/>
 <section className={styles.matrix} aria-label="Confusion matrix"><h2>Confusion matrix</h2><table><caption>Predicted rows × actual columns, for all {a.examples.length} examples.</caption><thead><tr><th scope="col">Decision</th><th scope="col">Actual positive</th><th scope="col">Actual negative</th></tr></thead><tbody><tr><th scope="row">Predicted positive<br/><small>Score ≥ {scorePercent(state.threshold)}%</small></th><td><strong>{c.tp}</strong><span>True positive (TP)</span></td><td><strong>{c.fp}</strong><span>False positive (FP)</span></td></tr><tr><th scope="row">Predicted negative<br/><small>Score &lt; {scorePercent(state.threshold)}%</small></th><td><strong>{c.fn}</strong><span>False negative (FN)</span></td><td><strong>{c.tn}</strong><span>True negative (TN)</span></td></tr></tbody></table></section>
 <LessonSummaries label="Decision metrics" summaries={[{label:"Precision",value:percent(m.precision),color:"#1760db",definition:"Among predicted positives, the fraction actually positive.",formula:`TP / (TP + FP) = ${c.tp} / ${m.predictedPositive}`,comparison:m.precision===null?"No predicted positives: zero denominator, not zero precision.":"A stricter cutoff does not guarantee higher precision."},{label:"Recall",value:percent(m.recall),color:"#ad4508",definition:"Among actual positives, the fraction predicted positive.",formula:`TP / (TP + FN) = ${c.tp} / ${m.actualPositive}`,comparison:"On fixed data, raising the cutoff cannot increase recall."},{label:"Positive queue",value:`${m.predictedPositive} / ${a.examples.length}`,color:"#5031dc",definition:"Examples predicted positive at this cutoff.",formula:`TP + FP = ${c.tp} + ${c.fp}`,comparison:"Scores and actual classes remain unchanged."}]}/>
 <section className={styles.optional} aria-label="Supporting decision evidence"><details><summary>All 12 decisions</summary><div className={styles.scroller} tabIndex={0} role="region" aria-label="Scrollable example decisions"><table><caption>Score percentages are rankings, not necessarily calibrated probabilities.</caption><thead><tr><th scope="col">ID / example</th><th scope="col">Score (%)</th><th scope="col">Actual</th><th scope="col">Predicted</th><th scope="col">Bucket</th></tr></thead><tbody>{a.examples.map(p=><tr key={p.id}><th scope="row">{p.id.toUpperCase()} · {p.label}</th><td>{Number((p.score*100).toFixed(2))}</td><td>{p.actual}</td><td>{p.predicted}</td><td>{titleFor[p.bucket]} ({p.bucket.toUpperCase()})</td></tr>)}</tbody></table></div></details><details><summary>More metrics</summary><p>F1: <strong>{percent(m.f1)}</strong>. 2TP / (2TP + FP + FN) = {2*c.tp} / {2*c.tp+c.fp+c.fn}. Zero denominator is undefined; otherwise a zero numerator gives zero, including no predicted positives when actual positives exist.</p><p>Accuracy: <strong>{percent(m.accuracy)}</strong>. (TP + TN) / total = {c.tp+c.tn} / {a.examples.length}. It counts correct positives and negatives, without weighting their different mistake costs.</p></details></section><p className={styles.context}>Metric percentages are rounded to two decimal places. This is a fixed illustrative batch. A score need not be a calibrated probability. Different mistake costs can justify different cutoffs; these examples do not identify an optimal real-world policy.</p><p role="status" aria-live="polite" aria-atomic="true" className={sharedStyles.liveUpdate}>{scenario.label}, cutoff {scorePercent(state.threshold)}%. TP {c.tp}, FP {c.fp}, FN {c.fn}, TN {c.tn}; precision {percent(m.precision)}, recall {percent(m.recall)}; predicted positive {m.predictedPositive}. Scores and actual classes fixed.</p></LearningPage>
}
