"use client";
import { useMemo, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import sharedStyles from "@/components/learning-page/learning-page.module.css";
import { analyzeOverfitting, type OverfittingAnalysis } from "./overfitting-engine";
import { overfittingScenarios } from "./scenario";
import { fitDefaults, fitExperiments, type FitState } from "./learning-experiments";
import styles from "./playground.module.css";
const metric = (value: number) => value === 0 ? "0" : Math.abs(value) < .00001 ? value.toExponential(2) : value.toFixed(5);
const same = (a: FitState,b: FitState) => a.scenario === b.scenario && a.degree === b.degree && Math.abs(a.noise-b.noise)<1e-9;
const pathFor = (points: {x:number;y:number}[],xFor:(x:number)=>number,yFor:(y:number)=>number) => points.map((p,i)=>`${i?"L":"M"}${xFor(p.x).toFixed(3)},${yFor(p.y).toFixed(3)}`).join(" ");
function FitPlot({analysis:a}:{analysis:OverfittingAnalysis}) {
  const xFor=(x:number)=>52+(x+1)/2*402;
  const yFor=(y:number)=>22+(a.plotMaxY-y)/(a.plotMaxY-a.plotMinY)*210;
  return <section className={styles.plotSection} aria-label="Fitted curve"><h2>Fitted curve</h2><p>Training circles determine the fit; held-out squares measure its predictions. The dashed curve is the underlying signal before noise.</p><div className={styles.legend}><span>● Training: {a.trainPoints.length}</span><span>■ Held-out: {a.testPoints.length}</span><span>━ Fitted curve</span><span>┄ Underlying signal</span></div>
    <svg viewBox="0 0 480 280" role="img" aria-label={`Degree ${a.degree} fitted curve with ${a.trainPoints.length} training circles, ${a.testPoints.length} held-out squares and dashed underlying signal. x from −1 to 1; y from ${a.plotMinY} to ${a.plotMaxY}. Point predictions are available below.`}>
      {[a.plotMinY,0,a.plotMaxY].map(y=><g key={y}><line x1={52} x2={454} y1={yFor(y)} y2={yFor(y)} stroke="#dfe4f4"/><text x={44} y={yFor(y)+6} textAnchor="end">{y}</text></g>)}
      {[-1,0,1].map(x=><g key={x}><line x1={xFor(x)} x2={xFor(x)} y1={22} y2={232} stroke="#dfe4f4"/><text x={xFor(x)} y={257} textAnchor="middle">{x}</text></g>)}
      <path d={pathFor(a.curve.map(p=>({x:p.x,y:p.trueY})),xFor,yFor)} fill="none" stroke="#536487" strokeWidth={2} strokeDasharray="7 5"/><path d={pathFor(a.curve,xFor,yFor)} fill="none" stroke="#5031dc" strokeWidth={2.5}/>
      {a.trainPoints.map(p=><circle key={p.id} cx={xFor(p.x)} cy={yFor(p.y)} r={4.5} fill="#1760db" stroke="white" strokeWidth={1}/>)}{a.testPoints.map(p=><rect key={p.id} x={xFor(p.x)-4} y={yFor(p.y)-4} width={8} height={8} fill="#ad4508" stroke="white" strokeWidth={1}/>)}<text x={14} y={140}>y</text><text x={473} y={258}>x</text>
    </svg><p className={styles.caption}>Axes stay fixed across degrees for this scenario and noise: y {a.plotMinY} to {a.plotMaxY}. Changing scenario or noise can change this range. Plot lines join 120 evaluated x positions; exact predictions at every observed point appear below.</p></section>;
}
function LossPlot({analysis:a}:{analysis:OverfittingAnalysis}) {
  const max=Math.max(.00001,...a.lossByDegree.flatMap(p=>[p.trainMse,p.testMse]))*1.1;
  const xFor=(x:number)=>62+(x-1)/11*392;
  const yFor=(y:number)=>24+(1-y/max)*145;
  const points=(field:"trainMse"|"testMse")=>a.lossByDegree.map(p=>({x:p.degree,y:p[field]}));
  return <section className={styles.plotSection} aria-label="Loss by degree"><h2>Loss by polynomial degree</h2><p>Every degree uses the same current points and fitting rule. Read both losses; degree and gap alone do not diagnose overfitting.</p><div className={styles.legend}><span>● Solid: training MSE</span><span>■ Dashed: held-out MSE</span></div><svg viewBox="0 0 480 220" role="img" aria-label={`Training and held-out MSE for degrees 1 through 12, degree ${a.degree} highlighted. Linear vertical scale 0 to ${metric(max)}. Complete values are in All degree losses.`}>
    {[0,max/2,max].map(y=><g key={y}><line x1={62} x2={454} y1={yFor(y)} y2={yFor(y)} stroke="#dfe4f4"/><text x={54} y={yFor(y)+6} textAnchor="end" fontSize={16}>{y===0?"0":y<.001?y.toExponential(1):y.toFixed(2)}</text></g>)}{[1,4,8,12].map(d=><text key={d} x={xFor(d)} y={194} textAnchor="middle">{d}</text>)}
    <line x1={xFor(a.degree)} x2={xFor(a.degree)} y1={24} y2={169} stroke="#5031dc" strokeDasharray="4 4"/><path d={pathFor(points("trainMse"),xFor,yFor)} fill="none" stroke="#1760db" strokeWidth={2}/><path d={pathFor(points("testMse"),xFor,yFor)} fill="none" stroke="#ad4508" strokeWidth={2} strokeDasharray="6 4"/>{a.lossByDegree.map(p=><g key={p.degree}><circle cx={xFor(p.degree)} cy={yFor(p.trainMse)} r={p.degree===a.degree?5:3} fill="#1760db"/><rect x={xFor(p.degree)-3} y={yFor(p.testMse)-3} width={6} height={6} fill="#ad4508"/></g>)}<text x={62} y={16} fontSize={16}>MSE</text><text x={258} y={216} textAnchor="middle">Polynomial degree</text>
  </svg><p className={styles.caption}>The loss scale stays fixed when degree changes. The chart summarizes these two finite sets; it does not guarantee an error on future data.</p></section>;
}
export function OverfittingPlayground() {
  const [state,setState]=useState<FitState>(fitExperiments[0].baseline);
  const [index,setIndex]=useState(0);
  const [prediction,setPrediction]=useState<string|null>(null);
  const [explanation,setExplanation]=useState<string|null>(null);
  const [transferAnswer,setTransferAnswer]=useState<string|null>(null);
  const a=useMemo(()=>analyzeOverfitting(state.scenario,state.degree,state.noise),[state]);
  const experiment=fitExperiments[index];const transfer=index===fitExperiments.length;
  const reached=!!prediction&&!!experiment&&same(state,experiment.target);const complete=reached&&explanation===experiment?.correctExplanation;
  const transferReached=same(state,{scenario:"sparse",degree:10,noise:.34});
  function clearAnswers(){setExplanation(null);setTransferAnswer(null);}
  function start(next=index){setIndex(next);setState(fitExperiments[next]?.baseline??fitDefaults);setPrediction(null);clearAnswers();}
  function edit(patch:Partial<FitState>){setState(current=>({...current,...patch}));clearAnswers();}
  const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="fit-prediction" explanationName="fit-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>Choosing a prediction restores this experiment’s starting data, degree and noise.</>} observation={prediction===experiment.correctPrediction?"Your prediction matches the evidence.":"The two errors challenge your prediction. Compare the same data across degrees."}
    action={<div className={sharedStyles.actionPrompt}><p><strong>Now try it.</strong> {experiment.action}</p><p className={sharedStyles.small}>Reset starts this experiment again.</p></div>}
    onNext={()=>start(index+1)} nextLabel={index===2?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Test the comparison on sparse data":"Compare before labeling"}>
    {transfer?<><p>Choose Sparse Training, set Polynomial degree to 10 and Noise amplitude to 0.34. In All degree losses, compare degrees 4 and 10. Which explanation fits the evidence?</p><ExperimentChoices legend="Transfer explanation" name="fit-transfer" choices={[{id:"diverge",label:"Training MSE falls from about 0.02222 to a tiny positive value; held-out MSE rises from 0.00903 to 0.40228. The more flexible fit generalizes worse on these held-out points."},{id:"degree",label:"Degree 10 is always worse on held-out data, even without looking at losses."},{id:"testfit",label:"The curve was fitted to the training and held-out points together."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!transferReached?<p role="status" className={sharedStyles.feedback}>First choose Sparse Training, set Polynomial degree to 10 and Noise amplitude to 0.34.</p>:transferAnswer!=="diverge"?<p role="status" className={sharedStyles.feedback}>Try again. Compare the two degree rows on the same points; held-out data never enters the fit.</p>:<><ExperimentResult title="Transfer explained">With fewer training examples, a flexible fit can nearly interpolate the training points and still miss held-out points. This example supports overfitting through the error comparison, not a universal degree threshold.</ExperimentResult><ExperimentButton onClick={()=>setIndex(4)}>Explore freely</ExperimentButton></>)}</>:<><p>Try all three scenarios and degrees 1–12. Change noise, then compare errors on the same points before deciding whether extra flexibility helps. A wiggly line or a positive gap alone is not proof.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Overfitting" subtitle="Fit familiar points. Check predictions on held-out points." rail={rail}>
    <LessonToolbar label="Data scenarios" scenarios={overfittingScenarios} selectedId={state.scenario} onSelect={scenario=>edit({scenario})} onReset={()=>start(experiment||transfer?index:0)}/>
    <div className={styles.parameters}><LessonRangeControl label="Polynomial degree" min={1} max={12} step={1} value={state.degree} onChange={degree=>edit({degree})} help="Degree 1 is a straight line; higher degrees allow more flexible curves."/><LessonRangeControl label="Noise amplitude" min={0} max={.45} step={.01} value={state.noise} onChange={noise=>edit({noise})} help="Scales each split’s own fixed deviations from the underlying signal."/></div>
    <FitPlot analysis={a}/><LessonSummaries label="Fit errors" summaries={[
      {label:"Training MSE",value:`≈ ${metric(a.trainMse)}`,color:"#1760db",definition:`Average squared error on ${a.trainPoints.length} points used for fitting.`,formula:"mean((observed y − predicted y)²)",comparison:"Fits minimize training error plus a fixed tiny coefficient penalty."},
      {label:"Held-out MSE",value:`≈ ${metric(a.testMse)}`,color:"#ad4508",definition:`Average squared error on ${a.testPoints.length} points withheld from fitting.`,formula:"Same error formula; different points.",comparison:"Lower here means better predictions on this set."},
      {label:"Held-out − train",value:`≈ ${metric(a.gap)}`,color:"#5031dc",definition:"Difference between the two finite-set errors.",formula:"Held-out MSE − training MSE",comparison:"Negative is possible; a positive gap alone is not proof of overfitting."},
    ]}/><LossPlot analysis={a}/>
    <p className={styles.practical}>These fixed, illustrative splits use different noise patterns and are not an unbiased estimate of future error. In real work, choose complexity on validation data and reserve an untouched test set for final evaluation. Repeatedly choosing from test error leaks evaluation information.</p>
    <section className={styles.optional} aria-label="Supporting fit evidence"><details><summary>All degree losses</summary><div className={styles.scroller} tabIndex={0} role="region" aria-label="Scrollable degree losses"><table><caption>Same points and noise at all degrees. MSE is in squared y units; values are rounded. Scientific notation preserves tiny nonzero errors.</caption><thead><tr><th scope="col">Degree</th><th scope="col">Training MSE</th><th scope="col">Held-out MSE</th></tr></thead><tbody>{a.lossByDegree.map(p=><tr key={p.degree} data-current={p.degree===state.degree}><th scope="row">{p.degree}{p.degree===state.degree?" (current)":""}</th><td>{metric(p.trainMse)}</td><td>{metric(p.testMse)}</td></tr>)}</tbody></table></div></details><details><summary>All point predictions</summary><div className={styles.scroller} tabIndex={0} role="region" aria-label="Scrollable point predictions"><table><caption>Observed y = signal + Noise amplitude × fixed deviation. Residual = observed − predicted. MSE averages the squared residuals within each split.</caption><thead><tr><th scope="col">Split / point</th><th scope="col">x</th><th scope="col">Observed y</th><th scope="col">Predicted y</th><th scope="col">Residual²</th></tr></thead><tbody>{[...a.trainPoints,...a.testPoints].map(p=><tr key={p.id}><th scope="row">{p.split==="train"?"Training":"Held-out"} {Number(p.id.split("-")[1])+1}</th><td>{p.x}</td><td>{metric(p.y)}</td><td>{metric(p.predictedY)}</td><td>{metric(p.residual**2)}</td></tr>)}</tbody></table></div></details><details><summary>How the fit is computed</summary><p>A degree d polynomial is a₀ + a₁x + … + a_d x^d. Only training points determine these coefficients. A fixed tiny penalty makes the fit unique even when coefficients outnumber training examples; its size does not jump with degree. The fitting objective is sum of squared training errors + 10⁻⁷ × (0.1a₀² + a₁² + … + a_d²). MSE displays the average squared prediction error alone, excluding that penalty. Numerical QR fitting avoids unstable normal equations.</p><p>The common illustrative signal is 0.58 sin(π(x + 0.12)) + 0.34x − 0.24x². Each preset keeps its original x positions and fixed train/held-out noise patterns. Noise zero removes deviations, but a finite polynomial need not match this signal exactly. The plotted signal is a teaching reference unavailable for real unknown data.</p></details></section>
    <p role="status" aria-live="polite" aria-atomic="true" className={sharedStyles.liveUpdate}>{a.scenario.label}, degree {state.degree}, noise {state.noise}. Training MSE {metric(a.trainMse)}; held-out MSE {metric(a.testMse)}; held-out minus train {metric(a.gap)}. Only training points fit the curve.</p>
  </LearningPage>;
}
