"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonAction, LessonRangeControl, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeLln, llnChart, llnModels, type LlnModelId } from "./lln-engine";
import { llnBaseline, reachedLln, type LlnState } from "./lesson-state";
import { llnExperiments } from "./learning-experiments";
import styles from "./playground.module.css";
export function LawLargeNumbersPlayground() {
  const [state,setState]=useState<LlnState>(()=>llnBaseline()),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null),[width,setWidth]=useState(640);
  const chartRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const element=chartRef.current;if(!element)return;const update=()=>setWidth(Math.max(200,element.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(element);return()=>observer.disconnect();},[]);
  const analysis=useMemo(()=>analyzeLln(state.model,state.count,state.seed),[state.model,state.count,state.seed]),chart=llnChart(analysis,width),experiment=llnExperiments[index],transfer=index===5,reached=!!prediction&&!!experiment&&reachedLln(index,state),complete=reached&&explanation==="0";
  function clear(){setExplanation(null);setTransferAnswer(null);}
  function start(next=index){setIndex(next);setState(llnBaseline(next));setPrediction(null);clear();}
  function edit(patch:Partial<LlnState>){setState(s=>({...s,...patch}));clear();}
  const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 5`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="lln-prediction" explanationName="lln-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>A different prediction restores the starting model, count and seed. Reset restarts this experiment. Counts reveal a prefix; they do not resample it.</>} observation={prediction==="0"?"The observed evidence matches your prediction.":"The evidence challenges your prediction."}
    onNext={()=>start(index+1)} nextLabel={index===4?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"An imbalance is not a debt":"Explore other prefixes"}>
    {transfer?<><p>Without Guide help, choose Fair coin, set Run seed to 3209 and Number of draws to 1000. Read the observed average and model expectation. Does the imbalance change the ideal next-head probability or require an exactly balanced finite run?</p><ExperimentChoices legend="Transfer explanation" name="lln-transfer" choices={[{id:"independent",label:"This run averages 0.495. Under the independent fair-coin model, the next-head probability remains 0.5; no balancing outcome or exact finite average is guaranteed."},{id:"debt",label:"There are fewer heads than expected, so the next flip owes a head and must balance the count."},{id:"exact",label:"Any 1000-draw fair-coin run must average exactly 0.5."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!reachedLln(5,state)?<p role="status" className={shared.feedback}>First choose Fair coin, seed 3209 and 1000 draws, then read the actual record.</p>:transferAnswer!=="independent"?<p role="status" className={shared.feedback}>Try again. Independence keeps the source probabilities fixed. LLN concerns the long-run average, not compensating future outcomes or exact finite balance.</p>:<><ExperimentResult title="Transfer explained">Seed 3209 gives 495 heads in 1000 draws. A finite imbalance does not create a debt: the ideal fair coin keeps probability 0.5 for its next head.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(6);clear();}}>Explore freely</ExperimentButton></>)}</>:<><p>Choose any model, reveal more or fewer draws of one seed, or compare another seed. Next draw adds one to the shown prefix. All three models keep their own fixed probabilities; a finite average can be above or below its target.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Law of Large Numbers Simulator" subtitle="Extend one run and see what averaging changes." rail={rail}>
    <LessonToolbar label="Probability models" scenarios={llnModels} selectedId={state.model} onSelect={id=>edit({model:id as LlnModelId})} onReset={()=>start(experiment||transfer?index:0)}/>
    <section className={shared.evidence} aria-label="Simulation controls"><p data-model-description>{state.model==="die"?"Each integer face 1–6 has probability 1/6. Expectation: 3.5.":`Heads = 1, tails = 0. The fixed model’s probability of the next head is ${analysis.expectation}, regardless of previous outcomes.`} The ideal model assumes independent draws from this same fixed distribution. The seeded simulation makes the examples reproducible.</p>
      <div className={shared.controlGrid}><LessonRangeControl label="Number of draws" value={state.count} min={1} max={10000} step={1} help="Reveal a longer or shorter prefix of this run; this does not resample it." onChange={count=>edit({count})}/><LessonRangeControl label="Run seed" value={state.seed} min={1} max={9999} step={1} help="Reproduce another sequence while keeping the model probabilities fixed." onChange={seed=>edit({seed})}/></div>
      <div className={styles.actions}><LessonAction disabled={state.count===10000} onClick={()=>{setState(s=>({...s,count:Math.min(10000,s.count+1)}));clear();}}>Next draw</LessonAction><p role="status" data-run-status>Showing the first {state.count} draws of {analysis.model.label}, seed {state.seed}.</p></div>
    </section>
    <section className={shared.evidence} aria-label="Running average"><h2>Running average</h2><div className={styles.legend}><span>Solid line · observed average</span><span>Dashed line · model expectation {analysis.expectation}</span></div>
      <div className={styles.chart} ref={chartRef}><svg viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`${analysis.model.label}, ${state.count} draws, seed ${state.seed}. Last average ${analysis.last.mean.toFixed(4)}, expected ${analysis.expectation}. Exact checkpoints are below.`} data-lln-chart>
        {chart.yTicks.map(t=><g key={t.value}><line x1={chart.left} x2={chart.width-chart.right} y1={t.y} y2={t.y}/><text x={chart.left-8} y={t.y+4} textAnchor="end">{t.value}</text></g>)}
        <line x1={chart.left} x2={chart.width-chart.right} y1={chart.expectedY} y2={chart.expectedY} data-expected/>
        <polyline points={chart.points} data-running-mean/><circle cx={chart.last.x} cy={chart.last.y} r="4"/>
        {chart.xTicks.map(t=><text key={t.n} x={t.x} y={chart.height-chart.bottom+19} textAnchor={t.n===1?"start":t.n===state.count?"end":"middle"}>{t.n}</text>)}<text x={(chart.left+chart.width-chart.right)/2} y={chart.height-3} textAnchor="middle">Number of draws</text><text x="4" y="12">Average</text>
      </svg></div><p>Each point is total / draws so far; the line joins discrete draw counts. A longer prefix need not be closer after every draw, and a finite run need not reach the expected value exactly.</p>
      <p className={shared.math} data-recent-values>Recent individual values, draws {Math.max(1,state.count-7)}–{state.count}: {analysis.draws.slice(-8).map(d=>d.value).join(", ")}. Newest value: {analysis.last.value}.</p>
    </section>
    <LessonSummaries label="Observed versus model" summaries={[{label:"Observed average",color:"#5031dc",value:analysis.last.mean.toFixed(4),definition:"Average of this shown prefix.",formula:`${analysis.last.total} / ${state.count}`},{label:"Model expectation",color:"#ad4508",value:analysis.expectation.toFixed(4),definition:"Fixed probability-weighted mean.",formula:analysis.model.formula},{label:"Absolute average gap",color:"#33486d",value:analysis.averageGap.toFixed(4),definition:"Distance from the model mean.",formula:"|observed average − expectation|"}]}/>
    <section className={shared.evidence} aria-label="Exact evidence"><p className={shared.math} data-total-gap>Absolute total gap = |{analysis.last.total} − {state.count} × {analysis.expectation}| = {analysis.totalGap.toFixed(4)}. Divide by {state.count} to get the average gap {analysis.averageGap.toFixed(4)}.</p><h2>Exact checkpoints</h2><table className={`${shared.dataTable} ${styles.table}`} data-checkpoints><caption>Selected prefixes of the same run. Changing only Number of draws retains every earlier value.</caption><thead><tr><th scope="col">Draws</th><th scope="col">Total</th><th scope="col">Average</th><th scope="col">Average gap</th></tr></thead><tbody>{analysis.checkpoints.map(d=><tr key={d.n}><th scope="row">{d.n}</th><td>{d.total}</td><td>{d.mean.toFixed(4)}</td><td>{Math.abs(d.mean-analysis.expectation).toFixed(4)}</td></tr>)}</tbody></table></section>
    <section className={shared.evidence} aria-label="Law and simulation scope"><details><summary>Model assumptions and what LLN says</summary><p>The model holds the same probabilities for every draw and assumes independence: past results do not alter the next result’s distribution. All three examples have bounded values, hence a finite mean. For independent draws from a fixed distribution with a finite mean, the chance of the average differing from that mean by more than any fixed positive tolerance tends to zero as the draw count grows.</p><p>This is an asymptotic statement, not a finite guarantee, a claim of improvement at every step, or a demand that the next result balance earlier ones. It concerns the average rather than the sum or a single outcome. Dependent draws, changing distributions or a source without a finite mean require other analysis.</p><table className={`${shared.dataTable} ${styles.table}`}><caption>Current fixed distribution · {analysis.model.label}</caption><thead><tr><th scope="col">Value</th><th scope="col">Probability</th></tr></thead><tbody>{analysis.model.values.map((value,i)=><tr key={value}><th scope="row">{value}</th><td>{state.model==="die"?"1/6":analysis.model.probabilities[i]}</td></tr>)}</tbody></table><a href="https://www.stat.berkeley.edu/users/stark/SticiGui/Text/expectation.htm" target="_blank" rel="noreferrer">Berkeley SticiGui · The Long Run and the Expected Value</a></details>
      <details><summary>How reproducible simulation works</summary><p>Run seed starts a deterministic 32-bit pseudorandom generator. Each generated uniform value maps to a coin result or an integer die face. Raising Number of draws extends the same prefix. Lowering it reveals an earlier prefix; it is not fresh sampling. Changing model keeps the underlying uniform stream but remaps outcomes, so displayed runs still use one fixed distribution.</p><p>Different seeds can produce different averages, and sometimes equal ones. These finite pseudorandom examples illustrate an ideal independent model; they do not prove randomness, independence, or the law of large numbers. They are not a game prediction tool.</p></details></section>
  </LearningPage>;
}
