"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeSimpson, simpsonChart, simpsonGap, simpsonPreset, simpsonPresetId, simpsonPresets, simpsonRate, type SimpsonState } from "./simpson-engine";
import { reachedSimpson, simpsonBaseline } from "./lesson-state";
import { simpsonExperiments } from "./learning-experiments";
import styles from "./playground.module.css";

export function SimpsonPlayground() {
  const [state, setState] = useState(() => simpsonBaseline()), [index, setIndex] = useState(0);
  const [prediction, setPrediction] = useState<string | null>(null), [explanation, setExplanation] = useState<string | null>(null), [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const [width, setWidth] = useState(640), chartRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const element = chartRef.current; if (!element) return; const update = () => setWidth(Math.max(200, element.getBoundingClientRect().width)); update(); const observer = new ResizeObserver(update); observer.observe(element); return () => observer.disconnect(); }, []);
  const a = useMemo(() => analyzeSimpson(state), [state]), chart = simpsonChart(a, width), experiment = simpsonExperiments[index], transfer = index === 3;
  const reached = !!prediction && !!experiment && reachedSimpson(index, state), complete = reached && explanation === "0";
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function start(next = index) { setIndex(next); setState(simpsonBaseline(next)); setPrediction(null); clear(); }
  function edit(patch: Partial<SimpsonState>) { setState(s => ({ ...s, ...patch })); clear(); }
  const rail = experiment ? <GuidedExperiment label={`Experiment ${index + 1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="simpson-prediction" explanationName="simpson-explanation"
    onPredict={id => { start(); setPrediction(id); }} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores this experiment’s starting shares and view. Reset restarts it.</>} observation={prediction === "0" ? "The observed evidence matches your prediction." : "The evidence challenges your prediction."}
    onNext={() => start(index + 1)} nextLabel={index === 2 ? "Try the transfer check" : "Next experiment"} /> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Rebuild a new overall comparison" : "Inspect task mixes"}>
    {transfer ? <><p>Without Guide help, set Easy share A to 30 and Easy share B to 70, then choose By difficulty. Before checking an answer, use the weights and counts to reconstruct both overall rates and their gap. Explain whether the table proves causation.</p>
      {reachedSimpson(3, state) && <><ExperimentChoices legend="Transfer explanation" name="simpson-transfer" choices={[
        { id: "weighted", label: "A has 27 easy + 21 hard successes = 48%; B has 56 easy + 6 hard = 62%. The overall gap is −14 points even though A leads by 10 points in each difficulty. Different weights explain the reversal; the table alone does not prove a causal effect." },
        { id: "average", label: "A is always 60% and B 50% overall because every overall rate is the plain average of its subgroup rates." },
        { id: "causal", label: "The grouped advantage proves A causes exactly 10 percentage points more success in every setting." },
      ]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (transferAnswer !== "weighted" ? <p role="status" className={shared.feedback}>Try again. Use each algorithm’s own easy and hard shares. A weighted association is not an intervention or proof of causation.</p> : <><ExperimentResult title="Transfer explained">The new mixes give A 48/100 and B 62/100, a −14-point overall gap. A still leads within both difficulty groups. Reconstructing the different weights explains the arithmetic; a causal interpretation needs evidence and assumptions beyond this table.</ExperimentResult><ExperimentButton onClick={() => { setIndex(4); clear(); }}>Explore freely</ExperimentButton></>)}</>}
    </> : <><p>Change either easy share, switch views and inspect counts together. Each algorithm always keeps 100 trials; a subgroup with no trials has no observed rate. Reset returns to Experiment 1.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Simpson's Paradox & Confounding Lab" subtitle="Change task mixes; compare grouped and overall success." rail={rail}>
    <LessonToolbar scenarios={simpsonPresets} selectedId={simpsonPresetId(state)} onSelect={id => { setState(s => simpsonPreset(id, s.view)); clear(); }} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={shared.evidence} aria-label="Task mix and success comparison"><h2>Your comparison</h2><p>Constructed toy counts: 100 trials per algorithm, not real data or random samples. Each trial is an easy or hard task. Changing a mix constructs new counts at fixed success rates.</p><LessonToggleGroup label="Comparison view" choices={[{ id: "combined", label: "Combined" }, { id: "grouped", label: "By difficulty" }]} value={state.view} onChange={view => edit({ view: view as SimpsonState["view"] })} />
      <p role="status" className={shared.math} data-simpson-status>Overall A {simpsonRate(a.groups[0].rate)} · B {simpsonRate(a.groups[1].rate)} · A − B = {simpsonGap(a.gap)}. {a.shared < 2 ? "Both difficulty groups are not jointly represented; no full two-group comparison." : state.view === "grouped" ? a.reversal ? "Reversal: A leads within both groups, B leads overall." : "A does not trail overall; no reversal." : ""}</p>
      <div className={styles.chart} ref={chartRef}><svg data-simpson-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`${state.view === "combined" ? "Combined" : "By difficulty"} success rates on a fixed 0 to 100 percent scale. Rows label Algorithms A and B. Bars show successes divided by trials. Absent groups have no bar; equivalent current counts and rates follow below.`}>
        {chart.ticks.map(t => <g key={t.text}><line x1={t.x} x2={t.x} y1="28" y2={chart.baseline} /><text x={t.x} y={chart.baseline + 20} textAnchor="middle">{t.text}</text></g>)}
        {chart.headings.map(h => <text data-heading key={h.text} x={chart.left} y={h.y}>{h.text}</text>)}
        {chart.rows.map(r => <g key={r.id} data-comparison-row={r.id}><text x="8" y={r.y + 4}>{r.algorithm}</text>{r.rate !== null ? <><rect data-rate-bar x={r.x} y={r.y - 12} width={r.barWidth} height="24" fill={r.algorithm === "A" ? "#5031dc" : "#087c78"} /><text data-rate-label x={r.labelX} y={r.y - 2}>{simpsonRate(r.rate)}</text><text data-count-label x={r.labelX} y={r.y + 16}>{r.success}/{r.total}</text></> : <text x={r.labelX} y={r.y + 4}>No observations</text>}</g>)}
      </svg></div>
      <div className={shared.controlGrid}><LessonRangeControl label="Easy share A" value={state.easyA} min={0} max={100} step={10} unit="%" help={`Algorithm A keeps 100 total trials. Hard share A is ${100 - state.easyA}%.`} onChange={easyA => edit({ easyA })} /><LessonRangeControl label="Easy share B" value={state.easyB} min={0} max={100} step={10} unit="%" help={`Algorithm B keeps 100 total trials. Hard share B is ${100 - state.easyB}%.`} onChange={easyB => edit({ easyB })} /></div>
      <h2>How the rates are constructed</h2><p className={shared.math} data-simpson-weights>A: {state.easyA}% × 90% + {100 - state.easyA}% × 30% = {simpsonRate(a.groups[0].rate)}.<br />B: {state.easyB}% × 80% + {100 - state.easyB}% × 20% = {simpsonRate(a.groups[1].rate)}.</p><p>These are fixed construction rates weighted by each algorithm’s own task mix. A zero-weight term is an assumption contributing zero; it is not an observed rate for an absent group.</p>
      <div data-simpson-group-evidence>{(["easy", "hard"] as const).map(key => <p key={key}><strong>{key === "easy" ? "Easy" : "Hard"} observed:</strong> {a.groups.map(g => `${g.id} ${g[key].success}/${g[key].total} = ${simpsonRate(g[key].rate)}`).join(" · ")}. {a.groups.every(g => g[key].total > 0) ? "A − B = +10 percentage points." : "Within-group gap undefined: both algorithms need trials here."}</p>)}</div>
    </section>
    <LessonSummaries label="Overall and within-group comparison" summaries={[
      { label: "Overall gap", color: "#5031dc", value: simpsonGap(a.gap), definition: "Difference of overall success percentages.", formula: "A minus B · pp = percentage points" },
      { label: "Within-group gap", color: "#087c78", value: a.shared ? "+10 pp" : "Undefined", definition: a.shared ? `Same gap in ${a.shared} jointly represented difficulty ${a.shared === 1 ? "group" : "groups"}.` : "No difficulty has trials for both algorithms.", formula: "A subgroup rate minus B subgroup rate", comparison: a.shared < 2 ? "An absent group has no observed rate, not a 0% success rate." : "Unequal task weights can reverse or amplify the overall gap." },
    ]} />
    <section className={shared.evidence} aria-label="Count evidence and causal limits"><p>Confounding could occur if difficulty influences which algorithm is assigned and whether a task succeeds. Difficulty is conceptualized before evaluation here. The counts alone do not establish that causal story, rule out other confounders or prove an algorithm’s causal effect. Grouping is not always the appropriate adjustment; causal context matters.</p><details><summary>Counts by difficulty</summary><div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="Success and trial count evidence"><table><caption>Current constructed counts. Each algorithm keeps 100 total trials in either view.</caption><thead><tr>{["Algorithm", "Difficulty", "Successes", "Trials", "Observed rate"].map(h => <th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{a.groups.flatMap(g => (["easy", "hard", "overall"] as const).map(key => { const r = key === "overall" ? { success: g.success, total: 100, rate: g.rate } : g[key]; return <tr key={`${g.id}-${key}`}><th scope="row">{g.id} · {key}</th><td>{key}</td><td>{r.success}</td><td>{r.total}</td><td>{simpsonRate(r.rate)}</td></tr>; }))}</tbody></table></div></details><details><summary>Conventions and sources</summary><p>Overall success = (easy successes + hard successes)/100. An observed subgroup rate is successes/subgroup trials and is undefined when that denominator is zero. Changing easy shares in steps of 10 keeps all constructed success counts integral. The chart always maps 0–100% to the same scale; switching views preserves counts. Both percentages and percentage-point gaps are shown exactly for this finite model.</p><p>Simpson’s reversal concerns different aggregate and within-group associations. It does not by itself determine which comparison has a causal interpretation, mean that every grouping is justified, or imply that adjusting every variable removes bias. This page supplies no causal estimator, real algorithm benchmark, significance test or automatic correction.</p><a href="https://www.stat.berkeley.edu/~stark/SticiGui/Text/experiments.htm" target="_blank" rel="noreferrer">Berkeley · Weighted comparisons and confounding</a><br /><a href="https://ftp.cs.ucla.edu/pub/stat_ser/r414.pdf" target="_blank" rel="noreferrer">Pearl · Understanding Simpson’s paradox and causal context</a></details></section>
  </LearningPage>;
}
