"use client";
import { useMemo, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSelect, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzePosition, editPositionStart, positionBaseline, positionModes, positionNumber as number, positionOrders, positionPresetId, positionQueries, positionScenarios, positionScoreX as x, samePosition, type PositionMode, type PositionState, type PositionToken } from "./position-engine";
import { positionExperiments } from "./learning-experiments";
import { reachedPosition } from "./lesson-state";
import styles from "./playground.module.css";

export function PositionPlayground() {
  const [state, setState] = useState<PositionState>(positionBaseline);
  const [index, setIndex] = useState(0), [prediction, setPrediction] = useState<string | null>(null), [explanation, setExplanation] = useState<string | null>(null), [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const a = useMemo(() => analyzePosition(state), [state]), experiment = positionExperiments[index], transfer = index === 3;
  const reached = !!prediction && !!experiment && reachedPosition(index, state), complete = reached && explanation === "0";
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function start(next = index) { setIndex(next); setState(positionBaseline()); setPrediction(null); clear(); }
  function edit(next: PositionState) { if (!samePosition(state, next)) { setState(next); clear(); } }
  const rail = experiment ? <GuidedExperiment label={`Experiment ${index + 1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="position-prediction" explanationName="position-explanation"
    onPredict={id => { start(); setPrediction(id); }} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores No position. Reset restarts this experiment.</>} observation={prediction === "0" ? "The evidence matches your prediction." : "The evidence challenges your prediction."}
    onNext={() => start(index + 1)} nextLabel={index === 2 ? "Try the transfer check" : "Next experiment"} /> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Change order, then shift together" : "Explore identity and position"}>
    {transfer ? <><p>Without Guide help, choose Rotate Q / K. Set Token order to B A C, Query token to B and Start position to 2, in either order. Compare B’s per-key scores with the A B C at start 0 reference. Which differences come from changed relative offsets, and which do not come from the common shift?</p>{reachedPosition(3, state) && <><ExperimentChoices legend="Transfer explanation" name="position-transfer" choices={[
      { id: "relative", label: "B is now at position 2; A and C are at 3 and 4. Relative offsets from B are +1,0,+2 for keys A,B,C, giving raw scores sin(1)≈0.841471,1,−sin(2)≈−0.909297. Reordering changes the A/C scores versus ABC; the common start shift alone would preserve them. RoPE keeps unit norms but does not guarantee language understanding or monotonic score decay." },
      { id: "absolute", label: "The new start position causes every rotary score to change, regardless of the token order or relative offsets." },
      { id: "weight", label: "B’s self-score 1 proves an attention probability of 1 and guaranteed use of its value." },
    ]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (transferAnswer !== "relative" ? <p role="status" className={shared.feedback}>Try again. Subtract the selected query’s position from each key position. Reordering changes those offsets; a common shift does not. Raw dot products are not attention probabilities.</p> : <><ExperimentResult title="Transfer explained">Rotary dot products combine content and relative position. Common shifts preserve offsets; reorders need not. These toy scores demonstrate a mechanism, not learned language ability.</ExperimentResult><ExperimentButton onClick={() => { setIndex(4); clear(); }}>Explore freely</ExperimentButton></>)}</>}</> : <><p>Try all six Token order choices, all three Position signal rules and Query token identities, and Start position 0–4. No signal ignores positions. Rotary preserves unit lengths and common-shift scores for any fixed order. Absolute can change lengths and scores. The reference always uses A B C at start 0 with the same mode/query; changing both order and start compares both factors.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  const vector = (v: readonly number[]) => `(${v.map(number).join(", ")})`;
  return <LearningPage title="Positional Encoding & Token Order" subtitle="Rearrange tokens. Compare identity with position signals." rail={rail}>
    <LessonToolbar scenarios={positionScenarios} selectedId={positionPresetId(state)} onSelect={id => edit(positionBaseline(id as PositionMode))} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={shared.evidence} aria-label="Position signals and raw query-key scores"><h2>Your dataset</h2><p>Three authored identities have fixed two-number vectors: A=(1,0), B=(0,1), C=(−1,0). Positions start at zero. Query token selects an identity and follows it when reordered. These vectors do not represent learned word meanings. No mask, attention weights or model outputs run here.</p><ol className={styles.slots} aria-label="Current token positions" start={0}>{a.slots.map(slot => <li key={slot.position} data-position-slot={slot.position}>Position {slot.position}<strong>{slot.token}</strong></li>)}</ol>
      <h3>Query {state.query}: raw dot scores with each key</h3><p className={shared.small}>Purple bar / zero dot: current score. Gray dashed tick: A B C at start 0 reference, using the same Position signal and Query token. Signed raw scores are unscaled dot products: multiply matching Q/K coordinates, then add. They are not probabilities or attention weights.</p>
      <div className={styles.chart} tabIndex={0} role="region" aria-label="Signed score comparison chart; exact values in the token table"><svg viewBox="0 0 600 220" aria-hidden="true">{[-4,-3,-2,-1,0,1,2,3,4].map(v => <g key={v}><line x1={x(v)} x2={x(v)} y1={15} y2={178} stroke={v === 0 ? "#536487" : "#dfe4f4"} /><text x={x(v)} y={202} textAnchor="middle">{v}</text></g>)}{a.rows.map((row, k) => { const score = a.scores[k]!, ref = a.reference[k]!, y = 40 + k * 55; return <g key={row.token} data-position-chart={row.token}><text x={12} y={y + 5}>Key {row.token}</text><line x1={90} x2={490} y1={y} y2={y} stroke="#dfe4f4" />{Math.abs(score) > 1e-12 ? <rect data-position-bar x={Math.min(x(0),x(score))} y={y - 6} width={Math.abs(x(score)-x(0))} height={12} fill="#5031dc" /> : <circle data-position-zero cx={x(0)} cy={y} r={4} fill="#5031dc" />}<line data-position-ref x1={x(ref)} x2={x(ref)} y1={y - 12} y2={y + 12} stroke="#536487" strokeWidth={2} strokeDasharray="3 2" /><text data-position-score x={510} y={y + 5}>{number(score)}</text></g>; })}</svg></div>
      <div className={shared.controlGrid}><LessonSelect label="Token order" choices={positionOrders} value={state.order} onChange={order => edit({ ...state, order })} /><div><h3>Position signal</h3><LessonToggleGroup label="Position signal" choices={positionModes} value={state.mode} onChange={mode => edit({ ...state, mode: mode as PositionMode })} /></div><LessonSelect label="Query token" choices={positionQueries} value={state.query} onChange={query => edit({ ...state, query: query as PositionToken })} /><LessonRangeControl label="Start position" value={state.start} min={0} max={4} step={1} help="Shift every zero-based position by the same amount; token order and identity stay fixed." onChange={v => edit(editPositionStart(state,v))} /></div>
      <p role="status" data-position-rule className={shared.math}>{state.mode === "none" ? "No signal: Q and K use unchanged token vectors." : state.mode === "absolute" ? "Absolute: add p=(sin(position), cos(position)) to each base vector, then use fixed identity projections for Q/K." : "Rotary: rotate projected Q and K by position radians. R(p)(x,y)=(cos(p)x−sin(p)y, sin(p)x+cos(p)y)."}</p><p className={shared.small}>A radian is an angle unit. Sine and cosine provide the shown position coordinates. These are two-dimensional, one-frequency examples; learned query/key projections are replaced with fixed identity projections. All actual control/scenario changes clear stale explanations and transfer answers; reapplying the same state preserves them.</p>
    </section>
    <LessonSummaries label="Position and reference-score comparison" summaries={[
      { label: "Query position", color: "#5031dc", value: String(a.queryRow.position), definition: "Selected token’s actual zero-based position.", formula: "start position + slot index", comparison: `Query ${state.query} has current Q vector ${vector(a.queryRow.vector)}.` },
      { label: "Changed scores", color: "#087c78", value: String(a.changed), definition: "How many per-key scores differ from reference.", formula: "compare same key identity, mode and query", comparison: "Reference fixes A B C at start 0. A 10⁻¹² tolerance handles floating arithmetic." },
      { label: "Largest difference", color: "#ad4508", value: number(a.maxDifference), definition: "Maximum absolute raw-score difference.", formula: "max |current score − reference score|", comparison: "Changing both order and start compares both factors. Display rounding is not calculation." },
    ]} />
    <section className={shared.evidence} aria-label="Exact position vectors and scores"><h2>Follow identity through the signal</h2><p>Rows stay keyed by token identity so a reorder is easy to compare. Absolute adds the position’s sine/cosine pair; Rotary rotates Q/K instead of adding a vector. Each raw score uses the selected query’s Q and that row’s K. Fixed identity projections make Q and K equal for the same token here; real learned projections need not.</p><div className={`${shared.tableScroll} ${styles.table}`} tabIndex={0} role="region" aria-label="Exact token positions, Q/K vectors and unscaled scores"><table><caption>Current query {state.query} · {state.mode} · Order {state.order.split("").join(" ")} · Start {state.start}. Reference: A B C at start 0, same mode and query. Six-decimal display; computation uses unrounded values.</caption><thead><tr>{["Key token","Position","Base vector","Q / K vector","Vector length","Raw score","Reference score","Difference"].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.rows.map((row,k) => <tr key={row.token} data-position-row={row.token} aria-current={row.token === state.query ? "true" : undefined}><th scope="row">{row.token}</th><td>{row.position}</td><td>{vector(row.base)}</td><td>{vector(row.vector)}</td><td>{number(row.norm)}</td><td>{number(a.scores[k]!)}</td><td>{number(a.reference[k]!)}</td><td>{number(a.differences[k]!)}</td></tr>)}</tbody></table></div></section>
    <section className={shared.evidence} aria-label="Position construction and limits"><details><summary>Construction and limits</summary><p>All six permutations contain the same three token identities once. Start position 0–4 gives three slots at start, start+1 and start+2. The query follows its selected identity. No signal leaves the base vectors unchanged. Absolute adds (sin(p),cos(p)) in this single sine/cosine pair, then applies identity query/key projections. Rotary applies R(p) to the projected Q and K; this is a 2D RoPE example at one radian per position, not an addition to the token embedding. Full models use many dimensions, frequencies and learned projections.</p><p>For Rotary, Q at position m dotted with K at n equals baseQ dotted with R(n−m)baseK. A common shift preserves n−m and therefore the score for fixed content/order. Rotation preserves vector length; all raw unit vectors here have rotary length 1 and self-score 1. Absolute addition need not preserve length or scores after a shift. Rotary scores combine content and offsets and can oscillate; this demo makes no monotonic distance-decay claim.</p><p>No signal gives permutation-invariant per-token pair scores in this isolated unmasked, content-only calculation. Position-indexed vectors still move with the permutation. Masks and other position signals can convey order; do not generalize this result to every model without this particular encoding. The reference fixes both order A B C and start 0, so changing both controls compares both factors. Presets restore all controls to A B C, start 0, query A in the selected rule. Reset/predictions restore No position for the current experiment; free Reset starts Experiment 1.</p><p>Raw dot scores are unscaled, can be negative or exceed 1, and are bounded by −4..4 here because the largest encoded length is 2. No softmax, probabilities, attention-weighted values, model output, tokenizer, training, semantic answer or context-length extrapolation is supplied. Position signals make order information available; they do not prove learned language understanding. Values smaller than 10⁻¹² display as zero; Changed scores uses that tolerance, not six-decimal rounded equality.</p><a href="https://proceedings.neurips.cc/paper_files/paper/2017/file/3f5ee243547dee91fbd053c1c4a845aa-Paper.pdf" target="_blank" rel="noreferrer">Attention Is All You Need · Absolute sinusoidal encoding</a><br /><a href="https://arxiv.org/html/2104.09864v5" target="_blank" rel="noreferrer">RoFormer · Rotary query/key encoding and relative position</a></details></section>
  </LearningPage>;
}
