"use client";
import { useEffect, useMemo, useRef, useState, type PointerEvent } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonAction, LessonRangeControl, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeLine, lineChart, lineDragValue, lineNumber as number, linePointerY, linePresets, lineSigned, type LineDrag, type LineScenario, type LineState } from "./line-engine";
import { lineBaseline, reachedLine } from "./lesson-state";
import { lineExperiments } from "./learning-experiments";
import styles from "./playground.module.css";

export function LinePlayground() {
  const [state, setState] = useState(() => lineBaseline()), [index, setIndex] = useState(0);
  const [prediction, setPrediction] = useState<string | null>(null), [explanation, setExplanation] = useState<string | null>(null), [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const [width, setWidth] = useState(640), chartRef = useRef<HTMLDivElement>(null), drag = useRef<LineDrag | null>(null);
  useEffect(() => { const element = chartRef.current; if (!element) return; const update = () => setWidth(Math.max(200, element.getBoundingClientRect().width)); update(); const observer = new ResizeObserver(update); observer.observe(element); return () => observer.disconnect(); }, []);
  const a = useMemo(() => analyzeLine(state), [state]), chart = lineChart(a, width), experiment = lineExperiments[index], transfer = index === 3, example = a.points[2];
  const reached = !!prediction && !!experiment && reachedLine(index, state), complete = reached && explanation === "0";
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function start(next = index) { setIndex(next); setState(lineBaseline(next)); setPrediction(null); drag.current = null; clear(); }
  function edit(patch: Partial<LineState>) { setState(s => ({ ...s, ...patch })); clear(); }
  function pointerStart(event: PointerEvent<SVGSVGElement>) {
    if (event.button !== 0) return;
    const rect = event.currentTarget.getBoundingClientRect(), px = (event.clientX - rect.x) / rect.width * chart.width, py = (event.clientY - rect.y) / rect.height * chart.height, line = chart.own;
    const dx = line.x2 - line.x1, dy = line.y2 - line.y1, t = Math.max(0, Math.min(1, ((px - line.x1) * dx + (py - line.y1) * dy) / (dx * dx + dy * dy)));
    const mode = Math.hypot(px - line.x1, py - line.y1) <= 18 ? "intercept" : Math.hypot(px - line.x2, py - line.y2) <= 18 ? "slope" : Math.hypot(px - line.x1 - t * dx, py - line.y1 - t * dy) <= 12 ? "body" : null;
    if (!mode) return;
    event.preventDefault(); drag.current = { mode, slope: state.slope, intercept: state.intercept, startY: linePointerY(event.clientY, rect, chart) }; event.currentTarget.setPointerCapture(event.pointerId);
  }
  function pointerMove(event: PointerEvent<SVGSVGElement>) { if (drag.current) edit(lineDragValue(drag.current, linePointerY(event.clientY, event.currentTarget.getBoundingClientRect(), chart))); }
  const rail = experiment ? <ExperimentRail label={`Experiment ${index + 1} of 3`} title={experiment.title} phase={!prediction ? 0 : reached ? 2 : 1}>
    {!reached && <><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="line-prediction" choices={experiment.predictions} value={prediction} onChange={id => { start(); setPrediction(id); }} /><p className={shared.small}>Changing prediction restores this experiment’s starting line and hides the reference. Reset restarts it.</p></>}
    {prediction && !reached && <p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
    {reached && <><p role="status" className={shared.observation}>{prediction === "0" ? "The observed evidence matches your prediction." : "The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="line-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation} />{explanation && !complete && <p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
    {complete && <><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={() => start(index + 1)}>{index === 2 ? "Try the transfer check" : "Next experiment"}</ExperimentButton></>}
  </ExperimentRail> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Explain a descending prediction" : "Fit fixed pairs"}>
    {transfer ? <><p>Without Guide help, choose Falling, set Slope to −0.5 and Intercept to 5.4, then Reveal best-fit line. Reconstruct Point 3’s prediction and signed residual, and compare your attempt with the reference before choosing an explanation.</p>{reachedLine(3, state) && <><ExperimentChoices legend="Transfer explanation" name="line-transfer" choices={[
      { id: "vertical", label: "My prediction falls by 0.5 Y units per X unit. At X = 2 it predicts 4.4, so Point 3’s residual is 5 − 4.4 = +0.6. My SSE is 1.70; the reference slope −0.8 and intercept 6.0 reduce it to 0.80. This describes these points, not a causal effect or guaranteed new-data accuracy." },
      { id: "positive", label: "A negative slope means every residual must be negative." },
      { id: "sum", label: "My signed residual sum is zero, so no straight line can have smaller squared error." },
    ]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (transferAnswer !== "vertical" ? <p role="status" className={shared.feedback}>Try again. Separate slope direction from observed-minus-predicted residual sign. Signed cancellation does not minimize squared error or prove causation.</p> : <><ExperimentResult title="Transfer explained">Your descending candidate predicts 4.4 at X = 2 while observed Y is 5, giving a positive residual +0.6. Its signed sum is zero, yet SSE 1.70 exceeds the reference’s 0.80. The reference is a fit to these five points; no causal or new-data guarantee follows.</ExperimentResult><ExperimentButton onClick={() => { setIndex(4); clear(); }}>Explore freely</ExperimentButton></>)}</>}</> : <><p>Move the solid line, switch fixed datasets or reveal the reference. Inspect signed vertical gaps and squared contributions together. Reset returns to Experiment 1.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Linear Regression Line Fitting" subtitle="Move a line; explain slope, intercept and vertical residuals." rail={rail}>
    <LessonToolbar scenarios={linePresets} selectedId={state.scenario} onSelect={id => edit({ scenario: id as LineScenario, revealed: false })} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={styles.evidence} aria-label="Fixed observations and movable line"><h2>Your dataset</h2><p>Five fixed toy observations. Move only the solid line: drag the square at X = 0 for Intercept, the diamond at X = 4 for Slope, or the solid line vertically to shift it. The circles stay fixed. Use the native controls below for exact or keyboard edits.</p><p role="status" data-line-status className={styles.formula}>Your line: ŷ = {number(state.slope, 1)}X + {number(state.intercept, 1)}. SSE = {number(a.sse)}. Point 3: X = 2, observed Y = {example.y}, predicted Y = {number(example.predicted)}, residual = {lineSigned(example.residual)}.</p>
      <div className={styles.chart} ref={chartRef}><svg data-line-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`Five fixed observations and a movable solid line on fixed X 0 to 4 and Y −4 to 12 axes. Orange square changes intercept, diamond changes slope. Orange segments show vertical residuals at the same X. Point 3 has observed Y ${example.y}, predicted Y ${number(example.predicted)}, signed residual ${lineSigned(example.residual)}. ${state.revealed ? "A dashed reference is visible." : "Best-fit reference hidden."} Equivalent paired values follow in the optional table.`} onPointerDown={pointerStart} onPointerMove={pointerMove} onPointerUp={event => { pointerMove(event); drag.current = null; }} onPointerCancel={() => { drag.current = null; }} onLostPointerCapture={() => { drag.current = null; }}>
        {chart.xTicks.map(t => <g key={t.value}><line x1={t.x} x2={t.x} y1={chart.top} y2={chart.baseline} /><text x={t.x} y={chart.baseline + 24} textAnchor="middle">{t.value}</text></g>)}{chart.yTicks.map(t => <g key={t.value}><line x1={chart.left} x2={chart.width - chart.right} y1={t.y} y2={t.y} /><text x={chart.left - 12} y={t.y + 4} textAnchor="end">{t.value}</text></g>)}<text x="7" y="14">Y</text><text x={chart.width / 2} y={chart.height - 6} textAnchor="middle">X</text>
        {state.revealed && <line data-reference {...chart.reference} />}{chart.points.map((p, i) => <line data-residual={i + 1} key={`r${i}`} x1={p.cx} x2={p.cx} y1={p.cy} y2={p.py} />)}<line data-candidate {...chart.own} />{chart.points.map((p, i) => <circle data-observation={i + 1} key={i} cx={p.cx} cy={p.cy} r={i === 2 ? 7 : 6} data-example={i === 2 ? "true" : undefined} />)}<rect data-intercept-handle x={chart.own.x1 - 8} y={chart.own.y1 - 8} width="16" height="16" /><polygon data-slope-handle points={chart.diamond} />
      </svg></div><p>Solid indigo = your line; circles = fixed observations, with Point 3 outlined. Orange segments are signed vertical gaps at each X; their lengths show absolute residual size. {state.revealed && "Dashed teal = the least-squares reference."} A handle can coincide with an observation; moving it still changes only the line.</p>
      <div className={styles.controls}><LessonRangeControl label="Slope" value={state.slope} min={-1} max={1} step={.1} help="Predicted Y change per one X unit. The diamond pivots the line about X = 0." onChange={slope => edit({ slope })} /><LessonRangeControl label="Intercept" value={state.intercept} min={0} max={8} step={.1} help="Predicted Y at X = 0. The square or solid line shifts every prediction equally." onChange={intercept => edit({ intercept })} /></div>
      <LessonAction onClick={() => edit({ revealed: !state.revealed })}>{state.revealed ? "Hide best-fit line" : "Reveal best-fit line"}</LessonAction>{state.revealed && <p role="status" data-line-fit className={styles.formula}>Dashed reference: ŷ = {number(a.fit.slope, 1)}X + {number(a.fit.intercept, 1)}. SSE = {number(a.fit.sse)}. Signed residual sum = {lineSigned(a.fit.residualSum)}. Your solid line and controls are unchanged.</p>}
      <h2>Build the vertical residual</h2><p className={styles.formula} data-line-construction>Point 3: observed {example.y} − predicted {number(example.predicted)} = {lineSigned(example.residual)}. Squared contribution = {number(example.squared)}.<br />SSE = sum of all five squared residuals = {number(a.sse)}. Signed residual sum = {lineSigned(a.residualSum)}.</p><p>Positive residuals lie above the line; negative ones below it. Residuals are differences, not necessarily data mistakes. Signed gaps can cancel; their squares do not. SSE uses squared Y units and describes fit to these points.</p>
    </section>
    <LessonSummaries label="Line parameters" summaries={[
      { label: "Slope", color: "#5031dc", value: number(state.slope, 1), definition: "Change in predicted Y per one X unit.", formula: "Hold Intercept fixed → pivot about X = 0" },
      { label: "Intercept", color: "#ad4508", value: number(state.intercept, 1), definition: "Predicted Y at X = 0.", formula: "Hold Slope fixed → parallel vertical shift" },
    ]} />
    <section className={styles.evidence} aria-label="Paired residual evidence and fitting limits"><p>This is a descriptive fit to five fixed toy pairs. Neither a small SSE nor the fitted slope establishes causation or guarantees accuracy on new observations.</p><details><summary>Pair and residual table</summary><div className={styles.table} role="region" tabIndex={0} aria-label="All five observations and residuals"><table><caption>Your solid candidate. All observed X and Y values stay fixed until you switch datasets. Residual = observed minus predicted at the same X.</caption><thead><tr>{["Point", "X", "Observed Y", "Predicted Y", "Residual", "Squared"].map(h => <th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{a.points.map((p, i) => <tr key={i}><th scope="row">{i + 1}</th><td>{p.x}</td><td>{p.y}</td><td>{number(p.predicted)}</td><td>{lineSigned(p.residual)}</td><td>{number(p.squared)}</td></tr>)}</tbody></table></div>{state.revealed && <p className={styles.formula}>Reference residuals (Points 1–5): {a.fit.points.map(p => lineSigned(p.residual)).join(", ")}. Its squared sum is {number(a.fit.sse)}.</p>}</details><details><summary>Conventions and sources</summary><p>Least squares with an intercept minimizes Σ[observed Y − (Slope × X + Intercept)]² over all straight lines, not just the editable tenths grid. Slope = Σ[(X − mean X)(Y − mean Y)] / Σ(X − mean X)²; Intercept = mean Y − Slope × mean X. The five distinct X values make the denominator positive and the minimum unique. The reference parameters happen to be tenths for these prepared datasets; calculations use full precision before display.</p><p>Normality is not required to compute this descriptive minimum. No regression inference, causal estimate, loss landscape, R²/residual diagnostic model or train/test guarantee is supplied here. Straight is an exact constructed boundary where the reference residuals are zero; the scattered examples retain nonzero residuals.</p><a href="https://www.itl.nist.gov/div898/handbook/pmd/section4/pmd431.htm" target="_blank" rel="noreferrer">NIST · Least-squares criterion and straight-line coefficients</a><br /><a href="https://openstax.org/books/introductory-statistics/pages/12-3-the-regression-equation" target="_blank" rel="noreferrer">OpenStax · Signed vertical residuals and line interpretation</a></details></section>
  </LearningPage>;
}
