export type ReferenceState = { reference: string; candidate: string; normalization: string; order: number };
export const referenceAnswers = [{id:"cat",label:"Cat on mat",text:"the cat sat on the mat"},{id:"paraphrase",label:"Feline on rug",text:"the feline rested on the rug"},{id:"empty",label:"Empty reference",text:""}];
export const candidateAnswers = [{id:"exact",label:"Exact wording",text:"the cat sat on the mat"},{id:"surface",label:"Case & punctuation",text:"The CAT sat on the mat!"},{id:"reordered",label:"Reordered words",text:"the mat sat on the cat"},{id:"paraphrase",label:"Paraphrase",text:"the feline rested on the rug"},{id:"negated",label:"Negated answer",text:"the cat did not sit on the mat"},{id:"short",label:"One word",text:"cat"},{id:"repeat",label:"Repeated word",text:"cat cat cat cat"},{id:"empty",label:"Empty candidate",text:""}];
export const normalizationChoices=[{id:"raw",label:"Raw"},{id:"normalized",label:"Normalized"}];
export const bleuChoices=[{id:"1",label:"1 (unigrams)"},{id:"2",label:"2 (unigrams + bigrams)"}];
export const referenceScenarios=[{id:"surface",label:"Surface",shortLabel:"Case & punctuation"},{id:"order",label:"Order",shortLabel:"Same words"},{id:"paraphrase",label:"Paraphrase",shortLabel:"Different words"}];
export function referenceBaseline(id="surface"):ReferenceState{return{reference:"cat",candidate:id==="order"?"reordered":id==="paraphrase"?"paraphrase":"surface",normalization:id==="surface"?"raw":"normalized",order:2};}
export function sameReference(a:ReferenceState,b:ReferenceState){return a.reference===b.reference&&a.candidate===b.candidate&&a.normalization===b.normalization&&a.order===b.order;}
export function referencePresetId(s:ReferenceState){return referenceScenarios.find(p=>sameReference(s,referenceBaseline(p.id)))?.id??"custom";}
export function editReference(s:ReferenceState,key:keyof ReferenceState,value:string){const choices=key==="reference"?referenceAnswers:key==="candidate"?candidateAnswers:key==="normalization"?normalizationChoices:bleuChoices;if(!choices.some(c=>c.id===value))return s;const v=key==="order"?Number(value):value;return s[key]===v?s:{...s,[key]:v};}
export function normalizeAnswer(text:string){return text.toLowerCase().replace(/[\u0021-\u002f\u003a-\u0040\u005b-\u0060\u007b-\u007e]/g,"").replace(/\b(a|an|the)\b/g," ").trim().replace(/\s+/g," ");}
const tokenize=(text:string)=>text.trim()?text.trim().split(/\s+/):[];
const counts=(tokens:readonly string[])=>tokens.reduce<Record<string,number>>((acc,t)=>({...acc,[t]:(acc[t]??0)+1}),{});
function overlapRows(a:readonly string[],b:readonly string[]){const ca=counts(a),cb=counts(b);return [...new Set([...a,...b])].map(gram=>({gram,candidate:ca[gram]??0,reference:cb[gram]??0,clipped:Math.min(ca[gram]??0,cb[gram]??0)}));}
function commonSubsequence(a:readonly string[],b:readonly string[]){const dp=Array.from({length:a.length+1},()=>Array<number>(b.length+1).fill(0));for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)dp[i]![j]=a[i-1]===b[j-1]?dp[i-1]![j-1]!+1:Math.max(dp[i-1]![j]!,dp[i]![j-1]!);const sequence:string[]=[];let i=a.length,j=b.length;while(i>0&&j>0){if(a[i-1]===b[j-1]){sequence.unshift(a[i-1]!);i--;j--;}else if(dp[i-1]![j]!>=dp[i]![j-1]!)i--;else j--;}return{length:dp[a.length]![b.length]!,sequence};}
export const toyDictionary:Record<string,readonly number[]>={cat:[1,0],feline:[1,0],sat:[0,1],sit:[0,1],rested:[0,1],mat:[1,1],rug:[1,1]};
function meanVector(text:string){const tokens=tokenize(normalizeAnswer(text));return[0,1].map(j=>tokens.length?tokens.reduce((sum,t)=>sum+(toyDictionary[t]?.[j]??0),0)/tokens.length:0);}
export function analyzeReference(s:ReferenceState){const referenceRaw=referenceAnswers.find(a=>a.id===s.reference)!.text,candidateRaw=candidateAnswers.find(a=>a.id===s.candidate)!.text;const referenceText=s.normalization==="normalized"?normalizeAnswer(referenceRaw):referenceRaw,candidateText=s.normalization==="normalized"?normalizeAnswer(candidateRaw):candidateRaw,referenceTokens=tokenize(referenceText),candidateTokens=tokenize(candidateText),referenceLength=referenceTokens.length,candidateLength=candidateTokens.length;const tokenRows=overlapRows(candidateTokens,referenceTokens),overlap=tokenRows.reduce((sum,r)=>sum+r.clipped,0),precision=candidateLength?overlap/candidateLength:0,recall=referenceLength?overlap/referenceLength:0,f1=overlap?2*overlap/(candidateLength+referenceLength):0;const common=commonSubsequence(candidateTokens,referenceTokens),lcs=common.length,rouge=lcs?2*lcs/(candidateLength+referenceLength):0;const ngrams=[1,2].map(order=>{const grams=(t:readonly string[])=>t.slice(0,Math.max(0,t.length-order+1)).map((_,i)=>t.slice(i,i+order).join(" "));const rows=overlapRows(grams(candidateTokens),grams(referenceTokens)),clipped=rows.reduce((sum,r)=>sum+r.clipped,0),total=Math.max(0,candidateLength-order+1);return{order,rows,clipped,total,precision:total?clipped/total:0};});const bp=candidateLength===0?0:candidateLength>=referenceLength?1:Math.exp(1-referenceLength/candidateLength),bleu=bp*(s.order===1?ngrams[0]!.precision:Math.sqrt(ngrams[0]!.precision*ngrams[1]!.precision));const candidateVector=meanVector(candidateRaw),referenceVector=meanVector(referenceRaw),dot=candidateVector.reduce((sum,v,i)=>sum+v*referenceVector[i]!,0),candidateNorm=Math.hypot(...candidateVector),referenceNorm=Math.hypot(...referenceVector),cosine=candidateNorm===0||referenceNorm===0?null:Math.max(-1,Math.min(1,dot/(candidateNorm*referenceNorm))),em=Number(referenceText===candidateText);return{referenceRaw,candidateRaw,referenceText,candidateText,referenceTokens,candidateTokens,referenceLength,candidateLength,tokenRows,overlap,precision,recall,f1,lcs,sequence:common.sequence,rouge,ngrams,bp,bleu,candidateVector,referenceVector,dot,candidateNorm,referenceNorm,cosine,em,scores:[{id:"em",label:"Exact match",value:em},{id:"f1",label:"Token F1",value:f1},{id:"bleu",label:`BLEU-${s.order}`,value:bleu},{id:"rouge",label:"ROUGE-L F1",value:rouge},{id:"cosine",label:"Toy cosine",value:cosine}]};}
export const referenceNumber=(n:number|null)=>n===null?"Undefined":Number(n.toFixed(6)).toLocaleString("en-US",{useGrouping:false,maximumFractionDigits:6});
export const referenceBarWidth=(n:number)=>360*n;
