"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeTesting, formatTestingP, testingChart, testingPresets, type TestingState } from "./testing-engine";
import { testingBaseline, reachedTesting } from "./lesson-state";
import { testingExperiments } from "./learning-experiments";
import styles from "./playground.module.css";

export function TestingPlayground() {
  const [state, setState] = useState<TestingState>(() => testingBaseline()), [index, setIndex] = useState(0);
  const [prediction, setPrediction] = useState<string | null>(null), [explanation, setExplanation] = useState<string | null>(null), [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const [width, setWidth] = useState(640), chartRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const element = chartRef.current;
    if (!element) return;
    const update = () => setWidth(Math.max(200, element.getBoundingClientRect().width));
    update();
    const observer = new ResizeObserver(update);
    observer.observe(element);
    return () => observer.disconnect();
  }, []);
  const a = useMemo(() => analyzeTesting(state), [state]), chart = testingChart(a, width), experiment = testingExperiments[index], transfer = index === 4;
  const reached = !!prediction && !!experiment && reachedTesting(index, state), complete = reached && explanation === "0";
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function start(next = index) { setIndex(next); setState(testingBaseline(next)); setPrediction(null); clear(); }
  function edit(patch: Partial<TestingState>) { setState(s => ({ ...s, ...patch })); clear(); }
  const rail = experiment ? <ExperimentRail label={`Experiment ${index + 1} of 4`} title={experiment.title} phase={!prediction ? 0 : reached ? 2 : 1}>
    {!reached && <><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="testing-prediction" choices={experiment.predictions} value={prediction} onChange={id => { start(); setPrediction(id); }} /><p className={shared.small}>Changing prediction restores this experiment’s starting settings. Reset restarts it.</p></>}
    {prediction && !reached && <p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
    {reached && <><p role="status" className={shared.observation}>{prediction === "0" ? "The observed evidence matches your prediction." : "The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="testing-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation} />{explanation && !complete && <p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
    {complete && <><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={() => start(index + 1)}>{index === 3 ? "Try the transfer check" : "Next experiment"}</ExperimentButton></>}
  </ExperimentRail> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Negative gap, stricter rule" : "Explore null evidence"}>
    {transfer ? <><p>Without Guide help, set Observed gap to −1.5, Size per group to 100 and Significance level to 1%. Explain the two-sided p-value and decision.</p><ExperimentChoices legend="Transfer explanation" name="testing-transfer" choices={[
      { id: "null", label: "Z is about −2.6517 and p ≈ 0.0080, below α = 0.01, so the two-sided rule rejects H0. Observed B is lower than A, but p is a null-tail probability, not the probability that H0 is true or proof of a causal, practically large difference." },
      { id: "posterior", label: "H0 has probability 0.8% of being true, and the negative sign means p must be negative too." },
      { id: "proof", label: "The 1% threshold proves B is worse than A for every individual, with exactly a 1% chance of being wrong." },
    ]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (!reachedTesting(4, state) ? <p role="status" className={shared.feedback}>First set Observed gap −1.5, Size per group 100 and Significance level 1%. Read the observed Z, p-value and decision.</p> : transferAnswer !== "null" ? <p role="status" className={shared.feedback}>Try again. p is the probability of at least this null-model extremeness in either direction. Compare it with the separately selected threshold; avoid posterior, proof and individual-guarantee claims.</p> : <><ExperimentResult title="Transfer explained">SE = √(16 / 100 + 16 / 100) = 0.5657; Z ≈ −2.6517. Two-sided p ≈ 0.0080 ≤ 0.01, so the rule rejects H0 under this model. The signed observed gap and uncertainty are distinct from practical importance or causal proof.</ExperimentResult><ExperimentButton onClick={() => { setIndex(5); clear(); }}>Explore freely</ExperimentButton></>)}</> : <><p>Compare gaps, hypothetical sizes and thresholds. Keep the null curve separate from observed summaries, p separate from α and statistical evidence separate from practical importance. Reset returns to Experiment 1.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;

  return <LearningPage title="Hypothesis Testing Basics" subtitle="Compare an A/B gap with what the null model predicts." rail={rail}>
    <LessonToolbar label="Observed gap shortcuts" scenarios={testingPresets} selectedId={testingPresets.find(p => p.difference === state.difference)?.id ?? "custom"} onSelect={id => { const preset = testingPresets.find(p => p.id === id); if (preset) edit({ difference: preset.difference }); }} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={styles.evidence} aria-label="A/B test controls"><p>One toy A/B comparison: independent normal groups, known population SD 4 in each. Illustrative observed sample means A = 20 and B = {a.meanB.toFixed(2)}, with {state.size} observations per group ({2 * state.size} total). Editing these hypothetical summaries does not collect data or reveal true means.</p><p className={styles.formula}>H0: μB − μA = 0. H1: μB − μA ≠ 0. The alternative includes either direction.</p><div className={styles.controls}>
      <LessonRangeControl label="Observed gap" value={state.difference} min={-3} max={3} step={0.05} help="Observed sample mean B minus A, in score units. This is not the true population difference." onChange={difference => edit({ difference })} />
      <LessonRangeControl label="Size per group" value={state.size} min={1} max={400} step={1} help="Hypothetical independent observation count in each group; both group mean uncertainties contribute." onChange={size => edit({ size })} />
      <LessonRangeControl label="Significance level" unit="%" value={state.alpha} min={1} max={10} step={1} help="Decision threshold α, separate from the p-value. Choose it before collecting real test data." onChange={alpha => edit({ alpha })} />
    </div><p role="status" data-testing-status>Observed gap {state.difference.toFixed(2)}; size {state.size} per group; α = {(state.alpha / 100).toFixed(2)}. Two-sided decision: {a.reject ? "reject H0" : "fail to reject H0"}.</p></section>
    <section className={styles.evidence} aria-label="Null model and two-sided tails"><h2>Test statistic if H0 is true</h2><p>The standard-normal null curve stays centered at zero. Orange areas are both p-value tails beyond ±|observed Z|; indigo dashed lines are the decision’s critical boundaries, not the p-value. The dark baseline dot is the signed observed Z.</p><div className={styles.chart} ref={chartRef}><svg data-testing-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`Standard-normal Z density under H0 on fixed −12 to 12 axis. Observed Z ${a.z.toFixed(4)}, mirrored extremeness boundaries ±${Math.abs(a.z).toFixed(4)}, two-sided p approximately ${formatTestingP(a.p)}. Critical boundaries ±${a.critical.toFixed(4)} at significance ${state.alpha}%. Probability is computed to infinity; exact tail evidence follows.`}>
      <text x="4" y="16">Density</text>{chart.densityTicks.map(tick => <g key={tick.value}><line x1={chart.left} x2={chart.width - chart.right} y1={tick.y.toFixed(3)} y2={tick.y.toFixed(3)} /><text x={chart.left - 7} y={(tick.y + 4).toFixed(3)} textAnchor="end">{tick.value}</text></g>)}{chart.tails.map((points, i) => <polygon key={i} points={points} data-tail={i === 0 ? "left" : "right"} />)}<polyline points={chart.curve} data-null-curve />{chart.criticals.map((x, i) => <line key={i} x1={x.toFixed(3)} x2={x.toFixed(3)} y1={chart.top} y2={chart.baseline} data-critical />)}{chart.extremes.map((x, i) => <line key={i} x1={x.toFixed(3)} x2={x.toFixed(3)} y1={chart.top} y2={chart.baseline} data-extreme />)}<circle cx={chart.observedX.toFixed(3)} cy={chart.baseline} r="4" data-observed />{chart.ticks.map((tick, i) => <text key={tick.value} x={tick.x.toFixed(3)} y={chart.baseline + 20} textAnchor={i === 0 ? "start" : i === 4 ? "end" : "middle"}>{tick.value}</text>)}<text x={(chart.width / 2).toFixed(3)} y="295" textAnchor="middle">Z · standardized gap under H0</text>
    </svg></div><p className={styles.formula} data-testing-geometry>Observed Z = {a.z.toFixed(4)}; |Z| = {Math.abs(a.z).toFixed(4)}. Critical boundaries: ±{a.critical.toFixed(4)}. Shaded tails total p ≈ {formatTestingP(a.p)}.</p><p>The plot shows only −12 to 12; each computed tail extends to infinity. Density height is not point probability. Decisions compare full-precision computed p with α; displayed probabilities are rounded.</p></section>
    <section className={styles.evidence} aria-label="Test statistic construction"><p className={styles.formula} data-testing-formula>SE difference = √(4² / {state.size} + 4² / {state.size}) = {a.se.toFixed(4)}. Z = ({state.difference.toFixed(2)} − 0) / {a.se.toFixed(4)} = {a.z.toFixed(4)}.</p><p>Independent mean variances add, so both groups contribute uncertainty. This standard-normal rule is exact under the stated normal known-SD model, rather than a universal small-sample approximation.</p></section>
    <LessonSummaries label="Statistic, null evidence and decision" summaries={[
      { label: "Observed Z", color: "#33486d", value: a.z.toFixed(4), definition: "Signed gap measured in difference SEs.", formula: `Observed gap / SE = ${state.difference.toFixed(2)} / ${a.se.toFixed(4)}` },
      { label: "Two-sided p-value", color: "#ad4508", value: `≈ ${formatTestingP(a.p)}`, definition: "Extreme-data probability under H0.", formula: "P(|Z| ≥ |z observed| given H0)" },
      { label: "Decision", color: "#5031dc", value: a.reject ? "Reject H0" : "Fail to reject", definition: "A predeclared rule; neither outcome is proof.", formula: `p ${a.reject ? "≤" : ">"} α = ${(state.alpha / 100).toFixed(2)}` },
    ]} />
    <section className={styles.evidence} aria-label="Probability interpretation and optional evidence"><p>p does not give the probability H0 is true. Failing to reject does not prove equal means. Statistical significance alone does not establish a large, practically important or causal effect. Choose α and the two-sided procedure before collecting real data.</p>
      <details><summary>Exact tail probabilities</summary><p className={styles.formula} data-testing-tails>Each null tail ≈ {a.tail.toPrecision(10)}; total two-sided p ≈ {a.p.toPrecision(10)}. α = {(state.alpha / 100).toFixed(2)}. Rule: reject if computed p ≤ α, including equality. Current decision: {a.reject ? "reject H0" : "fail to reject H0"}.</p><p>These numerical probabilities are shown to 10 significant digits. The decision uses full computed precision. A&S 26.2.17 supplies moderate tails; above |Z| = 4, a 100-term NIST DLMF 7.9.2 continued fraction preserves small-tail relative precision. Tiny positive p-values use scientific notation, never a displayed zero.</p></details>
      <details><summary>Model assumptions</summary><p>Independent normal observations, known population SD 4 in both groups and equal group sizes give difference variance 16 / n + 16 / n. Under H0: μB − μA = 0, the standardized statistic has standard-normal law. The observed means 20 and {a.meanB.toFixed(2)} are hypothetical summaries; the true means are not known. Editing n holds the gap fixed for a controlled comparison and does not generate new observations. A real new sample may have a different gap.</p><p>The p-value conditions on H0 and all model assumptions. It does not invert that conditional probability, measure practical importance or validate causal design. α concerns the test’s repeated false-rejection rate when H0 is true under its model, rather than the probability this particular conclusion is wrong. Unknown SD, paired or unequal groups, non-normal small samples, dependence, biased collection, power, multiple testing and sequential peeking are outside scope. A one-sided hypothesis must be specified in advance and is a different test.</p><a href="https://www.stat.berkeley.edu/~stark/SticiGui/Text/testing.htm" target="_blank" rel="noreferrer">Berkeley SticiGui · Null hypotheses, p-values and decision rules</a><br /><a href="https://www.stat.berkeley.edu/~stark/SticiGui/Text/zTest.htm" target="_blank" rel="noreferrer">Berkeley SticiGui · Two-sided Z tails and independent mean differences</a><br /><a href="https://www.itl.nist.gov/div898/handbook/prc/section2/prc22.htm" target="_blank" rel="noreferrer">NIST · Known-SD tests and preselected significance</a><br /><a href="https://dlmf.nist.gov/7.9" target="_blank" rel="noreferrer">NIST DLMF · Small-tail numerical continued fractions</a></details>
    </section>
  </LearningPage>;
}
