"use client";
import { useEffect, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonAction, LessonRangeControl, LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeSearch, formatRate, winRate } from "./mcts-engine";
import { advanceMcts, mctsBaseline, reachedMcts, type MctsState } from "./lesson-state";
import { mctsExperiments } from "./learning-experiments";
import { searchProblems, type SearchProblemId } from "./scenario";
import styles from "./playground.module.css";
export function MonteCarloTreeSearchPlayground() {
  const [state, setState] = useState<MctsState>(() => mctsBaseline()), [index, setIndex] = useState(0), [prediction, setPrediction] = useState<string | null>(null), [explanation, setExplanation] = useState<string | null>(null), [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const experiment = mctsExperiments[index], transfer = index === 5, analysis = analyzeSearch(state.search, state.c), left = Math.max(0, state.budget - state.search.rootVisits), problem = searchProblems.find(p => p.id === state.problem)!;
  const reached = !!prediction && !!experiment && reachedMcts(index, state), complete = reached && explanation === "0", last = state.last, beforeAnalysis = last ? analyzeSearch(last.before, last.c) : null;
  useEffect(() => {
    if (!state.running) return;
    const timer = setTimeout(() => setState(s => s.running ? advanceMcts(s) : s), 380);
    return () => clearTimeout(timer);
  }, [state]);
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function start(next = index) { setIndex(next); setState(mctsBaseline(next)); setPrediction(null); clear(); }
  function edit(patch: Partial<MctsState>) { setState(s => ({ ...s, ...patch, running: false })); clear(); }
  function step() { setState(s => advanceMcts({ ...s, running: false })); clear(); }
  const rail = experiment ? <ExperimentRail label={`Experiment ${index + 1} of 5`} title={experiment.title} phase={!prediction ? 0 : reached ? 2 : 1}>
    {!reached && <><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="mcts-prediction" choices={experiment.predictions} value={prediction} onChange={id => { start(); setPrediction(id); }}/><p className={shared.small}>Choosing another prediction restores the starting counts and controls. Reset restarts this experiment. Experiment 4 starts after one recorded successful Step.</p></>}
    {prediction && !reached && <p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
    {reached && <><p role="status" className={shared.observation}>{prediction === "0" ? "The evidence matches your prediction." : "The recorded evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="mcts-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation}/>{explanation && !complete && <p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
    {complete && <><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={() => start(index + 1)}>{index === 4 ? "Try the transfer check" : "Next experiment"}</ExperimentButton></>}
  </ExperimentRail> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Same mechanics, another illustration" : "Explore selection and updates"}>
    {transfer ? <><p>Without Guide help, choose Grid Route, set Exploration constant to 0.1 and Total visit budget to 66. Run two new Steps. Which path gets updated, and what can you conclude about the grid?</p><ExperimentChoices legend="Transfer explanation" name="mcts-transfer" choices={[{ id: "mechanics", label: "A gets both results: A becomes 29/40 and Root 41/66. These scripted counts show selection and backup; they do not solve a route or prove A best." }, { id: "solver", label: "A is now the proven optimal grid route." }, { id: "bonus", label: "D must get both results because it has the fewest visits, regardless of c." }]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer && (!reachedMcts(5, state) ? <p role="status" className={shared.feedback}>First choose Grid Route, set c to 0.1 and the total budget to 66, then take exactly two new Steps. Read the actual counts.</p> : transferAnswer !== "mechanics" ? <p role="status" className={shared.feedback}>Try again. Changing the illustration does not change scores, result scripts or game rules. Selection uses the entire score; sampled counts are not a proof.</p> : <><ExperimentResult title="Transfer explained">At low c, A gets the next two scripted successes. Root and A update together; the route sketch adds no game-solving guarantee.</ExperimentResult><ExperimentButton onClick={() => { setIndex(6); clear(); }}>Explore freely</ExperimentButton></>)}</> : <><p>Change c, continue up to 160 total visits, pause, or lower the budget without deleting counts. Changing illustrations leaves the same mechanics and record. Reset restarts the experiments.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Monte Carlo Tree Search" subtitle="Choose a branch, read a scripted result, and update its visited path." rail={rail}>
    <LessonToolbar label="Search illustrations" scenarios={searchProblems} selectedId={state.problem} onSelect={id => edit({ problem: id as SearchProblemId })} onReset={() => start(experiment || transfer ? index : 0)}/>
    <section className={styles.evidence} aria-label="Demo controls"><h2>Scripted mechanics demo</h2><p>This is a small demonstration of selection and backpropagation, not a game solver. All three illustrations share generic branches A–D and repeating scripted outcomes. No legal moves, deeper tree expansion or random game rollout is implemented.</p>
      <div className={styles.controls}><LessonRangeControl label="Exploration constant" value={state.c} min={.1} max={2.5} step={.1} help="c gives the exploration bonus more or less weight. Editing a control pauses Run; counts stay fixed." onChange={c => edit({ c })}/><LessonRangeControl label="Total visit budget" value={state.budget} min={65} max={160} step={1} help="Includes the 64 seeded visits. Lowering the budget stops without undoing evidence." onChange={budget => edit({ budget })}/></div>
      <div className={styles.actions}><LessonAction onClick={step} disabled={!left || state.running}>Step</LessonAction>{state.running ? <LessonAction onClick={() => edit({})}>Pause</LessonAction> : <LessonAction onClick={() => { clear(); setState(s => ({ ...s, running: true })); }} disabled={!left}>Run</LessonAction>}<p role="status" data-search-status>{state.search.rootVisits} total visits = 64 seeded + {state.search.stepIndex} new step{state.search.stepIndex === 1 ? "" : "s"}. {left} remaining.{state.running ? " Running…" : !left ? " Budget reached; raise it to continue." : " Ready."}</p></div>
    </section>
    <section className={styles.evidence} aria-label="Selection scores"><h2>Next selection · branch {analysis.selectedMove.label}</h2><p className={styles.formula}>score = Q + c × sqrt(ln N / n)</p><p>Q is successes / visits. N is parent visits; n is branch visits. ln is the natural logarithm. At fixed N and c, fewer visits give a larger bonus. UCB means upper confidence bound; here the score is a selection priority, can exceed 1, and is not a win probability or proof.</p>
      <table className={styles.table} data-score-table><caption>Current branch scores · two-decimal display; selection uses full precision. Ties use A–D order.</caption><thead><tr><th scope="col">Branch</th><th scope="col">Successes / visits</th><th scope="col">Q</th><th scope="col">Bonus</th><th scope="col">Score</th><th scope="col">Meaning</th></tr></thead><tbody>{analysis.moves.map(m => <tr key={m.id} data-next={m.isSelected} data-branch={m.id}><th scope="row">{m.label}</th><td>{m.wins} / {m.visits}</td><td>{formatRate(m.q)}</td><td>{formatRate(m.bonus)}</td><td>{formatRate(m.ucb)}</td><td>{[m.isSelected ? "Next selection" : "", m.isBestObserved ? "Best observed Q" : ""].filter(Boolean).join(" · ") || "Wait"}</td></tr>)}</tbody></table>
      <p>Best observed Q: {analysis.bestObservedMove.label}. This describes the record. Next selection chooses where to sample next; neither label is a final move recommendation.</p>
    </section>
    <section className={styles.evidence} aria-label="Visited path"><h2>Root and four existing branches</h2><p>Dashed outline: next selection. Solid orange path and “Last”: last completed Step. Counts are successes / visits. The diagram adds no child nodes.</p>
      <svg className={styles.tree} viewBox="0 0 640 260" role="img" aria-label={`Root ${state.search.rootWins}/${state.search.rootVisits}. Next branch ${analysis.selectedMove.label}. ${last ? `Last completed branch ${last.after.moves.find(m => m.id === last.branch)!.label}: ${last.result ? "success" : "failure"}.` : "No new result yet."}`}>
        {analysis.moves.map((m,i) => <line key={m.id} x1="320" y1="65" x2={80 + i * 160} y2="166" data-last={last?.branch === m.id}/>)}
        <rect x="262" y="8" width="116" height="62" rx="7"/><text x="320" y="32">Root</text><text x="320" y="54" data-count>{state.search.rootWins} / {state.search.rootVisits}</text>
        {analysis.moves.map((m,i) => <g key={m.id}><rect x={22 + i * 160} y="164" width="116" height="65" rx="7" data-next={m.isSelected} data-last={last?.branch === m.id}/><text x={80+i*160} y="188">Branch {m.label}</text><text x={80+i*160} y="211" data-count>{m.wins} / {m.visits}</text><text x={80+i*160} y="251">{[m.isSelected ? "Next" : "", last?.branch === m.id ? "Last" : ""].filter(Boolean).join(" · ")}</text></g>)}
      </svg><div className={styles.compactTree} role="group" aria-label="Root and child counts"><p><strong>Root</strong> · {state.search.rootWins} / {state.search.rootVisits}</p><p>↓ Four existing child branches</p><div>{analysis.moves.map(m => <p key={m.id} data-next={m.isSelected} data-last={last?.branch === m.id}><strong>Branch {m.label}</strong><span>{m.wins} / {m.visits}</span><span>{[m.isSelected ? "Next" : "", last?.branch === m.id ? "Last" : ""].filter(Boolean).join(" · ") || "Not visited last"}</span></p>)}</div></div><p data-root-count>Root Q = {state.search.rootWins} / {state.search.rootVisits} = {formatRate(analysis.rootQ)}. Root counts sum the child counts, so its Q is weighted by visits, not an equal average of four branch Q values.</p>
    </section>
    <section className={styles.evidence} aria-label="Last completed update"><h2>Last completed update</h2>{last && beforeAnalysis ? <><p role="status" data-last-result>Step {last.after.stepIndex} selected branch {last.after.moves.find(m => m.id === last.branch)!.label} at c = {last.c}. Scripted {last.result ? "success" : "failure"}; reward {Number(last.result)}. Visited path: Root → {last.after.moves.find(m => m.id === last.branch)!.label}.</p><p data-before-scores>Scores before that Step: {beforeAnalysis.moves.map(m => `${m.label} ${formatRate(m.ucb)}`).join(" · ")}. Next selection above uses the updated counts and current c.</p><table className={styles.table} data-backup-table><caption>Before → after the recorded Step. Every visited node gains one visit; success adds 1, failure adds 0.</caption><thead><tr><th scope="col">Node</th><th scope="col">Successes</th><th scope="col">Visits</th><th scope="col">Q</th></tr></thead><tbody>{[{ label: "Root", beforeWins:last.before.rootWins, afterWins:last.after.rootWins, beforeVisits:last.before.rootVisits, afterVisits:last.after.rootVisits },...last.before.moves.map(m => { const after=last.after.moves.find(a=>a.id===m.id)!; return {label:`Branch ${m.label}`,beforeWins:m.wins,afterWins:after.wins,beforeVisits:m.visits,afterVisits:after.visits}; })].map(m=><tr key={m.label}><th scope="row">{m.label}</th><td>{m.beforeWins} → {m.afterWins}</td><td>{m.beforeVisits} → {m.afterVisits}</td><td>{formatRate(winRate(m.beforeWins,m.beforeVisits))} → {formatRate(winRate(m.afterWins,m.afterVisits))}</td></tr>)}</tbody></table></> : <p data-last-result>No new result yet. Press Step to create a recorded update. The seeded counts are teaching fixtures, not a reconstructed game history.</p>}</section>
    <section className={styles.evidence} aria-label="Demo scope"><details><summary>What full MCTS adds</summary><ol><li>Selection follows a policy down an existing tree.</li><li>Expansion adds a legal successor at an expandable node.</li><li>Simulation plays out or evaluates that state to produce a reward.</li><li>Backpropagation updates the visited path from the reward.</li></ol><p>This demo implements root selection and a two-node count backup. It substitutes repeating 0/1 outcome scripts for simulation and has no expansion, terminal game rules or alternating player perspective. Repeated scripts are not independent random samples, so Monte Carlo convergence guarantees do not apply. A real implementation must specify game rules, rollout policy, reward viewpoint and final-action rule.</p><p>An unvisited branch gets priority ∞ in this engine and is selected before visited ones; all four provided branches begin visited. Q is displayed as 0 for an unvisited branch as a placeholder, not a reward estimate.</p><a href="https://cs.gettysburg.edu/~tneller/cs371/mcts-survey.pdf" target="_blank" rel="noreferrer">Browne et al. · A Survey of Monte Carlo Tree Search Methods</a></details><details><summary>Illustration and result scripts</summary><p>{problem.goal} Changing an illustration does not change the search record or outcome scripts.</p><p className={styles.board} aria-label={`${problem.label} sketch`}>{problem.board.map(row => row.map(cell => cell || "·").join(" ")).join("\n")}</p><p>Each branch repeats its listed script. The next result uses the branch’s pre-Step visit count modulo script length as a zero-based index, including seeded visits.</p><ul>{state.search.moves.map(m=><li key={m.id}>Branch {m.label}: {m.rolloutPattern.map(x=>x?"1":"0").join(", ")} · next index {m.visits % m.rolloutPattern.length}</li>)}</ul></details></section>
  </LearningPage>;
}
