"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { ExperimentButton,ExperimentChoices,ExperimentRail,ExperimentResult,LearningPage,LessonRangeControl,LessonSummaries,LessonToggleGroup,LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeBias,biasChart,biasNumber as number,biasScenarios,type BiasState } from "./bias-variance-engine";
import { biasBaseline,reachedBias } from "./lesson-state";
import { biasExperiments } from "./learning-experiments";
import styles from "./playground.module.css";
export function BiasVariancePlayground(){
 const [state,setState]=useState(()=>biasBaseline()),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null),[width,setWidth]=useState(640),chartRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const el=chartRef.current;if(!el)return;const update=()=>setWidth(Math.max(200,el.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(el);return()=>observer.disconnect();},[]);
 const a=useMemo(()=>analyzeBias(state),[state]),chart=biasChart(a,width),comparisons=useMemo(()=>Array.from({length:5},(_,degree)=>analyzeBias({...state,degree})),[state]),experiment=biasExperiments[index],transfer=index===3,reached=!!prediction&&!!experiment&&reachedBias(index,state),complete=reached&&explanation==="0";
 function clear(){setExplanation(null);setTransferAnswer(null);}
 function start(next=index){setIndex(next);setState(biasBaseline(next));setPrediction(null);clear();}
 function edit(patch:Partial<BiasState>){setState(s=>({...s,...patch}));clear();}
 const rail=experiment?<ExperimentRail label={`Experiment ${index+1} of 3`} title={experiment.title} phase={!prediction?0:reached?2:1}>
  {!reached&&<><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="bias-prediction" choices={experiment.predictions} value={prediction} onChange={id=>{start();setPrediction(id);}}/><p className={shared.small}>Changing prediction restores this experiment’s starting state. Reset restarts it.</p></>}
  {prediction&&!reached&&<p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
  {reached&&<><p role="status" className={shared.observation}>{prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="bias-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation}/>{explanation&&!complete&&<p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
  {complete&&<><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={()=>start(index+1)}>{index===2?"Try the transfer check":"Next experiment"}</ExperimentButton></>}
 </ExperimentRail>:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"New noise, new prediction location":"Separate one fit from repeated fits"}>
  {transfer?<><p>Without Guide help, choose High noise, Polynomial degree 2, Training draw 11 and X = 1.5. Compare Expected error with degree 4 in Compare all degrees. Which terms differ, and does a zero training error remove fresh response noise?</p>{reachedBias(3,state)&&<><ExperimentChoices legend="Transfer explanation" name="bias-transfer" choices={[
   {id:"terms",label:"At this probe both degrees have zero squared bias and the same response noise 2.250000. Degree 2 variance 0.966295 gives expected error 3.216295 rounded; degree 4 variance 3.643890 gives error 5.893890. Its zero training error does not remove independent response noise. These expectations belong to this finite toy distribution."},
   {id:"train",label:"Degree 4 must have lower expected error because it fits training rows exactly."},
   {id:"noise",label:"Choosing a different displayed training draw changes response noise and the cohort expectation."},
  ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="terms"?<p role="status" className={shared.feedback}>Try again. Compare squared bias, variance and response noise in the degree table at the same probe. Training fit and fresh-response expectation answer different questions.</p>:<><ExperimentResult title="Transfer explained">Here the difference in expected error comes from repeated-fit variance. The fresh response noise remains 2.250000 in both models. Neither one selected fit nor zero training error changes this expectation.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(4);clear();}}>Explore freely</ExperimentButton></>)}</>}</>:<><p>Change degree, displayed training draw, noise or probe. Training draw selects one of 32 equally weighted fits; it does not change their average or variance. Compare all degrees can also reveal nonmonotone squared bias at one probe.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
 </ExperimentRail>;
 return <LearningPage title="Bias-Variance Tradeoff Lab" subtitle="Compare repeated fits, not just one training score." rail={rail}>
  <LessonToolbar scenarios={biasScenarios} selectedId={state.scenario} onSelect={scenario=>edit({scenario:scenario as BiasState["scenario"]})} onReset={()=>start(experiment||transfer?index:0)}/>
  <section className={styles.evidence} aria-label="Repeated fits and the selected dataset"><h2>Your dataset</h2><p>Five fixed training positions X = −2, −1, 0, 1, 2. Each target is the known toy mean f(X) = 2 + X + X² plus an independent ±{a.amplitude} sign. Fit all 32 equally likely sign combinations separately. At zero noise these weighted outcomes coincide.</p><p role="status" data-bias-status className={styles.formula}>Probe X = {state.probe} · Known mean {number(a.truth)} · Average prediction {number(a.mean)} · Selected prediction {number(a.selectedPrediction)} · Selected training MSE {number(a.selected.trainMse)}</p>
   <div className={styles.chart} ref={chartRef}><svg data-bias-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`Fixed X −2 to 2 and Y −4 to 12. All 32 fitted curves, selected draw ${state.draw} degree ${state.degree}, average fit, known mean and five selected observations. Probe X ${state.probe}. Coincident curves can overlap; All 32 fitted datasets preserves every outcome numerically.`}>
    {chart.yTicks.map(t=><g key={t.value}><line x1={chart.left} x2={chart.width-chart.right} y1={t.y} y2={t.y}/><text x={chart.left-12} y={t.y+4} textAnchor="end">{t.value}</text></g>)}{chart.xTicks.map(t=><text key={t.value} x={t.x} y={chart.baseline+24} textAnchor="middle">{t.value}</text>)}<text x="7" y="14">Y</text><text x={chart.width/2} y={chart.height-6} textAnchor="middle">X</text>
    {chart.paths.map(p=><path key={p.draw} data-fit-draw={p.draw} d={p.path}/>)}<path data-selected-fit d={chart.selected}/><path data-known-mean d={chart.truth}/><path data-average-fit d={chart.mean}/><line data-probe x1={chart.probe.x} x2={chart.probe.x} y1={chart.top} y2={chart.baseline}/><polygon data-probe-prediction points={chart.probe.square}/><polygon data-probe-truth points={chart.probe.diamond}/>{chart.points.map(p=><circle key={p.id} data-training-point={p.id} cx={p.cx} cy={p.cy} r="5"/>)}
   </svg></div><p>Thin dotted = all 32 fits; wide solid indigo = selected fit; short-dashed teal = average fit; long-dashed navy = known mean. Circles = selected targets. At the probe, hollow square = selected prediction, diamond = known mean. Coincident curves do not imply extra uncertainty; the table retains all 32 outcomes.</p>
   <div className={styles.controls}><LessonRangeControl label="Polynomial degree" value={state.degree} min={0} max={4} step={1} help="Degree 0 is constant, 1 a line, 2 allows a quadratic, 4 interpolates the five training targets. All degrees use least squares." onChange={degree=>edit({degree})}/><LessonRangeControl label="Training draw" value={state.draw} min={1} max={32} step={1} help="Select one displayed dataset and fit from the same 32 equally weighted outcomes. Aggregate error terms stay unchanged." onChange={draw=>edit({draw})}/></div><h3>Prediction location</h3><LessonToggleGroup label="Prediction location" choices={[{id:"0.5",label:"X = 0.5"},{id:"1.5",label:"X = 1.5"}]} value={String(state.probe)} onChange={probe=>edit({probe:Number(probe) as BiasState["probe"]})}/>
   <p className={styles.formula} data-bias-decomposition>At X = {state.probe}: {number(a.error)} expected squared error = {number(a.biasSquared)} squared bias + {number(a.variance)} prediction variance + {number(a.noise)} response noise (display rounded).</p><p>Summaries round to three decimals; formulas and tables use six. Expected error averages all 64 combinations of 32 training outcomes and two independent fresh response signs at this probe. This is an exact toy-distribution expectation, not a realized test score or a future-performance guarantee.</p>
  </section>
  <LessonSummaries label="Expected error components at the selected probe" summaries={[
   {label:"Squared bias",color:"#5031dc",value:number(a.biasSquared,3),definition:"Squared miss of the average fitted prediction from the known conditional mean.",formula:"(average prediction − known mean)²"},
   {label:"Prediction variance",color:"#ad4508",value:number(a.variance,3),definition:"Across 32 training outcomes at this fixed probe, not across X or one fit’s residuals.",formula:"Σ(prediction − average)² / 32"},
   {label:"Response noise",color:"#087c78",value:number(a.noise,3),definition:"Variance of a fresh ±noise response, independent of training outcomes.",formula:`amplitude² = ${a.amplitude}²`},
   {label:"Expected error",color:"#0c1230",value:number(a.error,3),definition:"Average squared gap to a fresh response over this exact finite model.",formula:"Squared bias + variance + noise"},
  ]}/>
  <section className={styles.evidence} aria-label="Exact repeated-fit evidence"><details><summary>All 32 fitted datasets</summary><div className={styles.table} role="region" tabIndex={0} aria-label="All training outcomes and predictions"><table><caption>Every draw has probability 1/32. Signs correspond to ascending X positions; draw changes only the displayed selection. Targets and predictions use six-decimal display.</caption><thead><tr>{["Draw","Signs","Y at−2","Y at−1","Y at0","Y at1","Y at2","Probe prediction","Training MSE"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.fits.map((f,i)=><tr key={f.draw} aria-current={f.draw===state.draw?"true":undefined}><th scope="row">{f.draw}{f.draw===state.draw?" (selected)":""}</th><td>{f.signs.map(v=>v>0?"+":"−").join(" ")}</td>{f.ys.map((v,j)=><td key={j}>{number(v)}</td>)}<td>{number(a.predictions[i])}</td><td>{number(f.trainMse)}</td></tr>)}</tbody></table></div></details>
   <details><summary>Compare all degrees</summary><div className={styles.table} role="region" tabIndex={0} aria-label="All degrees at the same noise and probe"><table><caption>Same noise and probe; average training MSE uses all 32 outcomes and five targets per fit. Squared bias need not fall at every location as degree increases.</caption><thead><tr>{["Degree","Squared bias","Prediction variance","Response noise","Expected error","Average training MSE"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{comparisons.map(c=><tr key={c.degree}><th scope="row">{c.degree}</th><td>{number(c.biasSquared)}</td><td>{number(c.variance)}</td><td>{number(c.noise)}</td><td>{number(c.error)}</td><td>{number(c.fits.reduce((sum,f)=>sum+f.trainMse,0)/32)}</td></tr>)}</tbody></table></div></details>
   <details><summary>Construction and limits</summary><p>Fit polynomial coefficients to minimize the sum of squared gaps on each dataset’s five targets. The mean function is known only for constructing and evaluating this toy; it does not enter the fitting procedure. For degree 4 five distinct X positions identify a unique interpolant. Curves plot 81 evaluated X positions joined by short straight segments, including both probe positions.</p><p>Each training target’s sign is independently equally likely plus or minus. Draw ID minus1 is its five-bit mask, from lowest bit at X = −2 to highest at X = 2. A fresh response at the probe has an independent plus/minus sign and the same amplitude. Its conditional mean is f(X) and noise variance is amplitude². Average over the full32-fit distribution, using variance divisor 32. Expanding squared prediction error under this independence gives squared bias + prediction variance + response noise. Expected error is also computed directly from all 64 combinations.</p><p>A single fit’s squared residual is neither squared bias nor repeated-training prediction variance. Training draw does not change the underlying distribution. Noise-free collapses all 32 weighted outcomes to identical targets; degree 2 or higher recovers this quadratic with zero error. At X = 0.5 degree 1 has more squared bias than degree 0, so neither a monotone bias curve nor a universal U-shaped total error is assumed. No sampling estimate, confidence interval, real model-selection procedure, causal conclusion or guarantee about other populations is made.</p><a href="https://scikit-learn.org/stable/auto_examples/ensemble/plot_bias_variance.html" target="_blank" rel="noreferrer">scikit-learn · Repeated-training bias, variance and noise</a></details></section>
 </LearningPage>;
}
