"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSelect, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { umapChart, umapFrame, umapNumber as number, umapPoints, umapScenarios, umapTrajectory, type UmapState } from "./umap-engine";
import { umapBaseline, reachedUmap } from "./lesson-state";
import { umapExperiments } from "./learning-experiments";
import styles from "./playground.module.css";

export function UmapPlayground() {
  const [state,setState]=useState(umapBaseline),[selected,setSelected]=useState(0),[width,setWidth]=useState(640);
  const [index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
  const chartRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const el=chartRef.current;if(!el)return;const update=()=>setWidth(Math.max(200,el.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(el);return()=>observer.disconnect();},[]);
  const run=useMemo(()=>umapTrajectory(state.scenario,state.neighbors,state.minDist),[state.scenario,state.neighbors,state.minDist]);
  const frame=useMemo(()=>umapFrame(run,state.iterations),[run,state.iterations]);
  const graph=run.graph,chart=umapChart(frame.positions,selected,width),inspected=`P${selected+1}`,experiment=umapExperiments[index],transfer=index===3;
  const reached=!!prediction&&!!experiment&&reachedUmap(index,state),complete=reached&&explanation==="0";
  function clear(){setExplanation(null);setTransferAnswer(null);}
  function start(next=index){setIndex(next);setState(umapBaseline(next));setSelected(0);setPrediction(null);clear();}
  function edit(next:UmapState){if(next.scenario===state.scenario&&next.neighbors===state.neighbors&&next.minDist===state.minDist&&next.iterations===state.iterations)return;setState(next);clear();}
  const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="umap-prediction" explanationName="umap-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores this experiment’s starting settings and P1 inspection. Reset restarts it.</>} observation={prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}
    onNext={()=>start(index+1)} nextLabel={index===2?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Change original feature units":"Inspect neighborhood evidence"}>
    {transfer?<><p>Without Guide help, compare Two groups with Scaled source at Neighbors 3, Min distance 0.2 and Optimization iterations 200. Scaled source multiplies all three features by 5. Inspect original distances, local rho/sigma, union weights and map coordinates. Must the map coordinates also multiply by 5?</p>
      {reachedUmap(3,state)&&<><ExperimentChoices legend="Transfer explanation" name="umap-transfer" choices={[
        {id:"invariant",label:"Original coordinates and distances scale by 5; local rho and sigma scale by 5 too. Their normalized distance ratios, neighbor ranks and source union weights stay the same within floating precision. With the same starting map and curve, this solver gives the same map within numerical tolerance. Map units do not recover original feature units. Nonuniform feature scaling is a different operation."},
        {id:"units",label:"Every map coordinate must multiply by 5 because UMAP reproduces original distance units exactly."},
        {id:"classes",label:"Multiplying all features by 5 creates five times as many true classes and deletes some original IDs."},
      ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="invariant"?<p role="status" className={shared.feedback}>Try again. Compare (distance−rho)/sigma before and after uniform scaling. The common factor cancels; the eight IDs remain. A map fits neighborhood membership, not the original coordinate units.</p>:<><ExperimentResult title="Transfer explained">Uniform source rescaling can leave the normalized neighborhood graph and finite map unchanged. Interpret graph connections and packing without treating map axes or global gaps as original feature units.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(4);clear();}}>Explore freely</ExperimentButton></>)}</>}
    </>:<><p>Vary neighborhood scale and map packing separately, inspect graph memberships, then compare actual optimization checkpoints. Use original vectors and source connections before interpreting apparent clusters or global gaps.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="UMAP Manifold Projection Lab" subtitle="Change graph scale; inspect map packing." rail={rail}>
    <LessonToolbar scenarios={umapScenarios} selectedId={state.scenario} onSelect={scenario=>{if(scenario!==state.scenario){edit({...state,scenario:scenario as UmapState["scenario"],iterations:0});setSelected(0);}}} onReset={()=>start(experiment||transfer?index:0)}/>
    <section className={shared.evidence} aria-label="Source graph edges on finite UMAP map">
      <h2>Your dataset</h2><p>A small deterministic UMAP graph-objective demo on eight fixed 3D points. Map axes are arbitrary, not original feature units. Full-pair optimization differs from umap-learn’s production solver. This plot auto-fits with equal axis scales. {state.iterations===0?"These are initial coordinates, before optimization.":`This is the actual ${state.iterations}-step checkpoint.`}</p>
      <div className={styles.chart} ref={chartRef}><svg data-umap-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`Equal-scale UMAP map; inspected ${inspected} has ring and label. Dashed source-union edges are drawn on current map positions; exact original/map coordinates and weights are in the table.`}>
        {chart.ticks.map(t=><g key={t.value}><line x1={t.x} x2={t.x} y1={chart.top} y2={chart.bottom}/><line x1={chart.left} x2={chart.left+chart.span} y1={t.y} y2={t.y}/><text x={t.x} y={chart.bottom+22} textAnchor="middle">{t.value.toFixed(2)}</text><text x={chart.left-12} y={t.y+4} textAnchor="end">{t.value.toFixed(2)}</text></g>)}
        <line className={styles.axis} x1={chart.left} x2={chart.left+chart.span} y1={chart.origin.y} y2={chart.origin.y}/><line className={styles.axis} x1={chart.origin.x} x2={chart.origin.x} y1={chart.top} y2={chart.bottom}/>
        <text x={chart.left+chart.span/2} y={chart.bottom+49} textAnchor="middle">Map coordinate 1</text><text x={chart.left+chart.span/2} y="16" textAnchor="middle">Vertical: map coordinate 2</text>
        {chart.points.map((p,j)=>graph.union[selected][j]>0&&<line data-umap-edge={p.id} key={p.id} className={styles.edge} style={{strokeWidth:number(1+3*graph.union[selected][j])}} x1={chart.selected.x} y1={chart.selected.y} x2={p.x} y2={p.y}/>)}
        {chart.points.map(p=><circle data-umap-point={p.id} key={p.id} cx={p.x} cy={p.y} r="4" className={styles.circle}/>)}
        <circle data-umap-selected={inspected} cx={chart.selected.x} cy={chart.selected.y} r="10" className={styles.selected}/><text data-umap-label x={chart.selected.x+chart.selected.labelX} y={chart.selected.y+chart.selected.labelY} textAnchor={chart.selected.anchor}>{inspected}</text>
      </svg></div>
      <p>Dashed spokes show source union connections on current map positions. Thickness is 1+3×weight; spoke length is map distance, not original distance. Choose Inspect point to locate any ID. Only its label is shown; every exact row remains at overlaps. Points are not draggable.</p>
      <div className={shared.controlGrid}><LessonRangeControl label="Neighbors" value={state.neighbors} min={3} max={6} step={1} help="Count other IDs used in each source neighborhood; changing it restarts at 0." onChange={neighbors=>edit({...state,neighbors,iterations:0})}/><LessonRangeControl label="Min distance" value={state.minDist} min={0} max={.8} step={.2} help="Shape the soft map-membership curve at fixed spread 1; this is not a hard distance bound. Changing it restarts at 0." onChange={minDist=>edit({...state,minDist,iterations:0})}/><LessonRangeControl label="Optimization iterations" value={state.iterations} min={0} max={200} step={50} help="Inspect actual fifty-step checkpoints; a finite run is not a certified global optimum." onChange={iterations=>edit({...state,iterations})}/></div>
      <LessonSelect label="Inspect point" value={String(selected)} choices={chart.points.map((p,i)=>({id:String(i),label:p.id}))} onChange={id=>setSelected(Number(id))}/>
      <p role="status" data-umap-status className={shared.math}>{umapScenarios.find(s=>s.id===state.scenario)!.label} · Neighbors {state.neighbors} · Min distance {state.minDist} · Iterations {state.iterations} · Inspect {inspected} · Components {graph.components} · Loss {number(frame.loss)}</p>
    </section>
    <section className={shared.evidence} aria-label="Source graph and map membership">
      <p data-umap-construction className={shared.math}>Inspect {inspected}: rho = {number(graph.rows[selected].rho)}; sigma = {number(graph.rows[selected].sigma)}. Directed u = exp(−max(0,d−rho)/sigma) for selected neighbors; source union w = u+v−uv. Map q = 1/[1+a×(distance²+10⁻¹²)ᵇ], a = {number(run.curve.a)}, b = {number(run.curve.b)}.</p>
      <p>Rho is the nearest positive source distance; sigma sets local distance scale. Membership means edge strength between 0 and 1. Directed rows sum log₂(Neighbors), not 1. Source union weights and map memberships are not normalized probability rows or global joint distributions. Self is excluded. A graph component is a group linked by paths, not a proved semantic class.</p>
      <div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="All eight identities, source and map coordinates, and inspected membership row"><table><caption>Every ID retains exact original and current map coordinates. Non-neighbor directed weight is exactly zero; reverse connections can still give positive union weight. Values are rounded for display; all calculations use full precision.</caption><thead><tr>{["Case","Original (F1,F2,F3)","Map (X,Y)","Source distance",`u(${inspected}→j)`,`u(j→${inspected})`,`w${selected+1}j`,`q${selected+1}j`].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{umapPoints[state.scenario].map((p,j)=><tr data-umap-row={`P${j+1}`} key={j}><th scope="row">P{j+1}{j===selected&&" (self)"}</th><td>({p.map(number).join(", ")})</td><td>({frame.positions[j].map(number).join(", ")})</td><td>{number(graph.distances[selected][j])}</td><td>{number(graph.directed[selected][j])}</td><td>{number(graph.directed[j][selected])}</td><td>{number(graph.union[selected][j])}</td><td>{number(frame.q[selected][j])}</td></tr>)}</tbody></table></div>
      <p data-umap-evidence className={shared.math}>Directed row sum {number(graph.rows[selected].sum)} = log₂({state.neighbors}); {graph.edges} positive union edges; {graph.components} connected components. Source-weighted mean map-edge distance {number(frame.weightedDistance)} = Σi&lt;j wᵢⱼ×map distance / Σi&lt;j wᵢⱼ. This describes packing for a fixed graph; it is not task quality.</p>
    </section>
    <LessonSummaries label="Source connectivity and finite map fit" summaries={[
      {label:"Graph components",color:"#5031dc",value:String(graph.components),definition:"Groups linked by positive union edges.",formula:`${graph.edges} edges among 28 possible pairs`,comparison:"Graph connectivity is not true semantic class count."},
      {label:"Fit loss",color:"#087c78",value:number(frame.loss),definition:"Bernoulli graph-fit divergence, in nats.",formula:"Σi<j [w ln(w/q)+(1−w) ln((1−w)/(1−q))]",comparison:"Compare fitting for fixed graph/curve; not accuracy."},
      {label:"Closest map pair",color:"#ad4508",value:number(frame.minimumDistance),definition:"Smallest distance among the 28 map pairs.",formula:"min i<j ||yᵢ−yⱼ||",comparison:"Min distance shapes a curve; no hard lower bound."},
    ]}/>
    <section className={shared.evidence} aria-label="UMAP construction and solver limits"><details><summary>Construction and limits</summary>
      <p>Eight fixed three-feature vectors use equal Euclidean weights without standardization. This demo follows the paper’s k-other-neighbors convention. Exact ranks use distance then ID for ties; local connectivity uses the nearest positive distance and sigma is searched to match log₂(k). It does not reproduce umap-learn’s self-containing neighbor-array convention or every supported data case. Union w=u+v−uv is symmetric with no extra normalization.</p>
      <p>At fixed spread 1, five supported Min distance settings use precomputed a/b coefficients from the official nonlinear least-squares convention: 300 samples on [0,3] fit a smooth 1/(1+a×distance²ᵇ) curve to an offset exponential. The optimizer uses distance²+10⁻¹² for finite zero-distance evaluation. Min distance is not a hard constraint; it shapes the curve.</p>
      <p>The loss sums Bernoulli divergence over all 28 unordered nonself pairs, in nats. Terms with zero weight contribute zero by continuity. The source entropy term is retained, so this differs from cross-entropy-only reports by a graph-dependent constant. The gradient is 2bΣj(w−q)(yᵢ−yⱼ)/(distance²+10⁻¹²). Each deterministic step tries rate 1 with up to 24 halvings, accepts nonincrease and recenters; if no trial is accepted the map stays fixed. All 200 frames use one fixed initial coordinate array.</p>
      <p>This is full-pair fitting of the UMAP graph objective, without approximate-neighbor search, spectral initialization, stochastic edge sampling or negative sampling. It is a small teaching demo, not umap-learn output or performance parity. Finite maps do not certify a global optimum, original global distances, semantic clusters or downstream quality. The plot auto-fits and preserves equal scales; every exact coordinate stays in the table.</p>
      <p>Scenario/Neighbors/Min distance edits restart optimization at 0 and clear stale answers; checkpoint edits also clear them. Inspect point only changes evidence and preserves mastery. Prediction/Reset restores the current baseline; free-exploration Reset starts Experiment 1. Uniform scaling changes original units and local scales together; nonuniform feature scaling can change neighborhoods. No transforms, inverse reconstruction, arbitrary uploads, automatic best settings or production benchmarks are included.</p>
      <a href="https://arxiv.org/abs/1802.03426" target="_blank" rel="noreferrer">McInnes, Healy & Melville · Original UMAP paper</a><br/><a href="https://umap-learn.readthedocs.io/en/latest/how_umap_works.html" target="_blank" rel="noreferrer">UMAP documentation · Graph membership and optimization</a><br/><a href="https://umap-learn.readthedocs.io/en/latest/_modules/umap/umap_.html" target="_blank" rel="noreferrer">UMAP implementation · Curve fitting convention</a>
    </details></section>
  </LearningPage>;
}
