"use client";
import { useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSelect, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeAutograd, formatNumber as f, functionValue, getDefaultValues, getFormulaDefinition, learningRate, sliceCharts, type FormulaId, type ParameterKey } from "./autograd-graphs-engine";
import { autogradExperiments, autogradTransferStart, autogradTransferTarget, type AutogradState } from "./learning-experiments";
import { GraphFigure, SliceFigure } from "./TraceFigures";
import styles from "./playground.module.css";
const same=(a:AutogradState,b:AutogradState)=>a.formula===b.formula&&a.stage===b.stage&&getFormulaDefinition(a.formula).parameters.every(p=>a.values[p.key]===b.values[p.key]);
export function AutogradGraphsPlayground(){
 const [state,setState]=useState<AutogradState>(autogradExperiments[0].baseline),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const analysis=analyzeAutograd(state.formula,state.values),definition=analysis.definition,experiment=autogradExperiments[index],transfer=index===5,backward=state.stage==="backward";
 const reached=!!prediction&&!!experiment&&same(state,experiment.target)&&(index===2||index===3?state.curves&&state.parameter===experiment.target.parameter:index===4?state.preview:true),complete=reached&&explanation==="0",transferReached=same(state,autogradTransferTarget)&&state.curves&&state.parameter==="b";
 const other=definition.parameters.find(p=>p.key!==state.parameter)!,charts=sliceCharts(analysis,state.parameter),proposed={...state.values,...Object.fromEntries(analysis.updatePreview.map(r=>[r.key,r.after]))},proposedOutput=functionValue(state.formula,proposed);
 function clear(){setExplanation(null);setTransferAnswer(null);}
 function edit(next:AutogradState){setState(next);clear();}
 function start(next=index){setIndex(next);setState(autogradExperiments[next]?.baseline??autogradTransferStart);setPrediction(null);clear();}
 function selectFormula(id:FormulaId){const d=getFormulaDefinition(id);edit({...state,formula:id,values:getDefaultValues(d),parameter:id==="polynomial"?"b":id==="sigmoid"?"x":"m"});}
 const rail=experiment?<ExperimentRail label={`Experiment ${index+1} of 5`} title={experiment.title} phase={!prediction?0:reached?2:1}>
 {!reached&&<><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="autograd-prediction" choices={experiment.predictions} value={prediction} onChange={id=>{start();setPrediction(id);}}/><p className={shared.small}>A different prediction restores starting settings. Reset restarts this experiment.</p></>}
 {prediction&&!reached&&<p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
 {reached&&<><p role="status" className={shared.observation}>{prediction==="0"?"Your prediction matches the evidence.":"The numeric evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="autograd-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation}/>{explanation&&!complete&&<p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
 {complete&&<><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={()=>start(index+1)}>{index===4?"Try the transfer check":"Next experiment"}</ExperimentButton></>}
 </ExperimentRail>:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"A finite edit at zero slope":"Explore the three graphs"}>
 {transfer?<><p>Polynomial starts at a=−4, b=2. Its two messages to b cancel, so df/db=0 and f=−4. Predict a finite edit: set b to 2.5 with a fixed, then explain the new output without Guide help.</p><ExperimentChoices legend="Transfer explanation" name="autograd-transfer" choices={[{id:"local",label:"The new output is −3.75, a change of 0.25. Zero derivative at b=2 is a local slope; the quadratic still changes under this finite edit with a fixed."},{id:"constant",label:"A zero derivative proves the function is constant for every b."},{id:"trained",label:"Backward trained a new value of a to make the output change."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!transferReached?<p role="status" className={shared.feedback}>First set b to 2.5, keeping Polynomial, a=−4, Backward, Curve parameter b and its slices open. Reset restores b=2.</p>:transferAnswer!=="local"?<p role="status" className={shared.feedback}>Try again. This is a finite move on a curved function. Only b was edited; the backward view and zero local slope did not change a.</p>:<><ExperimentResult title="Transfer explained">A stationary point has zero local derivative, while a finite edit can change a curved function. The new calculation recomputes gradients; no optimizer was applied.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(6);clear();}}>Explore freely</ExperimentButton></>)}</>:<><p>Switch formulas, edit either argument, inspect both stages and compare either parameter’s slices. The optional preview never changes the editors. Reset restarts experiments.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
 </ExperimentRail>;
 return <LearningPage title="Autograd Graphs" subtitle="Cache values. Multiply backward. Add shared paths." rail={rail}>
 <LessonToolbar scenarios={[{id:"polynomial",label:"Polynomial",shortLabel:"Multiply, square, add"},{id:"sigmoid",label:"Sigmoid",shortLabel:"Squash a product"},{id:"squared-error",label:"Squared error",shortLabel:"Fixed x=2, y=5"}]} selectedId={state.formula} onSelect={id=>selectFormula(id as FormulaId)} onReset={()=>start(experiment||transfer?index:0)}/>
 <section className={styles.evidence} aria-label="Formula and arguments"><h2>Your dataset · two adjustable arguments</h2><p className={styles.formula} data-formula>{definition.expression}</p><p>{state.formula==="squared-error"?"m is slope, c is intercept. Fixed x=2, y=5; error=2m+c−5 and L=error².":state.formula==="sigmoid"?"Sigmoid squashes w×x into (0,1). Both arguments are adjustable; the output is not automatically a probability.":"b feeds multiply and square; add their outputs to get f."}</p><div className={styles.controls}>{definition.parameters.map(p=><LessonRangeControl key={p.key} label={p.label} value={state.values[p.key]} min={p.min} max={p.max} step={p.step} help="Edit one argument. The other stays fixed; all current values and gradients are recomputed." onChange={value=>edit({...state,values:{...state.values,[p.key]:value}})}/>)}</div>
 <LessonToggleGroup label="Graph stage" choices={[{id:"forward",label:"Forward"},{id:"backward",label:"Backward"}]} value={state.stage} onChange={id=>edit({...state,stage:id as AutogradState["stage"]})}/><p>Backward shows local output sensitivity with other arguments fixed. Switching views never updates parameters.</p></section>
 <section className={styles.evidence} aria-label="Computation graph"><h2>{backward?"Follow the backward messages":"Follow the forward cache"}</h2><GraphFigure analysis={analysis} backward={backward}/><p>{backward?"Pink arrows return output sensitivities, opposite the forward computation. Backward starts with output sensitivity 1. Each node shows total sensitivity after adding its incoming messages; fixed x,y are not requested targets.":"Blue arrows carry current cached values. Each node follows from its inputs; the table supplies the same evidence in text. Focus a graph or table area and use arrow keys to scroll at narrow widths."}</p></section>
 <LessonSummaries label="Current calculation" summaries={[{label:state.formula==="squared-error"?"Loss L":"Output f",color:"#167d59",value:f(analysis.output),definition:"Value of the selected formula at the current arguments.",formula:definition.expression},...definition.parameters.map(p=>({label:backward?`Gradient for ${p.key}`:`Current ${p.key}`,color:backward?"#b72f62":"#1470ba",value:f(backward?analysis.gradients[p.key]:state.values[p.key]),definition:backward?`Local output sensitivity to ${p.key}, with the other argument fixed.`:"Manually selected input; neither view changes it.",formula:backward?`d${state.formula==="squared-error"?"L":"f"}/d${p.key}`:"No optimizer applied"}))]}/>
 {backward&&<section className={styles.evidence} aria-label="Backward reconciliation"><h2>Multiply locally; add shared paths</h2>{state.formula==="polynomial"?<p className={styles.sum} data-path-sum>To b: {f(state.values.a)} from multiply + {f(2*state.values.b)} from square = {f(analysis.gradients.b)}. To a: {f(state.values.b)}. Each total is a sensitivity, not a new parameter value.</p>:state.formula==="sigmoid"?<p className={styles.sum} data-path-sum>Local sigmoid derivative f(1−f) = {f(analysis.output*(1-analysis.output))}. df/dx = local × w = {f(analysis.gradients.x)}; df/dw = local × x = {f(analysis.gradients.w)}.</p>:<p className={styles.sum} data-path-sum>error = {f(2*state.values.m+state.values.c-5)}; square’s local derivative 2×error = {f(2*(2*state.values.m+state.values.c-5))}. dL/dm = 2×error×2 = {f(analysis.gradients.m)}; dL/dc = 2×error = {f(analysis.gradients.c)}.</p>}<details><summary>Backward message details</summary><p>Incoming is sensitivity of the final output to the source node. Local is sensitivity of that source operation to this destination input. Their product is one returning message; multiple messages reaching a shared node add.</p><div className={styles.table} tabIndex={0} role="region" aria-label="Backward messages table scroll area"><table><caption>One reverse pass. Fixed constants are omitted as differentiation targets.</caption><thead><tr><th scope="col">Return edge</th><th scope="col">Incoming</th><th scope="col">Local</th><th scope="col">Message</th></tr></thead><tbody>{analysis.messages.map((m,i)=><tr key={i} data-message={`${m.from}-${m.to}`}><th scope="row">{m.from} → {m.to}</th><td>{f(m.incoming)}</td><td>{f(m.local)}</td><td>{f(m.message)}</td></tr>)}</tbody></table></div></details></section>}
 <section className={styles.evidence}><details open={state.curves} onToggle={e=>{if(e.currentTarget.open!==state.curves)edit({...state,curves:e.currentTarget.open});}}><summary>Function and derivative slices</summary><LessonSelect label="Curve parameter" choices={definition.parameters.map(p=>({id:p.key,label:p.label}))} value={state.parameter} onChange={id=>edit({...state,parameter:id as ParameterKey})}/><p data-held-argument>Holding {other.key}={f(state.values[other.key])} fixed. Each function curve varies only {state.parameter}; the paired derivative curve is its local slope at each position. A zero slope at a stationary point does not make a curved function constant. Zero is explicitly marked; axes adapt to the selected slice.</p><div className={styles.charts}>{charts.map(chart=><div className={styles.chartScroll} key={chart.yLabel}><SliceFigure chart={chart}/></div>)}</div></details>
 <details open={state.preview} onToggle={e=>{if(e.currentTarget.open!==state.preview)edit({...state,preview:e.currentTarget.open});}}><summary>One-step preview</summary><p>This proposes simultaneous changes using the same original gradients, with fixed rate {learningRate}. It leaves the input editors and current graph unchanged. Proposals are not clipped to slider bounds. On Polynomial and Sigmoid, this is a mathematical descent preview for f; only Squared error defines a loss, and x,y there stay fixed. A finite step has no universal improvement guarantee.</p><div className={styles.table} tabIndex={0} role="region" aria-label="Optimizer proposal table scroll area"><table><caption>Separate optimizer proposal: new = current − 0.1×gradient.</caption><thead><tr><th scope="col">Argument</th><th scope="col">Current</th><th scope="col">Gradient</th><th scope="col">Proposed</th></tr></thead><tbody>{analysis.updatePreview.map(r=><tr key={r.key} data-update={r.key}><th scope="row">{r.key}</th><td>{f(r.before)}</td><td>{f(r.gradient)}</td><td>{f(r.after)}</td></tr>)}</tbody></table></div><p className={styles.formula} data-preview-output>Current output {f(analysis.output)}; proposed output {f(proposedOutput)}. No step is applied.</p></details>
 <details><summary>What this model includes</summary><p>Three fixed scalar formulas illustrate reverse-mode autograd through analytically evaluated operations and derivatives. No framework graph capture, optimizer execution, or repeated-call gradient accumulator runs here. In real PyTorch, backward computes gradients; optimizer steps change parameters separately. Summing different paths within one backward pass differs from accumulating .grad across repeated backward calls.</p><p>Parameter slices hold the other argument fixed; the update preview moves both simultaneously. The toy domains use the displayed original ranges and 0.1 edits. Preview proposals can lie outside those editing ranges. Cached values, local derivatives, returning messages, accumulated input gradients and updated parameters are distinct quantities. Labels are rounded, with scientific notation retaining tiny nonzero values.</p><p><a href="https://docs.pytorch.org/docs/2.14/notes/autograd.html" target="_blank" rel="noreferrer">PyTorch autograd mechanics</a> · <a href="https://docs.pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html" target="_blank" rel="noreferrer">Autograd tutorial</a></p></details></section>
 </LearningPage>;
}
