import type { AutogradTrace, ChartLine } from "./autograd-graphs-engine";
import { formatNumber as f } from "./autograd-graphs-engine";
import styles from "./playground.module.css";
export function GraphFigure({analysis,backward}:{analysis:AutogradTrace;backward:boolean}) {
 const nodes=analysis.graph.nodes,byId=new Map(nodes.map(n=>[n.id,n])),edges=backward?analysis.graph.backwardEdges:analysis.graph.forwardEdges,color=backward?"#b72f62":"#1470ba";
 return <><div className={styles.graphScroll} tabIndex={0} role="region" aria-label="Computation graph scroll area"><svg className={styles.graph} viewBox="0 0 760 350" role="img" aria-label={backward?"Backward output sensitivities, opposite the forward arrows":"Forward computation and current cached values"}><defs><marker id="autograd-message-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0 L7 3.5 L0 7Z" fill={color}/></marker></defs>
 {edges.map((e,i)=>{const a=byId.get(e.from)!,b=byId.get(e.to)!,dx=b.x-a.x,dy=b.y-a.y,t=1/Math.max(Math.abs(dx)/54,Math.abs(dy)/38),x1=a.x+dx*t,y1=a.y+dy*t,x2=b.x-dx*t,y2=b.y-dy*t;return <g key={i} aria-hidden="true"><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={color} strokeWidth="2" markerEnd="url(#autograd-message-arrow)"/><title>{backward?`${e.from} → ${e.to}: message ${f(analysis.messages[i].message)}`:`${e.from} → ${e.to}: cached value`}</title></g>;})}
 {nodes.map(n=><g key={n.id} aria-hidden="true" data-graph-node={n.id}><rect x={n.x-54} y={n.y-38} width="108" height="76" rx="5" fill="white" stroke={n.tone==="constant"?"#8a94a8":color}/><text x={n.x} y={n.y-18} textAnchor="middle" className={styles.nodeName}>{n.label}</text><text x={n.x} y={n.y+2} textAnchor="middle">{backward?n.tone==="constant"?"fixed constant":"output sensitivity":n.subLabel}</text><text x={n.x} y={n.y+24} textAnchor="middle" className={styles.nodeValue} data-node-value={n.tone==="constant"&&backward?"constant":backward?analysis.nodeGradients[n.id]:n.value}>{backward?n.tone==="constant"?"not requested":f(analysis.nodeGradients[n.id]):f(n.value)}</text></g>)}
 </svg></div><div className={styles.table} tabIndex={0} role="region" aria-label="Node values table scroll area"><table><caption>Exact node values{backward?" and total output sensitivities":""}. Numeric display uses nine significant digits, with scientific notation for tiny nonzero values.</caption><thead><tr><th scope="col">Node</th><th scope="col">Operation</th><th scope="col">Cached value</th>{backward&&<th scope="col">Output sensitivity</th>}</tr></thead><tbody>{nodes.map(n=><tr key={n.id} data-node-row={n.id}><th scope="row">{n.label}</th><td>{n.subLabel}</td><td data-cached={n.value}>{f(n.value)}</td>{backward&&<td data-gradient={n.tone==="constant"?"constant":analysis.nodeGradients[n.id]}>{n.tone==="constant"?"Not requested":f(analysis.nodeGradients[n.id])}</td>}</tr>)}</tbody></table></div></>;
}
const tick=(v:number)=>v===0?"0":Math.abs(v)<.001?v.toExponential(2):String(Number(v.toPrecision(3)));
export function SliceFigure({chart}:{chart:ChartLine}) {
 const width=320,height=190,left=60,right=15,top=15,bottom=35;
 const minX=chart.samples[0].x,maxX=chart.samples.at(-1)!.x,ys=[0,chart.currentY,...chart.samples.map(p=>p.y)],low=Math.min(...ys),high=Math.max(...ys),padding=Math.max((high-low)*.12,.001),minY=low-padding,maxY=high+padding;
 const x=(v:number)=>left+(v-minX)/(maxX-minX)*(width-left-right),y=(v:number)=>top+(maxY-v)/(maxY-minY)*(height-top-bottom);
 const path=chart.samples.map((p,i)=>`${i?"L":"M"}${x(p.x).toFixed(4)} ${y(p.y).toFixed(4)}`).join(" "),color=chart.yLabel==="gradient"?"#b72f62":"#1470ba";
 return <figure className={styles.chart}><figcaption><strong>{chart.label}</strong><span data-chart-current={chart.yLabel}>{chart.xLabel}={f(chart.currentX)}; {chart.yLabel}={f(chart.currentY)}</span></figcaption><svg viewBox="0 0 320 190" role="img" aria-label={`${chart.label} against ${chart.xLabel}; exact current values in caption`} data-chart={chart.yLabel} data-min-y={minY} data-max-y={maxY}><g aria-hidden="true">{[minY,0,maxY].map((v,i)=><g key={i}><line x1={left} x2={width-right} y1={y(v)} y2={y(v)} stroke={v===0?"#76839b":"#dfe4f4"}/><text x={left-6} y={y(v)+4} textAnchor="end">{tick(v)}</text></g>)}<line x1={left} x2={left} y1={top} y2={height-bottom} stroke="#76839b"/><path data-slice-path d={path} stroke={color} fill="none" strokeWidth="2"/><line x1={x(chart.currentX)} x2={x(chart.currentX)} y1={top} y2={height-bottom} stroke="#9fa9bd" strokeDasharray="3 3"/><circle data-slice-dot data-value={chart.currentY} cx={x(chart.currentX)} cy={y(chart.currentY)} r="4" fill={color}/><text x={left} y={height-15}>{minX}</text><text x={width-right} y={height-15} textAnchor="end">{maxX}</text><text x={(left+width-right)/2} y={height-8} textAnchor="middle">{chart.xLabel}</text></g></svg></figure>;
}
