"use client";
import { useMemo, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSelect, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeMask, editMask, maskBaseline, maskPresetId, maskQueries, maskScenarios, maskTokens, sameMask, type MaskState } from "./mask-engine";
import { maskExperiments } from "./learning-experiments";
import { reachedMask } from "./lesson-state";
import styles from "./playground.module.css";

export function MaskPlayground() {
  const [state, setState] = useState<MaskState>(maskBaseline);
  const [index, setIndex] = useState(0), [prediction, setPrediction] = useState<string | null>(null), [explanation, setExplanation] = useState<string | null>(null), [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const a = useMemo(() => analyzeMask(state), [state]), experiment = maskExperiments[index], transfer = index === 3;
  const reached = !!prediction && !!experiment && reachedMask(index, state), complete = reached && explanation === "0";
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function start(next = index) { setIndex(next); setState(maskBaseline()); setPrediction(null); clear(); }
  function edit(next: MaskState) { if (!sameMask(state, next)) { setState(next); clear(); } }
  const rail = experiment ? <ExperimentRail label={`Experiment ${index + 1} of 3`} title={experiment.title} phase={!prediction ? 0 : reached ? 2 : 1}>
    {!reached && <><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="mask-prediction" choices={experiment.predictions} value={prediction} onChange={id => { start(); setPrediction(id); }} /><p className={shared.small}>Changing prediction restores Early slice. Reset restarts this experiment.</p></>}
    {prediction && !reached && <p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
    {reached && <><p role="status" className={shared.observation}>{prediction === "0" ? "The evidence matches your prediction." : "The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="mask-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation} />{explanation && !complete && <p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
    {complete && <><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={() => start(index + 1)}>{index === 2 ? "Try the transfer check" : "Next experiment"}</ExperimentButton></>}
  </ExperimentRail> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Combine independent conditions" : "Explore token eligibility"}>
    {transfer ? <><p>Without Guide help, choose Padding contrast. Choose Allow under Padding keys and Causal under Attention direction, in either order. Reconstruct the eligible keys for query 6 · mat. Explain why removing padding-key exclusion can still leave the padding keys blocked.</p>{reachedMask(3, state) && <><ExperimentChoices legend="Transfer explanation" name="mask-transfer" choices={[
      { id: "intersection", label: "Keys 3–6 pass; past=3, self=1, future=0. Keys 1–2 are outside window 3–8. Keys 7–8 pass the padding setting but are future to query 6, so causal still blocks them. Permission is not a weight; padding query rows stay excluded by separate demo policy." },
      { id: "override", label: "Allow padding overrides every other mask, so keys 7–8 must become eligible under Causal too." },
      { id: "weight", label: "A check proves attention weight 1 and guarantees that the token contributes to the model output." },
    ]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (transferAnswer !== "intersection" ? <p role="status" className={shared.feedback}>Try again. Every condition must pass independently. Read each key’s reason; eligibility does not determine an attention weight or model output.</p> : <><ExperimentResult title="Transfer explained">Removing one exclusion leaves other conditions intact. Window, direction and padding-key eligibility are separate questions.</ExperimentResult><ExperimentButton onClick={() => { setIndex(4); clear(); }}>Explore freely</ExperimentButton></>)}</>}</> : <><p>Try all three presets, all six query tokens, both Attention direction and Padding keys settings, and window boundaries. Length changes clamp Window start if needed but never move the query. Try a query outside the slice, including a padding-only window at start 7, length 2. An inactive query has no eligible keys; this demo invents no attention output for it.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Context Windows & Attention Masks" subtitle="Move the context window. See which keys each query may use." rail={rail}>
    <LessonToolbar scenarios={maskScenarios} selectedId={maskPresetId(state)} onSelect={id => edit(maskBaseline(id))} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={styles.evidence} aria-label="Token eligibility matrix"><h2>Your dataset</h2><p>A query is the token seeking context; a key is a candidate token it may use. Read query tokens down rows and key tokens across columns. These eight illustrative global positions stay fixed. &lt;PAD&gt; is a filler slot, not real text. The shared window contains positions <strong data-mask-window>{state.start}–{a.last}</strong>.</p>
      <div className={styles.table} tabIndex={0} role="region" aria-label="Eight query rows and eight key columns"><table><caption>✓ Allowed · × Blocked. Permission, not attention weight. Highlighted row: query {state.query} · {maskTokens[state.query - 1]}. Padding query rows are excluded by a separate demo policy.</caption><thead><tr><th scope="col">Query ↓ / Key →</th>{maskTokens.map((token, k) => <th key={k} scope="col">{k + 1}<span>{token}</span></th>)}</tr></thead><tbody>{a.matrix.map((row, q) => <tr key={q} data-mask-query={q + 1} aria-current={q + 1 === state.query ? "true" : undefined}><th scope="row">{q + 1} · {maskTokens[q]}</th>{row.map((reason, k) => <td key={k} data-mask-key={k + 1} data-mask-reason={reason} className={reason === "Allowed" ? styles.allowed : undefined} title={reason}><span aria-hidden="true">{reason === "Allowed" ? "✓" : "×"}</span><span className={styles.sr}>Query {q + 1} · {maskTokens[q]} to key {k + 1} · {maskTokens[k]}: {reason}</span></td>)}</tr>)}</tbody></table></div>
      <div className={styles.controls}><LessonRangeControl label="Window start" value={state.start} min={1} max={9 - state.length} step={1} help="First global position in the shared slice. Moving it does not move or renumber the query." onChange={v => edit(editMask(state, "start", v))} /><LessonRangeControl label="Window length" value={state.length} min={1} max={8} step={1} help="Number of slots in the slice, including any padding. A longer slice clamps start if needed; the query stays fixed." onChange={v => edit(editMask(state, "length", v))} /><LessonSelect label="Query token" choices={maskQueries} value={String(state.query)} onChange={v => edit(editMask(state, "query", Number(v)))} /><div><h3>Attention direction</h3><LessonToggleGroup label="Attention direction" choices={[{ id: "causal", label: "Causal" }, { id: "bidirectional", label: "Bidirectional" }]} value={state.direction} onChange={v => edit({ ...state, direction: v as MaskState["direction"] })} /></div><div><h3>Padding keys</h3><LessonToggleGroup label="Padding keys" choices={[{ id: "exclude", label: "Exclude" }, { id: "allow", label: "Allow" }]} value={state.padding} onChange={v => edit({ ...state, padding: v as MaskState["padding"] })} /></div></div>
      <p role="status" data-mask-status>{a.active ? `Query ${state.query} · ${maskTokens[state.query - 1]} is active in window ${state.start}–${a.last}. Eligible keys: ${a.keys.map(k => `${k} · ${maskTokens[k - 1]}`).join(", ")}.` : `Query ${state.query} · ${maskTokens[state.query - 1]} is outside window ${state.start}–${a.last}: inactive, with no eligible keys. No attention weights or output are computed.`}</p><p className={shared.small}>Actual changes to any control clear stale explanations and transfer answers. Reapplying the same state preserves them. The table is read-only: use the controls to edit and arrow keys to scroll a focused table.</p>
    </section>
    <LessonSummaries label="Selected-query eligible key counts" summaries={[
      { label: "Eligible keys", color: "#5031dc", value: String(a.count), definition: "Keys passing every eligibility condition.", formula: "in window AND padding rule AND direction", comparison: a.active ? "Eligibility does not specify attention magnitude or guarantee use." : "Inactive query: no eligible keys or computed attention result." },
      { label: "Past keys", color: "#087c78", value: String(a.past), definition: "Eligible keys before the selected query.", formula: "eligible key position < query position", comparison: "A past key outside the slice is still unavailable." },
      { label: "Self / future", color: "#ad4508", value: `${a.self} / ${a.future}`, definition: "Eligible self and later-position keys.", formula: "key = query / key > query", comparison: "An active causal query permits self and excludes future keys." },
    ]} />
    <section className={styles.evidence} aria-label="Selected-query key reasons"><h2>Why each key passes or fails</h2><p>All conditions must pass. Causal allows key position ≤ query position, including self. Bidirectional permits either direction in this comparison. Exclude removes padding keys; Allow removes that condition only. The table names the first failing condition, so more than one condition may block a key.</p><div className={`${styles.table} ${styles.reasons}`} tabIndex={0} role="region" aria-label="Eight selected-query key reasons"><table><caption>Query {state.query} · {maskTokens[state.query - 1]} · Window {state.start}–{a.last} · {state.direction} · padding keys {state.padding}</caption><thead><tr><th scope="col">Key position</th><th scope="col">Token</th><th scope="col">Eligibility or first reason</th></tr></thead><tbody>{a.matrix[state.query - 1]!.map((reason, k) => <tr key={k}><th scope="row">{k + 1}</th><td>{maskTokens[k]}</td><td>{reason === "Allowed" ? "✓ Allowed" : `× ${reason}`}</td></tr>)}</tbody></table></div></section>
    <section className={styles.evidence} aria-label="Mask construction and limits"><details><summary>Construction and limits</summary><p>This is one global shared slice, not a rolling local-attention band for each query or a model’s maximum context capacity. Window length counts all slots, including padding. Editing length clamps start to stay inside positions 1–8; the selected query never moves or renumbers. The Query token control offers only the six real tokens. Padding query rows are always excluded by explicit demo policy, independently of the padding-key setting: a key-padding mask by itself does not generally exclude query rows.</p><p>For an active real query, a key is eligible exactly when it is inside the slice, passes the padding-key setting, and passes the direction setting. The first-failing reason order is padding query, query outside window, key outside window, padding key excluded, then future key blocked. Multiple conditions can fail. An outside query is inactive and has no eligible keys; the lab does not invent weights or outputs for all-blocked rows.</p><p>Checks are semantic permission labels, not an API’s Boolean encoding: PyTorch MultiheadAttention uses Boolean True to block, while scaled_dot_product_attention uses True to allow. No attention scores, softmax, vectors, model output, prediction, training or tokenizer run here. Permission alone does not guarantee nonzero attention weight or a contribution to output. Bidirectional and Allow padding are deliberate comparisons, not recommendations for a causal language model.</p><p>Early slice uses start 1, length 4, query 4, Causal and Exclude. Later slice uses start 3, length 4, query 6, Causal and Exclude. Padding contrast uses start 3, length 6, query 6, Bidirectional and Exclude. Reset and predictions restore Early slice in the current experiment; free Reset starts Experiment 1.</p><a href="https://docs.pytorch.org/docs/2.14/generated/torch.nn.MultiheadAttention.html" target="_blank" rel="noreferrer">PyTorch · Attention and padding-key masks</a><br /><a href="https://docs.pytorch.org/docs/2.14/generated/torch.nn.functional.scaled_dot_product_attention.html" target="_blank" rel="noreferrer">PyTorch · Causal eligibility and Boolean mask convention</a></details></section>
  </LearningPage>;
}
