"use client";
import {useMemo,useState} from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonSelect, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import {analyzePreference,displayChoices,judgeChoices,preferenceBaseline,preferenceNumber as number,preferencePresetId,preferenceScenarios,rubricChoices,samePreference,sequenceChoices,type PreferenceState} from "./preference-engine";
import {preferenceExperiments} from "./learning-experiments";
import {reachedPreference} from "./lesson-state";
import styles from "./playground.module.css";

export function PreferencePlayground(){
 const[state,setState]=useState<PreferenceState>(preferenceBaseline);
 const[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const a=useMemo(()=>analyzePreference(state),[state]),experiment=preferenceExperiments[index],transfer=index===4,reached=!!prediction&&!!experiment&&reachedPreference(index,state),complete=reached&&explanation==="0";
 function clear(){setExplanation(null);setTransferAnswer(null);}
 function start(next=index){setIndex(next);setState(preferenceBaseline());setPrediction(null);clear();}
 function edit(next:PreferenceState){if(!samePreference(state,next)){setState(next);clear();}}
 const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 4`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="preference-prediction" explanationName="preference-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores Accuracy first. Reset restarts this experiment.</>} observation={prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}
    onNext={()=>start(index+1)} nextLabel={index===3?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Transfer the evaluator and rating convention":"Explore preferences and rankings"}>
  {transfer?<><p>Without Guide help, set Rubric to Balanced, Judge rule to Longer-answer bonus +2, Display order to B first and Rating sequence to P6 → P1. Reconstruct P1/P3’s judged scores, count A/B/Tie and reference matches, then inspect the first rating update. Does B first change the length rule?</p>
   {reachedPreference(4,state)&&<><ExperimentChoices legend="Transfer explanation" name="preference-transfer" choices={[
    {id:"counts",label:"Verdicts B,B,A,A,Tie,B give A 2 wins, B 3 and 1 tie. A’s score is 2.5/6=0.416667; reference agreement is 3/6=0.5. P1 scores A=3,B=4; P3 A=5,B=3. B first does not affect the length rule. Reverse starts at P6: expected A=0.5, outcome=0, delta=−16, ratings A=984/B=1016. Final A≈984.766875/B≈1015.233125. These authored reference matches and toy ratings do not validate real model quality."},
    {id:"position",label:"B first awards B +4 under every judge, so all six verdicts must be B."},
    {id:"validity",label:"Agreement 0.5 proves this real judge has 50% human accuracy, and ties never change unequal Elo ratings."}
   ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="counts"?<p role="status" className={shared.feedback}>Try again. Add only the selected judge bonus, compare final scores, and keep all six pairs in each denominator. The first reverse Elo update starts with equal ratings.</p>:<><ExperimentResult title="Transfer explained">State the answers, evaluator, tie convention, reference and rating sequence before interpreting the ranking.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(5);clear();}}>Explore freely</ExperimentButton></>)}</>}
  </>:<><p>Try all three rubrics and judge rules in both display and rating orders. Under Rubric only or Longer-answer bonus +2, swapping Display order changes presentation but not votes. Equal judged scores tie. Equal word counts receive no length bonus. Rating sequence changes only sequential aggregation. A tie can move unequal ratings. Reset starts Experiment 1.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
 </ExperimentRail>;
 return <LearningPage title="Preference & Judge Metrics Lab" subtitle="Trace the judge. Explain the ranking." rail={rail}>
  <LessonToolbar scenarios={preferenceScenarios} selectedId={preferencePresetId(state)} onSelect={id=>edit(preferenceBaseline(id))} onReset={()=>start(experiment||transfer?index:0)}/>
  <section className={shared.evidence} aria-label="Authored answer pairs"><h2>Your dataset</h2>
   <p>Six authored prompts have two fixed authored answers, A and B. Each answer has disclosed accuracy/completeness and style marks from 0 to 2. They are teaching judgments, not universal ground truth or measured human ratings. Style evaluates wording separately from correctness: a fluent answer can be false. No actual language model or human judge runs here.</p>
   <p>Display order changes which candidate is shown first, while its A/B identity stays fixed. The marks and whitespace word counts travel with the answer. All six pairs remain in every aggregate.</p>
   <div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="Six prompts with displayed candidate answers and marks"><table><caption>{state.display==="A-first"?"A is displayed first, B second":"B is displayed first, A second"}. Marks are accuracy / style. Words are whitespace-separated tokens including punctuation.</caption><thead><tr><th scope="col">Prompt</th><th scope="col">First candidate</th><th scope="col">Second candidate</th></tr></thead><tbody>{a.rows.map(r=><tr key={r.id} data-preference-pair={r.id}><th scope="row">{r.id} · {r.prompt}</th>{(state.display==="A-first"?["A","B"]:["B","A"]).map(candidate=><td key={candidate} data-candidate={candidate}><strong>{candidate}</strong><p>{candidate==="A"?r.answerA:r.answerB}</p><span className={styles.itemDetails}>Marks {candidate==="A"?r.featuresA.join(" / "):r.featuresB.join(" / ")} · Words {candidate==="A"?r.wordsA:r.wordsB}</span></td>)}</tr>)}</tbody></table></div>
   <div className={shared.controlGrid}><LessonSelect label="Rubric" choices={rubricChoices} value={state.rubric} onChange={rubric=>edit({...state,rubric})}/><LessonSelect label="Judge rule" choices={judgeChoices} value={state.judge} onChange={judge=>edit({...state,judge})}/><LessonSelect label="Display order" choices={displayChoices} value={state.display} onChange={display=>edit({...state,display})}/><LessonSelect label="Rating sequence" choices={sequenceChoices} value={state.sequence} onChange={sequence=>edit({...state,sequence})}/></div>
   <p>Base score = accuracy weight × accuracy mark + style weight × style mark. Rubric only uses that score. First-position bonus +4 adds four only to the first displayed candidate. Longer-answer bonus +2 adds two only to the strictly longer answer; equal lengths get no bonus. A larger judged score wins; equal judged scores tie.</p>
   <p role="status" data-preference-status>A wins {a.winsA} · B wins {a.winsB} · Ties {a.ties} · All 6 pairs counted. Raw A win rate = {a.winsA}/6 = <span data-preference-raw>{number(a.rawA)}</span>. A/B tie-adjusted scores = <span data-preference-adjusted-a>{number(a.adjustedA)}</span> / <span data-preference-adjusted-b>{number(a.adjustedB)}</span>.</p>
   <p className={shared.small}>Every actual control or preset change clears stale explanation/transfer answers; reapplying the same state preserves them. Reset and prediction changes restore Accuracy first for the current experiment.</p>
  </section>
  <LessonSummaries label="Current preference and rating results" summaries={[
   {label:"A tie-adjusted score",color:"#5031dc",value:number(a.adjustedA),definition:"Mean pair outcome, with half credit for ties.",formula:"(A wins + 0.5 × ties) / 6",comparison:`${a.winsA} wins, ${a.ties} ties. Raw win rate counts no tie credit; both use all six pairs.`},
   {label:"Reference agreement",color:"#087c78",value:number(a.agreement),definition:"Exact A/B/Tie matches with a fixed authored rubric.",formula:"matching verdicts / 6",comparison:`${a.agrees}/6. Reference: Accuracy first + Rubric only. This is not independent human validation.`},
   {label:"A online Elo",color:"#ad4508",value:number(a.current.finalA),definition:"Sequential pairwise rating after six toy updates.",formula:"R′A = RA + 32 × (SA − EA)",comparison:`B=${number(a.current.finalB)}; both start at 1000. K=32, scale=400. Not a current Arena Bradley–Terry fit.`},
  ]}/>
  <section className={shared.evidence} aria-label="Weighted scores and exact verdict matching"><h2>Trace the judge’s decision</h2><p>Judge scores include only the selected bonus. The fixed reference always uses accuracy weight 3, style weight 1 and no bonus: A,A,A,A,Tie,A. Agreement means the same A/B/Tie label. Baseline agreement 1 is true by construction, because the judge and reference use the same rule; it does not establish independent validity or chance-corrected agreement.</p>
   <div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="Six judged score constructions and reference verdicts"><table><caption>Scores keep candidate identity fixed even when Display order swaps.</caption><thead><tr>{["Item","Base A","Base B","Bonus A / B","Judged A / B","Verdict","Reference","Exact match"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.rows.map(r=><tr key={r.id} data-preference-verdict={r.id}><th scope="row">{r.id}</th><td>{r.baseA}</td><td>{r.baseB}</td><td>{r.bonusA} / {r.bonusB}</td><td>{r.scoreA} / {r.scoreB}</td><td>{r.verdict}</td><td>{r.reference}</td><td>{r.agrees?"Yes":"No"}</td></tr>)}</tbody></table></div>
  </section>
  <section className={shared.evidence} aria-label="Sequential online Elo construction"><h2>Update a pairwise rating</h2><p>Start A=B=1000. Expected A outcome EA=1/(1+10^((RB−RA)/400)). SA is 1 for an A win, 0 for a B win and 0.5 for a tie. Add Δ=32×(SA−EA) to A and subtract the same Δ from B. Ratings always sum to 2000; no intermediate rounding is used. A tie can change unequal ratings. The expectation is a rating-model quantity, not measured correctness or a guaranteed future win probability.</p>
   <div className={`${shared.tableScroll} ${styles.table}`} role="region" tabIndex={0} aria-label="Six sequential pairwise rating updates"><table><caption>{state.sequence==="forward"?"P1 → P6":"P6 → P1"}: later expected scores use the updated ratings.</caption><thead><tr>{["Item","Before A","Before B","Expected A","Outcome A","Δ A","After A","After B"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{a.current.history.map(h=><tr key={h.id} data-preference-update={h.id}><th scope="row">{h.id}</th>{[h.beforeA,h.beforeB,h.expected,h.outcome,h.delta,h.afterA,h.afterB].map((v,i)=><td key={i}>{number(v)}</td>)}</tr>)}</tbody></table></div>
   <p data-preference-order-comparison>Same votes, different sequence: Forward A=<span data-preference-forward-a>{number(a.forward.finalA)}</span>, B=<span data-preference-forward-b>{number(a.forward.finalB)}</span>; Reverse A=<span data-preference-reverse-a>{number(a.reverse.finalA)}</span>, B=<span data-preference-reverse-b>{number(a.reverse.finalB)}</span>. Sequential updates depend on the ratings before each battle. Reordering can change the result without changing answers or vote counts.</p>
   <p>This is a small historical online Elo illustration with a chosen K=32. It is not a real leaderboard, a current Arena Bradley–Terry maximum-likelihood fit, confidence interval, statistical significance test or universal model-quality measure. No real models are trained, generated or compared. The position and length bonuses construct interpretable bias examples; they are not calibrated estimates of real evaluator bias.</p>
  </section>
  <section className={shared.evidence} aria-label="Preference conventions and limits"><details><summary>Construction and limits</summary><p>The finite model has three rubrics, three judge rules, two display orders and two rating sequences: 36 states. Marks are authored accuracy/completeness and style values 0..2, with no actual learned semantic scoring. Words are whitespace tokens. An equal judged score is one Tie. Raw A win rate counts wins only; adjusted scores give each tie one half. All six items, including ties, remain in every denominator; adjusted A+B=1. Reference is the fixed Accuracy first/Rubric only verdict list, with exact label matching, not independent human votes or a gold standard. Agreement is neither validity nor Cohen’s kappa.</p><p>Position order and rating sequence are different controls. The former changes presentation and the selected position bonus, while A/B identities persist; the latter changes only the order of rating updates. Rubric-only and length-rule votes do not depend on display order. Length bonus rewards the strictly longer answer, not actual information quality. Score gaps can outweigh a position bonus. Equal lengths receive no length bonus. No claim is made that real judge biases follow these arithmetic rules or that swapping removes them.</p><p>Online Elo starts both ratings at 1000, uses base 10, scale 400 and constant K=32. Each SA is 1/0/0.5; expectation is recomputed from the previous ratings. No intermediate rounding occurs. Opposite updates conserve the rating sum, ties can change unequal ratings, and reordering fixed votes can change the final ratings. This illustrates a classic sequential procedure rather than current Arena’s Bradley–Terry fitting or an objective ranking. Six authored examples support no uncertainty inference or general real-model performance claim.</p>
   <a href="https://arxiv.org/abs/2306.05685" target="_blank" rel="noreferrer">Judging LLM-as-a-Judge · Rubrics, agreement and bias</a><br/><a href="https://arxiv.org/abs/2406.07791" target="_blank" rel="noreferrer">Judging the Judges · Position consistency</a><br/><a href="https://www.lmsys.org/blog/2023-12-07-leaderboard/" target="_blank" rel="noreferrer">LMSYS · Online Elo to Bradley–Terry</a><br/><a href="https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/monitor/rating_systems.py" target="_blank" rel="noreferrer">FastChat · Pairwise rating formulas</a>
  </details></section>
 </LearningPage>;
}
