"use client";
import {useMemo,useState} from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonAction, LessonRangeControl, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import sharedStyles from "@/components/learning-page/learning-page.module.css";
import {adjustApproximation,analyzeKlDivergence,formatKl,formatRatio,type KlDirection} from "./kl-divergence-engine";
import {klCategories,referenceScenarios,initialApproximation} from "./scenario";
import {klDefaults,klExperiments,klScenarios,missA,type KlState} from "./learning-experiments";
import styles from "./playground.module.css";
const percent=(v:number)=>Math.round(v*100);
const same=(a:KlState,b:KlState)=>a.scenario===b.scenario&&a.direction===b.direction&&a.q.every((v,i)=>Math.abs(v-b.q[i])<1e-10);
const signed=(v:number)=>`${v>0?"+":""}${formatKl(v)}`;
export function KlDivergencePlayground(){
 const [state,setState]=useState<KlState>(klDefaults),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const reference=referenceScenarios.find(s=>s.id===state.scenario)!.values;
 const a=useMemo(()=>analyzeKlDivergence(klCategories,reference,state.q,state.direction),[reference,state]);
 const experiment=klExperiments[index],transfer=index===3,reached=!!prediction&&!!experiment&&same(state,experiment.target),complete=reached&&explanation===experiment?.correctExplanation;
 const transferReached=same(state,{scenario:"rare-event",q:initialApproximation,direction:"p-to-q"});
 function clear(){setExplanation(null);setTransferAnswer(null)}
 function start(next=index){setIndex(next);setState(klExperiments[next]?.baseline??klDefaults);setPrediction(null);clear()}
 function edit(next:KlState){setState(next);clear()}
 const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 3`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="kl-prediction" explanationName="kl-explanation"
    onPredict={id=>{start();setPrediction(id)}} onExplain={setExplanation}
    predictionHelp={<>Choosing a prediction restores this experiment’s starting P, Q and direction.</>} observation={prediction===experiment.correctPrediction?"Your prediction matches the evidence.":"The signed terms and total challenge your prediction. Compare them with the starting values."}
    onNext={()=>start(index+1)} nextLabel={index===2?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Change the reference":"Compare the weights"}>
 {transfer?<><p>Choose Rare event, Baseline Q and P → Q. Q stays 45/25/20/10 while P changes to 88/4/4/4. Which bucket drives the larger positive penalty?</p><ExperimentChoices legend="Transfer explanation" name="kl-transfer" choices={[{id:"a",label:"A: its P weight rises to 88% and its P/Q ratio rises. Its positive term outweighs the three negative offsets."},{id:"all",label:"All four terms must be positive because the total KL is positive."},{id:"q",label:"Q changed when the reference changed, so Q alone explains the larger penalty."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!transferReached?<p className={sharedStyles.feedback} role="status">First choose Rare event, Baseline Q and P → Q.</p>:transferAnswer!=="a"?<p className={sharedStyles.feedback} role="status">Try again. Read A’s weight and ratio. Changing P keeps Q fixed; B, C and D still contribute negative offsets.</p>:<><ExperimentResult title="Transfer explained">A contributes about +0.5902 nats. The other terms offset part of it; the total is about 0.4159. Q stayed fixed, so the changed source distribution explains this comparison.</ExperimentResult><ExperimentButton onClick={()=>setIndex(4)}>Explore freely</ExperimentButton></>)}</>:<><p>Try all three references, edit Q and compare both directions. Balanced P does not guarantee equal totals. Move Q(A) past P(A): more mass on A is not always better.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
 </ExperimentRail>;
 return <LearningPage title="KL Divergence Intuition Lab" subtitle="Change the weights. Compare the directions." rail={rail}>
 <LessonToolbar label="Reference distribution P" scenarios={klScenarios} selectedId={state.scenario} onSelect={id=>edit({...state,scenario:id})} onReset={()=>start(experiment||transfer?index:0)}/>
 <p className={styles.context}>Choosing a reference changes P while keeping Q and direction fixed. KL adds source probability × ln(source / target); ln is the natural logarithm and the units are nats.</p>
 <h2 className={styles.controlHeading}>Direction</h2><LessonToggleGroup label="Direction" choices={[{id:"p-to-q",label:"P → Q"},{id:"q-to-p",label:"Q → P"}]} value={state.direction} onChange={id=>edit({...state,direction:id as KlDirection})}/>
 <h2 className={styles.controlHeading}>Quick settings for Q</h2><div className={styles.actions}>{[{label:"Miss A",values:missA},{label:"Baseline Q",values:initialApproximation},{label:"Match P",values:reference}].map(p=><LessonAction key={p.label} onClick={()=>edit({...state,q:[...p.values]})}>{p.label}</LessonAction>)}</div>
 <div className={sharedStyles.controlGrid}>{klCategories.map((c,i)=><LessonRangeControl key={c.id} label={`Q ${c.label} probability`} unit="%" value={percent(state.q[i])} min={1} max={97} step={1} onChange={v=>edit({...state,q:adjustApproximation(state.q,i,v/100)})} help="This bucket keeps the chosen whole percent. Others redistribute with at least 1% each; Q stays 100%."/>)}</div>
 <section className={sharedStyles.evidence} aria-label="Distributions and signed terms"><h2>Distributions and signed terms</h2><p>P and Q share a fixed 0–100% scale. Current contribution: {a.sourceLabel} × ln({a.sourceLabel} / {a.targetLabel}). The direction changes the formula, keeping the probabilities fixed.</p><div className={styles.axis}><span/><div><span>0%</span><span>50%</span><span>100%</span></div><span/></div>{a.contributions.map(r=><div key={r.category.id} className={styles.termRow}><strong>Bucket {r.category.label}</strong>{[{label:"P",value:r.referenceValue},{label:"Q",value:r.approximationValue}].map(b=><div key={b.label} className={styles.barRow}><span>{b.label}</span><div className={styles.track} role="img" aria-label={`Bucket ${r.category.label}, ${b.label} ${percent(b.value)}%`}><span data-distribution={b.label} style={{width:`${Number((b.value*100).toPrecision(6))}%`}}/></div><output>{percent(b.value)}%</output></div>)}<p>Contribution = {r.sourceValue} × ln({r.sourceValue} / {r.targetValue}) ≈ <strong>{signed(r.contribution)} nats</strong>.</p></div>)}</section>
 <LessonSummaries label="Directional KL totals" summaries={[{label:`KL(${a.sourceLabel} || ${a.targetLabel})`,value:formatKl(a.score),color:"#5031dc",definition:`Current direction: ${a.sourceLabel} supplies the weights and numerator. Units: nats.`,formula:`Σ ${a.sourceLabel} × ln(${a.sourceLabel} / ${a.targetLabel})`,comparison:"Signed bucket terms add to this nonnegative total."},{label:`KL(${a.targetLabel} || ${a.sourceLabel})`,value:formatKl(a.reverseScore),color:"#1760db",definition:`Opposite direction: ${a.targetLabel} supplies the weights and numerator. Units: nats.`,formula:`Σ ${a.targetLabel} × ln(${a.targetLabel} / ${a.sourceLabel})`,comparison:"The same two distributions can have different KL totals."}]}/>
 <section className={styles.optional} aria-label="Supporting KL evidence"><details><summary>Worked contributions</summary><p>Values use actual probabilities without clipping. Displayed terms are rounded; the total uses full precision.</p><div className={styles.scroller} role="region" aria-label="Scrollable KL calculation" tabIndex={0}><table><caption>Source {a.sourceLabel}, target {a.targetLabel}. Each term is source × ln(source / target).</caption><thead><tr><th scope="col">Bucket</th><th scope="col">Source {a.sourceLabel}</th><th scope="col">Target {a.targetLabel}</th><th scope="col">Ratio</th><th scope="col">Term (nats)</th></tr></thead><tbody>{a.contributions.map(r=><tr key={r.category.id}><th scope="row">{r.category.label}</th><td>{r.sourceValue}</td><td>{r.targetValue}</td><td>{formatRatio(r.ratio)}</td><td>{signed(r.contribution)}</td></tr>)}</tbody><tfoot><tr><th scope="row" colSpan={4}>Sum</th><td>{formatKl(a.score)}</td></tr></tfoot></table></div><p>The controls keep each bucket positive. Mathematically, a zero source contributes zero, including when both values are zero. Positive source mass against a zero target gives infinite KL.</p></details><details><summary>Signed contribution chart</summary><p>Fixed −0.5 to 4.5 nats scale covers the available controls. Negative terms extend left of zero; positive terms extend right. This chart scale is not a universal maximum for KL.</p><div className={styles.signedAxis}><span>−0.5</span><span>0</span><span>4.5 nats</span></div>{a.contributions.map(r=><div key={r.category.id} className={styles.signedRow}><strong>{r.category.label}</strong><div className={styles.signedTrack} role="img" aria-label={`Bucket ${r.category.label} contribution ${signed(r.contribution)} nats`}><span className={styles.zero}/><span className={styles.signedBar} data-sign={r.contribution<0?"negative":"positive"} style={{left:`${Number((10+Math.min(0,r.contribution)*20).toPrecision(6))}%`,width:`${Number((Math.abs(r.contribution)*20).toPrecision(6))}%`}}/></div><output>{signed(r.contribution)}</output></div>)}</details></section>
 <p className={styles.context}>Individual terms can be negative, while normalized KL is nonnegative. It is zero when the distributions match, generally directional, and has no universal maximum.</p>
 <p className={sharedStyles.liveUpdate} role="status" aria-live="polite" aria-atomic="true">Source {a.sourceLabel}, target {a.targetLabel}. {a.contributions.map(r=>`${r.category.label}: P ${percent(r.referenceValue)}%, Q ${percent(r.approximationValue)}%, contribution ${signed(r.contribution)} nats`).join("; ")}. KL {formatKl(a.score)} nats, opposite {formatKl(a.reverseScore)} nats.</p>
 </LearningPage>;
}
