"use client";
import { useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSelect, LessonSummaries, LessonToggleGroup, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import sharedStyles from "@/components/learning-page/learning-page.module.css";
import { analyzeBatchNormalization, formatValue as f, valueToPercent } from "./batch-normalization-engine";
import { batchExperiments, batchTransferStart, batchTransferTarget, type BatchState } from "./learning-experiments";
import { batchNormalizationScenarios, type BatchScenarioId } from "./scenario";
import styles from "./playground.module.css";
const same = (a: BatchState, b: BatchState) => a.scenario === b.scenario && a.batchSize === b.batchSize && a.gamma === b.gamma && a.beta === b.beta && a.mode === b.mode && a.selected === b.selected;
function Stage({ title, values, selected, mean, std, color }: { title: string; values: number[]; selected: number; mean: number; std: number; color: string }) {
  return <figure className={styles.stage}><figcaption><strong>{title}</strong><span>Mean {f(mean,6)} · std {f(std,6)}</span></figcaption><div className={styles.plot} aria-hidden="true"><div className={styles.zero} />{values.map((value, i) => <div key={i} className={styles.plotRow}><span className={styles.rowLabel}>{i+1}</span><div className={styles.lane}><span className={styles.dot} data-stage-value={value} data-selected={i === selected} style={{ left: `${valueToPercent(value,-8,8).toPrecision(6)}%`, background: color }} /></div></div>)}<div className={styles.axis}><span>−8</span><span>0</span><span>8</span></div></div></figure>;
}
export function BatchNormalizationPlayground() {
  const [state,setState] = useState<BatchState>(batchExperiments[0].baseline), [index,setIndex] = useState(0);
  const [prediction,setPrediction] = useState<string|null>(null), [explanation,setExplanation] = useState<string|null>(null), [transferAnswer,setTransferAnswer] = useState<string|null>(null);
  const scenario = batchNormalizationScenarios.find(s => s.id === state.scenario)!;
  const a = analyzeBatchNormalization({ values: scenario.values, batchSize: state.batchSize, gamma: state.gamma, beta: state.beta, epsilon: .001, mode: state.mode, runningMean: scenario.runningMean, runningStd: scenario.runningStd });
  const experiment = batchExperiments[index], transfer = index === 5;
  const reached = !!prediction && !!experiment && same(state,experiment.target), complete = reached && explanation === "0", transferReached = same(state,batchTransferTarget);
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function edit(next: BatchState) { setState({ ...next, selected: Math.min(next.selected,next.batchSize-1) }); clear(); }
  function start(next=index) { setIndex(next); setState(batchExperiments[next]?.baseline ?? batchTransferStart); setPrediction(null); clear(); }
  const rail = experiment ? <GuidedExperiment label={`Experiment ${index+1} of 5`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="batch-prediction" explanationName="batch-explanation"
    onPredict={id => { start(); setPrediction(id); }} onExplain={setExplanation}
    predictionHelp={<>A different prediction restores starting settings. Reset restarts this experiment.</>} observation={prediction === experiment.correctPrediction ? "Your prediction matches the evidence." : "The numeric evidence challenges your prediction."}
    onNext={() => start(index+1)} nextLabel={index === 4 ? "Try the transfer check" : "Next experiment"} /> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "Add a batchmate during inference" : "Compare references"}>
    {transfer ? <><p>Outlier is now in Inference, Batch size 7, Scale 1.5 and Shift −0.5. Predict what happens to example 1 when Batch size increases to 8. Try it, then explain without Guide help.</p><ExperimentChoices legend="Transfer explanation" name="batch-transfer" choices={[{ id:"fixed",label:"Existing examples keep the same z and y: the frozen reference, Scale and Shift are unchanged. The displayed batch’s aggregate mean and spread can change when a new example is added." },{id:"batch",label:"Every existing example changes because inference recomputes the batch reference."},{id:"zero",label:"All eight normalized values must become zero."}]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (!transferReached ? <p role="status" className={sharedStyles.feedback}>First set Batch size to 8 while keeping Outlier, Inference, Scale 1.5, Shift −0.5 and Example 1. Reset restores Batch size 7.</p> : transferAnswer !== "fixed" ? <p role="status" className={sharedStyles.feedback}>Try again. Adding a value changes the set being summarized, but the frozen reference used by existing examples does not change.</p> : <><ExperimentResult title="Transfer explained">Example 1 keeps its z and y. Inference with tracked statistics is independent of batchmates when the saved reference and parameters stay fixed.</ExperimentResult><ExperimentButton onClick={() => { setIndex(6); clear(); }}>Explore freely</ExperimentButton></>)}</> : <><p>Compare all four fixed batches, all batch sizes and both modes. Scale and Shift change y immediately; no optimizer runs. Selected activation follows one example. The exact table and model notes give the assumptions.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Batch Normalization Lab" subtitle="Compare each activation with its batchmates—or a frozen reference." rail={rail}>
    <LessonToolbar scenarios={batchNormalizationScenarios.map(s => ({id:s.id,label:s.label,shortLabel:s.helper}))} selectedId={state.scenario} onSelect={id => edit({...state,scenario:id as BatchScenarioId})} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={sharedStyles.evidence} aria-label="BatchNorm controls"><h2>Your mini-batch · one feature</h2><p>Each row is the same feature’s activation—a numeric signal—for a different example. Batch size includes the first N values of a fixed dataset; it does not randomly sample.</p><div className={sharedStyles.controlGrid}><LessonRangeControl label="Batch size" value={state.batchSize} min={4} max={8} step={1} help="Include the first 4–8 examples." onChange={batchSize => edit({...state,batchSize})} /><div><h3>Statistics source</h3><LessonToggleGroup label="Normalization mode" choices={[{id:"training",label:"Training"},{id:"inference",label:"Inference"}]} value={state.mode} onChange={mode => edit({...state,mode:mode as BatchState["mode"]})} /><p>{state.mode === "training" ? "Use this batch’s mean and population variance." : "Use this preset’s illustrative frozen mean and variance."}</p></div><LessonRangeControl label="Scale" value={state.gamma} min={.5} max={2} step={.05} help="Gamma multiplies z; this demo uses positive scale." onChange={gamma => edit({...state,gamma})} /><LessonRangeControl label="Shift" value={state.beta} min={-2} max={2} step={.05} help="Beta adds the same offset to each output." onChange={beta => edit({...state,beta})} /></div><LessonSelect label="Selected activation" choices={a.rawValues.map((x,i) => ({id:String(i),label:`Example ${i+1} · x = ${f(x,2)}`}))} value={String(state.selected)} onChange={id => edit({...state,selected:Number(id)})} /></section>
    <section className={sharedStyles.evidence} aria-label="Linked activation stages"><div className={styles.stages}><Stage title="Input x" values={a.rawValues} selected={state.selected} mean={a.mean} std={a.std} color="#1470ba" /><Stage title="Normalized z" values={a.normalizedValues} selected={state.selected} mean={a.normalizedMean} std={a.normalizedStd} color="#5031dc" /><Stage title="Output y" values={a.outputValues} selected={state.selected} mean={a.outputMean} std={a.outputStd} color="#167d59" /></div><p className={sharedStyles.small}>Fixed numeric axes −8 to 8 keep changes in spread visible; rows link the same example. x and y are activation values; z is dimensionless. Outlined dots mark the selected example. Exact values are available in the table below.</p></section>
    <section className={sharedStyles.evidence} aria-label="Selected activation calculation"><h2>Follow example {state.selected+1}</h2><p className={`${sharedStyles.math} ${styles.formula}`} data-selected-z>z = ({f(a.rawValues[state.selected],6)} − ({f(a.normalizationMean,6)})) / √({f(a.normalizationVariance,6)} + 0.001) = {f(a.normalizedValues[state.selected],6)}</p><p className={`${sharedStyles.math} ${styles.formula}`} data-selected-y>y = {f(state.gamma,2)} × ({f(a.normalizedValues[state.selected],6)}) + ({f(state.beta,2)}) = {f(a.outputValues[state.selected],6)}</p><p>Displayed substitutions are rounded; calculations use full precision. Epsilon (0.001) is a small positive term protecting the denominator.</p></section>
    <LessonSummaries label="Active normalization reference" summaries={[{label:"Used mean",color:"#5031dc",value:f(a.normalizationMean,4),definition:state.mode === "training" ? "Mean of the current batch." : "Illustrative frozen reference mean.",formula:state.mode === "training" ? "mean = Σx / N" : "fixed for this preset"},{label:"Used variance",color:"#5031dc",value:f(a.normalizationVariance,4),definition:state.mode === "training" ? "Average squared distance from the batch mean." : "Frozen reference variance (saved std²).",formula:state.mode === "training" ? "variance = Σ(x−mean)² / N" : `${f(scenario.runningStd,2)}²`,comparison:`Denominator √(variance+0.001) = ${f(a.denominator,6)}`},{label:"Output spread",color:"#167d59",value:f(a.outputStd,4),definition:"Population standard deviation around the current output mean.",formula:"std(y) = |Scale| × std(z)",comparison:`mean(y) = Scale × mean(z) + Shift = ${f(a.outputMean,6)}`}]} />
    <section className={sharedStyles.evidence}><details><summary>Per-example exact values and both references</summary><div className={`${sharedStyles.tableScroll} ${styles.table}`}><table><caption>Computed values, rounded to six decimals. The selected row is marked.</caption><thead><tr><th scope="col">Example</th><th scope="col">Input x</th><th scope="col">Normalized z</th><th scope="col">Output y</th></tr></thead><tbody>{a.rawValues.map((x,i) => <tr key={i} data-active={state.selected === i}><th scope="row">{i+1}{state.selected === i ? " · selected" : ""}</th><td>{f(x,6)}</td><td>{f(a.normalizedValues[i],6)}</td><td>{f(a.outputValues[i],6)}</td></tr>)}</tbody></table></div><p>Current batch: mean {f(a.mean,6)}, population variance {f(a.variance,6)}, std {f(a.std,6)}.</p><p>Frozen preset: mean {f(scenario.runningMean,6)}, variance {f(scenario.runningStd**2,6)}, std {f(scenario.runningStd,6)}. These illustrative estimates do not update.</p><p>Normalized mean {f(a.normalizedMean,6)}, std {f(a.normalizedStd,6)}. Standard deviation is measured around this actual mean, including in Inference.</p></details><details><summary>What this model includes</summary><p>One scalar feature across examples, using population variance (divide by N) for the training forward calculation. Epsilon makes Training std(z)=√(variance/(variance+epsilon)); a constant batch would give z=0 and y=Shift. Scale and Shift correspond to gamma and beta: you set them manually here. Real learnable scales can also be zero or negative.</p><p>The Inference path represents BatchNorm with tracked running statistics. Real PyTorch tracks running mean and variance during training; its running variance update uses an unbiased batch estimate (divide by N−1). This lesson keeps explicit illustrative references frozen and does not simulate running updates, optimizer steps or training quality. BatchNorm configured without tracked statistics can use batch statistics in evaluation too.</p><p>This demonstrates normalization mechanics and parameter effects; it does not establish faster optimization or higher accuracy. <a href="https://docs.pytorch.org/docs/2.14/generated/torch.nn.BatchNorm1d.html" target="_blank" rel="noreferrer">PyTorch BatchNorm1d reference</a>.</p></details></section>
    <p role="status" aria-live="polite" aria-atomic="true" className={sharedStyles.liveUpdate}>{scenario.label}, {state.mode}, {state.batchSize} examples. Used mean {f(a.normalizationMean,6)}, variance {f(a.normalizationVariance,6)}. Example {state.selected+1}: x {f(a.rawValues[state.selected],6)}, z {f(a.normalizedValues[state.selected],6)}, y {f(a.outputValues[state.selected],6)}.</p>
  </LearningPage>;
}
