"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import {analyzeClt,cltChart,cltModels,type CltState} from "./clt-engine";
import {cltBaseline,reachedClt} from "./lesson-state";
import {cltExperiments} from "./learning-experiments";
import styles from "./playground.module.css";
export function CentralLimitPlayground(){
  const [state,setState]=useState<CltState>(()=>cltBaseline()),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null),[width,setWidth]=useState(640);
  const chartRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const element=chartRef.current;if(!element)return;const update=()=>setWidth(Math.max(200,element.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(element);return()=>observer.disconnect();},[]);
  const a=useMemo(()=>analyzeClt(state),[state]),chart=cltChart(a,width),experiment=cltExperiments[index],transfer=index===4,reached=!!prediction&&!!experiment&&reachedClt(index,state),complete=reached&&explanation==="0";
  function clear(){setExplanation(null);setTransferAnswer(null);}
  function start(next=index){setIndex(next);setState(cltBaseline(next));setPrediction(null);clear();}
  function edit(patch:Partial<CltState>){setState(s=>({...s,...patch}));clear();}
  const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 4`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="clt-prediction" explanationName="clt-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores this experiment’s source, size and interval radius. Reset restarts it.</>} observation={prediction==="0"?"The observed evidence matches your prediction.":"The evidence challenges your prediction."}
    onNext={()=>start(index+1)} nextLabel={index===3?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"A wider interval, another source":"Compare other approximation states"}>
    {transfer?<><p>Without Guide help, choose Two peaks, set Sample size to 80 and Interval radius to 2. Explain the observed interval share, normal comparison and original source values.</p><ExperimentChoices legend="Transfer explanation" name="clt-transfer" choices={[{id:"approx",label:"Observed share in [−2,2) is 93.9% versus normal reference about 95.45%. Original outcomes stay 0 or 10; the finite standardized mean distribution can approximate normal interval probabilities without becoming exactly continuous or making every error fall inside."},{id:"exact",label:"Exactly 95.45% of every finite batch must lie inside; a different share means the source changed."},{id:"source",label:"The original individual observations now follow a normal distribution, so they are no longer only 0 or 10."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!reachedClt(4,state)?<p role="status" className={shared.feedback}>First choose Two peaks, Sample size 80 and Interval radius 2. Read the observed count and normal reference.</p>:transferAnswer!=="approx"?<p role="status" className={shared.feedback}>Try again. The finite batch and discrete sampling law need not match a continuous reference exactly. Normal approximation concerns averages, while the original source remains fixed.</p>:<><ExperimentResult title="Transfer explained">939 of 1000 means lie in [−2,2), giving 93.9%. The standard-normal reference is approximately 95.45%. Population outcomes remain 0 or 10 and sample SE is 5 / √80 = 0.5590. This comparison is approximate and leaves some means outside the interval.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(5);clear();}}>Explore freely</ExperimentButton></>)}</>:<><p>Compare other sources, sizes and intervals. Increasing Sample size extends the same prepared samples. Keep source shape, standardized moments and a finite normal approximation distinct. Reset returns to Experiment 1.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Central Limit Theorem Lab" subtitle="Compare sample means with a normal reference." rail={rail}>
    <LessonToolbar label="Source distributions" scenarios={cltModels} selectedId={state.model} onSelect={model=>edit({model:model as CltState["model"]})} onReset={()=>start(experiment||transfer?index:0)}/>
    <section className={shared.evidence} aria-label="Averaging controls"><p>Independent draws from one fixed source with finite positive variance. {a.model.description}</p><p data-source-moments>Known population mean = {a.model.mean}; population SD = {a.model.sd.toFixed(4)}. Sampling changes neither this source law nor its moments.</p><div className={shared.controlGrid}><LessonRangeControl label="Sample size" value={state.size} min={1} max={400} step={1} help="Observations inside each of the 1000 averages. Extend or shorten the same sample prefixes." onChange={size=>edit({size})}/><LessonRangeControl label="Interval radius" value={state.radius} min={0.5} max={3} step={0.5} unit="SE units" help="Compare −r ≤ Z < r. Include the lower edge and exclude the upper edge, matching the bins." onChange={radius=>edit({radius})}/></div><p role="status" data-clt-status>1000 prepared samples, each with {state.size} {state.size===1?"observation":"observations"} from {a.model.label}. Interval: −{state.radius} ≤ Z &lt; {state.radius}.</p></section>
    <section className={shared.evidence} aria-label="Standardized mean distribution"><h2>1000 standardized sample means</h2><p>Z = (sample mean − population mean) / (population SD / √n). Theoretical Z mean is 0 and SD is 1 at every n; these moments do not guarantee a normal shape. The fixed standardized axis lets us compare shape, rather than simply shrinking raw averages.</p><p>Indigo bars: observed counts. Orange points and line: standard-normal expected counts in the same half-unit bins, rather than a density curve. The shaded interval is [−{state.radius}, {state.radius}).</p><div className={styles.chart} ref={chartRef}><svg viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`Finite histogram of 1000 standardized means at size ${state.size} from ${a.model.label}. Fixed Z axis −6 to 6; count axis 0 to 1000. Observed count ${a.within} in interval −${state.radius} included to ${state.radius} excluded. Normal reference ${(a.normalShare*100).toFixed(2)} percent. Exact bin counts below.`} data-clt-chart><text x="4" y="16">Count</text><rect x={chart.intervalLeft} y={chart.top} width={chart.intervalRight-chart.intervalLeft} height={chart.baseline-chart.top} data-interval/>{chart.counts.map(t=><g key={t.value}><line x1={chart.left} x2={chart.width-chart.right} y1={t.y} y2={t.y}/><text x={chart.left-7} y={t.y+4} textAnchor="end">{t.value}</text></g>)}{chart.bars.map(b=><rect key={b.lower} x={b.x} y={b.y} width={b.width} height={b.height} data-bin={b.lower} data-count={b.count} data-expected={b.expected.toFixed(6)}/>)}<polyline points={chart.reference} data-normal-reference/>{chart.bars.map(b=><circle key={b.lower} cx={b.referenceX.toFixed(3)} cy={b.referenceY.toFixed(3)} r="2.5" data-reference-point/>)}{[chart.intervalLeft,chart.intervalRight].map((x,i)=><line key={i} x1={x} x2={x} y1={chart.top} y2={chart.baseline} data-interval-edge/>)}{chart.ticks.map((t,i)=><text key={t.value} x={t.x} y={chart.baseline+19} textAnchor={i===0?"start":i===4?"end":"middle"}>{t.value}</text>)}<text x={(chart.left+chart.width-chart.right)/2} y={chart.height-5} textAnchor="middle">Z · standardized sample mean</text></svg></div><p data-clt-tails>Finite histogram: {1000-a.below-a.above} means inside the plotted window, {a.below} below −6 and {a.above} above 6. All bins plus those tails total 1000; outside values are counted, not clamped into an edge bin.</p></section>
    <LessonSummaries label="Averaging and normal comparison" summaries={[{label:"Sample SE",color:"#33486d",value:a.se.toFixed(4),definition:"Theoretical spread of raw sample means.",formula:`σ / √n = ${a.model.sd.toFixed(4)} / √${state.size}`},{label:"Observed interval share",color:"#5031dc",value:`${(a.share*100).toFixed(1)}%`,definition:"Fraction of this finite batch in the interval.",formula:`${a.within} / 1000 with −${state.radius} ≤ Z < ${state.radius}`},{label:"Normal reference",color:"#ad4508",value:`${(a.normalShare*100).toFixed(2)}%`,definition:"Approximate sampling-law comparison.",formula:`Φ(${state.radius}) − Φ(−${state.radius})`}]}/>
    <section className={shared.evidence} aria-label="Exact comparison evidence"><p className={shared.math} data-clt-comparison>{a.within} of 1000 Z values satisfy −{state.radius} ≤ Z &lt; {state.radius}, giving observed share {(a.share*100).toFixed(1)}%. Standard-normal reference = {(a.normalShare*100).toFixed(2)}%. A finite simulated share is not an exact source probability or a guaranteed match.</p><details><summary>Exact histogram counts</summary><div className={styles.scrollTable} tabIndex={0} role="region" aria-label="Scrollable standardized histogram counts"><table className={`${shared.dataTable} ${styles.table}`}><caption>24 bins of width 0.5; last bin includes 6. Normal reference counts are 1000 times probability in each bin, computed numerically. Outside tails are listed below the plot.</caption><thead><tr><th scope="col">Z interval</th><th scope="col">Observed count</th><th scope="col">Normal expected count</th></tr></thead><tbody>{a.bins.map((b,i)=><tr key={b.lower}><th scope="row">[{b.lower}, {b.upper}{i===23?"]":")"}</th><td>{b.count}</td><td>{b.expected.toFixed(3)}</td></tr>)}</tbody></table></div></details><details><summary>Representative first sample</summary><p>Sample 1 has total {a.current.total.toFixed(6)} / size {state.size} = mean {a.current.mean.toFixed(6)}; standardized Z = {a.current.z.toFixed(6)}. Its first {a.current.first.length} observations: {a.current.first.map(v=>v.toFixed(4)).join(", ")}. This existing first sample is illustrative; no special outcome was selected. Display values are rounded; classification uses full precision.</p></details></section>
    <section className={shared.evidence} aria-label="Source and theorem assumptions"><details><summary>Source and sampling assumptions</summary><p>{a.model.rule} These are declared ideal source moments, not estimated from the displayed batch. Independent draws from a fixed finite-positive-variance source give mean μ and SE σ / √n for the sample mean. Standardization gives theoretical mean 0 and variance 1; normality is an additional asymptotic approximation.</p><p>A seed-1309 32-bit generator creates 1000 nonoverlapping blocks of 400 uniform positions. Each source transforms those positions through its declared rule. Size reveals the first n draws in every block; finite pseudorandom examples do not prove independence or convergence. Discrete outcomes can recur; the continuous source also retains the same law on each draw.</p><p>The CLT concerns standardized averages as n grows under its assumptions. Approximation quality depends on source and desired accuracy; no universal size-20 rule applies. Finite means may remain discrete and the observed batch may be jagged. Normal CDF values use the Abramowitz–Stegun 26.2.17 numerical approximation. The orange line joins expected bin counts, rather than plotting density. Counts outside −6 to 6 remain explicit. The selected interval includes its lower boundary and excludes its upper boundary; discrete endpoint mass can matter.</p><p>Individual observations do not become normal, and a finite histogram neither proves the theorem nor guarantees exact interval shares, monotone improvement or a bound on every sample error. Dependence, infinite-variance sources, confidence intervals, continuity corrections and rigorous approximation-error bounds are outside this lesson.</p><a href="https://www.stat.berkeley.edu/~stark/SticiGui/Text/clt.htm" target="_blank" rel="noreferrer">Berkeley SticiGui · Normal approximation and source dependence</a><br/><a href="https://ocw.mit.edu/courses/18-05-introduction-to-probability-and-statistics-spring-2022/mit18_05_s22_lec06b.pdf" target="_blank" rel="noreferrer">MIT 18.05 · Standardization and the Central Limit Theorem</a></details></section>
  </LearningPage>;
}
