"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonAction, LessonToolbar } from "@/components/learning-page/learning-page";
import { GuidedExperiment } from "@/components/learning-page/guided-experiment";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeSampling, samplingChart, samplingModels, type SamplingModelId, type SamplingState } from "./sampling-engine";
import { samplingBaseline, reachedSampling } from "./lesson-state";
import { samplingExperiments } from "./learning-experiments";
import styles from "./playground.module.css";
export function SamplingPlayground() {
  const [state,setState]=useState<SamplingState>(()=>samplingBaseline()),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null),[width,setWidth]=useState(640);
  const chartRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const element=chartRef.current;if(!element)return;const update=()=>setWidth(Math.max(200,element.getBoundingClientRect().width));update();const observer=new ResizeObserver(update);observer.observe(element);return()=>observer.disconnect();},[]);
  const a=useMemo(()=>analyzeSampling(state),[state]),chart=samplingChart(a,width),experiment=samplingExperiments[index],transfer=index===5,reached=!!prediction&&!!experiment&&reachedSampling(index,state),complete=reached&&explanation==="0";

  function clear(){setExplanation(null);setTransferAnswer(null);}
  function start(next=index){setIndex(next);setState(samplingBaseline(next));setPrediction(null);clear();}
  function edit(patch:Partial<SamplingState>){setState(s=>({...s,...patch}));clear();}
  const rail=experiment?<GuidedExperiment label={`Experiment ${index+1} of 5`} experiment={experiment}
    reached={reached} complete={complete} prediction={prediction} explanation={explanation}
    predictionName="sampling-prediction" explanationName="sampling-explanation"
    onPredict={id=>{start();setPrediction(id);}} onExplain={setExplanation}
    predictionHelp={<>Changing prediction restores this experiment’s starting source, size, sample number and revealed state. Reset restarts it.</>} observation={prediction==="0"?"The observed evidence matches your prediction.":"The evidence challenges your prediction."}
    onNext={()=>start(index+1)} nextLabel={index===4?"Try the transfer check":"Next experiment"} />:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"A different source and sample":"Compare other sample prefixes"}>
    {transfer?<><p>Without Guide help, choose Two levels, set Sample size to 400 and Sample number to 7. Keep the population revealed. Explain the selected estimate and what the larger sample does and does not imply.</p><ExperimentChoices legend="Transfer explanation" name="sampling-transfer" choices={[{id:"estimate",label:"This sample averages 5.275 while the source mean is 5, giving error 0.275. Larger samples tend to stabilize estimates under the ideal model, without forcing exact equality or changing individual source values 0 and 10."},{id:"exact",label:"A size-400 sample must equal 5 exactly, so any difference proves the population mean changed."},{id:"values",label:"Each individual observation must now be close to 5, because a larger average is more stable."}]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(!reachedSampling(5,state)?<p role="status" className={shared.feedback}>First choose Two levels, Sample size 400 and Sample number 7, with the population revealed. Read the selected sample and source records.</p>:transferAnswer!=="estimate"?<p role="status" className={shared.feedback}>Try again. Sample averages can differ from a fixed population parameter; increasing size does not change the source’s individual outcomes or guarantee exact equality.</p>:<><ExperimentResult title="Transfer explained">The selected sample has total 2110 / 400 = 5.275, compared with population mean 5. Its error is 0.275. Individual outcomes remain 0 or 10; a finite sample need not equal the source mean.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(6);clear();}}>Explore freely</ExperimentButton></>)}</>:<><p>Choose another source, size or sample number. Next sample advances within the 20 prepared blocks; the exact editor can revisit any of them. Size edits reveal the same block’s prefix. The finite batch illustrates variability, not a guarantee for every sample. Reset returns to Experiment 1.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Sampling & Sample Size Lab" subtitle="Compare estimates from repeated samples." rail={rail}>
    <LessonToolbar label="Toy populations" scenarios={samplingModels} selectedId={state.model} onSelect={model=>edit({model:model as SamplingModelId})} onReset={()=>start(experiment||transfer?index:0)}/>
    <section className={shared.evidence} aria-label="Sampling controls"><p>The ideal model selects each population record with equal probability on every independent draw, with replacement: records can repeat. These fixed toy sources use reproducible simulated samples. Population details start hidden.</p><div className={shared.controlGrid}><LessonRangeControl label="Sample size" value={state.size} min={1} max={1000} step={1} help="Show more or fewer observations from the same prepared sample, without resampling it." onChange={size=>edit({size})}/><LessonRangeControl label="Sample number" value={state.sample} min={1} max={20} step={1} help="Select another prepared sample from the same source at the same size." onChange={sample=>edit({sample})}/></div><div className={styles.actions}><LessonAction disabled={state.sample===20} onClick={()=>edit({sample:Math.min(20,state.sample+1)})}>Next sample</LessonAction><LessonAction disabled={state.revealed} onClick={()=>edit({revealed:true})}>Reveal population</LessonAction></div><p role="status" data-sampling-status>Showing sample {state.sample} of 20, with {state.size} observations from {a.model.label}. {state.revealed?"Population revealed; revealing changes information only.":"Population records and mean are hidden until you reveal them."}</p></section>
    <section className={shared.evidence} aria-label="Repeated sample estimates"><h2>20 sample estimates</h2><p>Each row is one sample mean, not an individual observation. A double ring marks the selected sample. {state.revealed?"The dashed line marks the population mean.":"The population reference stays hidden until revealed."}</p><div className={styles.chart} ref={chartRef}><svg viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`Twenty sample means at size ${state.size} from ${a.model.label}. Selected sample ${state.sample} averages ${a.current.mean.toFixed(4)}. Observed means range ${a.meanMinimum.toFixed(4)} to ${a.meanMaximum.toFixed(4)}. ${state.revealed?`Population mean ${a.target.toFixed(4)}.`:"Population mean hidden."} Exact sample means are in the optional table below.`} data-sampling-chart>
      <text x="4" y="12">Sample</text><text x={chart.width-4} y="12" textAnchor="end">Mean</text>{state.revealed&&<line x1={chart.targetX} x2={chart.targetX} y1={chart.top-9} y2={chart.baseline} data-population-mean/>}
      {chart.rows.map(r=><g key={r.number} data-sample={r.number} data-selected={r.selected}><text x={chart.left-14} y={r.y+4} textAnchor="end">{r.number}</text><circle cx={r.x} cy={r.y} r="3.5"/>{r.selected&&<circle cx={r.x} cy={r.y} r="6.5" data-selected-ring/>}<text x={chart.width-4} y={r.y+4} textAnchor="end">{r.mean.toFixed(4)}</text></g>)}<line x1={chart.left} x2={chart.width-chart.right} y1={chart.baseline} y2={chart.baseline}/>{chart.ticks.map((t,i)=><text key={t.value} x={t.x} y={chart.baseline+19} textAnchor={i===0?"start":i===2?"end":"middle"}>{t.value}</text>)}<text x={(chart.left+chart.width-chart.right)/2} y={chart.height-3} textAnchor="middle">Sample mean</text>
    </svg></div><p data-estimate-range>Twenty observed means range from {a.meanMinimum.toFixed(4)} to {a.meanMaximum.toFixed(4)}. This is a finite illustrative batch. The horizontal scale uses this source’s full value range {a.minimum}–{a.maximum}; changing Sample size does not shrink the axis or the source.</p></section>
    <LessonSummaries label="Estimate and population truth" summaries={[{label:"Sample mean",color:"#5031dc",value:a.current.mean.toFixed(4),definition:"Statistic from the selected observations.",formula:`${a.current.total} / ${state.size}`},{label:"Population mean",color:"#ad4508",value:state.revealed?a.target.toFixed(4):"Hidden",definition:"Fixed source parameter, initially unknown.",formula:state.revealed?`Sum of ${a.model.values.length} source records / ${a.model.values.length}`:"Reveal population to compare"},{label:"Absolute error",color:"#33486d",value:state.revealed?a.error.toFixed(4):"Hidden",definition:"Selected estimate’s distance from truth.",formula:"|sample mean − population mean|"}]}/>
    <section className={shared.evidence} aria-label="Selected sample evidence"><p className={shared.math} data-selected-sample>Sample {state.sample}: total {a.current.total} / size {state.size} = mean {a.current.mean.toFixed(4)}.{state.revealed?` Absolute error = |${a.current.mean.toFixed(4)} − ${a.target.toFixed(4)}| = ${a.error.toFixed(4)}.`:" Population mean and error remain hidden."}</p><p data-individual-values>Recent individual observations: {a.current.values.slice(-8).join(", ")}. This selected sample’s individual values range from {a.observedMinimum} to {a.observedMaximum}. These are observations, not averages.</p>{state.revealed&&<p data-population-records>Revealed source records: {a.model.values.join(", ")}. Each record is equally likely in the ideal model; duplicate values have multiple records. Source mean = {a.target.toFixed(4)}. Sampling with replacement keeps every record available.</p>}<details><summary>Exact means of the 20 samples</summary><table className={`${shared.dataTable} ${styles.table}`}><caption>All samples use the same source and size {state.size}; selected sample is labelled.</caption><thead><tr><th scope="col">Sample</th><th scope="col">Total</th><th scope="col">Mean</th></tr></thead><tbody>{a.samples.map(s=><tr key={s.number}><th scope="row">{s.number}{s.number===state.sample?" · selected":""}</th><td>{s.total}</td><td>{s.mean.toFixed(4)}</td></tr>)}</tbody></table></details></section>
    <section className={shared.evidence} aria-label="Sampling model assumptions"><details><summary>Model assumptions and reproducible sampling</summary><p>A population parameter describes the source; a sample statistic estimates it. The ideal independent, fixed-source, equal-record model uses replacement, so repeated values are expected and sample size can exceed the number of source records. This is not sampling without replacement or a census. All supplied sources are bounded and have finite means.</p><p>A seed-1309 deterministic 32-bit generator creates 20 nonoverlapping blocks of 1000 positions each. Sample number selects a block; Sample size reveals its prefix. Next sample chooses the next block, stopping at 20; the exact editor can revisit any prepared block. Changing source remaps those same positions. Finite pseudorandom illustrations are not proof of independence, randomness, monotone improvement or exact finite estimates.</p><p>Larger independent samples from a fixed bounded source tend to reduce mean-estimate variability. A particular sample or larger prefix can still be worse, and the original observations do not contract around their mean. Biased sampling, formal sampling distributions, standard error and confidence intervals require later lessons.</p><a href="https://www.stat.berkeley.edu/users/stark/SticiGui/Text/sampling.htm" target="_blank" rel="noreferrer">Berkeley SticiGui · Samples, statistics and populations</a><br/><a href="https://www.stat.berkeley.edu/users/stark/SticiGui/Text/expectation.htm" target="_blank" rel="noreferrer">Berkeley SticiGui · Expected sample means</a></details></section>
  </LearningPage>;
}
