"use client";
import { useEffect, useMemo, useRef, useState, type PointerEvent } from "react";
import { ExperimentButton, ExperimentChoices, ExperimentRail, ExperimentResult, LearningPage, LessonRangeControl, LessonSummaries, LessonToolbar } from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import { analyzeShape, analyzeShapePairs, shapeChart, shapeDataset, shapeDrag, shapeNumber as number, shapePresetId, shapePresets, type ShapeState } from "./shape-engine";
import { shapeBaseline, reachedShape } from "./lesson-state";
import { shapeExperiments } from "./learning-experiments";
import styles from "./playground.module.css";

export function ShapePlayground() {
  const [state, setState] = useState(() => shapeBaseline()), [index, setIndex] = useState(0);
  const [prediction, setPrediction] = useState<string | null>(null), [explanation, setExplanation] = useState<string | null>(null), [transferAnswer, setTransferAnswer] = useState<string | null>(null);
  const [width, setWidth] = useState(640), chartRef = useRef<HTMLDivElement>(null), dragging = useRef(false);
  useEffect(() => { const element = chartRef.current; if (!element) return; const update = () => setWidth(Math.max(200, element.getBoundingClientRect().width)); update(); const observer = new ResizeObserver(update); observer.observe(element); return () => observer.disconnect(); }, []);
  const a = useMemo(() => analyzeShape(state), [state]), chart = shapeChart(a, width), experiment = shapeExperiments[index], transfer = index === 4, fixed = analyzeShapePairs(a.points.slice(0, 6));
  const reached = !!prediction && !!experiment && reachedShape(index, state), complete = reached && explanation === "0";
  function clear() { setExplanation(null); setTransferAnswer(null); }
  function start(next = index) { setIndex(next); setState(shapeBaseline(next)); setPrediction(null); dragging.current = false; clear(); }
  function edit(patch: Partial<ShapeState>) { setState(s => ({ ...s, ...patch })); clear(); }
  function pointerMove(event: PointerEvent<SVGSVGElement>) { if (!dragging.current) return; edit(shapeDrag(event.clientX, event.clientY, event.currentTarget.getBoundingClientRect(), chart)); }
  function pointerStart(event: PointerEvent<SVGSVGElement>) { if (event.button !== 0) return; const rect = event.currentTarget.getBoundingClientRect(), px = (event.clientX - rect.x) / rect.width * chart.width, py = (event.clientY - rect.y) / rect.height * chart.height, p = chart.points[6]; if (Math.hypot(px - p.x, py - p.y) > 20) return; event.preventDefault(); dragging.current = true; event.currentTarget.setPointerCapture(event.pointerId); }
  const rail = experiment ? <ExperimentRail label={`Experiment ${index + 1} of 4`} title={experiment.title} phase={!prediction ? 0 : reached ? 2 : 1}>
    {!reached && <><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="shape-prediction" choices={experiment.predictions} value={prediction} onChange={id => { start(); setPrediction(id); }} /><p className={shared.small}>Changing prediction restores this experiment’s starting pairs. Reset restarts it.</p></>}
    {prediction && !reached && <p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}
    {reached && <><p role="status" className={shared.observation}>{prediction === "0" ? "The observed evidence matches your prediction." : "The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="shape-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation} />{explanation && !complete && <p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}
    {complete && <><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={() => start(index + 1)}>{index === 3 ? "Try the transfer check" : "Next experiment"}</ExperimentButton></>}
  </ExperimentRail> : <ExperimentRail label={transfer ? "Transfer check" : "Free exploration"} title={transfer ? "New spacing, same order?" : "Inspect shape and influence"}>
    {transfer ? <><p>Without Guide help, keep Increasing curve and move Point 7 to X coordinate 9 and Y coordinate 8. Explain the numeric pattern and its paired ranks.</p><ExperimentChoices legend="Transfer explanation" name="shape-transfer" choices={[
      { id: "ranked", label: "Point 7 still has the largest X and Y, with ranks 7 and 7. Spearman rho stays 1 while Pearson r changes to about 0.9717. Perfect rank agreement does not make the raw pattern a straight line or prove causation." },
      { id: "line", label: "Spearman 1 proves the numeric points lie on a straight line and Pearson must also be 1." },
      { id: "none", label: "Changing numeric spacing means there can no longer be any relationship." },
    ]} value={transferAnswer} onChange={setTransferAnswer} />{transferAnswer && (!reachedShape(4, state) ? <p role="status" className={shared.feedback}>First choose Increasing curve and set X coordinate 9 and Y coordinate 8. Keep the six fixed pairs unchanged.</p> : transferAnswer !== "ranked" ? <p role="status" className={shared.feedback}>Try again. Compare Point 7’s ranks with the numeric spacings; rank agreement, straight-line alignment and causal evidence are different claims.</p> : <><ExperimentResult title="Transfer explained">The new diamond (9,8) remains highest in both orderings. Its rank pair stays (7,7), so rho stays 1. Pearson responds to changed numeric spacing and becomes about 0.9717. The plot remains a curved pattern; neither score proves causation.</ExperimentResult><ExperimentButton onClick={() => { setIndex(5); clear(); }}>Explore freely</ExperimentButton></>)}</> : <><p>Switch families or move only the diamond. Inspect the raw plot, both coefficients and paired ranks together. Reset returns to Experiment 1.</p><ExperimentButton onClick={() => start(0)}>Restart experiments</ExperimentButton></>}
  </ExperimentRail>;
  return <LearningPage title="Correlation Shape & Outliers Lab" subtitle="Move one pair; compare straight-line and rank alignment." rail={rail}>
    <LessonToolbar scenarios={shapePresets} selectedId={shapePresetId(state)} onSelect={id => { setState(shapeDataset(id)); clear(); }} onReset={() => start(experiment || transfer ? index : 0)} />
    <section className={styles.evidence} aria-label="Pattern and movable observation"><h2>Your dataset</h2><p>Six indigo circles are fixed pairs. The orange diamond is movable Point 7. Drag the diamond or use the X coordinate and Y coordinate controls below. Its leader-linked number label is not its data position.</p><p role="status" className={styles.formula} data-shape-status>Pearson r = {number(a.r)}; Spearman rho = {number(a.rho)}. Point 7: X = {state.x.toFixed(1)}, Y = {state.y.toFixed(1)}.</p>
      <div className={styles.chart} ref={chartRef}><svg data-shape-chart viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label={`Seven paired observations on fixed X and Y axes 0 to 10. Six circles stay fixed; diamond Point 7 at (${state.x}, ${state.y}) moves. Pearson r ${number(a.r)}, Spearman rho ${number(a.rho)}. Exact coordinates and rank table provide equivalent data.`} onPointerDown={pointerStart} onPointerMove={pointerMove} onPointerUp={event => { pointerMove(event); dragging.current = false; }} onPointerCancel={() => { dragging.current = false; }} onLostPointerCapture={() => { dragging.current = false; }}>
        {chart.ticks.map(t => <g key={t.value}><line x1={t.x.toFixed(3)} x2={t.x.toFixed(3)} y1={chart.top} y2={chart.baseline} /><line x1={chart.left} x2={chart.width - chart.right} y1={t.y.toFixed(3)} y2={t.y.toFixed(3)} /><text x={t.x.toFixed(3)} y={chart.baseline + 20} textAnchor="middle">{t.value}</text><text x={chart.left - 10} y={(t.y + 4).toFixed(3)} textAnchor="end">{t.value}</text></g>)}<text x="8" y="18">Y</text><text x={(chart.width / 2).toFixed(3)} y="346" textAnchor="middle">X</text>
        {chart.points.slice(0, 6).map((p, i) => <circle key={i} data-fixed-point={i + 1} cx={p.x.toFixed(3)} cy={p.y.toFixed(3)} r="6" />)}<line data-leader x1={chart.points[6].x.toFixed(3)} y1={chart.points[6].y.toFixed(3)} x2={chart.label.x.toFixed(3)} y2={chart.label.y.toFixed(3)} /><polygon data-probe points={chart.diamond} /><text data-probe-label x={chart.label.x.toFixed(3)} y={(chart.label.y + 4).toFixed(3)} textAnchor="middle">7</text>
      </svg></div><div className={styles.controls}><LessonRangeControl label="X coordinate" value={state.x} min={0} max={10} step={.5} help="Movable Point 7 only. The six fixed circles keep their paired values." onChange={x => edit({ x })} /><LessonRangeControl label="Y coordinate" value={state.y} min={0} max={10} step={.5} help="Movable Point 7 only. Equal values share average ranks." onChange={y => edit({ y })} /></div><p className={styles.formula} data-shape-ranks>Point 7: X rank = {a.rx[6]}; Y rank = {a.ry[6]}. Smallest value has rank 1; seven distinct values fill ranks 1 to 7.</p><p>Ranks order X and Y separately, then keep each observation’s pair together. Equal values share their average occupied rank. If the diamond coincides with a fixed circle, only Point 7 moves; the table retains both observations.</p></section>
    <LessonSummaries label="Value and rank correlation" summaries={[
      { label: "Pearson r", color: "#5031dc", value: number(a.r), definition: "Straight-line alignment of numeric values.", formula: "Centered paired products / both value spreads" },
      { label: "Spearman rho", color: "#ad4508", value: number(a.rho), definition: "Alignment of paired average ranks.", formula: "Pearson correlation of rank X and rank Y" },
    ]} />
    <section className={styles.evidence} aria-label="Rank evidence and interpretation"><p>Monotonic means one direction throughout; a curve can be monotonic without being straight. A U shape turns back. Neither coefficient describes every pattern, proves independence or establishes causation. Spearman is less sensitive to numeric distance, but changed rank order can still influence it. A low score is not an automatic reason to remove a point.</p><details><summary>Rank and paired-value table</summary><div className={styles.table} role="region" tabIndex={0} aria-label="Paired rank evidence"><table><caption>Seven current pairs. Rank each variable separately; average ties and preserve observation identity.</caption><thead><tr>{["Point", "X", "Y", "X rank", "Y rank"].map(h => <th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{a.points.map((p, i) => <tr key={i}><th scope="row">{i + 1}{i === 6 ? " · movable" : " · fixed"}</th><td>{p.x.toFixed(1)}</td><td>{p.y.toFixed(1)}</td><td>{a.rx[i]}</td><td>{a.ry[i]}</td></tr>)}</tbody></table></div></details><details><summary>Six fixed-point reference</summary><p className={styles.formula}>Prepared six-circle reference: Pearson r = {number(fixed.r)}; Spearman rho = {number(fixed.rho)}. Current seven-pair dataset: Pearson r = {number(a.r)}; Spearman rho = {number(a.rho)}.</p><p>This controlled toy comparison isolates the diamond’s influence. It is not a recommendation to exclude inconvenient real observations; investigate provenance and scientific context.</p></details><details><summary>Conventions and sources</summary><p>Pearson r = Σ[(X − mean X)(Y − mean Y)] / √(Σ(X − mean X)² × Σ(Y − mean Y)²). Spearman applies that same formula to average-rank pairs. The simplified no-tie formula is not used because these datasets can tie. If either raw or ranked spread were zero, the corresponding coefficient would be undefined. The six fixed pairs always vary in this editor, so that boundary cannot be reached by moving just Point 7.</p><p>Calculations use full precision before four-decimal display. All editable coordinates are half-unit values from 0 to 10; the fixed plot axes use the same bounds. This page compares descriptive scores; no normality assumption, inferential test, causal estimate, outlier-removal rule or claim that either score captures all dependence is supplied.</p><a href="https://www.itl.nist.gov/div898/software/dataplot/refman2/ch2/rankcorr.pdf" target="_blank" rel="noreferrer">NIST · Average-rank Spearman formula</a><br /><a href="https://www.stat.berkeley.edu/~stark/SticiGui/Text/correlation.htm" target="_blank" rel="noreferrer">Berkeley · Shape, influence and correlation limits</a></details></section>
  </LearningPage>;
}
