"use client";
import {useMemo,useState} from "react";
import {ExperimentButton,ExperimentChoices,ExperimentRail,ExperimentResult,LearningPage,LessonSelect,LessonSummaries,LessonToolbar} from "@/components/learning-page/learning-page";
import shared from "@/components/learning-page/learning-page.module.css";
import {analyzeSafety,policyChoices,variantChoices,subsetChoices,safetyBaseline,safetyNumber as number,safetyPresetId,safetyScenarios,sameSafety,type SafetyState} from "./safety-engine";
import {safetyExperiments} from "./learning-experiments";
import {reachedSafety} from "./lesson-state";
import styles from "./playground.module.css";
export function SafetyPlayground(){
 const[state,setState]=useState<SafetyState>(safetyBaseline),[index,setIndex]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[explanation,setExplanation]=useState<string|null>(null),[transferAnswer,setTransferAnswer]=useState<string|null>(null);
 const a=useMemo(()=>analyzeSafety(state),[state]),experiment=safetyExperiments[index],transfer=index===4,reached=!!prediction&&!!experiment&&reachedSafety(index,state),complete=reached&&explanation==="0";
 function clear(){setExplanation(null);setTransferAnswer(null);}function start(next=index){setIndex(next);setState(safetyBaseline());setPrediction(null);clear();}function edit(next:SafetyState){if(!sameSafety(state,next)){setState(next);clear();}}
 const rail=experiment?<ExperimentRail label={`Experiment ${index+1} of 4`} title={experiment.title} phase={!prediction?0:reached?2:1}>
 {!reached&&<><h3>Make a prediction</h3><p>{experiment.question}</p><ExperimentChoices legend="Your prediction" name="safety-prediction" choices={experiment.predictions} value={prediction} onChange={id=>{start();setPrediction(id);}}/><p className={shared.small}>Changing prediction restores Balanced baseline. Reset restarts this experiment.</p></>}{prediction&&!reached&&<p className={shared.actionPrompt}><strong>Now try it.</strong> {experiment.action}</p>}{reached&&<><p role="status" className={shared.observation}>{prediction==="0"?"The evidence matches your prediction.":"The evidence challenges your prediction."}</p><h3>{experiment.explanation}</h3><ExperimentChoices legend="Your explanation" name="safety-explanation" choices={experiment.explanations} value={explanation} onChange={setExplanation}/>{explanation&&!complete&&<p role="status" className={shared.feedback}>Try again. {experiment.retry}</p>}</>}{complete&&<><ExperimentResult>{experiment.takeaway}</ExperimentResult><ExperimentButton arrow onClick={()=>start(index+1)}>{index===3?"Try the transfer check":"Next experiment"}</ExperimentButton></>}
 </ExperimentRail>:<ExperimentRail label={transfer?"Transfer check":"Free exploration"} title={transfer?"Transfer a benign-only policy":"Explore policy and population changes"}>{transfer?<><p>Without Guide help, set Policy to Strict authored, Prompt variant to Reworded and Evaluation subset to Benign only. Reconstruct false refusal, robust success and consistency. Explain which unsafe rates are Undefined.</p>{reachedSafety(4,state)&&<><ExperimentChoices legend="Transfer explanation" name="safety-transfer" choices={[
 {id:"counts",label:"B2/B3 are refused in Reworded, so false refusal=2/4=0.5. Only B1 is Help in every variant: robust success=1/4=0.25. B1/B2/B3 are consistent across variants: consistency=3/4=0.75, including consistently refused benign B2/B3. With no included unsafe families, harmful compliance and conditional jailbreak success are Undefined. These are authored outcomes, not proof of real-model safety."},
 {id:"missing",label:"There are no unsafe rows in this subset, so harmful compliance is a measured perfect 0."},
 {id:"citation",label:"Consistency=0.75 means 75% are correctly helped in all three variants."}
 ]} value={transferAnswer} onChange={setTransferAnswer}/>{transferAnswer&&(transferAnswer!=="counts"?<p role="status" className={shared.feedback}>Try again. Count benign refusals in the selected column, then correct and identical rows across all variants. Do not replace an absent class with a zero error rate.</p>:<><ExperimentResult title="Transfer explained">Use labeled populations and baseline eligibility; separate consistent decisions from correct decisions.</ExperimentResult><ExperimentButton onClick={()=>{setIndex(5);clear();}}>Explore freely</ExperimentButton></>)}</>}</>:<><p>Compare Original wording, Reworded and Abstract wrapper within each policy. Robust success and consistency use all variants and do not change with the selected column. Switch Benign only and Unsafe only to expose Undefined rates. Reset starts Experiment 1.</p><ExperimentButton onClick={()=>start(0)}>Restart experiments</ExperimentButton></>}</ExperimentRail>;
 return<LearningPage title="Safety, Refusal & Robustness Metrics Lab" subtitle="Compare safety decisions with their labeled denominators." rail={rail}>
 <LessonToolbar scenarios={safetyScenarios} selectedId={safetyPresetId(state)} onSelect={id=>edit(safetyBaseline(id))} onReset={()=>start(experiment||transfer?index:0)}/>
 <section className={styles.evidence} aria-label="Authored safety dataset"><h2>Your dataset</h2><p>Eight authored prompt families have fixed labels: four benign requests should receive Help, four unsafe goals should receive Refusal. Help means appropriate help on a benign request; Harmful compliance means following an unsafe goal. Labels and outcomes are known by construction. No model, harmful response generation or actual jailbreak attack runs.</p><p>Policy and Prompt variant select a disclosed toy outcome bank. Reworded and Abstract wrapper represent alternate wording of the same goal; no actionable attack text is supplied. These are authored examples, not empirical performance or a universal safety policy.</p>
 <div className={styles.controls}><LessonSelect label="Policy" choices={policyChoices} value={state.policy} onChange={policy=>edit({...state,policy})}/><LessonSelect label="Prompt variant" choices={variantChoices} value={state.variant} onChange={variant=>edit({...state,variant})}/><LessonSelect label="Evaluation subset" choices={subsetChoices} value={state.subset} onChange={subset=>edit({...state,subset})}/></div>
 <p role="status" data-safety-status>Included {a.total} families · Benign {a.benignCount} · Unsafe {a.unsafeCount} · Harmful {a.harmfulCount} · False refusals {a.falseRefusalCount} · Originally refused unsafe {a.eligibleCount} · Newly harmful among eligible {a.jailbreakCount} · All-variant correct {a.robustCount} · All-variant consistent {a.consistentCount} · Selected refusals {a.refusalCount}.</p>
 <p className={shared.small}>Each actual control/preset change clears stale explanation/transfer answers; reapplying the same state preserves them. Excluded rows remain visible for comparison and contribute to no numerator or denominator.</p>
 <div className={styles.table} role="region" tabIndex={0} aria-label="Authored outcomes across three prompt variants"><table><caption>Selected column: {variantChoices.find(v=>v.id===state.variant)!.label}. Help is correct for benign; Refusal is correct for unsafe. All-variant columns inspect the full row.</caption><thead><tr><th scope="col">Family / goal</th><th scope="col">Label</th><th scope="col">Included?</th>{variantChoices.map(v=><th scope="col" key={v.id} data-selected={state.variant===v.id}>{v.label}{state.variant===v.id?" · Selected":""}</th>)}<th scope="col">Originally refused unsafe?</th><th scope="col">Now harmful among eligible?</th><th scope="col">All variants correct?</th><th scope="col">All variants identical?</th></tr></thead><tbody>{a.rows.map(r=><tr key={r.id} data-safety-row={r.id}><th scope="row">{r.id}<span className={styles.itemDetails}>{r.title}</span></th><td>{r.benign?"Benign":"Unsafe"}</td><td>{r.included?"Yes":"No"}</td>{r.outcomes.map((o,i)=><td key={i} data-selected={variantChoices[i]!.id===state.variant}>{o}</td>)}<td>{r.eligible?"Yes":"No"}</td><td>{r.jailbreakSuccess?"Yes":"No"}</td><td>{r.robust?"Yes":"No"}</td><td>{r.consistent?"Yes":"No"}</td></tr>)}</tbody></table></div>
 </section>
 <LessonSummaries label="Current safety error and conditional attack results" summaries={[
 {label:"Harmful compliance",color:"#5031dc",value:number(a.harmfulRate),definition:"Unsafe requests followed in the selected variant.",formula:"harmful included unsafe / included unsafe",comparison:`${a.harmfulCount}/${a.unsafeCount}. Undefined when the unsafe class is absent.`},
 {label:"False refusal",color:"#087c78",value:number(a.falseRefusalRate),definition:"Benign requests refused in the selected variant.",formula:"refused included benign / included benign",comparison:`${a.falseRefusalCount}/${a.benignCount}. Undefined when the benign class is absent.`},
 {label:"Conditional jailbreak success",color:"#ad4508",value:number(a.jailbreakRate),definition:"Originally refused unsafe families now harmful.",formula:"newly harmful eligible / eligible unsafe",comparison:`${a.jailbreakCount}/${a.eligibleCount}. Eligibility is Original Refusal under the same policy; originally harmful families are excluded.`},
 ]}/>
 <section className={styles.evidence} aria-label="Robust success and decision consistency"><h2>Correct across variants, or just consistent?</h2><p>Robust success = included families correctly handled in all three variants / included families = {a.robustCount}/{a.total} = <strong data-safety-robust>{number(a.robustRate)}</strong>. A benign family must receive Help in every variant; an unsafe family must receive Refusal in every variant.</p><p>Decision consistency = included families with identical outcomes across all three variants / included families = {a.consistentCount}/{a.total} = <strong data-safety-consistency>{number(a.consistency)}</strong>. Consistently refusing benign requests or consistently following unsafe goals is still wrong. Selecting a different variant changes current error rates but cannot change either all-variant measure.</p><p>Conditional jailbreak success is an explicitly conditional attack success rate (ASR), not a universal benchmark convention. In Original wording it is 0 by construction: eligible families are precisely those originally refused. That does not exclude original harmful compliance outside its denominator. All-unsafe harmful compliance includes those families. A zero error rate on four authored cases does not prove real-model safety, and an absent class produces Undefined rather than a fabricated perfect score.</p></section>
 <section className={styles.evidence} aria-label="Safety conventions and limits"><details><summary>Construction and limits</summary><p>The bank has three authored policies, three prompt variants and three nonempty evaluation subsets: 27 states. All eight labeled families and outcomes are fixed teaching examples; the names Balanced, Strict and Permissive describe this bank, not deployed defenses. Labels do not resolve context-dependent real-world safety judgments. Partial refusals, safe redirection, harmful detail severity, adaptive attackers, multi-attempt budgets, stochastic variation, uncertainty intervals and judge reliability are out of scope.</p><p>Harmful compliance and false refusal use distinct classes in the selected variant. Conditional ASR counts only unsafe families originally refused under the same policy and subset. Changing policy also changes eligibility; it does not establish a causal attack ranking across real systems. Robust success is correctness in all three disclosed variants, not a guarantee for unseen prompts. Consistency ignores correctness. All fractions with a zero denominator are Undefined. Excluded rows remain visible but do not contribute. Reset/prediction restore Balanced baseline for the current exercise; free Reset starts Experiment 1.</p><a href="https://arxiv.org/abs/2308.01263" target="_blank" rel="noreferrer">XSTest · Safe requests and excessive refusal</a><br/><a href="https://arxiv.org/abs/2404.01318" target="_blank" rel="noreferrer">JailbreakBench · Explicit evaluation conventions</a></details></section>
 </LearningPage>;
}
